skyportal/handlers/comment.py, skyportal/model_util.py, static/js/components/CommentList.jsx
- Correct the SQLAlchemy query
- Add different comments to different sources, so that filtering
can be visually inspected
- Fix incorrect `created_at` field in rendering
=> Correctly filter source comments

static/js/API.js, static/js/CustomMessageHandler.js, static/js/actions.js, static/js/containers/PlotContainer.jsx, static/js/reducers.js
This is an attempt to make the console messages easier to debug.  They
should now look like this:
- WebSocket skyportal/FETCH_COMMENTS {source_id: "14gqr"}
- Action API_CALL
- Action FETCH_COMMENTS_OK
=> Log WebSocket actions, and use more intuitive API action names

skyportal/models.py, skyportal/tests/conftest.py, skyportal/tests/fixtures.py, skyportal/tests/frontend/test_frontpage.py, skyportal/tests/frontend/test_sources.py
Sources that belong to a public group are viewable to all users; specific actions (commenting, uploading files, etc.) still require the relevant ACLs.
Closes #48.
=> Add `public` flag to `Group`s

Dockerfile, Makefile, tools/test_frontend.py
- The old `make debug` is now `make run` (i.e., `make run` always
starts in debug mode)
- A new target, `run_production`, is added, which starts without the
`--debug` flag, and loads `config.yaml`.
- The `testrun` target is now called `run_testing`.
- The `rundocker` target has been removed, use `run_production`.
- Switch to the newest baselayer, which allows switching off the
`webpack` service.  This is necessary to fire up the server without
`node_modules` present---something we want to do in the Docker
container.  (All Javascript files are packed into
`static/bundle.js`.)
=> Refactor server launching

skyportal/tests/frontend/test_frontpage.py, static/js/actions.js, static/js/components/SourceList.jsx, static/js/containers/SourceListContainer.jsx, static/js/reducers.js
Previously, the sources were fetched upon hydration; i.e., with each
and every page fetch.  Now, only the profile information is retrieved
during hydration.
Closes #60
=> Fetch sources when source lists are loaded

skyportal/initial_setup.py
Usage:
```
usage: initial_setup.py [-h] [--nodrop] [--adminusername ADMINUSER]
[--username USER]
Initialize Skyportal and add admin/users
optional arguments:
-h, --help            show this help message and exit
--nodrop              do not force drop existing databases
--adminusername ADMINUSER
Email of the admin user (e.g., testuser@cesium-ml.org)
--username USER       Email of a normal user (e.g., user@cesium-ml.org)
```
So for example:
```bash
PYTHONPATH=$PYTHONPATH:"." python skyportal/initial_setup.py  \
--adminuser=<email> --user=<anotheremail>
```
If you just want to add a user to an existing database make sure you add the `--nodrop` flag:
```bash
PYTHONPATH=$PYTHONPATH:"." python skyportal/initial_setup.py  \
--nodrop --user=<anotheremail>
```
=> initialization script to be run the first time

Makefile
- Display the SkyPortal version with `make help`
- `make help` is now the default target
- Use a different mechanism for calling out to the baselayer Makefile
=> Improve Make help message

skyportal/handlers/__init__.py, skyportal/handlers/base.py, skyportal/handlers/become_user.py, skyportal/handlers/comment.py, skyportal/handlers/group.py, skyportal/handlers/logout.py, skyportal/handlers/photometry.py, skyportal/handlers/plot.py, skyportal/handlers/profile.py, skyportal/handlers/source.py, skyportal/handlers/spectrum.py, skyportal/handlers/sysinfo.py, skyportal/handlers/token.py, skyportal/handlers/userinfo.py, skyportal/tests/frontend/test_groups.py, skyportal/tests/frontend/test_versioned_requests.py, static/js/reducers.js
This PR introduces a change to how we call the `success` and `error` handler methods: when passing in `data`, this must always be an explicit keyword argument (e.g. `self.success(data=data)`).
Closes #143.
=> Return skyportal version with each API response

skyportal/handlers/source.py, skyportal/tests/api/test_sources.py
Infer source group(s) from user/token group membership if IDs not explicitly specified in POST handler
=> Infer source group(s) from user/token group membership 

skyportal/handlers/group.py, skyportal/handlers/source.py, skyportal/handlers/token.py, skyportal/model_util.py, skyportal/models.py, skyportal/tests/api/test_groups.py, skyportal/tests/api/test_user.py, skyportal/tests/conftest.py, skyportal/tests/frontend/test_groups.py, skyportal/tests/frontend/test_sources.py, skyportal/tests/frontend/test_tokens.py, static/js/ducks/group.js
`Token.groups` now points to `Token.created_by.groups` for simplified token group membership logic.
Tokens now belong to all groups that the creating user is a member of.
Closes https://github.com/skyportal/skyportal/issues/255
=> Add groups property to tokens

skyportal/handlers/comment.py, skyportal/handlers/instrument.py, skyportal/handlers/photometry.py, skyportal/handlers/source.py, skyportal/handlers/spectrum.py, skyportal/handlers/telescope.py, skyportal/handlers/thumbnail.py, skyportal/models.py, skyportal/tests/api/test_instrument.py, skyportal/tests/api/test_telescope.py, tools/load_demo_data.py
Ensures that tokens/users initiating requests have requisite permissions (group membership and ACLs) before creating/reading/updating/deleting entries for the following endpoints:
- `source`
- `photometry`
- `spectrum`
- `thumbnail`
- `comment`
- `group`
- `telescope`
- `instrument`
Also adds group membership for telescopes (and thereby their child instruments) for access control.
Closes #155 and #244
=> Add API security checks

requirements.txt
This will allow us to use newer marshmallow features such as `Schema.from_dict`
=> Bump & unpin versions for apispec and all marshmallow packages in requirements.txt

static/js/components/Plot.jsx
This fixes a bug where the bokeh plots re-render whenever any part of `state.source` is updated, included when adding comments. This significantly speeds up updates to the source page.
=> Wrap Plot component with React.memo

requirements.txt
`astroquery` 0.3.8 (previous minimum required version) breaks with newest `astropy` 4.0
=> Bump minimum required astroquery version 

skyportal/handlers/api/internal/profile.py, skyportal/handlers/api/internal/token.py, skyportal/handlers/api/news_feed.py, skyportal/tests/frontend/test_tokens.py, skyportal/tests/frontend/test_user.py, static/js/API.js, static/js/components/GroupList.jsx, static/js/components/HomePage.jsx, static/js/components/NewTokenForm.jsx, static/js/components/NewsFeed.jsx, static/js/components/Profile.jsx, static/js/ducks/groups.js, static/js/ducks/newsFeed.js, static/js/ducks/profile.js
This avoids checks inside components to ensure that state is defined and
of correct form.
It would be good to review other components that do this kind of checking too.
---
The major changes here are now:
- The backend never returns undefined for profile preferences, but rather an empty dictionary.
- The newsfeed component now checks for its preferences, and if not found applies a set of default preferences.
- TODO: The default preferences should probably be merged with whatever is provided by the user, so we can ensure that the widget always has all of its configuration parameters.
- Random cleanups, but specifically API.js, which I rewrote to give more logical error responses: a) connection error b) JSON decoding error c) actual 400 and similar errors that are reported by the backend.
=> Set initial state for profile and newsFeed reducers.

webpack.config.js
On some OSs, you can run out of notification handles doing this. Not
monitoring node_modules should make monitoring the rest of skyportal +
baselayer more reliable.
Closes #363
=> webpack: do not monitor changes in node_modules

skyportal/app_server.py, skyportal/handlers/api/__init__.py, skyportal/handlers/api/internal/__init__.py, skyportal/handlers/api/internal/profile.py, skyportal/handlers/api/internal/source_views.py, skyportal/handlers/api/source.py, skyportal/models.py, skyportal/tests/frontend/test_top_sources.py, static/js/actions.js, static/js/components/HomePage.css, static/js/components/HomePage.jsx, static/js/components/NewsFeed.jsx, static/js/components/Source.jsx, static/js/components/TopSources.jsx, static/js/ducks/source.js, static/js/ducks/topSources.js
This PR adds a most viewed sources widget to the home page. The number of sources displayed, and the time range to include are customizable by the user and are persisted in the DB. The `/api/internal/source_views` endpoint and associated handlers are added (handlers for POST, for registering new source views, and GET, for fetching the list of top sources, are implemented). Front-end source views (fetching of non-cached source) and token `/api/sources/<id>` GET requests are added to the new `SourceViews` table, along with the username/token ID (and a bool indicating whether it was a token or a front-end user) and timestamp.
=> Most viewed sources widget

.gitignore, config.yaml.defaults, static/js/components/Main.jsx.template
This allows external developers to add new components to SkyPortal, and to have them render on `/their_choice_of_url`.
Currently, those components are expected to live in the same directory
as the SkyPortal components, but this can be addressed later.
To add text or components to the frontpage, you have to build a new component that renders `static/js/components/HomePage` inside of it (or just replace `HomePage` entirely, if you wish).
=> Allow specification of JS routes in config

skyportal/models.py
Uses the sdss.org URL for DR12 for image cutouts.﻿
=> Update SDSS URL to DR12

skyportal/handlers/api/instrument.py, skyportal/models.py, skyportal/tests/api/test_instrument.py, skyportal/tests/conftest.py, skyportal/tests/frontend/test_followup_requests.py
This PR introduces some slight refinements of the `Instrument` data model, namely:
* The introduction of a `filters` field, that is an `Array` of `Enum`. The allowed Enum values are the filters defined by our photometry library, `sncosmo`. The `filters` of an instrument can be `[]`, indicating no filters. This would be appropriate for, e.g., a Spectrograph without any imaging capabilities. 
* Update of the `InstrumentHandler` to this modification and proper rendering of the allowed filter values for new instruments in the api docs:
* Requirement that a user be a system admin to update or delete instruments. This is because follow-up requests will assume a certain schema for instruments, and we dont want anyone messing around with the capabilities of the instruments or it could affect …
=> Refine Instrument data model

skyportal/handlers/api/internal/plot.py, skyportal/handlers/api/photometry.py, skyportal/models.py, skyportal/plot.py, skyportal/schema.py, skyportal/tests/api/test_bulk_delete_photometry.py, skyportal/tests/api/test_photometry.py, skyportal/tests/api/test_thumbnail.py, skyportal/tests/conftest.py, skyportal/tests/fixtures.py, skyportal/tests/frontend/test_scanning_page.py, skyportal/tests/frontend/test_upload_photometry.py, static/js/components/UploadPhotometry.jsx, tools/load_demo_data.py
This PR introduces photometry-level permissions checking. Each `Photometry` point has its own `groups` relationship, and the intersection between a user's group list and a photometry point's group list determines access. 
- The photometry POST API endpoint handler now requires a `group_ids` field;
- `Obj.get_if_owned_by` now first checks whether an associated candidate or source is part of the given user's group, and if not, then checks whether the user has access to any of the object's photometry, raising an access error if not;
- `Obj.get_photometry_owned_by_user` is added;
- `photometry_plot` has been updated to only render those photometry points that should be visible to the current user;
- `SourcePhotometryHandler` now returns only those photometry points a user should have access …
=> Implement photometry-level permission checking

skyportal/handlers/api/candidate.py, skyportal/handlers/api/comment.py, skyportal/handlers/api/photometry.py, skyportal/handlers/api/source.py, skyportal/models.py, skyportal/tests/api/test_candidates.py, skyportal/tests/api/test_comments.py, skyportal/tests/api/test_filters.py, skyportal/tests/conftest.py, skyportal/tests/fixtures.py, skyportal/tests/frontend/test_groups.py, skyportal/tests/frontend/test_sources.py, static/js/components/CommentEntry.css, static/js/components/CommentEntry.jsx, static/js/components/CommentList.jsx, static/js/ducks/source.js
This PR introduces groups <--> comments relationships so that each comment has its own groups list. Users may now customize which of their groups should have access to a comment when commenting on the source page (by default, all groups are checked, and the checkbox area is not displayed). See screenshot below for front-end functionality demo.
=> Implement comment-level group access; clean up front-end tests

requirements.txt, skyportal/app_server.py, skyportal/handlers/api/__init__.py, skyportal/handlers/api/taxonomy.py, skyportal/model_util.py, skyportal/models.py, skyportal/tests/api/test_taxonomy.py, skyportal/tests/conftest.py, tools/load_demo_data.py
This PR is the first of several in the `Classification` epic. Here we introduce the Taxonomy infrastructure (Table, API Handlers, Tests) which allow programmatic access to add, retrieve, and delete classification taxonomies. 
Some features:
- Taxonomies are stored as JSONB and validated against the JSON schema in the `tdtax` project
- Taxonomies are added with group-level permission
- A `name` and (semantic) `version` is associated with each taxonomy
- Taxonomies added with the same `name` as other taxonomies will, by default, become the latest version, setting the others with the same `name` with `isLatest == False`
- New ACLs `Taxonomy` and `Taxonomy Delete` are introduced. By default only the `Super admin` role has the ability to delete Taxonomies once they are in the DB.
For future …
=> PR#1 Classification Epic: Taxonomy Infrastructure

skyportal/handlers/api/photometry.py, skyportal/models.py, skyportal/schema.py, skyportal/tests/api/test_photometry.py, skyportal/tests/fixtures.py
This PR introduces a unique `alert_id` column to the `Photometry` table and updates the handler such that when a POST request is received with an alert ID that already exists in the DB, only the associated photometry entry's groups list is updated. Schema, tests and test fixtures are updated.
=> Add unique alert_id column to Photometry table & update Photometry handler

package.json, skyportal/tests/frontend/test_upload_photometry.py, static/js/components/UploadPhotometry.jsx
This PR improves CSV parsing in the photometry upload front-end component. We use `PapaParse` for parsing CSV, which auto-detects the delimiter, simplifying our form by not requiring the delimiter to be specified. This also allows for escaped (quoted) values that contain the delimiter, as in the example screenshot below.
=> Use PapaParse for parsing CSV strings

.gitignore, .travis.yml, pytest.ini
@dannygoldstein: Here's the starting point for the pull request we discussed.
To get everything wired up end-to-end, we'll need to do just a few things:
This is done in 71c3b173bcb3a9a0698735b574d4928a8616bc75. It currently assumes that XML report(s) will reside in the `test-results` directory. If it would be helpful to use a different directory, that's totally fine. We'll just need to update the `BUILDPULSE_REPORT_PATH` in `.travis.yml` accordingly.
Please ping me when the first two items are done, and we can make sure that everything is flowing through nicely. And of course, if you run into any trouble with those items or if you have any questions at all, just let me know. :bow:
=> Update Travis CI build to send test results to BuildPulse

config.yaml.defaults, skyportal/handlers/api/group.py, skyportal/handlers/api/user.py, skyportal/model_util.py, skyportal/models.py, skyportal/schema.py, skyportal/tests/api/test_groups.py, skyportal/tests/api/test_user.py, static/js/components/GroupList.jsx, tools/data_loader.py
This PR adds individual user groups, which are automatically created whenever new users are added, to facilitate the sharing of data between individual users (PR forthcoming). This PR also adds a public group to which all users are automatically added (upon user creation).
=> Add individual user groups & public group that all users automatically belong to

requirements.txt, skyportal/tests/frontend/test_followup_requests.py, skyportal/tests/frontend/test_scanning_page.py, skyportal/tests/frontend/test_sources.py
This PR adds the `pytest-rerunfailures` dependency, using it to mark flaky tests to be rerun if they fail (up to two times, and this is easily configurable). This should greatly improve the overall reliability of the test suite.
A few small test bugs are also addressed.
=> Use `pytest-rerunfailures` to mark flaky front-end tests to be rerun up to 2 times

skyportal/model_util.py
`System admin` should be enough, but we haven't yet allowed sysadmin to
do everything on the system.  So, this works around that for now.
=> Provisioned admin token now gets all ACLs

.gitignore, config.yaml.defaults, static/js/components/Main.jsx.template, static/js/components/SidebarAndHeader.jsx, static/js/components/SidebarAndHeader.jsx.template
Sidebar entries can now be specified in `config.yaml.defaults` under `app.sidebar`.
Links can either be internal (`/profile`) or can point to the outside world (those must start with `http` to be recognized).
=> Configure sidebar entries in `config.yaml.defaults`

package.json, skyportal/handlers/api/group.py, skyportal/handlers/api/user.py, skyportal/tests/frontend/test_groups.py, static/js/actions.js, static/js/components/NewGroupUserForm.jsx, static/js/ducks/users.js
This PR adds auto-complete functionality to the group users front-end form. If a _new_ username is provided, that user is created, along with the associated individual user group and associated `GroupUser` row for the site-wide public group. Tests are updated.
=> Auto-complete usernames & create new users via group users form

skyportal/handlers/api/group.py, skyportal/tests/frontend/test_groups.py, static/js/components/Group.jsx
This PR fixes a few group user management bugs. 
If a group only has a single admin, its associated delete button is disabled (another user must be made admin before they can be deleted so that no group has zero admins). See screen capture below for demo:
If a user is selected to be added that already exists, a simple, informative error message is displayed.
Closes #579 
Closes #577
=> Robustify group user management

Dockerfile
- `baselayer` expects `python >= 3.7`
- Ubuntu 20.04 LTS uses `3.8` by default
- `DEBIAN_FRONTEND=noninteractive` prevents interactive TZ setup
=> Use Ubuntu 20.04 in Dockerfile

package.json, static/js/components/ProfileDropdown.jsx
A very simple example of using styled-components. This replaces the Responsive component, and hopefully everyone finds its more explicit, easier to read, and a bit simpler.
We can continue down this path if people like this example.
This will keep the ProfileDropdown link on the right side of the header instead of positioned over the header on widths < 768px.
=> Mobile profile link

skyportal/handlers/api/candidate.py, skyportal/handlers/api/classification.py, skyportal/handlers/api/comment.py, skyportal/handlers/api/filter.py, skyportal/handlers/api/group.py, skyportal/handlers/api/instrument.py, skyportal/handlers/api/internal/source_views.py, skyportal/handlers/api/news_feed.py, skyportal/handlers/api/photometry.py, skyportal/handlers/api/source.py, skyportal/handlers/api/taxonomy.py, skyportal/handlers/api/telescope.py, skyportal/models.py
This PR improves permissions checking by introducing a new `User.accessible_groups` attribute, which returns either the normal user's group list (`User.groups`) in the case of non-system admin users, or, in the case of system admin users, returns all groups. This new attribute is used in place of `User.groups` for checking whether a user has access to the specified record(s). Some security lapses are also addressed.
Closes #619
=> System admin permissions

.travis/travis_install.sh
This avoids "429 too many requests" errors.
Also update geckodriver to v0.27.
=> Cache geckodriver download

skyportal/handlers/api/internal/source_views.py, static/js/components/TopSources.css, static/js/components/TopSources.jsx
This PR adds detection images to the top sources widget.
=> Add images to ``Top sources'' widget

data/db_demo.yaml, data/instruments.yaml, data/telescopes.yaml, requirements.txt, skyportal/app_server.py, skyportal/enum_types.py, skyportal/handlers/api/__init__.py, skyportal/handlers/api/followup_request.py, skyportal/handlers/api/instrument.py, skyportal/handlers/api/observingrun.py, skyportal/handlers/api/photometry.py, skyportal/models.py, skyportal/schema.py, skyportal/tests/api/test_assignments.py, skyportal/tests/api/test_instrument.py, skyportal/tests/api/test_observing_runs.py, skyportal/tests/api/test_telescope.py, skyportal/tests/conftest.py, skyportal/tests/fixtures.py, skyportal/tests/frontend/test_followup_requests.py, skyportal/tests/tools/test_sky.py
This PR is the first of several in the Observing Planning & Follow-up epic. Here we introduce the `ObservingRun` and `ClassicalAssignment` infrastructure (Table, API Handlers, Tests) which allow programmatic access to add, retrieve, and delete observing runs and add, retrieve and delete targets associated with those runs.
Some features:
- Observing Runs are associated with an instrument, a PI, names of observers, and a calendar date
- Observing run ORM objects provide convenience methods for calculating the run ephemerides, which will be used by the frontend to prevent users from assigning targets to runs that the Sun has already risen on
- Run owners and superusers can delete observing runs, which cascade to assignments
- Observing runs can optionally be associated with a group, for …
=> Observing Planning & Follow-up PR #1: Classical Targets API

data/db_demo.yaml, data/telescopes.yaml, skyportal/handlers/api/instrument.py, skyportal/handlers/api/telescope.py, skyportal/models.py, skyportal/tests/api/test_instrument.py, skyportal/tests/api/test_telescope.py, skyportal/tests/frontend/test_followup_requests.py, skyportal/tests/frontend/test_upload_photometry.py
In our current data model, `GroupTelescope`s are used to determine a user's access to instruments and telescopes. After a discussion on how access to instruments and telescopes is implemented, @acrellin and I decided that a better model would be to mediate facility access at the instrument level. Such a model more closely mirrors the astronomical proposal writing process: people apply for time on specific instruments and are granted time on them, as opposed to time on telescopes. In ch1158, @acrellin requested that the GroupTelescope model be removed and replaced with an Allocation model, which tracks InstrumentID, GroupID, and some other columns (PI, Proposal ID, Allocation ID [PK])
This PR facilitates the removal of `GroupTelescope`. A future PR will implement `Allocation`.
[ch1158]
=> remove GroupTelescopes in preparation for Allocations model

static/js/components/ClassificationForm.jsx
Since `state.allowed_classes` is now computed, rather than loaded from the source api, we need to allow the options to be an empty array. I believe that this obviates the need for PR #662 but the small fix there could also go in without effecting this PR.
=> allow ClassificationForm Autocomplete options to be an empty array as page loads

skyportal/handlers/api/source.py, skyportal/tests/frontend/test_assignments.py, skyportal/tests/frontend/test_frontpage.py, skyportal/tests/frontend/test_profile.py, skyportal/tests/frontend/test_tokens.py, static/js/actions.js, static/js/components/AssignmentForm.jsx, static/js/components/AssignmentList.css, static/js/components/AssignmentList.jsx, static/js/components/FollowupRequestForm.jsx, static/js/components/Source.jsx, static/js/ducks/observingRuns.js, static/js/ducks/source.js, static/js/ducks/telescopes.js, static/js/units.js
This PR is the second of several in the Observing Planning epic. Here we introduce the Assignments frontend, which provides two new React components, `AssignmentList` and `AssignmentForm`, which allow users to  add, view, and delete assignments of targets for follow-up to observing runs. This PR depends on #574. 
Specifics:
- Telescopes now have  a `robotic` attribute to determine whether the associated instruments should get robotic follow-up requests (@acrellin's follow-up requests API) or classical requests (this PR).
- An API error is thrown if a user attempts to assign a target to a run that it is already assigned to
- The AssignmentForm component renders "No upcoming runs..." if there are no runs with sunrise time > current time in the DB
- The AssignmentList component renders "No …
=> Observing Planning & Follow-up PR #2: Assignment frontend

skyportal/models.py
There were some ForeignKeys in models that were not indexed. This should speed up joins against those relationships.
=> index all foreign keys to improve join performance

static/js/components/TopSources.jsx
=> fix topsources rendering

skyportal/tests/frontend/test_frontpage.py, static/js/components/HeaderContent.jsx
This PR adds `top: "1rem"` to the styling of the `ProfileDropdown` component to afix it to the top of the page. Before this PR, it was only `position: fixed` to the right of the page. When adding a new component to the header (quick searchbar, coming soon!) I found that we needed both the top and right glue for proper formatting.
Note: the styling is added inline in `HeaderContent`, consistent with how it is currently done. It, like many other inline styling commands, ought to be moved using the makeStyles paradigm (or into css files).
Also: found a flaky test `test_frontpage.py::test_jump_to_page_invalid_values` which has been marked accordingly.
=> Afix ProfileDropdown to the top of page

skyportal/tests/tools/test_offset_util.py
This PR skips the test `test_get_ztfref_url` if the IRSA server it depends on is down. 
```
(skyportal2) Dannys-MBP:skyportal danny$ py.test skyportal/tests/tools/test_offset_util.py::test_get_ztfref_url
===================== test session starts =====================
platform darwin -- Python 3.7.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
Using --randomly-seed=1597018957
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/danny
plugins: Faker-4.1.1, postgresql-2.4.0, rerunfailures-9.0, randomly-3.4.0, factoryboy-2.0.3, benchmark-3.2.3
collected 1 item
skyportal/tests/tools/test_offset_util.py s             [100%]
===================== 1 skipped in …
```
=> do not run `test_get_ztfref_url` if irsa server is down

skyportal/handlers/api/user.py
The logs have been full of this error: 
```
[34mTraceback (most recent call last):
[34m  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
[34m    result = method(*self.path_args, **self.path_kwargs)
[34m  File "/home/travis/build/skyportal/skyportal/baselayer/app/access.py", line 31, in wrapper
[34m    return tornado.web.authenticated(method)(self, *args, **kwargs)
[34m  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/tornado/web.py", line 3174, in wrapper
[34m    return method(self, *args, **kwargs)
[34m  File "/home/travis/build/skyportal/skyportal/baselayer/app/access.py", line 46, in wrapper
[34m    return method(self, *args, **kwargs)
[34m  File …
```
=> Fix user handler bug

skyportal/handlers/api/photometry.py
From @acrellin  in slack:
> @dannygoldstein  is this an exception we're tripping intentionally in the tests? If so, we should explicitly catch it in the handler and return an error so the logs don't show the whole TB
> ```
> ERROR:tornado.application:Uncaught exception POST /api/photometry (127.0.0.1)
> HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/photometry', version='HTTP/1.0', remote_ip='127.0.0.1')
> Traceback (most recent call last):
>   File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "/home/travis/build/skyportal/skyportal/baselayer/app/access.py", line 29, in wrapper
>     return method(self, *args, **kwargs)
> …
```
=> patch photometry handler to trip more informative errors @acrellin

skyportal/tests/conftest.py
This PR adds a check to `conftest.py`, telling it to only download the latest IERS data if the iers data in disk cache (if any) is >= 14 days old. If there is no cached IERS data then it is downloaded.
=> only download IERS data if latest data is >=14 days old

package.json, skyportal/tests/frontend/test_data_sharing.py, skyportal/tests/frontend/test_quick_search.py, static/js/components/HeaderContent.jsx, static/js/components/QuickSearchBar.jsx, static/js/components/ShareDataForm.jsx
This PR adds a quick search bar for sources. Rather than having endusers type in the full source name to an address bar to jump to a source, this quick search bar will allow them to find and navigate to that source more quickly, from within the UI. Searches are debounced to 250ms to avoid making unnecessarily too many calls rapidly to the backend. This debouncing can be seen in the screenshot above, as the network does not get called when a long string is entered quickly. 
A maximum of 25 results are returned to avoid large data transfers from the backend to the frontend.
Future:
- allow searches for richer content, like comment strings or classification
- memoize the searches so that we do not rely on the browser to cache results
=> Quick Search Bar for Sources

skyportal/models.py
This fixes a bug in `Photometry.mag.expression` that caused usages of SQL hybrid of this property to error with `NotImplementedError: Operator 'getitem' is not supported on this expression`.
=> fix bug in Photometry.mag.expression

skyportal/plot.py, static/js/plotjs/stackm.js
- Add vertical bars for the first and last detection (if any)
- Update default zoom scale to use a slightly wider y-axis scale than the faintest and brightest detections
- Fix download for binned data
=> Update photometry plot

skyportal/tests/frontend/test_sources.py, static/js/components/StarList.css, static/js/components/StarList.jsx
This PR adds a dropdown menu to the StarList and ObservingRunStarList components  that allows you to choose the facility formatting guidelines that you would like applied to your starlist. 
This PR is an extension of #711 . It changes the `ObservingRunStarList` API (to have it take an `observingRun` object as opposed to an `observingRunId`) as defined in that PR, but does not alter the single-object `StarList` API that renders on the source page, which was written by others. 
This PR also fixes a bug in `skyportal/tests/frontend/test_sources.py::test_show_starlist` that caused the test to pass without the expected text being present. 
[ch1095]
=> Add facility selector to starlist component

.gitignore, config.yaml.defaults, requirements.txt, skyportal/app_server.py, skyportal/handlers/api/group.py, skyportal/handlers/api/internal/profile.py, skyportal/models.py, skyportal/onboarding.py, skyportal/tests/frontend/test_groups.py, skyportal/utils/onboarding.py, static/js/components/NewGroupUserForm.jsx, static/js/components/UpdateProfileForm.jsx, static/js/components/UserProfileInfo.jsx, static/js/ducks/profile.js, test_config.yaml
This PR introduces a new pipeline for inviting new users to collaborate on SkyPortal. A new user can be invited to join SP from the group page (admin must click "Confirm" in a dialog in this case, see screen capture below), and an `Invitation` instance will be created (this new table is added in this PR). When the row is inserted, an event listener is triggered, sending the user an email via Twilio Sendgrid containing a login link with a unique invite token. When they authenticate (only Google OAuth is currently supported), the matching `Invitation` record is fetched, which contains the group(s) and admin status(es) that should be granted to the user after they've authenticated and a new user instance is created. Upon initial authentication, they're directed to the profile page, where …
=> New user on-boarding

static/js/components/SharePage.jsx
Fixing incorrect MUI IconButton parameter for SharePage.jsx
=> Fix share page component error

static/js/components/AirmassPlot.jsx, static/js/components/CentroidPlot.jsx, static/js/components/VegaPlot.jsx
Edited by acrellin: does not close 793, as it's two separate issues
@acrellin There seems to be another issue, though, which is that clicking "search" as provisioned admin returns no results.  Any idea why that would be?  The initial page load produces results.
=> React sends null as a ref on component unmount; do not expect otherwise.

package.json
test PR to see if removing react dnd as a dependency fixes GA
=> Revert react-dnd and @date-io/dayjs version upgrades

static/js/components/UserAvatar.jsx
A user without a gravatar will not cause an insecure URL call.
=> use & to separate parameters in URL

skyportal/tests/frontend/test_upload_photometry.py
this should prevent test*.png from being written to skyportal/ by the test suite.
=> dont save screenshots in upload photometry

static/js/actions.js, static/js/components/GroupManagement.jsx, static/js/components/ShareDataForm.jsx
The issue was that sometimes the `fetchGroups()` call in `hydrate` (which does not fetch single user groups) was returning after the `fetchGroups(includeSingleUserGroups=true)` call in `ShareDataForm`. Now, when the component initially renders and when the groups list is updated, the groups list is checked, and if no single user groups are present, `fetchGroups(includeSingleUserGroups=true)` is called.
Closes https://github.com/skyportal/skyportal/issues/787
=> Ensure state.groups.all includes single user groups upon ShareDataForm render

static/js/components/Group.jsx
=> fix admin label positioning

static/js/components/CandidateList.jsx
Closes https://github.com/skyportal/skyportal/issues/861
=> Show spinner on initial scanning page load

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py
Closes https://github.com/skyportal/skyportal/issues/860 
This error was also occurring on the single candidate view page, and was fixed in the source (single, multiple) get handler as well.
=> Fix candidate, source handlers unowned comments bug

static/js/components/AssignmentForm.jsx
Currently, on the observing run page, the titles of observing runs that are not associated with any group render as "Loading...". This is because the render only completes successfully if a group ID is defined. 
This PR fixes this bug by defining render behavior when group ID is not defined for a run.
Before:
After:
=> fix rendering of observing run titles

static/js/components/RecentSources.jsx
Also switch to using the warm glow on thumbnail hovers like the top sources
=> Align rows in recent sources widget

static/js/components/UserAvatar.jsx, static/js/ducks/profile.js
Now, fall back to a transparent image.
Use CSS to add user initials underneath the image.  If a non-blank image is
fetched, it covers the user initials.
=> Fix 404s generated by invalid fetches to Gravatar

static/js/components/QuickSearchBar.jsx
- Do not use hardcoded event name in the quick search bar.
- Use the `<Link>` from `react-dom` instead of MUI to avoid reloading page from quick search bar.
=> fix QuickSearch in production; use react-dom to avoid reloading page

skyportal/handlers/api/user.py, skyportal/tests/api/test_user.py
The PR adds code to the `user` POST handler to catch when a phone number or email is not valid. Before we were not catching the exception upon database insert.
=> Catch bad emails and phone numbers upon user creation

skyportal/tests/api/test_bulk_delete_photometry.py
`api/test_bulk_delete_photometry` is currently failing on master as it has a hardcoded instrument id (id=1) which can sometimes refer to an instrument without `ztfg` filters. This fix has it use the `ztf_camera` fixture, which will always have the right filter set.
=> fix `test_bulk_delete_photometry`

skyportal/tests/frontend/test_followup_requests.py, static/js/components/FollowupRequestLists.jsx
Fixes followup request failures in #888
=> Use @id instead of @class to select elements in followup request tests

static/js/components/AssignmentList.jsx
Fixes #699 .
The currently merged solution to this issue (#759 ) is flawed in that it provides a dependency list with a length that can change (spread syntax). This can cause React errors.
The solution here avoids the spread syntax and passes a fixed dependency list to `useEffect` each time the component is rerendered. A useState hook is used to prevent redundant `fetchUser` calls between renders.
=> fix overfetching of users in AssigmentList

data/db_demo.yaml, skyportal/handlers/api/group.py, skyportal/tests/api/test_groups.py, skyportal/tests/frontend/test_groups.py, skyportal/tests/frontend/test_scanning_page.py, static/js/components/NewGroupForm.jsx
This PR updates the new group form component to use Material UI and uses a multi-select instead of a comma-separated text input for specifying new group admins. The API is also updated to use group admin user IDs instead of (outdated, error-prone) user email.
=> Refactor NewGroupForm to use MUI and update API to use user IDs instead of user emails

config.yaml.defaults, static/js/components/GroupList.jsx
Closes issue #896 
@dmitryduev This edits the default configs.
=> Make GroupList widget not resizable and add scrollbar

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/tests/tools/test_offset_util.py, skyportal/utils/__init__.py, skyportal/utils/offset.py
The PR introduces a new default behavior to use photometry-based centroiding of a source position for the purposes of making finding charts and offset/starlists. Rather than use the position at discovery time or the highest SNR detection of the source, combine all the positions available from associated photometry. If the calculated position is far (> 0.5 arcsec by default) from discovery, revert back to the original discovery image.
- always save ra,dec as discovery position if not specified
- introduce two weighting schemes (`snr` and `err`) to determine the offset from fiducial
- default finder imaging to ztfref and change the display scale to look better around galaxies
=> Better Finder Positions

config.yaml.defaults, skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/handlers/api/sysinfo.py, skyportal/models.py, skyportal/tests/api/test_candidates.py, skyportal/tests/api/test_sources.py, skyportal/tests/utils/test_cosmology.py, skyportal/utils/cosmology.py, static/js/components/About.jsx, static/js/components/Candidate.jsx, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx
- Site-wide configured  cosmology in `config.yaml` (named cosmologies from `astropy` or custom):
```
misc:
cosmology: Planck18_arXiv_v2
#cosmology: {H0: "65.0", Om0: 0.3, Ode0: 0.7, name: 'skyportal_user_cosmo'}
```
- Adding the distance calculations to Obj using either information in `altdata` (e.g. `altdata["parallax"]`) or using redshift + cosmology.
- Show on front-end if DM/luminosity distance is determined
- If redshift puts the source nearby (<350 km/s) then do no show DM/D_l unless a distance is established in altdata.
=> Cosmology calculations and display

skyportal/plot.py, static/js/components/Candidate.jsx, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx
Interestingly, it looks like our test suite and demo data ALWAYS set a redshift (zero or otherwise) so we never tested z=Null until ... production. This fixes a few places where z=Null was throwing errors on the frontend.
=> hotfix for frontend when z=Null

skyportal/tests/frontend/test_followup_requests.py
The followup request tests have been failing recently because they wait for the plots to load, and the plots have been taking a very long time to load on CI (>10s) causing the tests to timeout. 
This PR replaces the previous method of dealing with flakiness in the followup request frontend tests (refreshing the page and trying again in case of a plot timeout), and simply executes the page load once, but with an increased  timeout on the plot load from 10 to 20s.
=> improve stability of followup request tests

skyportal/plot.py
Fixes #969. 
This PR updates the photometry plot to make the default zoom take non-detections into account, showing both detections and non detections by default in magnitude space.
=> fix default zoom on photometry plot

static/js/components/CandidateList.jsx
Fixes #971 . 
With this PR, the scanning page now shows the number of candidates it says it shows.
=> Show correct number of candidates on scanning page

skyportal/plot.py
[ch1266]
Closes #975 . 
This PR adds an absolute magnitude axis to the photometry plot if `obj.dm is not None`, i.e., if the object has a distance modulus. 
If the distance modulus is not `None`, the loaded cosmology is used to calculate the distance modulus.
=> Add absolute magnitude to the photometry plot right axis if `obj.dm is not None`

skyportal/handlers/api/observingrun.py, skyportal/tests/frontend/test_observing_planner.py, static/js/components/RunSummary.jsx
Closes #980. 
[ch1135].
@AndyTza.
This PR adds chips that display an object's groups that are accessible to the current user on the observing run page.
=> display object groups on observing planner

skyportal/handlers/api/group.py, static/js/components/GroupManagement.jsx, static/js/components/Groups.jsx
This PR changes the permissions requirements around creating and editing groups, allowing anyone to create a group (which they are then an admin of by default) and allowing anyone who is an admin of a group to modify/delete that group. This allows for users to delete groups that they have created.
Closes https://github.com/skyportal/skyportal/issues/982
=> Allow anyone to create groups

skyportal/handlers/api/photometry.py, skyportal/handlers/api/spectrum.py, skyportal/schema.py, skyportal/tests/api/test_photometry.py, skyportal/tests/api/test_spectrum.py
This PR adds the ability to specify `group_ids="all"` in API calls for adding photometry and spectra. When specified as such, data will be shared with the site-wide public group.
Closes https://github.com/skyportal/skyportal/issues/990
=> Allow group_ids='all' in phot, spec POST handlers

skyportal/facility_apis/sedm.py, skyportal/handlers/api/facility_listener.py, skyportal/handlers/api/followup_request.py, skyportal/models.py, skyportal/tests/conftest.py
This PR moves the logging of remote facility transactions to the `staticmethod`s within the Listener and API classes for individual facilities. The previous implementation legislated a universal method for serializing these transactions based on `requests`. This didn't work, for example, for LT, which uses an XML/urllib based communication protocol. This PR solves this problem, accommodating the different HTTP request/response formats that different facilities have. 
This should allow #866 to move forward.
=> Refactor Transaction Logging in Remote Facility Framework

static/js/components/CandidateList.jsx, static/js/components/FilterCandidateList.jsx
Closes https://github.com/skyportal/skyportal/issues/933 
This PR fixes a bug where using the pagination buttons on the scanning page would result in the selected filter criteria being ignored in the associated fetch. The next/previous page buttons on the bottom of the page are replaced with a "Back to top :arrow_up:" button.
See screen capture demo:
=> Fix broken filtered scanning page results pagination buttons

skyportal/handlers/api/group.py, skyportal/tests/frontend/test_groups.py, static/js/components/Group.jsx, static/js/ducks/groups.js
This PR introduces a button to change the admin status of group users (only displayed to users with the "Manage users" ACL). `GroupUserHandler.patch` is implemented, along with an associated action creator. An additional change: disable the delete user icon button in the case of a single remaining group admin instead of setting its display property to "none", which caused a jarring misalignment.
Closes https://github.com/skyportal/skyportal/issues/578 
Screen capture demo:
=> Add toggle admin status button in group users list

skyportal/handlers/api/comment.py, static/js/components/CommentEntry.jsx
This PR fixes a bug where a user with System admin ACL could view a source saved to group(s) they're not part of, but could not use the front-end form to comment, as the front-end form only selects the users groups they're part of (here changed to all groups accessible to user).
Also, malformed comment attachments are better handled (used to fail silently, now returns informative error message)
=> Comment groups permissions updates & bug fixes

skyportal/plot.py
This updates the photometry plot to show 3 sigma detections. 
Fixes #999
=> change detect threshold to 3 sigma in bokeh plots

data/telescopes.yaml, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx, static/js/components/SourceNotification.jsx
- Remove redundant form title in source notifications
- Fix seed telescopes list to have nicknames and names properly assigned (they were flipped)
- Move surveys list to above photometry
[CH #1317](https://app.clubhouse.io/astromarshal/story/1317/remove-send-a-notification-from-source-notification-accordion)
[CH #1315](https://app.clubhouse.io/astromarshal/story/1315/move-surveys-above-photometry)
[CH #1324](https://app.clubhouse.io/astromarshal/story/1324/display-nicknames-for-groups-on-scanning-page)
=> Minor source page updates

skyportal/handlers/api/allocation.py, skyportal/model_util.py
This PR creates a new ACL - "Manage allocations", and replaces the requirement that only a System admin manage allocations with anyone who has this ACL. This will allow designated users to manage allocations (e.g., @rswalters).
=> add a new ACL for managing allocations - manage allocations

config.yaml.defaults, static/js/components/HeaderContent.jsx.template, static/js/components/Logo.css, static/js/components/Logo.jsx, static/js/components/Main.css, static/js/components/SidebarAndHeader.jsx.template
Will put up corresponding PR to Fritz to add the GROWTH logo as in sample image below:
Also a small spacing improvement on mobile for header bar (removed a margin if there's less space available)
=> Allow configuring multiple logos in header bar

package.json, skyportal/handlers/api/sysinfo.py, skyportal/tests/utils/test_gitlog.py, skyportal/utils/gitlog.py, static/js/components/About.jsx
- Ignore merge commits and display their parent commits instead
- Move hash into date bracket (instead of displaying at end of line)
- Use a regexp to ensure that PR number is from the end of the line
- Parse components of gitlog and send to frontend, where it is rendered into the template
(See updated screenshot below.)
=> Selectively display git commits; parse commits on backend and render on frontend

skyportal/models.py
Admin users do not have to be explicitly part of a taxonomy's groups in order to post classifications from it.
Closes #1096
=> Allow admins to post classifications for any taxonomy

.github/workflows/test.yaml, .gitignore, skyportal/tests/conftest.py
This PR adds the following automated behavior to the test suite:
1. When a test fails that uses the `driver` fixture, a screenshot is immediately captured showing the state of the screen on failure. These are saved to `test-results/`
2. When a test fails that uses the `driver` fixture, the web page source is immediately saved to `test-results/`.
3. On GA, the `test-results` directory is uploaded automatically as an artifact.
=> Automatically take screenshots and capture page source when tests fail 

skyportal/tests/tools/test_sky.py
Fixes the failure in this GA run https://github.com/skyportal/skyportal/runs/1244370861.
=> robustify astropy test that queries ADS

skyportal/tests/tools/test_sky.py
Fixes the error seen in e.g., this CI run: https://github.com/skyportal/skyportal/runs/1256432775
```
______________ ERROR collecting skyportal/tests/tools/test_sky.py ______________
skyportal/tests/tools/test_sky.py:36: in <module>
'skat': {'target': horizon_star, 'airmass': horizon_star_airmass},
E   NameError: name 'horizon_star' is not defined
```
related to #1093
=> Hotfix for airmass calculation tests

skyportal/handlers/api/source.py, skyportal/tests/frontend/test_sources.py, skyportal/tests/tools/test_offset_util.py, skyportal/utils/offset.py, static/js/components/StarList.jsx
Here, the full name of the source is preserved in the starlist. ZTF20abayrkw is outside of the public ZTF footprint so the DSS image is used as a backup/fallback. The source itself is bright enough (in the Gaia DR2) to qualify as an offset star (so it's also _o1). Notice that the source position and the offset position are slightly off (~30 mas)--the source position comes from the discovery position (and other astrometry of the event available) whereas the offset position comes from the ZTFref catalog position. The agreement is well within the tolerances expected for telescope offsets + guiding.
~~Please merge https://github.com/skyportal/skyportal/pull/1075 before this one.~~
- try to keep the full name of a source (for bookkeeping purposes)
- Add "Shane" format for starlist
- detect …
=> Starlist and finder fixes

doc/index.rst
This PR adds a link to the database migrations page in the docs
=> link database migrations page in docs

skyportal/handlers/api/source.py, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx, static/js/components/SourceSaveHistory.jsx
This PR adds save history to the source page, including tooltip for each group chip which shows who saved to each group when, as well as a table that can be displayed containing the entire save history (see screen capture demo below).
Closes https://github.com/skyportal/skyportal/issues/1083
=> Show source save history on source page

skyportal/app_server.py, skyportal/handlers/api/candidate.py, skyportal/handlers/api/internal/__init__.py, skyportal/handlers/api/internal/annotations_info.py, skyportal/tests/api/test_candidates.py, skyportal/tests/frontend/test_scanning_page.py, static/js/components/CandidateList.jsx, static/js/components/ScanningPageCandidateAnnotations.jsx, static/js/ducks/annotations.js, static/js/ducks/candidates.js
Implement filtering on annotation values on scanning page.
- Numeric annotation fields can be filtered for a provided range [min, max]
- Boolean annotations fields are filtered for `true` or `false`
- String annotations (and nested annotations converted to JSON strings) are filtered on exact matches for the string value provided.
=> Scanning page filtering on annotations

static/js/components/GroupSources.jsx
This fixes #1129 
```
TypeError: Cannot read property 'active' of undefined
if (0 === a.length)
return "No sources have been saved to this group yet. ";
var u = parseInt(r.id, 10)
, d = (null === (t = s.filter((function(e) {
return e.id === u
}
))[0]) || void 0 === t ? void 0 : t.name) || ""
, p = a.filter((function(e) {
return e.groups.filter((function(e) {
return e.id === u
}
))[0].active
}
```
=> Hotfix for group sources page 

static/js/components/RunSummary.jsx
This fixes a bug where only the first N elements were rendering in pullout rows on the observing run page, due to the use of rowIndex instead of dataIndex. So if there were 10 elements per page, the same 10 pullout rows would show on every page. This should map the pullout rows to the proper assignments on page number > 1
=> Fix observing run MUI datatable bug

data/db_demo.yaml, skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py
Until we can converge on the more long-term solution for the ra/dec bug we are seeing on fritz.science via #1132, this PR should fix the problem. It's just a simple change of the API validator to require that RA and Dec be nonnull in Source.POST and Candidate.POST.
=> Quick fix for null RA and Dec

skyportal/handlers/api/photometry.py
This PR locks the photometry table in SHARE ROW EXCLUSIVE mode when querying for duplicate photometry, inserting new photometry, and updating existing photometry via the API. This replaces the logic of transaction mode REPEATABLE READ and is an attempt to fix the bug shown here
```
Oct 21 21:21:48 fritz-1601421112-web-5fbf4d5bc6-xpxmk Fritz [!] Error in `/api/photometry`: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "deduplication_index" 
Oct 21 21:21:48 fritz-1601421112-web-5fbf4d5bc6-xpxmk Fritz     raise value.with_traceback(tb) 
Oct 21 21:21:48 fritz-1601421112-web-5fbf4d5bc6-xpxmk Fritz   File "/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context 
Oct 21 21:21:48 fritz-1601421112-web-5fbf4d5bc6-xpxmk …
```
=> lock the photometry table in SHARE ROW EXCLUSIVE mode to prevent concurrent data updates from K

skyportal/app_server.py, skyportal/handlers/api/__init__.py, skyportal/handlers/api/group.py, skyportal/tests/conftest.py, skyportal/tests/frontend/test_groups.py, static/js/components/AddUsersFromGroupForm.jsx, static/js/components/Group.jsx, static/js/components/NewGroupUserForm.jsx, static/js/ducks/groups.js
This PR adds a form to the group page that allows all users from selected group(s) to be added to a group.
A new back-end handler and associated endpoint (`/api/groups/<group_id>/usersFromGroups`) are added.
=> Implement form for adding all users from other group(s) to group page & associated back-end handler

skyportal/handlers/api/source.py, skyportal/models.py
This will keep the `Thumbnail` from being added to the DB w/ null `public_url`, and will instead re-try next time the source page is loaded.
=> Let PS1 thumbnail URL generation function error rather than silently return None

skyportal/handlers/api/observingrun.py, skyportal/models.py
Supersedes #1171, Fixes #1102 
This PR vectorizes the calculation of rise and set times of observing run assignments. Previously, this was being done one-by-one, and consequently took ~200ms per assignment. This PR should reduce this to ~200ms for the whole run.
=> vectorize calculation of ephemerides

skyportal/plot.py
Fixes #1051 .
This normalizes the spectra in the `spectroscopy_plot` function so they can be easily compared. The method used is to normalize by the integrated flux. 
Before: 
After:
cc @mansikasliwal @scizen9
=> normalize spectra by their integrated flux in source page spectroscopy plot

skyportal/models.py
Didn't catch this during development because our demo users don't have contact_email set initially (but the real users on production do) so the logic never reached the problematic line.
=> Fix source notification error associated with None user prefs

skyportal/handlers/api/observingrun.py
The observing run page was loading slowly due to an inefficient query that was sorting on unindexed columns that were not even needed to render the page. This PR fixes #1193. Fixes #1171 (and also is the true fix to #1102).
=> make observing run page load much faster

skyportal/handlers/api/candidate.py, static/js/components/CandidateList.jsx, static/js/components/FilterCandidateList.jsx, static/js/ducks/candidates.js
In this PR:
- Proper coercion of annotation filter values for fields that are booleans, strings, or nested objects
- Hook up the scanning page filter form (for groups and dates) state with the paging state in the MUI data table
Closes #1169 
Remaining known issue: 
Cannot have multiple filters set on annotation fields from different origins at the same time (i.e. cannot filter for `some_key (origin A): true` and `some_other_key (origin B): true` at the same time even if a candidate has both). Vague impressions is that this will require a bigger change to the sqlalchemy code for the candidates handler and more thinking than a quick change. Something like merge annotation rows into one big jsonb field so that one row knows it has both origins? Right now the queries technically look for …
=> Filtering fixes for scanning page

skyportal/handlers/api/candidate.py, skyportal/models.py, skyportal/tests/api/test_candidates.py
In this PR:
- In `/api/candidates.POST`, ingest `passed_at` into the db as `arrow.get(passed_at).datetime` (to preserve the current data model)
- Report filter_id,passed_at,passing_alert_id in `/api/candidates.GET` as in
=> Fix candidate passed_at parsing

skyportal/tests/conftest.py, skyportal/tests/tools/test_sky.py
We were using internal functions that are no longer available.
AstroPy now handles the caching internally, so we don't need these
fixtures any longer.
=> Remove caching and renewal of IERS table downloads

alembic/versions/f94174183e7e_add_spectrumreducers_and_.py, skyportal/handlers/api/spectrum.py, skyportal/models.py, skyportal/schema.py, static/js/components/UploadSpectrum.jsx
cc @mansikasliwal
This PR introduces a dropdown to the upload spectrum page that keeps track of who reduced and observed a spectrum. The uploader can select any number of users on the website from the menu to populate each field. This will make it easier to track who should be cited when a spectrum is used in a paper.
=> Record Users that reduced and observed a spectrum

alembic/versions/99822318096d_merge_886b65_and_f94174.py
This merges the two migrations that currently revise the same migration on master, going from 
```
(skyportal2) Dannys-MBP:skyportal danny$ alembic history
d0195eb7ecd0 -> 886b65e82e3e (head), Add user_acls join table
d0195eb7ecd0 -> f94174183e7e (head), add spectrumreducers and spectrumobservers
93d1e086aafb -> d0195eb7ecd0 (branchpoint), migration script for 1135
<base> -> 93d1e086aafb, Initial schema checkpoint
```
to
```
(skyportal2) Dannys-MBP:skyportal danny$ alembic history
f94174183e7e, 886b65e82e3e -> 99822318096d (head) (mergepoint), merge 886b65 and  f94174
d0195eb7ecd0 -> f94174183e7e, add spectrumreducers and spectrumobservers
d0195eb7ecd0 -> 886b65e82e3e, Add user_acls join table
93d1e086aafb -> d0195eb7ecd0 (branchpoint), migration script for 1135
<base> -> 93d1e086aafb, …
```
=> merge migrations 886b65_and_f94174

alembic/versions/1300e24dcfe9_scanning_page_filtering_updates.py, data/db_demo.yaml, skyportal/handlers/api/candidate.py, skyportal/models.py, skyportal/tests/api/test_candidates.py, skyportal/tests/conftest.py, skyportal/tests/frontend/test_recent_sources.py, skyportal/tests/frontend/test_scanning_page.py, static/js/components/CandidateList.jsx, static/js/components/FilterCandidateList.jsx, static/js/components/SaveCandidateButton.jsx
In this PR:
- change the scanning page filtering form to default to zero groups selected;
- apply date range filtering to `Candidate.passed_at` rather than `Obj.last_detected`;
- `Candidate.passed_at` is required both at the API level and DB level (and is now indexed);
- test updates
Closes https://github.com/skyportal/skyportal/issues/1226
Partially addresses https://github.com/skyportal/skyportal/issues/1223
=> Scanning page filtering updates

skyportal/app_server.py, skyportal/handlers/api/__init__.py, skyportal/handlers/api/acls.py, skyportal/handlers/api/roles.py, skyportal/handlers/api/user.py, skyportal/models.py, skyportal/tests/frontend/test_user_management.py, static/js/components/UserManagement.jsx, static/js/ducks/acls.js, static/js/ducks/roles.js
This PR expands the user management page by adding functionality for editing user roles and ACLs.
ACLs/roles handlers and associated endpoints are added.
Partially addresses https://github.com/skyportal/skyportal/issues/914
=> Update user ACLs and Roles via user management page

skyportal/tests/api/test_annotations.py
This PR fixes a transient failure in test_annotations.py::test_delete_annotation, which depends on the order the tests are run, as discovered by @stefanv:
=> Fix test_delete_annotation

static/js/components/StarList.jsx
This PR produces a significant speedup on the observing run page by only loading the starlist once, when the page first loads. Otherwise, any action to edit an assignment on the page force-reloads the starlist, causing simple operations to take a very long time to complete (e.g., 10 seconds to mark an assignment "observed".)
=> dont reload starlist anytime an assignment changes

static/js/components/RunSummary.jsx
This PR activates the upload spectrum link on the observing run actions menu
=> fix upload spectrum link on observing run page

static/js/components/CandidateList.jsx, static/js/components/RecentSources.jsx, static/js/components/TopSources.jsx
Properly ignore classifications with null probabilities on scanning page and home page widgets
=> Fix display of classifications with null probabilities

skyportal/handlers/api/comment.py
The current access model allows anyone with the `Manage groups` ACL to delete comments. This PR limits comment deletion to system admins and comment authors.
=> require system admin access or ownership for comment deletion

skyportal/handlers/api/observingrun.py, skyportal/tests/frontend/test_observing_planner.py, static/js/components/RunSummary.jsx
This PR fixes the group chip display on the observing run page. Fixes #1155. 
Whereas before long group names would be shown on the observing planner, causing groups to get cut off, and single user groups would be shown, this PR shows only group nicknames, and does not show single user groups. 
A test is updated to check that this is enforced.
=> fix group display on observing planner

skyportal/handlers/api/source.py
Don't include sources that were unsaved from the GET multiple sources handler.
Partially addresses #1303 and #1224 (likely fixes backend cause of the error, frontend patched in #1295)
=> Remove unsaved sources from source GET results

skyportal/handlers/api/internal/profile.py, static/js/actions.js, static/js/components/WeatherWidget.jsx
This PR removes initial weather fetching from `hydrate` to the weather component itself and refactors the fetching logic to minimize the number of requests when user preferences are updated.
Closes https://github.com/skyportal/skyportal/issues/1215
=> Improve weather fetching

.github/workflows/test.yaml
Most of the current GA builds are timing out. This PR increases the GA build timeout to 90 minutes from 45 minutes.
=> increase GA timeout to 90 minutes

skyportal/handlers/api/observingrun.py
The observing run page was loading quite slowly as an intermediate step in the `ObservingRun.get` handler was loading the `Obj.users` attribute for each assignment, which produced a record of ~100 users on fritz.science for each assignment, each of which had preferences loaded. This bloated the response size of a typical observing run.GET to ~20MB for, e.g., fritz.science/run/8. 
This PR prevents this data (which is not used at all on the frontend, and was never intended to be returned by this handler) from being returned. 
Fixes #1336 (hopefully).
=> Speed up observing run page

skyportal/handlers/api/spectrum.py
This fixes a small bug where spectra were being shared with correct groups via followup_request_ids, but the followup_request_ids themselves were not saved to the Spectrum objects through Spectrum.POST. Similar for Spectrum.assignment_id
=> track followup request id and assignment id in Spectrum object when posted through handler 

static/js/components/About.jsx
Pulls out just the MUI styling changes from #1184 (the templating changes in there are now obsolete given our new approach using a Fritz SP fork)
=> Use MUI Paper and Typography for About page

skyportal/handlers/api/source.py
This PR makes the compute-intensive part of the source offsets query asynchronous. This should vastly improve site stability and fix those intermittent 502s we have been seeing. 
Fixes #1349 (hopefully).
=> Make SourceOffsetHandler asynchronous

doc/index.rst
The quick start docs were missing the step where users logged in as provisioned admin to see any of the demo data. I added this to the docs.
=> fix quick start docs

alembic/versions/73ca57416d1c_index_saved_at.py, skyportal/handlers/api/source.py, skyportal/models.py, skyportal/tests/api/test_sources.py
This PR adds three new options to `SourceHandler.get`:
- in: query
name: savedBefore
nullable: true
schema:
type: string
description: |
Only return sources that were saved before this UTC datetime.
- in: query
name: savedAfter
nullable: true
schema:
type: string
description: |
Only return sources that were saved after this UTC datetime.
- in: query
name: saveSummary
nullable: true
schema:
type: boolean
description: |
Boolean indicating whether to only return the source save
information in the response (defaults to false). The schema
of this summary information is:
```
{
"group_id": 2,
"created_at": "2020-11-13T22:11:25.910271",
"saved_by_id": 1,
"saved_at": "2020-11-13T22:11:25.910271",
"requested": false,
"unsaved_at": null,
"modified": "2020-11-13T22:11:25.910271",
"obj_id": "16fil", …
```
=> Add savedBefore, savedAfter, and saveSummary query parameters to SourceHandler.get

skyportal/handlers/api/source_groups.py, skyportal/tests/frontend/test_group_sources.py, skyportal/tests/frontend/test_sources.py, skyportal/tests/frontend/test_weather.py, static/js/components/CandidateList.jsx, static/js/components/EditSourceGroups.jsx, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx
This PR changes the default behavior of the edit source groups handler by automatically saving the source as active if the requesting user has access to the target group, otherwise it is marked as inactive and requested. 
Instead of only user accessible groups, now all groups are shown in "save or request to save" part of dialog.
The wording displayed in the dialog is updated. 
See screen capture demo below.
Closes #1217
=> Change behavior of SourceGroupHandler.post and wording of EditSourceGroups

skyportal/handlers/api/source.py
This PR fixes a bug where an invalid obj ID was not caught soon enough and was passed to `register_source_view` and `add_ps1_thumbnail` before erroring.
Closes https://github.com/skyportal/skyportal/issues/1372
=> Fix source handler bug where invalid ID was not caught soon enough

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py, skyportal/tests/frontend/test_group_sources.py, static/js/components/GroupSources.jsx, static/js/components/SourceList.jsx, static/js/components/SourceTable.jsx
Adds sorting for source tables on the group sources page and the sources page (which all use SourceTable.jsx).
Partially closes [Fritz #100](https://github.com/fritz-marshal/fritz/issues/100) (There was a separate request in there about adding additional columns to the table; this PR is just sorting).
=> Implement server-side sorting for source tables

skyportal/tests/frontend/test_scanning_page.py, static/js/components/CandidateList.jsx, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx
Proposed re-skin:
- Focus user's attention on 1) object ID that when clicked always opens in a new tab 2) if it's saved 3) if it's classified:
That's how it looks like now:
=> Re-skin info section in CandidateList

data/db_demo.yaml, skyportal/handlers/api/group.py, skyportal/tests/frontend/test_groups.py, static/js/components/Group.jsx, static/js/components/InviteNewGroupUserForm.jsx, static/js/components/NewGroupUserForm.jsx, static/js/components/UserManagement.jsx, static/js/ducks/groups.js
This PR simplifies the logic of the `NewGroupUserForm` component by splitting the disparate cases it covered into two separate components -- one for adding existing users to the group, another for inviting new users to the site (& adding them to the group). This component was previously rather confusing both from a UX & DX perspective. The API is also updated to always use user ID instead of username for adding existing users to groups.
Closes https://github.com/skyportal/skyportal/issues/924
=> Refactor new group user & invite new user to group components; update API to use user ID instead of username

skyportal/__init__.py
If the SkyPortal version was modified to be, say,
"skyportal+myapp.123+git20100110.abcde", then we will only replace the
git tag, not the myapp tag.
=> Allow custom version tags

skyportal/tests/api/test_photometry.py, skyportal/tests/frontend/test_source_list.py
This PR updates the following: 
- Robustify  photometry API test that depended on response data ordering
- Increase maximum time delta for request that occasionally takes longer than previously-allotted time
=> Robustify tests

.github/workflows/build-and-deploy-docs.yaml
This aims to address the following error while starting the ssh-agent:
```
Error: Unable to process command '##[set-env name=SSH_AUTH_SOCK;]/tmp/ssh-auth.sock' successfully.
Error: The `set-env` command is disabled.
```
=> Update GA action versions

skyportal/handlers/api/internal/source_counts.py, static/js/components/SourceCounts.jsx, static/js/ducks/sourceCounts.js
Fix #1292 
Also just cleans up the `sourceCounts` redux store slightly (`since_days_ago` to `sinceDaysAgo` and setting initial to `null`).
=> Stop overwriting source counts prefs upon app reload

alembic/versions/2a17ca9d5438_add_fixed_location_col.py, alembic/versions/2a17ca9d5438_add_space_based_col.py, skyportal/models.py, skyportal/tests/conftest.py, skyportal/tests/frontend/test_observability.py, static/js/components/Observability.jsx
This PR keeps track of whether a given telescope is space based or ground based. If it is space based, it does not show the telescope's airmass plot on the observability page, partially addressing https://github.com/fritz-marshal/fritz-beta-feedback/issues/29.
=> Track whether a telescope is space based or ground based 

skyportal/handlers/api/observingrun.py, static/js/components/AssignmentForm.jsx
Addresses [Beta Feedback Issue #39](https://github.com/fritz-marshal/fritz-beta-feedback/issues/39).
On the source page, the options for "Assign Target to Observing Run" are now limited to observing runs whose end (the next sunrise after the run's calendar date) is after the current time.
=> Limit source assignment to upcoming observing runs

config.yaml.defaults
Most machines have at least 2 CPUs, including our test nodes on GitHub
Actions.
=> Increase default number of processes to 2

skyportal/handlers/api/followup_request.py
Currently the websocket message that updates the frontend after a followup request is successfully submitted to the telescope is dispatched using the wrong key, so never gets handled by the frontend's websocket message handler. This PR fixes this issue with a simple correction to use the correct key that the frontend looks for. I have tested this locally and verifies that it produces the expected behavior.
This PR fixes the CI. 
I am not sure why this did not cause the frontend / tests to fail earlier, this line has been as is for about 3 months. I guess the websocket message dispatched a few lines earlier was arriving later before, causing the `FETCH_LOADED_SOURCE` action dispatched by the frontend to hit the backend by the time the request was already submitted and the database updated. …
=> Hotfix websocket target for frontend

skyportal/handlers/api/observingrun.py, skyportal/plot.py
The current normalization scheme seems to result in gaps between spectra that should all be more or less on top of each other. This PR uses a much more stable normalization scheme, normalizing all spectra to a median flux of 1, to fix this issue.
=> Further improve normalization of spectra on spectroscopy plot

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/handlers/api/user.py, skyportal/models.py
The only place `User.preferences` is needed in the response data is in the profile handler, where it's already manually added to the response data
=> Override User.to_dict to not include preferences

skyportal/handlers/api/internal/plot.py, skyportal/handlers/api/observingrun.py, skyportal/handlers/api/spectrum.py, skyportal/plot.py, skyportal/tests/fixtures.py
The spectroscopy bokeh plot was not doing any ACL checking and was showing all spectra associated with an object rather than just the ones that were associated with any of the requesting user's groups. This PR fixes this by adding in an ACL check to the `spectroscopy_plot` function.
=> Fix permissions on spectroscopy plot 

package.json, requirements.txt, skyportal/plot.py
This PR:
* Fixes #1189 
* Fixes https://github.com/fritz-marshal/fritz/issues/111
* Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/52
* Partially addresses https://github.com/fritz-marshal/fritz-beta-feedback/issues/12
This PR introduces a new colormap for the spectrum plot to make the spectra easier to see. It shows the spectra as step functions rather than interpolated functions. It solves the problem of legend truncation. 
The step functions required an upgrade to the bokeh minor version patch (i.e., the third number in the semantic version). This is a minor thing and involves no changes to backwards compatbility. This is separate from #1293 which upgrades the bokeh major version.
=> spectroscopy plot improvements

skyportal/enum_types.py
Because they are not an Enum type used by postgres. Only by the webserver.
=> remove magsystems from enum types

static/js/components/CommentList.jsx
Address #957 
Comment substrings matching the emoji RegEx but not mapping to a legitimate emoji are now just let through.
@mcoughlin I think the main problem with what you were trying was that the "undefined" you were seeing printed was actually the javascript undefined property instead of a string that said "undefined" so your check wasn't working.
=> Fix emoji parsing for non-emoji colons in comments

skyportal/handlers/api/comment.py, skyportal/tests/api/test_comments.py
This PR deprecates parsing redshifts inside comments in favor of using the redshift frontend tool #1043
=> remove redshift parsing from comment handler

skyportal/handlers/api/spectrum.py, static/js/components/SourceTable.jsx
The API call to get a spectrum returns, by default, the original spectrum as is. 
If you want to normalize it, add a query argument ?normalization=median
Additional normalization schemes are easy to add in the back end. 
Currently this is used in the SourceTable component, where we provide this argument to the URL given to the VegaSpectrum.
=> Spectra normalization

skyportal/handlers/api/annotation.py, skyportal/handlers/api/candidate.py, skyportal/handlers/api/classification.py, skyportal/handlers/api/comment.py, skyportal/handlers/api/followup_request.py, skyportal/handlers/api/internal/plot.py, skyportal/handlers/api/internal/recent_sources.py, skyportal/handlers/api/internal/source_views.py, skyportal/handlers/api/internal/token.py, skyportal/handlers/api/observingrun.py, skyportal/handlers/api/photometry.py, skyportal/handlers/api/source.py, skyportal/handlers/api/source_groups.py, skyportal/handlers/api/spectrum.py, skyportal/handlers/api/thumbnail.py, skyportal/models.py
This is the first in a series of several PRs that refactor the source/obj/candidate/permissions handlers. This one simply renames the verbiage we use to indicate that a database record is readable to a user from `owned` to `readable`, laying the groundwork for methods that will refactor the readability logic for several mapped classes.
=> Source, Obj, Candidate, and Permissions Handler Refactor #1: Rename Owned -> Readable

Makefile, skyportal/openapi.py, tools/openapi/build-spec.py
This lets us update the Fritz API docs title and URL (using this mechanism will be a separate Fritz PR, once this PR is merged)
=> Customizable API docs

skyportal/handlers/api/source.py, static/js/ducks/source.js
This PR adds an optional `includeComments` query parameter to `SourceHandler.get` which defaults to `False`, and never ships comment attachment bytes.
Closes https://github.com/skyportal/skyportal/issues/1464
=> Add includeComments (default = false) query param to sources API and never include attachment data

requirements.txt, skyportal/utils/offset.py
Push to Gaia EDR3 (`gaiaedr3`). Also, adds an abstraction layer for Gaia queries: first try the ESA TAP+ portal via astroquery, then drop back to `gaia.aip.de` TAP.
=> GaiaQuery abstraction; push to Gaia EDR3

static/js/components/About.jsx
This can go in the docs, but for most hosted instances it doesn't make sense.
=> Remove instructions on how to change cosmology

static/js/components/Main.jsx.template, static/js/components/Source.jsx
By default, the window title is the app title.  Switching to a source
changes it to the source's name, and navigating away restores the app
name.
Closes https://github.com/fritz-marshal/fritz-beta-feedback/issues/71
=> Change window title to viewed source name

data/db_demo.yaml
@scizen9 was running into this bug locally when trying to access source pages through the web interface  (the error was being flashed as a notification)
https://github.com/astropy/astropy/issues/8788
we found that the reason for this is that when the main IERS mirror at NASA GSFC is down, it reverts to a backup mirror which serves a file that only has IERS data until 2020-08-22, which is not sufficiently late in time to calculate ephemerides for targets on runs in the demo data set (june 2021). The main IERS file from GSFC goes out till 2022, so it worked in that case.
This PR fixes that issue by moving the dates of the demo runs back in time so that they are within the period of IERS coverage for both the main and backup files.
=> make demo observing runs earlier in time to avoid running into outdated IERS file exceptions

skyportal/tests/api/test_photometry.py
Object photometry used to be returned in MJD order, an assumption that went into this test
https://github.com/skyportal/skyportal/runs/1535057564#step:13:579
However, that was removed at some point for performance reasons, so the comparisons in the failing test above were comparing photometry points of different IDs.
This PR sorts the photometry by MJD order in that test so that the correct photometry points are compared.
=> Ensure photometry is returned in the correct order for photometry api tests 

static/js/components/FilterCandidateList.jsx
- Set the default end date for scanning page to null
- Addresses #1493 
- Address console error introduced in #1476 regarding the `labelId` property on classifications and redshift filtering.
- Address console warning about `startDate` and `endDate` not passing a defaultValue to either the Controller or the useForm
Scanning page tests now all passing locally for me.
=> Set default end date for scanning to null

static/js/components/CommentAttachmentPreview.jsx
Catch JSON parsing errors for comment previews and display the error message instead.
Closes #1494
=> Catch JSON parsing errors for comment previews

skyportal/handlers/api/internal/source_views.py, skyportal/handlers/api/source.py
This PR ensures that the same permission check that is used in SourceHandler.get is used in SourceViewHandler.post, so that if a user is able to view a source page, an associated source view is registered without a permission error. Also, the source view registration for token requests is now performed after ensuring the source ID is valid.
Closes https://github.com/skyportal/skyportal/issues/1503
=> Use Obj.get_if_readable_by to determine source view handler permissioning rather than Source.get_obj_if_readable_by

skyportal/tests/frontend/test_group_sources.py, skyportal/tests/frontend/test_top_sources.py, static/js/components/GroupSources.jsx, static/js/components/SourceList.jsx, static/js/components/SourceTable.jsx
For the SourceTable.jsx component and the pages that use it (Sources and GroupSources):
- Save sorted column info across page changes (pass sort state to pagination handlers)
- Save displayed column info across component re-renders
- Properly detect and display sources that have no photometry points
Address https://github.com/fritz-marshal/fritz/issues/135
Also:
- Clean up `test_top_source_prefs` to use a `data-testid` XPATH instead of current one that was ambiguous and leading to flakiness
=> Properly save state across page changes in sources table

static/js/components/ManageDataForm.jsx
This PR fixes a bug where some spectrum files would not be properly encoded for download due to inclusion of characters that were not handled by `encodeURI`. 
The solution here casts these to blobs and then encodes those to plaintext urls using `URL.createObjectURL` as recommended by https://javascript.info/blob#blob-as-url. 
Tested this locally and it fixes the issue.
=> Fix encoding of plaintext spectrum data

skyportal/tests/frontend/test_profile.py
Test failure with `test_insufficient_name_entry_in_profile` was due to a fixture change - was testing empty first names in the profile form, but the user fixture was changed in #1253  to initialize users with a random first name
=> Fix broken profile test

skyportal/model_util.py
So that we can ensure that names are rendering as expected during local development, e.g. in the news feed:
=> Give provisioned-admin user a first and last name

requirements.docs.txt
A bug in 3.4.0 has been patched, but patch is not yet included in a release. https://github.com/sphinx-doc/sphinx/pull/8569
=> Temporarily pin sphinx==3.3.1

static/js/units.js
Fixes this issue reported by  dan perley:
Hi all, I think there is a major bug with the reporting/formatting of sexagesimal coordinates: as of right now, the coordinates of ZTF20acytfkf on its sources page (https://fritz.science/source/ZTF20acytfkf) are reported as:
05:02:33.6 +15:36:24.15 (α,δ= 75.6377796, 15.606709)
But I think the sexagesimal string conversion of the decimal coordinates should actually be
05:02:33.06
... which is an offset of order 10 arcseconds!
=> fix coordinate formatting

skyportal/handlers/api/news_feed.py, skyportal/tests/frontend/test_newsfeed.py, static/js/components/NewsFeed.jsx, static/js/components/RecentSources.jsx, static/js/components/SourceCounts.jsx, static/js/components/TopSources.jsx, static/js/components/UpdateProfileForm.jsx, static/js/components/WidgetPrefsDialog.jsx
This PR makes the news feed categories configurable via the widget preferences dialog form, and refactors that form to accommodate both text fields and checkbox groups (represented by an object whose keys are value names, and values are `true`/`false`, corresponding to checked/unchecked). A test is added.
Closes #1518 
Closes #1519 
Partially addresses #1383
=> Make news feed categories configurable via associated WidgetPrefsDialog

skyportal/models.py, skyportal/tests/api/test_sources.py
- The `flux` column of the `Photometry` model defines a default value of `'NaN'` and is not nullable. Thus, we should be checking for `nan` float values when looking for valid flux points instead of something like `self.flux is not None` or `if self.flux:`. For example:
- Additionally, Postgres considers NaN values to be greater than all non-NaN values, while python will properly return false for all comparisons against NaN:
(https://www.postgresql.org/docs/9.1/datatype-numeric.html)
This PR addresses issues stemming from these two points by using `np.isnan()` to check for NaN flux points instead of checking for `None` values in the python side of relevant hybrid properties, and using ` != 'NaN'` instead of `!= None` in the SQL expressions of the hybrid properties.
=> Correct hybrid properties dealing with 'NaN' flux values

skyportal/handlers/api/source.py, static/js/components/GroupSources.jsx, static/js/components/SourceTable.jsx, static/js/components/VegaSpectrum.jsx, static/js/ducks/sources.js
This PR fixes a few issues with plotting on the source tables (group sources and source list):
- empty photometry and spectra are now replaced with some text saying they're empty. 
- spectrum did not load in the VegaSpectrum because the API was changed.
=> Empty spectra in source table

.github/workflows/build-and-deploy-docs.yaml
I recently used your CI recipe for building/deploying documentation across repos [for another project](https://github.com/pygraphviz/pygraphviz/blob/master/.github/workflows/deploy-docs.yml) (thanks!)
One thing I noticed when setting this up is that, with the current configuration, I was getting failed workflow notifications whenever I pushed to master on my fork (e.g. when syncing with upstream) due to `secrets` not being set up on my fork. We didn't actually want the build+deploy job to run on forks - I found that adding the proposed line to the config is a nice way to prevent this from happening.
I'm not sure if you've experienced similar issues, but on the off chance that you have I thought I'd share our solution. Note also that if you still want the build to run and just suppress the …
=> CI: suppress doc build/deploy on forks

static/js/components/UserAvatar.jsx, static/js/components/UserProfileInfo.jsx
Update the user avatar and profile page name display to properly format Korean names. Korean names are generally written in last name, first name order with no space in between; a more natural (to a Korean speaker) set of initials for a Korean name would just be the full first name as first names are almost always <=2 characters in length and seeing first name -> last name order of the characters is strange (given the short length of names I don't think I've actually seen Koreans use "initials" in the manner of English names at all). 
Addresses #1567
=> Add support for Korean user names

skyportal/tests/frontend/test_observing_planner.py
Attempts to address frequent failures such as https://github.com/skyportal/skyportal/runs/1663491869#step:13:542
=> Increase timeout for assignment select in observing planner test

skyportal/plot.py
Adds an origin label to the photometry plot legend so people can see what pipeline  produced a particular photometry point
=> group by origin (if exists) in photometry plot

skyportal/plot.py
From 1 to 2 to address this request from @agoobar:
> The spectroscopy redshift slider/lines seem to stop at z=1. Can this please be expanded?
=> increase range of redshift slider

requirements.docs.txt
Closes https://github.com/skyportal/skyportal/issues/1528
=> Pin sphinx to 3.4.3, skipping over broken release

.github/workflows/build-and-deploy-docs.yaml
I accidentally used the wrong keyword in the doc deploy workflow in #1538 which is suppressing the doc deployment.
Reference: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
=> Fix conditional for CI doc deploy

skyportal/handlers/api/comment.py, skyportal/models.py
This fixes a critical bug affecting the fetching of Objs/Candidates.
The docstring for (`Source.get_obj_if_readable_by`) `get_source_if_readable_by` (which `Obj.get_if_readable_by` calls) states that it should  
> Return an Obj from the database if the Obj is a Source in at least
one of the requesting User or Token owner's accessible Groups. If the Obj is not a
Source in one of the User or Token owner's accessible Groups, raise an AccessError.
If the Obj does not exist, return `None`.
This fix brings the actual functionality in line with what is expected and what is stated in the docstring.
Closes #1535
=> Fix permissions-checking bug affecting fetching of Candidates/Sources/Objs

skyportal/models.py
It was added to `models.py` by mistake in #1599, but was already present there, with a different footprint, which is causing some issues on the frontend.
=> Remove mistakenly added another get_obj_annotations_readable_by in models.py

static/js/components/SourceTable.jsx
This is done by replacing `<a>` elements with `<Link>` elements.
Other changes:
- Add links to group chips
- Replace MaterialUI Link with React Router Link.
- Remove extraneous returns from arrow functions to satisfy linter.
=> Avoid navigating away from page in SourceTable

skyportal/handlers/api/comment.py, skyportal/handlers/api/group.py, skyportal/handlers/api/group_admission_request.py, skyportal/tests/frontend/test_notifications.py, static/js/components/Notifications.jsx
For now, just adds italicization to source/group/user names in message text.
Closes https://github.com/skyportal/skyportal/issues/1618
=> Render markdown in browser notifications text

static/js/components/CandidateList.jsx
Closes https://github.com/skyportal/skyportal/issues/1600
=> Preserve column view selection when paginating on scanning page

static/js/components/ThumbnailList.jsx
I added the little green cross-hairs (reticle) to all thumbnails, except SDSS which already has that. 
The old files in the demo data have a built-in cross-hairs so there's two sets in my instance of SkyPortal. I think this will go away for newer data where the thumbnails don't have anything on them.
=> cross hair to all thumbnails

skyportal/utils/offset.py
When a detection with null photometry coordinates  is used to calculate the best position for offset stars in https://github.com/skyportal/skyportal/blob/master/skyportal/handlers/api/source.py#L1309, the resulting `best_ra` and `best_dec`, will be `nan`. This can cause the offsets handler to fail and prevent StarList components from rendering properly.
=> handle phot ra,dec being sometimes being none in offfsets handler

static/js/components/CandidateList.jsx, static/js/components/FilterCandidateList.jsx
- The annotation filtering form properly validates against the program selection (it was still using all accessible groups by default)
- The annotation filtering state is passed along to FilterCandidateList.jsx so that the annotation filtering is persisted when you change the date range for scanning, for example.
- Fixed bug where on initial render of the scanning page, the annotation filtering logic was unaware of the initial FilterCandidateList form values (ie default start date). 
Closes #1653
=> Fix various scanning page bugs

requirements.txt
Some pinned reqs are causing trouble: https://github.com/fritz-marshal/fritz/runs/1867100185#step:6:2691 (conflict with https://github.com/cesium-ml/baselayer/blob/master/requirements.txt#L7)
Putting out this fire in this PR, but I suggest to loosen more requirements, otherwise we'll likely encounter similar problems in the future.
=> Loosen pip requirements

skyportal/plot.py
Upon startup or hard refresh, phase plot shows both phase 'a' and phase 'b' even though 'One phase' is selected.  Plot x-axis limits are correct, but phase 'b' data visible.  This PR fixes this and initially sets phase 'b' data to visible=False.
=> fix inital display of phase 'b'

skyportal/handlers/api/group.py, skyportal/tests/api/test_groups.py
Currently a GET call to `/api/groups/<group_id>` return the full list of group members with all their info, which could be hundreds of potentially unwanted entries.
=> Make including group users optional in GET /api/groups/<group_id>

skyportal/plot.py
Addresses issue [#87](https://github.com/fritz-marshal/fritz-beta-feedback/issues/87) by adding UTC time to date in spectrum plot hover.
=> added time to date in spectrum plot hover

skyportal/handlers/api/invitations.py
Before, the user would see a cryptic error message. Now:
=> Catch SMTP auth failure & return informative error message

skyportal/handlers/api/db_stats.py
Closes #1692 
Autovacuum is enabled by default, so we don't need to run `ANALYZE` as a cron job, as autovacuum already does that. Confirmation that we have autovacuum enabled on production:
```
fritz-1=> SHOW autovacuum;
autovacuum               
------------              
on                       
(1 row)                   
```
=> Use approximate photometry table count in DB Stats page for improved performance

skyportal/handlers/api/candidate.py
=> Order candidates by passed_at rather than last_detected_at for improved performance in CandidateHandler.get

static/js/components/FilterCandidateList.jsx
On the scanning page, once an end date had been selected, it could not be cleared without being marked as invalid & preventing form submission. This PR fixes that.
Before:
After:
Closes https://github.com/skyportal/skyportal/issues/1729
=> Allow scanning page end date to be nullified

config.yaml.defaults, jobs/count_unsaved_candidates.py
For informational (results are viewable on DB Stats page) & cron service debugging purposes.
=> Add hourly cron job that counts old, unsaved candidates/objs

skyportal/models.py
I had been seeing SQLA warnings saying something like "`delete` is required when specifying `delete-orphan` in `cascade`", and this is the only relationship in which we specify `delete-orphan`
=> Update SQLAlchemy relationship cascade params in Obj.classifications

skyportal/handlers/api/candidate.py
Closes #1733 
Another alternative would be to error if the user provides a `numPerPage` value higher than the cap.
=> Cap num candidates per page at 500

static/js/components/ClassificationForm.jsx, static/js/components/FavoritesButton.jsx, static/js/components/FollowupRequestForm.jsx
This PR disables the submit buttons for the classification form, followup request form, and favorite source star while a request is in process.
Closes #1562
=> Disable submit buttons while request in process

skyportal/tests/frontend/test_periodogram.py, static/js/components/Periodogram.jsx
- Handle the case where there is not much data observed over a very long time period, producing a more robust delta_t
- Handle the case when there is only a few data points (fixes what @dmitryduev found with a single photometry point). In that case, do not render the periodogram.
- ensure that we're only doing as many as 300,000 calculations (~<5 seconds in a modern browser)
- render the new light curve after resetting parameters.
=> Small fixes for the periodogram page

static/js/components/GroupUsers.jsx
The "Name" column was broken on the GroupUsers table and did not display names and sorting/filtering on it did not work as intended. This PR addresses the issue and closes #1745
=> Fix group member name display/sorting/filtering

skyportal/plot.py, skyportal/tests/frontend/test_upload_spectroscopy.py
Closes fritz-marshal/fritz-beta-feedback#13
Spectroscopy plot labels now only show the telescope name (only the instrument) and uses a more concise date formatting. Note that the telescope name is still available on the hover tool.
One question regarding this - do we have more US users or European users? Does MM/DD/YY formatting or DD/MM/YY make more sense?
=> Shorten spectroscopy legend labels

skyportal/handlers/api/group.py, static/js/components/GroupPageManageUserButtons.jsx, static/js/components/GroupUsers.jsx
This PR updates the permissions regarding modifying group members' admin status such that any group admin (regardless of ACLs) can grant/revoke the admin status of other group members, or remove users entirely.
Closes https://github.com/fritz-marshal/fritz/issues/191
=> Allow group admins to manage other group members

skyportal/app_server.py, skyportal/handlers/api/candidate.py, skyportal/tests/api/test_candidates.py
This PR updates the candidates API for DELETE requests such that resources to be deleted are now specified by `(obj_id, filter_id)` rather than the previously-used `Candidate.id`, which is impossible to obtain via the API.
Closes https://github.com/skyportal/skyportal/issues/1762
=> Update candidates DELETE API

skyportal/handlers/api/source.py, static/js/components/CandidateList.jsx, static/js/components/SaveCandidateButton.jsx
This PR updates the scanning page for candidates that are already saved to at least one group in the following way: If a candidate is already saved to at least one group but is not yet saved to **all** of the groups being scanned (those groups selected in the filter form), then the "Save to ..." button is now displayed in addition to the "Manage Groups" button, with those groups the source is already saved to being filtered out of the "Save to" groups (this applies both to the default button action and the "Edit groups and Save" groups list). 
In this screenshot I was scanning all three groups (i.e. "Program A", "Program B" and "Sitewide Group" were all selected in the candidate search form). Note that those groups that the source is already saved to are filtered out of the "Save to" …
=> Show save candidate button alongside manage groups button on scanning page when relevant

skyportal/handlers/api/internal/plot.py, skyportal/plot.py, static/js/components/SourceMobile.jsx, static/js/plotjs/download.js, static/js/plotjs/foldphase.js, static/js/plotjs/stackf.js, static/js/plotjs/stackm.js, static/js/plotjs/togglef.js, static/js/plotjs/togglem.js, static/js/plotjs/togglep.js
This PR re-introduces the changes in the reverted #1758 (refactoring the legend to use the legend component instead of checkboxes to support better colors and markers), and makes adjustments to the photometry plot layouts to make it properly responsive. This includes changes previously included in the closed #1759 PR, as well as new changes necessitated by the changes in #1758.
- Both photometry and spectroscopy plots now dynamically adjust height on smaller screens
- The spectroscopy plot was actually already doing this - I just removed the height parameter being passed in and going unused.
- The photometry plot now computes a height proportional to the number of instruments/filters as the legend is moved below the plot on smaller screens and thus will alter the needed height.
- The …
=> Re-introduce new photometry plot legend and make it responsive

static/js/components/HomePage.jsx.template
Wait until user preferences have been fetched before rendering the home page. Before, the default layouts were being rendered first because the user preferences hadn't been fetched yet; this caused the default layouts to be automatically saved to the preferences and override what was already there.
Closes #1612
=> Fix loading of user dashboard layout preferences

skyportal/handlers/api/spectrum.py
Prevents tracebacks like these from appearing in the logs
```
ERROR:tornado.application:Uncaught exception POST /api/spectrum/parse/ascii (127.0.0.1)
HTTPServerRequest(protocol='http', host='fritz.science', method='POST', uri='/api/spectrum/parse/ascii', version='HTTP/1.0', remote_ip='127.0.0.1')
Traceback (most recent call last):
File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "/skyportal/baselayer/app/access.py", line 32, in wrapper
return tornado.web.authenticated(method)(self, *args, **kwargs)
File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
return method(self, *args, **kwargs)
File "/skyportal/baselayer/app/access.py", line 51, in wrapper
return …
```
=> catch error for bad encoding on spectrum files

skyportal/plot.py
Unfortunately, the Bokeh plot is plotted with some `position: absolute` styling, so it wasn't straightforward to just get the div with the buttons to get pushed down reactively. 
The overlapping button issue is only with photometry plots without the period tab. I'm not sure exactly which plot widgets the extra needed height is coming from but adding some extra height to the plot layout appears to fix the issue. I was adding similar padding for the plots with periods but my reasoning for those were the extra text fields in the period tab so not exactly sure why the similar padding is needed here but I'll investigate that more later.
=> Add padding for non-period photometry plots

skyportal/tests/frontend/test_upload_spectroscopy.py
The new legend in the spectroscopy plot goes into the plot's `<canvas>` tag so can't be probed directly with an xpath like we used to. This PR fixes `test_upload_spectroscopy` by just going to the "Manage Data" page to check for successful spectrum upload.
=> Fix test_upload_spectroscopy

skyportal/plot.py
Closes fritz-marshal/fritz-beta-feedback#91
Should also close #1803 
Use the `frame_width` parameter instead of `width` in the photometry/spectroscopy plots to remove the legend from width/aspect ratio calculations. Also some other minor tweaks to the plot layouts (spectroscopy sliders are slightly narrower to account for padding; labels wrap to next line a little earlier)
=> Use frame width for plot scaling

skyportal/handlers/api/photometry.py, skyportal/schema.py, skyportal/tests/api/test_photometry.py
This PR fixes & greatly simplifies how altdata is handled in `PhotometryHandler.post`. Now, a list of objects can be provided or a single object can be broadcasted to all photometry points. Tests are added.
Closes https://github.com/skyportal/skyportal/issues/1814
=> Fix handling of photometry posted with altdata

skyportal/handlers/api/sysinfo.py, skyportal/tests/utils/test_gitlog.py, skyportal/utils/gitlog.py, static/js/components/About.jsx
To facilitate this, we now store git logs in JSON files, instead of as
text files.  Each JSON file contains some meta-data about the git log
(where to link PRs and commits to, what the project is called) as well
as the entries to the git log itself.
=> Allow listing git logs from multiple projects

doc/permissions.md, skyportal/app_server.py, skyportal/handlers/api/candidate.py, skyportal/handlers/api/facility_listener.py, skyportal/handlers/api/photometry.py, skyportal/handlers/api/source.py, skyportal/handlers/api/taxonomy.py, skyportal/models.py, skyportal/plot.py, skyportal/tests/api/test_candidates.py, skyportal/tests/api/test_sharing.py, skyportal/tests/api/test_taxonomy.py, skyportal/tests/api/test_telescope.py, skyportal/tests/conftest.py, skyportal/tests/frontend/test_weather.py, skyportal/tests/models/test_permissions.py
Merging https://github.com/cesium-ml/baselayer/pull/207 turned on automated permission checking for create, read, and update operations after they were unintentionally disabled since https://github.com/cesium-ml/baselayer/pull/184. Enabling these automated checks revealed a series of security vulnerabilities in skyportal that allowed API access to protected user data (photometry, spectra, etc.) and protected operations on user data (delete, update, etc.). 
The fix also revealed instances in which assumptions in the test suite violated underlying assumptions about the data model. 
This PR patches many of these up. The specific issues fixed in this PR include: 
* The candidate API GET endpoint had a major spectroscopy and photometry leak, returning all spectra and photometry regardless of …
=> Patch security vulnerabilities and data model violations revealed by test suite after enabling UACL

skyportal/handlers/api/candidate.py
To hotfix permission issues on production
=> Temporarily disable security checks in GET candidates

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/models.py, skyportal/tests/api/test_candidates.py, skyportal/tests/api/test_sources.py
This PR refactors the detection hybrid properties in the `Obj` class to hybrid methods which take in a user instance so that those are computed based on accessible Photometry rows instead of all rows. The Candidates and Sources GET handlers were updated to reflect this; this should take care of Photometry leaks in those handlers. Also added/updated some tests to check that hidden photometry data isn't reflected in returned candidates/sources.
I don't think I touched anything that you did in your #1833 PR @acrellin so we shouldn't have any merge conflicts. I also didn't uncomment the `self.verify_and_commit()` lines in the SourcesHandler, as that'll be done by that PR.
Finally, set `read = accessible_by_groups_members | accessible_by_owner` on Photometry rows to make it clear that whoever …
=> Control access to Photometry via Obj hybrid properties

doc/advanced_usage.md
This adds a `docs/advanced_usage.md` file with a single section (for now). 
The section shows an example of using the API to post an annotation. 
In this case the example is for adding Gaia data so that the source will have an HR diagram.
=> documentation HR diagrams

doc/dev.md, doc/permissions.md
1. give correct path to test_frontend.py in dev.md
2. close delimiter for code clip in permissions.md
=> Minor fixes to docs in dev.md and permissions.md

skyportal/handlers/api/internal/annotations_info.py
Since Objs are read public, we can actually skip the candidate filter check entirely, and just check for group membership in `GroupAnnotations`. I tried using `Annotation.query_rows_accessible_by()` but it was like 2x slower than doing it manually like this, at least on the demo data (maybe because read access on annotations has  `AccessibleIfRelatedRowsAreAccessible(obj='read')` defined and public access queries are still slower than not querying it at all).  On the demo data, I'm seeing ~2ms per call with this new version compared to ~7ms on the original query. 
Also, I held off on adding `self.verify_and_commit()` to this as that will only add to the time and it is basically just double-checking the access logic which should already be correct in the main query. I figured we could see …
=> Optimize annotations_info query

skyportal/handlers/api/candidate.py, skyportal/tests/api/test_candidates.py
This PR adds the `count()` query for `totalMatches` in the candidates query to the main query so that they are just called once together instead of essentially calling the same query twice. The block to check for out-of-range page numbers is moved to below the main query since now we don't know the total count beforehand. Also added a test for the pagination on the candidates query.
=> Combine count and limit/offset queries for scanning

data/db_demo.yaml
There are some discrepancies in users and stream access permissions within the current demo data. 
The following were addressed:
- Group A is marked as needing access to the `ztf_partnership` stream, but its members only have access to the `ztf_public` and `ztf_caltech` streams. Now these users have partnership stream access as well.
- `viewonlyuser` was not really special, as they were put in Group A (which requires partnership access) and given access to the Caltech stream. The user was moved to Group B (which only requires public stream access) and their access to the partnership and Caltech streams removed.
=> Fix user/group/streams in demo data

skyportal/model_util.py
Add the "Annotate" ACL to the corresponding roles.
=> Allow Group admins and Full users to annotate objs

skyportal/handlers/api/candidate.py
The root of the candidates list pagination test failing sometimes was that the default ORDER BY on `Candidates.passed_at` was being done on the wrong thing. Instead of the candidates in the candidates subquery, it was trying to order on the base `Candidates` table and was again introducing the `Candidates, Obj` cross-join we saw yesterday.
=> Fix candidates query ordering

skyportal/handlers/api/instrument.py, skyportal/handlers/api/observingrun.py, skyportal/tests/api/test_observing_runs.py, skyportal/tests/conftest.py
Refactor the `instrument.py` and `observingrun.py` handlers to use new permissions system. Also added a test for observing runs to make sure it doesn't leak groups nested in the run's assignments.  
@dannygoldstein There was a TODO comment about not turning on verify_and_commit here until the refactor due to "changes to persistent records that shouldn't be flushed". I wasn't sure if I followed exactly what you meant by that - let me know if there's anything more I need to do here.
=> Update permissions for instrument and observing run handlers

static/js/components/CandidateList.jsx
Annotation filtering on the scanning page does not support filtering across multiple annotation origins. As this doesn't seem to be a common use case, it seems fine to just make note of the limitation within the column tooltip.
Closes #1185
=> Update scanning page annotations tooltip to note known limitation

skyportal/handlers/api/candidate.py
I think this is the cleanest and most efficient fix: limits the subquery to just the Source records we actually need
Also removes an unnecessary `.filter(Group.id.in_(user_accessible_group_ids))` since we were already doing `Group.query_accessible_records_by`
=> Fix candidates saved groups

skyportal/handlers/api/source.py
Have been seeing a lot of 
```
Traceback (most recent call last):                                                                      
File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute              
result = method(*self.path_args, **self.path_kwargs)                                                
File "/skyportal/baselayer/app/access.py", line 32, in wrapper                                        
return tornado.web.authenticated(method)(self, *args, **kwargs)                                     
File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper               
return method(self, *args, **kwargs)                                                                
File "/skyportal/skyportal/handlers/api/source.py", …
```
=> Ensure source table row is not None before accessing attrs

skyportal/handlers/api/photometry.py, skyportal/schema.py, skyportal/tests/api/test_photometry.py
Closes https://github.com/skyportal/skyportal/issues/1861
Closes https://github.com/skyportal/skyportal/issues/1839
=> Do not allow negative `fluxerr` values in photometry POST handler

static/js/components/SurveyLinkList.jsx
WISE link had characters unintentionally deleted (restored) and the TNS link now points to current correct website.
Closes https://github.com/skyportal/skyportal/issues/1771
=> fixed typo in WISE link and updated TNS link in SurveyLinkList.jsx

data/db_demo.yaml, skyportal/handlers/api/group.py, skyportal/handlers/api/stream.py, skyportal/models.py, skyportal/tests/api/test_groups.py, skyportal/tests/api/test_streams.py, skyportal/tests/conftest.py, skyportal/tests/frontend/test_groups.py, skyportal/tests/models/test_permissions.py
This PR makes use of the framework developed in https://github.com/cesium-ml/baselayer/pull/207/ to enforce the following rules for Group / User / Stream membership:
1. A user can only join a group if they have access to all of the group's streams. 
2. A stream can only be removed from a group if none of the Group's filters currently filter the stream.
3. A stream can only be added to a group if all of the group's members have access to the stream.
4. A group user's admin status can only be modified by group admins.
5. Only a group admin or the target user can remove a user from a group.
6. Only system admins can grant and revoke stream access to users. 
7. Only a group admin can add a user to a group.
8. Users cannot add streams to single user groups.
9. No one can remove a user from …
=> Implement stream / group / user access logic and update group and stream handlers

skyportal/tests/frontend/test_remote.py, skyportal/tests/frontend/test_source_list.py, static/js/components/HomePage.jsx.template, static/js/components/WeatherWidget.jsx
A couple of tests have failed occasionally if they are run in a certain order such that no non-fixture sources from the other tests have been inserted into the test database, due to the page showing the `UninitializedDBMessage.jsx` component instead of the expected page. 
You can see `test_weather_widget` and `test_add_sources_two_groups` failing in such a manner [here](https://github.com/skyportal/skyportal/pull/1793/checks?check_run_id=2364225192).
This PR fixes that by 
- Remove the `UninitializedDBMessage.jsx` on the Home Page. Now that we have widgets like the `SourceCounts.jsx` on the dashboard, that will appear to display correct information even on an empty database, I don't think we need to overwrite all that to show a message that says "the Sources table is empty". The message …
=> Fix flaky tests associated with UnitializedDBMessage

skyportal/app_server.py
Each app instance launches ~10 threads (found by trial and error—we haven't been able to figure out how to control the number of threads exactly).  Each thread gets 2 connections, for when that thread spins off another job such as the PS1 loader.
=> Increase default DB connection pool

skyportal/facility_apis/sedm.py, static/js/components/EditFollowupRequestDialog.jsx, static/js/components/FollowupRequestForm.jsx, static/js/components/FollowupRequestLists.jsx
Closes fritz-marshal/fritz#141
This PR addresses this list of issues with the SEDM follow-up request forms per user feedback:
- Not sure about this one - the default is already set to `utcnow()`, and was unable to recreate issue locally. My only guess is that the user is in a timezone ahead of UTC, so the default date may appear to be in the past. But since we specify that the field is in UTC I think this is fine as is.
- When editing an existing request, the form is populated with the current values instead of the default ones  
- This has already been addressed by the permissions refactor
- Custom validation has been added to the front-end to check for this
=> Address various issues when adding/editing SEDM requests

static/js/components/VegaPlot.jsx
This will fix occasional apparent data points from the future (has been reported a few times + I think I saw that myself).
=> Fix mjdNow computation in VegaPlot.jsx

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/schema.py
Closes https://github.com/skyportal/skyportal/issues/1905
Closes https://github.com/skyportal/skyportal/issues/1904
=> Omit `Obj.redshift_history` and `Obj.internal_key` columns from POST API schema for related handlers

config.yaml.defaults, static/js/components/GroupList.jsx, static/js/components/HomePage.jsx.template, static/js/components/NewsFeed.jsx, static/js/components/RecentSources.jsx, static/js/components/TopSources.jsx, static/js/components/WeatherWidget.jsx
- Add parsing of `minW` from configs for widgets to impose reasonable minimum widths for each widget
- Bunch of CSS tweaks to make widgets more responsive otherwise, i.e. truncating long telescope names, adding scrollbars, etc.
Closes #1902
=> Make dashboard widgets more responsive

skyportal/models.py
This should speed up the sources page query a bit. The old definition basically had `Source.read = Source.read` so there was an unnecessary self-join in there.
=> Optimize sources query

skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py
Even with removeNested option, the multiple source query for RCF is still too slow that it times out. After discussing with Dan and Christoffer, I've modified the flag to also remove classifications from output.
=> Modified removeNested flag to also exclude classifications

skyportal/handlers/api/photometry.py
The current version of PUT for photometry using stream IDs makes anywhere from 1 to 3 extra database queries per duplicated photometry point compared to using group IDs.
- For group IDs, each duplicated photometry point just makes one query for the new groups to be added ([these lines](https://github.com/skyportal/skyportal/blob/390d9494e0ef63b6e58f30c7a0786829e99dc7a6/skyportal/handlers/api/photometry.py#L788-L793))
- For stream IDs, we make a call for the stream records associated with the passed-in stream IDs, and then a call to see if the `StreamPhotometry` row exists for each passed-in stream ID as well. 
This PR brings the reduces the number of database queries in the stream ID block to just one per duplicated photometry point (getting the list of streams already associated with a …
=> Reduce database queries in photometry PUT by stream id

skyportal/tests/utils/test_cache.py, skyportal/utils/cache.py
This addresses the issue where expired cache is still accessible until a new cache item is created.
=> Clean expired cache upon access

skyportal/tests/api/test_photometry.py
This regularly fails on GA, so marking this test `skip` for now until we can further optimize it to speed up the development & review process.
=> Skip photometry big post test for now

.pre-commit-config.yaml
This should resolve recent discrepancies in prettier output between the CI and local environments
=> Pin prettier version in pre-commit configs

static/js/components/InviteNewGroupUserForm.jsx
Minor update to PR that just went in: Since the select is uncontrolled, when we reset the form state values, that was not reflected in the select's state, opening the door for consecutive invitations to have the wrong role. This PR avoids that.
=> Do not reset role input field after submitting invitation

skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py, static/js/ducks/sources.js
By default, don't return photometry detection statistics like `last_detected_at` and `peak_detected_at` in the GET sources call in order to avoid heavy computations. 
I kept the fields in for the front-end's sources calls since those will all be through the paginated tables and thus limited to 100 sources per page.
=> Skip source detection stats by default in GET sources

doc/advanced_usage.md
I added a  short description in advanced usage for the spectroscopic lines. 
Let me know if you need more details. 
Point of information: There are some lines which were part of the default lines on skyportal before:
'Mn I’   : [12900, 13310, 13630, 13859, 15184, 15263]
'C I’     : [8335, 9093, 9406, 9658, 10693, 11330, 11754, 14543]
'Si I’    : [10585, 10827, 12032, 15888]
'S I’     : [9223, 10457, 13809, 18940, 22694]
'Ca I’   : [19453, 19753]
'Fe I’   : [11973]
'Co II’  :  [15759, 16064, 16361, 17239, 17462, 17772, 21347, 22205, 22497, 23613, 24596] 
These are all IR lines which we did not include for spectroscopic analysis. I see that they were implemented on the marshal previously. 
I would be happy to add a reference to them if you know where they are from, or for which science they …
=> Added documentation for spectroscopic lines

static/js/components/ThumbnailList.jsx
Per Dan Perley:
> Minor functionality suggestion: on the Candidates (scan) page, if you left click the SDSS/PS1 images, the page loads in the same window.  Once this happens there is no way to go back to where you were before - the "back" browser returns you to an empty Candidates query, so you have to re-issue the search and scan again from the beginning.  So, it would be nice if these links (and any other) opened in a new tab instead of in the same window.
=> Open external thumbnail links in new tab

skyportal/api_description.md
Some users who are less familiar with APIs/`requests` had been getting confused.
=> Clarify difference between query params and request body params in API docs preamble

static/js/components/SourceTable.jsx
Per Dan Perley via beta-testing channel:
> Would it be possible to make the user ID of the person who saved the transient available as an optional column to display under table of sources in "groups"?
I figured that the username would be more informative on the UI than the user ID, so I chose to display the username of the user who saved the Obj to a specific source instead. On the Sources page, instead of `Saved To Group By`, this column is made instead into a `Last Saved By` username.
=> Add saved by user to sources table

skyportal/plot.py
Looks like our current version of Bokeh (2.2.3) actually doesn't support the `star` marker shapes yet, so this PR just replaces that with the `inverted_triangle` option. https://docs.bokeh.org/en/2.2.3/docs/reference/models/markers.html?highlight=marker#module-bokeh.models.markers
Error reported in beta-testing channel:
=> Replace Bokeh star markers with inverted_triangle

static/js/components/SourceTable.jsx
Should fix this error on production:
Not sure why there are sources with no `saved_by` info in the first place and that may be an error in itself that we should look into, but we should at least handle it gracefully.
=> Handle null source saved_by fields

skyportal/models.py, skyportal/tests/frontend/test_notifications.py, static/js/components/FavoriteSourcesNotificationPreferences.jsx, static/js/components/UpdateProfileForm.jsx
This PR introduces an event listener that adds front-end user notifications (when enabled) for activity on users' favorite sources (can be configured to trigger on new comments, spectra and classifications for now -- and can be easily expanded). A generalized SQLAlchemy event listener is used for all three mappers. A new notification settings section is added to the user profile. 
The generated notifications:
On the profile page:
Closes https://github.com/skyportal/skyportal/issues/1619
=> Generate front-end notifications for selected activity on favorite sources

skyportal/facility_apis/lt.py, skyportal/facility_apis/sedm.py, skyportal/tests/api/test_followup_requests.py
This PR converts the `priority` follow-up request form field for the SEDM and LT APIs to be a float value in the `[1, 5]` range instead of an enumerated list of strings representing the integers in that range, to allow for more granularity in the priorities.
Closes #603
=> Use float priorities for SEDM and LT followup

skyportal/handlers/api/user_obj_list.py, static/js/ducks/sources.js
This PR addresses a potentially significant resource drain whereby any time a user updated one of their listings, their favorite sources (not just the `Listing`s, but the actual `Obj` data) were re-fetched. The issue was two-fold: the REFRESH_FAVORITE_SOURCES WS message was being pushed regardless of whether the relevant list was updated; and when the front-end received that message, it was always issuing a new (potentially expensive) request, regardless of whether the user was viewing the favorites page, where that information would be relevant.
=> Do not unnecessarily fetch favorite sources

static/js/components/CommentList.jsx, static/js/components/CommentListMobile.jsx
Before:
With this patch:
Closes https://github.com/skyportal/skyportal/issues/2068
=> Fix issue where multi-line comments were overlapping in compact mode

static/js/components/NewsFeed.jsx, static/js/components/UserAvatar.jsx
In compact comments mode, it was not possible to see more than the comment author's initials in the avatar, which is likely not enough information to fully identify the author. This PR adds a mouseover tooltip that displays the author's username, first name and last name.
Closes https://github.com/skyportal/skyportal/issues/2067
=> Show username + first/last in tooltip for UserAvatar

skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py, skyportal/tests/frontend/test_sources.py, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx
This PR introduces a check for duplicates in the handler for fetching individual sources by ID. If any duplicates are found, an array of their IDs is included in the response. 
On the front-end source page, if any duplicates exist, a message appears indicating so with links to all possible duplicate sources.
Partially addresses https://github.com/fritz-marshal/fritz/issues/178
=> Duplicate sources flag on source page

static/js/components/AddUsersFromGroupForm.jsx, static/js/components/AssignmentForm.jsx, static/js/components/NewGroupForm.jsx, static/js/components/NewGroupUserForm.jsx, static/js/components/SourceNotification.jsx, static/js/components/WidgetPrefsDialog.jsx
Unify the MUI button type used for submitting forms throughout the app (mostly on the Source page).
Close #916
=> Unify submit button styles

skyportal/tests/frontend/test_observability.py, static/js/components/Observability.jsx, static/js/components/ObservabilityPreferences.jsx, static/js/components/UpdateProfileForm.jsx
Partly addresses https://github.com/fritz-marshal/fritz-beta-feedback/issues/61
@dmitryduev Part of that issue was also a request for `the "hours over airmass 2.5" plot` from the GROWTH marshal. If you could point me to where the code for that is, I can try to port it over to SkyPortal as well.
=> Allow filtering of observability page via user preferences

skyportal/app_server.py, skyportal/handlers/api/gcn.py, skyportal/handlers/api/internal/__init__.py, skyportal/handlers/api/internal/recent_gcn_events.py, static/js/ducks/gcnEvents.js
Move the current multiple GET logic to a `RecentGcnEventsHandler` and implement separate GET multiple logic to just fetch all events (can be expanded later to support filtering etc), bringing it more inline with how we handle sources.
=> Clean up GcnEvent routes

static/js/components/SourceDesktop.jsx
Replaced "red" (which seems too "invasive") with "#457b9d". Compare:
=> Change duplicates text color

requirements.txt, tools/data_loader.py
This PR attempts to fix the issue with Photometry data loading (seen in the CI) caused by the recent update to `requests`.
Specifically, we can no longer have `np.nan` values in the JSON body sent to `requests.post()`: https://github.com/psf/requests/pull/5810.
~~I tried just replacing those NaN's with `None`, and the post at least goes through without error. But I'm not sure if it's a perfect solution, as now I see some weird behavior from the photometry plot with this newly loaded data:
Any thoughts?~~
EDIT: 
This PR just pins the `requests` version to be below the breaking-change version of 2.26.0
=> Pin working requests version

data/db_demo.yaml, skyportal/plot.py, static/js/components/ManageDataForm.jsx
Display spectrum origin and altdata values in the plot tooltips and the manage data table. Interestingly, it doesn't look like anyone is actually using the origin field for spectra (I didn't see any non-null or non-empty-string values in the fritz production replica database). Maybe seeing it in the tooltip will serve as advertisement so people are aware of it.
Also tweaked the spectrum plot styling to more accurately handle longer lists of spectra.
Origin and altdata columns on the Manage Data page:
New plot tooltip additions:
Before of having a large number of spectra (22 here):
After:
Closes #1797
=> Add origin/altdata to spectrum displays

skyportal/tests/api/test_photometry.py
With 50k points, the test consistently fails on CI.
=> Reduce big phot post test size from 50k points to 40k points

skyportal/schema.py
Fix documentation that was confusing regarding default handling of flux error column in upload.
Fixes issue #[2128](https://github.com/skyportal/skyportal/issues/2128)
=> Updated docstrings for SpectrumAsciiFileParseJSON

skyportal/models.py
We were not ensuring that `phot.fluxerr` was a non-zero number before attempting to compute SNR.
=> Photometry SNR bug hotfix: Ensure phot.fluxerr is non-zero number before computing SNR

.github/workflows/test_api_and_frontend.yaml, skyportal/handlers/become_user.py, tools/data_loader.py
This fixes a bug in the logic that didn't allow a user with the "Become user" ACL to become another user when not in debug mode, and now also allows users with the "System admin" ACL to do the same.
This PR also updates the GitHub actions workflows to only test `load_demo_data` in one workflow (the model tests), and bumps the data loader timeout to 3s.
=> Allow users with System admin or Become user ACLs to become users when not in debug mode

skyportal/app_server.py, skyportal/handlers/api/comment.py, static/js/components/CommentAttachmentPreview.jsx, static/js/components/CommentList.jsx
- Modify the app routing regexps to ensure that
`/api/comments/10/attachment/spectrum` is reachable
- Return a sensible error message if no attachment exists
- Modify CommentAttachmentPreview to fetch attachment from
the appropriate endpoint for either object or spectrum comment
Closes #2200
=> Fix spectrum comment previews

Makefile
Before, we used to check out the HEAD of the baselayer repository.
=> On first run, check out committed version of baselayer

.github/workflows/test_api_and_frontend.yaml
This is not strictly speaking necessary: SkyPortal make commands check
dependencies on each run already.  Still, this is a useful reminder in
the GitHub Actions workflow that we are switching SkyPortal versions
and, thereby, dependencies, and may avoid confusion.
=> Explicitly install SkyPortal dependencies for tested branch

static/js/components/SourceTableFilterForm.jsx
This is a temporary measure to prevent potential system slowdowns. See https://github.com/fritz-marshal/fritz/issues/338 for the description and background.
I only disabled things on the frontend, didn't touch the backend. In the latter case, there are multiple places where permissions checking potentially cause tons of lookups that are slow (last_detected_at, peak_magnitude, etc.), but let's hope that our theory is right and people were only using the front-end to issue these queries.
In the meantime, we should come up with a permanent solution.
=> Disable slow Obj filters in Sources tables

static/js/components/SourceTable.jsx, static/js/ducks/sources.js
This is a temporary stopgap to address major performance issues
when fetching sources including detection statistics. We will
revert this when those inefficiencies are addressed.
=> Do not include detection stats in sources action creators; remove Peak/Latest mag cols from SourceTable

skyportal/app_server.py
This updates the regex used for matching comment attachment preview
requests to the correct Tornado handler. This was likely broken when
the comment API was updated to include associated resource type.
Closes https://github.com/skyportal/skyportal/issues/2214
=> Fix faulty URL for PDF attachment previews

skyportal/models.py, skyportal/tests/api/test_thumbnail.py
This adds an event listener that deletes associated on-disk thumbnail files
upon removal of a row from the Thumbnail table. Tests are also added.
Closes https://github.com/skyportal/skyportal/issues/2279
=> Add event listener to remove on-disk thumbnail files upon removal

static/js/API.js, static/js/ducks/candidate.js, static/js/ducks/source.js
Before, when an API call failed for an unknown reason, we displayed
the error but did not try and propagate it further.  Now, the error
message is attached to the `*_FAIL` action so that it may be displayed
in a component or logged to the console.
=> Provide explicit feedback when API fetch fails

tools/data_loader.py
Let the user know what HTTP codes were expected/received.
Try 15 times before giving up, so that data loader has a better chance
on slow CI.
=> Make data loader reporting more transparent

.github/workflows/test_migrations.yaml
Bumps migration test workflow reference commit to
880cd56716015e33df22af1d256717ce98d7eb84. Also restricts
workflow to only run when relevant sections of code base
have been changed.
=> Bump migration test workflow reference commit; restrict GA runs

package.json, requirements.txt, skyportal/tests/frontend/sources_and_followup_etc/test_followup_requests.py, static/js/components/BokehModels.js, webpack.config.js
BokehJS now uses more JS features, so added the babel plugins for:
- optional chaining (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
- nullish coalescing operator (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator).
Tweaked the models to be in line with the latest BokehJS (mainly usage
of `super.render()`).
<strike>Depends on https://github.com/bokeh/bokeh/issues/11616 to be resolved.</strike>
=> Upgrade bokeh/bokehjs to 2.4

data/db_demo.yaml, doc/advanced_usage.md, doc/comment_url_migration.md, skyportal/app_server.py, skyportal/handlers/api/__init__.py, skyportal/handlers/api/annotation.py, skyportal/handlers/api/comment.py, skyportal/tests/api/test_annotations.py, skyportal/tests/api/test_candidates.py, skyportal/tests/api/test_color_mag.py, skyportal/tests/api/test_comments.py, skyportal/tests/api/test_comments_on_spectrum.py, skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py, skyportal/tests/frontend/sources_and_followup_etc/test_sources.py, skyportal/tests/frontend/test_newsfeed.py, skyportal/tests/frontend/test_scanning_page.py, static/js/components/CommentAttachmentPreview.jsx, static/js/ducks/source.js
This patch updates the comments API endpoints such that
we consistently use plural nouns when specifying resources,
e.g. `api/sources/<source_id>/comments/<comment_id>`.
We also add `api/spectra` in addition to the existing (now
deprecated) `api/spectrum` endpoint. Tests and demo data yaml
are updated.
=> Use plural nouns consistently in comments API endpoints

skyportal/handlers/api/annotation.py, skyportal/handlers/api/comment.py, skyportal/tests/api/test_annotations.py, skyportal/tests/api/test_comments.py, skyportal/tests/api/test_comments_on_spectrum.py
This patch adds a handler for fetching all comments associated with
the specified resource (obj, spectrum), and adds tests for this
handler as well as the already-existing annotations handler.
=> Add handler for GET api/{sources,spectra}/comments endpoint

skyportal/handlers/api/annotation.py, skyportal/tests/api/test_annotations.py, skyportal/tests/api/test_comments.py, skyportal/tests/api/test_comments_on_spectrum.py
This is already provided in the request URL.
Closes https://github.com/skyportal/skyportal/issues/2330
=> Do not require obj_id in annotation POST payload

tools/data_loader.py
This addresses the edge case where, after the maximum number of
attempts to connect to the running app instance, the `status` variable 
is referenced without being defined.
See https://github.com/skyportal/skyportal/issues/2292#issue-1010100911
=> Address edge case where status is undefined in data loader

package.json
In some installations, this package was missing after
running `make run`, causing webpack bundling to fail.
=> Explicitly require react-resizable in package.json

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py
This patch ensures that a valid user ID is always provided
to the thumbnail generation routine in the case that the request
is initiated by a token.
Resolves errors like the following:
```
[10:33:35 api/candidate] Unable to add linked thumbnails to ZTFJ201825+380316: (psycopg2.errors.InvalidTextRepresentation) 
invalid input syntax for type integer: "856bab7b-15f9-4ba1-b302-f091ab8ce15b"                                                      
LINE 3: WHERE users.id = '856bab7b-15f9-4ba1-b302-f091ab8ce15b'                                                                
```
=> Provide valid user ID to thumbnail gen routine

data/db_demo.yaml
This PR comments out the loading of instrument field data
in the demo data yaml for faster data loader run times.
=> Do not load all instrument fields in demo data

skyportal/handlers/api/internal/profile.py, skyportal/handlers/api/user.py
This patch updates our usage of the validate_email API to
accord with the new (breaking) API changes and also disables
often-expensive network-dependent checks (e.g. initiating SMTP
connections, etc).
=> Update py3-validate-email API usage

package.json, webpack.config.js
Upgrade webpack to v5.x and browserify non-polyfilled node modules for
v5 compatibility.
=> Upgrade webpack to v5

package.json, webpack.config.js
This patch includes a module plugin to resolve
the no-longer-polyfilled Buffer library.
=> Update webpack config to resolve missing Buffer

static/js/components/CommentEntry.jsx, static/js/usernameTrie.js
This patch limits the number of matches returned by the user
mention auto-complete trie to ensure scalable performance with
arbitrarily large user bases.
Closes https://github.com/skyportal/skyportal/issues/2477
=> Limit number of matches returned by auto-complete

skyportal/tests/__init__.py
This allows us to bypass pre-existing netrc configurations
on the user's system that would be used to override the specified
authorization headers for every request.
Closes #2496
=> Use requests.Session in api utility function

doc/dev.md
Fixes issue #2522. Change "xfvb" to "xvfb"
=> Fix typo in docs

config.yaml.defaults, data/db_demo.yaml, data/instruments.yaml, data/telescopes.yaml, skyportal/facility_apis/__init__.py, skyportal/facility_apis/sedmv2.py, skyportal/tests/flaky/test_followup_requests.py
This PR enables the two pathways that would need to exist here: (i) a local SkyPortal instance that the request is being made on and (ii) an external SkyPortal instance that this instance would take to (like we would for any other system). So we support both pathways.
=> SEDMv2 triggering interface

Dockerfile
E.g., the nginx configuration is templated, and depends on the skyportal
config to know which IP addresses to whitelist.
Closes gh-2536
=> Dockerfile: copy config before setting up services which may rely on it

.github/workflows/test_migrations.yaml, requirements.docs.txt, skyportal/app_server.py, skyportal/handlers/api/candidate.py, skyportal/handlers/api/internal/annotations_info.py, skyportal/handlers/api/photometry.py, skyportal/handlers/api/public_group.py, skyportal/handlers/api/source.py, skyportal/models/group.py, skyportal/models/schema.py, skyportal/tests/api/test_photometry.py, skyportal/tests/conftest.py, skyportal/tests/fixtures.py, skyportal/tests/tools/test_offset_util.py
This PR upgrades SQLAlchemy to 1.4.* from 1.3. It pins a branch of `baselayer` that has `requirements.txt` explicitly stating the dependency of `sqlalchemy>=1.4.0'. This move has a number of breaking changes. In addition to the original PR, we may opt to merge #2570 into this branch.
* Pin BL that requires SQLA v>=1.4.0
* Use SQLA 1.4-compatible registry mappers in schema
* Refactor Values construct in photometry handler
* Use select API instead of query in PhotometryHandler, PublicGroupHandler, conftest & fixtures
* use a version that eralchemy which works with SQLA1.4
* fix AttributeError on Base in schema.py
* safe alias the group logic
* fix candidate.py
* use VALUES constructor in get_obj_id_values
* use 1.4 func.jsonb_each instead of <1.4 formula
* remove legacy code
Co-authored-by: …
=> SQLAlchemy 1.4.X compat version

package.json
Webpack would not build on my machine without it, even after removing
`node_modules`.  I am not sure why it works on CI; it could be that I
have a newer version of node/npm.
=> Add @material-ui/styles peer dependency

skyportal/plot.py
When loading a source page that has a redshift, the spectral lines are not red-shifted when the plot is shown. The redshift is only applied after changing the redshift in the slider or input box. 
This patch fixes this by adding a couple of missing lines in `plot.py`.
=> fix redshift of lines 

static/js/components/SourceTable.jsx
Currently the CSV file downloaded gets very confused by our objects (just says [object Object]).
This makes the CSV file print out relevant things similar to how the table displays in the App.
"id","ra","dec","redshift","classification","groups"
"ZTF21aaqjmps","202.5050541","13.4111859","0.0246","","Sitewide Group;Program A;Program B"
"ZTF18aabcvnq","172.0534465","25.6596908","","Time-domain Source;variable","Sitewide Group;Program A;Program B"
"ZTFe028h94k","229.9620403","34.8442757","","","Sitewide Group;Program A;Program B"
"ZTFrlh6cyjh","342.4596","51.2634","","","Sitewide Group;Program A;Program B"
"ZTFJ201825+380316","304.60791628","38.05469","","","Sitewide Group;Program A;Program B"
=> Make download CSV file more useful

static/js/components/AllocationPage.jsx, static/js/components/InstrumentPage.jsx, static/js/components/TelescopePage.jsx
This PR adds the requirement of admin privileges to use the Add functionality on the allocations, telescopes, and instruments pages.
=> Hide ability to add allocations, telescopes, and instruments to non-admins

skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py, static/js/ducks/source.js
When PS1 cutout arrives, the photometry and spectroscopy disappears. It turns out it is because the photometry option only exist in multiple source request (despite what the docstring says). This adds it back in.
See https://github.com/ZwickyTransientFacility/scope/issues/61
=> Fix disappearing photometry/spectroscopy bug

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py
This PR fixes the sources query parameter includeDetectionStats when querying for multiple sources, which was previously broken.
Closes #2641.
=> Fix includeDetectionStats when querying multiple sources

static/js/components/GcnEvents.jsx, static/js/components/RecentSources.jsx, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx, static/js/components/SourceTable.jsx, static/js/components/Theme.jsx, static/js/components/TopSources.jsx
Adds styling for improving skyportal in dark mode.
before: low contrast between background and typography body text
after: better contrast
before: links are quite dark
after: lighter links
=> Improve dark mode

skyportal/handlers/api/source.py, skyportal/tests/api/test_sources.py
This PR enables source filtering by annotations. This is important as it allows one to identify sources by, for example, thresholding on redshift values or other numerical annotations.
=> filter sources by annotation

data/db_demo.yaml, static/js/components/UploadSpectrum.jsx
Display a user's full name in the option for adding observers/reducers when uploading a spectra
=> Display names of users in options when uploading a spectra

static/js/components/AllocationPage.jsx, static/js/components/ShiftPage.jsx, static/js/ducks/allocation.js
This PR emulates the shift page so that Allocations can be removed.
=> Make it possible to delete allocations from front-end

requirements.docs.txt
This PR restricts jinga2 to be below 3.1.0, which breaks our docs.
=> Fix doc requirements

doc/setup.md
Recently, skyportal couldn't get installed properly as pycurl (package installed with pip) was broken. It seems that adding these 2 packages fixed it. I would suggest to the reviewer to make sure they aren't already installed on his distro before trying it so he can compare and verify their necessity.
=> Adding missing packages that broke pycurl

static/js/components/GcnSelectionForm.jsx
This PR aims to resolve the issue where the GCN Event page was crashing. It behaved like this:
Now the page behaves like this
It isn't perfect but the page does not crash anymore.
=> Resolved issue where GcnEvent page was crashing

skyportal/handlers/api/candidate.py
Problem: When a token/bot is trying to POST a candidate we get this error: 
```
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=DetachedInstanceError("Parent instance <Token at 0x7f6ea25394f0> is not bound to a Session; lazy load operation of attribute 'created_by' cannot proceed")>
Traceback (most recent call last):
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/skyportal/skyportal/handlers/api/candidate.py", line 1046, in <lambda>
obj.id, self.associated_user_object.id
File "/skyportal/skyportal/handlers/base.py", line 15, in associated_user_object
return self.current_user.created_by
File "/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 481, in …
```
=> Fix missing bot user in Candidates handler

skyportal/plot.py, static/js/components/SourceDesktop.jsx
Adds the ability to hide the right pane on the source page to allow for larger plots. Fixes part of #2396 
Also I made the width of the plots responsive to the size of the div containing them, previously it was hardcoded to 800.
=> Add ability to hide right pane on source page

skyportal/plot.py, static/js/components/SourceDesktop.jsx
Allows the user to adjust the size of the data points on the photometry plot. With #2857 and #2778, this should close #2396
=> Adjustable data point size for photometry plot

skyportal/facility_apis/ps1.py, skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py
There are a couple of places in the skyportal code (i.e., not in baselayer) where we generate sessions. 
Right now they use try/catch/finally to make sure the session gets closed properly. 
I'm not sure if that is good enough so I'm going to replace the finally with a `with Session() as session` block. 
This may help prevent us from slowly losing DB connections from the pool.
=> Context Manager Session

static/js/components/LocalizationPlot.jsx
Determines color for the instrument tiles based on the filters, here's the color for these filters:
And with just the first 3:
Also I made the galaxy points green to distinguish from sources
=> Determine instrument tile color based on filters

data/db_demo.yaml, tools/data_loader.py
This PR adds follow-up requests associated to existing spectra to the demo data to facilitate studying data base queries.
=> Add follow-up requests to demo data

skyportal/tests/frontend/sources_and_followup_etc/test_sources.py, static/js/components/SourceDesktop.jsx
Quick fix for the problem brought up in slack where the source page would freak out due to the ResizeObserver
This reverts back to having some hardcoded plot widths based on if the right pane is hidden or not. I would like to make the plot widths fully responsive but I would have to find a good solution, the ResizeObserver does not seem to work well
Once approved I'll also make a PR on fritz
=> Remove ResizeObserver on source page

doc/setup.md
This PR addresses the issue mentioned here : https://github.com/skyportal/skyportal/issues/2876
In which we talk about how the current lines given in the docs that a user needs to add to the config file of postgresql (pg_hba.conf) does not work because of the changes made to baselayer in this PR: https://github.com/cesium-ml/baselayer/pull/269
=> Wrong configuration in the Docs for pg_hba.conf

doc/setup.md
This PR adds some info to the docs for when using Let's Encrypt certificates.
=> Add nginx info when using Let's Encrypt certificates

README.md
The link to skyportal's logo in the readme points to the master branch that has been renamed main, so it doesnt work anymore. This extra short PR fixes that.
=> Fixes link to SkyPortal logo

doc/setup.md
This PR adds the configuration (in the documentation) for machines where SkyPortal is deployed using IPv6 rather than IPv4.
It was discussed after merging https://github.com/skyportal/skyportal/pull/2938
=> Documentation : PostgreSQL Configuration

static/js/components/GcnSelectionForm.jsx, static/js/components/NewAPIObservation.jsx, static/js/components/NewAPIQueuedObservation.jsx, static/js/components/NewAllocation.jsx, static/js/components/NewShift.jsx
It seems that a recent modification to either:
- rjsf
- dayjs
- the way the calendar that open on your browser works
affect the format of the date returned by the form (or it could just be that this error was never noticed before).
Here's what happens:
A form has a default value, and when submitting it without modifying a start and end date, all is well, and the date ends in "+00:00" as expected, which we delete. But right now, it seems that modifying the date manually or via the calendar that pops up, modifies the format of the date which then ends int '.000Z'.
This PR takes care of this by also deleting '.000Z'.
=> Fix issue with converting Local input in form to UTC date

static/js/components/FollowupRequestPage.jsx
Currently the FollowupRequestPage component incorrectly rerenders with every table click. This fixes that.
=> FollowupRequestPage rerendering

skyportal/facility_apis/atlas.py, skyportal/facility_apis/ztf.py
See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#why-does-assignment-fail-when-using-chained-indexing
In our case, the code was probably doing the right thing.  But the
SettingWithCopy warning is issued conservatively whenever copies *may*
be returned, and rewriting the statements the way it is done here is
safer overall.
=> For Pandas DataFrames, ensure that assignments are made on views, not copies

skyportal/handlers/api/internal/profile.py, skyportal/tests/frontend/test_profile.py, static/js/components/ClassificationsShortcutForm.jsx, static/js/components/FavoriteSourcesNotificationPreferences.jsx, static/js/components/FilterCandidateList.jsx, static/js/components/Group.jsx, static/js/components/NotificationPreferences.jsx, static/js/components/ObservabilityPreferences.jsx, static/js/components/SlackPreferences.jsx, static/js/components/UIPreferences.jsx, static/js/components/UpdateProfileForm.jsx, static/js/components/UserPreferencesHeader.jsx
Adds classification shortcuts for selecting classifications on the scanning page
Also, I noticed there was some duplicated code with creating the headers and help icons on the preferences page so there's a new component: UserPreferencesHeader.
closes #2858
=> classification shortcuts

tools/set_user_role.py
Using it in production i discovered an issue i couldn't have noticed when using `make load_demo_data`, is that if a user has no roles to begin with, we can't set a new role for him. A for loop tries to access the roles in user.roles, but as user.roles is empty, it can't iterate.
=> tools/set_user_role.py - error when adding a role to a user that has no roles yet.

skyportal/tests/frontend/test_profile.py
Currently, when running GitHub actions, one test from test_user_profile.py consistently fails with the following error: `xfailed` , which is ignored. This PR fixes that test.
=> Removed unexpected xpassed and xfailed in test_user_profile.py

skyportal/handlers/api/telescope.py, static/js/components/NewTelescope.jsx
Solves issue mentionned in https://github.com/skyportal/skyportal/issues/2985, where we would encounter an error because the lon, lat, elevation field are required if the telescope has a fixed location, but that wasn't verified in both frontend and backend.
=> lon lat elevation : validation in NewTelescope.jsx and in the handler if the telescope is fixed

package.json
the bokeh dependencies that changed recently:
```
es5-ext (0.10.53->0.10.61)
flatbush (3.3.0-> 3.3.1)
mathjax-full (3.2.0 -> 3.2.1)
nouislider (15.5.0 -> 15.6.0)
proj4 (2.7.5 -> 2.8.0)
tslib (2.3.1 -> 2.4.0)
```
It looks like pinning mathjax_full will fix broken plotting.
=> pin mathjax_full

static/js/components/FollowupRequestLists.jsx, static/js/components/FollowupRequestPrioritizationForm.jsx, static/js/components/FollowupRequestSelectionForm.jsx, static/js/components/GcnSelectionForm.jsx
This PR changes the message displayed on the frontend when there are no follow up requests to show to the user. 
This solves the issue raised by @guynir42 https://github.com/skyportal/skyportal/issues/3004
=> changed message displayed when no followup requests are found

config.yaml.defaults, services/gcn_service/gcn_service.py
=> Configuration for the GCN Service

skyportal/tests/frontend/test_about_page.py, static/js/components/Main.jsx.template
The "Invalid route" message disappeared, this puts it back in and adds a test for invalid routes.
=> Fix invalid route message

skyportal/utils/offset.py
During the transition from EDR2 to DR3 the main Gaia catalog used by astroquery has become unstable. We look for this but did not catch the new error that is arising. This PR attempts to fix this.
The backup Gaia catalog also changed its units reporting. This PR fixes this.
=> Catch (new) Gaia exception

static/js/components/FollowupRequestForm.jsx
This PR uses the allocation lookup in the FollowupRequestForm drop down.
=> Use allocation lookup in form

skyportal/handlers/api/annotation_services.py, skyportal/handlers/api/observation_plan.py, skyportal/handlers/api/source.py, skyportal/handlers/api/unsourced_finder.py, skyportal/services/test_server/test_api_server.py, skyportal/tests/api/test_color_mag.py, skyportal/tests/api/test_finders.py, skyportal/tests/api/test_sources.py, skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py, skyportal/tests/frontend/sources_and_followup_etc/test_sources.py, skyportal/utils/offset.py, static/js/components/FindingChart.jsx
🛰 Use Gaia DR3 as the main catalog for astrometry & color-mag diagrams, replacing EDR3.
=> Migrate to Gaia DR3 queries

.flake8
This slightly relaxes the limit on line length from 80 to 88. This gives black a bit more freedom to reformat long lines reasonably well. Note that we also allow a 10% margin of overshoot. As they say in the black docs: "try to respect --line-length, but don’t become crazy if you can’t".
=> Slightly relax line lengths

static/js/components/WidgetPrefsDialog.jsx
This PR adds more space at the top of Widget titles (partially addresses https://github.com/skyportal/skyportal/issues/3075).
=> Add extra space up top

config.yaml.defaults
We are retiring the 8-year-old pharos and replacing it with minar.  The web server is up and running and this should be a
seamless transition.  Please let me know when this is deployed so we don't lose SEDM requests through the cracks.
=> Change sedm_endpoint from pharos to minar

skyportal/facility_apis/_base.py, skyportal/facility_apis/interface.py, skyportal/facility_apis/ztf.py, skyportal/handlers/api/observation.py, static/js/components/ObservationPage.jsx, static/js/components/QueueAPIDisplay.jsx, static/js/ducks/queued_observations.js
This PR adds a basic queue interface to the observations page, where the queues can be displayed (and deleted if that capability exists).
=> Add basic queue interface

static/js/components/SelectWithChips.jsx
This PR addresses a comment made by @stefanv on slack, saying that the calculation of the max number of chips to display in the component lacked clarity, and could be shortened.
=> SelectWithChips component - Clarified calculation of NB of chips to display

static/js/ducks/source.js
This PR uses a much more reasonable check for nearby sources in the SourceExists handler.
=> SourceExist radius check is in degrees, not arcseconds

skyportal/handlers/api/followup_request.py
This PR reopens the follow-up request form, which was never really the culprit once we dealt with pagination.
=> Reopen follow-up request form

static/js/components/CommentList.jsx, static/js/components/CompactCommentList.jsx, static/js/components/RegularCommentList.jsx
Currently, when we write a long comment on skyportal, we have to scroll to the side to see all of it:
I fixed it by going to the next line when the text does not have any space left:
=> Improvement of the comment component

static/js/components/ShowClassification.jsx
This PR increases the size and weight of the classification on the source page, should close https://github.com/skyportal/skyportal/issues/3125
Before:
After:
=> Adjusted classification Chip font size and weight

static/js/components/GroupsSelect.jsx
The GroupSelects component is still importing components from an older version of MUI. The result is that wherever it is used, it breaks the display of the page. This PR just updates the imports to MUI5 to solve that problem.
=> Updated GroupsSelect.jsx imports to MUI5

skyportal/handlers/api/followup_request.py
Jesper got that error when trying to create a followup request.
The issue is that ValueError gets thrown in post_assignment, but the exception handler expects a ValidationError only.
=> Fix ValueError has no attribute normalized_messages error

skyportal/handlers/api/annotation_services.py
When clicking add Gaia cross match (or Wise, etc) there's a backend error that has to do with the group objects coming from a different session. This moves the `annotation_services` handler to the SQL 2.0 method style (mostly) and fixes that bug.
=> Fix group in different session bug in annotation_services

static/js/components/OriginSelect.jsx
Making the origin select async to try reducing the execution time (related to https://github.com/skyportal/skyportal/issues/3186)
=> Making the origin select async

skyportal/models/telescope.py, skyportal/tests/tools/test_timezone.py
This PR fixes a bug where the airmass plots are not reporting UT time, but actually timezone time. This splits out the observer property into one for UT and one that is timezone cognizant, which may be useful for reporting local time on the front-end.
=> Separate observer and observer_timezone

docker-compose.yaml
This PR bumps default postgres in docker-compose to 14.4, required for all of the healpix-alchemy infrastructure.
=> Use newer version of postgres in default compose

skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py, static/js/components/ProgressIndicators.jsx, static/js/components/SourceList.jsx, static/js/components/SourceTable.jsx
This PR attempts to fix #3118, where the problem was that when clicking on the download button of the mui datatable of the source list, it only downloads the source currently displayed (so only the current page of the table), and not all the sources matching the filters and/or sorting selected by a user. 
In this PR, the sources are download 10 by 10 which is fine to test the feature. But this could (and probably should) more be done like 100 by 100 to limit API calls.
PREVIEW: (please click on the image to see it fullscreen, makes it easier to read)
=> Sources list - Download all sources, not just the ones displayed.

skyportal/models/obj.py
This PR checks that altdata is a dictionary. It addresses the recent fritz error "AttributeError: 'str' object has no attribute 'get'"
=> Check that altdata is a dictionary

skyportal/handlers/api/instrument.py, static/js/components/ModifyInstrument.jsx, static/js/components/NewInstrument.jsx
This PR makes instrument's sensitivity_data modifiable from the front-end.
=> Make sensitivity_data modifiable from the front-end

skyportal/tests/api/test_groups.py, skyportal/tests/api/test_obj_photometry.py, skyportal/tests/api/test_sources.py, skyportal/tests/rate_limiting/test_rate_limiting.py
This PR removes an unnecessary test now that we no longer return photometry for multiple sources.
=> No longer return photometry for multiple sources

skyportal/handlers/api/photometry.py, skyportal/models/phot_stat.py
This PR uses the new syntax for the Photometry handler. I noticed that with DBSession() as session is still required for handlers that require being able to create a table lock, i.e.
session.execute(
f'LOCK TABLE {Photometry.__tablename__} IN SHARE ROW EXCLUSIVE MODE'
)
=> Use new syntax for Photometry handler

skyportal/models/user_notification.py
This PR adds logs not just on errors, but on notifications in general.
Here is an example of a notification successfully sent on frontend, email, slack, but with a failure on SMS:
```
[34;1m[13:36:38 notifications] Sent frontend notification to user 1, body: New classification *AGN* for source *ZTF18aabcvnq*, resource_type: sources[0m
[34;1m[13:36:39 notifications] Sent slack notification to user 1 at slack_url: https://hooks.slack.com/services/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, body: New classification *AGN* for source *ZTF18aabcvnq*, resource_type: sources[0m
[34;1m[13:36:45 notifications] Sent email notification to user 1 at email: theophile.dulaz@gmail.com, subject: SkyPortal - New followed classification on a source, body: New classification *AGN* for source …
```
=> Notification Logs

skyportal/models/user_notification.py
This PR addresses a bug introduces by a PR that added logs to the notifications. It seems that some notifications, instead of having a user object as a target, have a user_id. The code added to the user notification model did not take that into account. This fixes that issue and allows tests to pass.
=> Fix group frontend tests

skyportal/handlers/api/group.py, skyportal/handlers/api/phot_stat.py, skyportal/handlers/api/photometry.py
This PR makes some minor updates to the PhotStat infrastructure. 
- It adds a re-calculation of PhotStats when photometry bulk delete is used. 
- It makes the updates of photometry use all points (regardless of access rights) when calculating PhotStats in all cases. 
- It moves the PhotStats handler to the new select style and uses the verified session. 
- It returns a meaningful error for any failures to generate/update a phot stats through the `PhotStatsUpdateHandler`.
=> PhotStat minor updates

skyportal/handlers/api/source.py
This PR addresses a bug mentioned on the beta-testing channel on slack. Users experienced difficulties with the source page where they saw the classifications being duplicated many times.
=> Bugfix: Duplicate classification on the source page

skyportal/handlers/api/phot_stat.py, skyportal/handlers/api/photometry.py
Turns out there were some cases where a single `Obj` had multiple `PhotStat` associated with it. 
This closes this loophole and uses the PATCH method to delete any additional `PhotStat` rows beyond the one getting a fresh update.
=> verify only one PhotStat per Obj

static/js/components/AllocationPage.jsx, static/js/components/NewDefaultObservationPlan.jsx, static/js/ducks/allocations.js
This PR addresses an issue found by users of the instance of Skyportal I have in production. On the allocation page, the list of allocations only shows the ones with an obs plan API type. This is because in the component to create new default obs plans, a useEffect is fetching allocations with the API type, which end up replacing the list of all allocations in the store.
=> Bug: Allocation page - List of allocations only showing allocations with an obs plan API

skyportal/handlers/api/group_admission_request.py, skyportal/models/user_notification.py, skyportal/tests/frontend/test_notifications.py
This PR addresses an issue posted on the beta-testing channel on Slack. Some group admins complained that they were not notified clearly enough that users asked to join their group. This ensures that they are notified by email.
However, in order to work without modifying the current notification framework too much, it adds very little code that simply "bypasses" some of the verification logic to be sure that an email is sent, regardless of the user preferences.
It would be nice for reviewers to test this new feature, as well as existing features of the notification framework to make sure that everything else still works as intended.
=> Group admission request: Notify group admins by email

static/js/components/FollowupRequestForm.jsx, static/js/components/FollowupRequestPreferences.jsx, static/js/components/NewAPIObservation.jsx, static/js/components/NewAPIQueuedObservation.jsx, static/js/components/NewDefaultObservationPlan.jsx, static/js/components/ObservationPlanRequestForm.jsx, static/js/components/QueueAPIDisplay.jsx, static/js/ducks/allocations.js
This PR continues what has been done in #3267, which only solved the problem caused by one component from the allocations page itself. This adds similar changes but to all pages of SkyPortal that can affect the allocation's list, but in general have a negative effect on each other, causing some components to display incorrect allocations.
Caution: We talked about it with @mcoughlin, so I did my best to fix what I could from what I understood of the instruments, their API, allocations and how they work with Followup requests, Observations and Observation Plans. Now it would make sense to properly run the code and play with it to see if everything still behaves as expect.
=> Issues with Allocations on the Frontend: Full allocation's list replaced by sublists in several components

static/js/actions.js, static/js/components/ShiftPage.jsx
This PR aims to solve a problem we had on the shift page. Currently, using the routing (i.e /shifts/<shift_id>) gets you to the shift page and automatically opens the calendar on the right week and displays the shift management menu, comments and summary of the shift which id has been passed in the route. However, if you already had selected a shift (which is stored as the current shift in the redux store), this does not work.
This PR adresses that issue.
=> Routing changes on the shift page

skyportal/handlers/api/webhook.py
This PR changes now() -> utcnow() in webhook to be sure all timing is done in UTC.
=> utcnow in webhook

skyportal/plot.py
On the source page, to see the options below the spectroscopy plot, you have to scroll *quite a lot*. Because of that, the UX is impacted, as you can't see both the options and how they affect the plot without having to scroll up and down every time.
=> Spectroscopy plot - Height of the plot is insufficient, too much scrolling on the Source Page

static/js/components/SourceAnalysisPage.jsx
Currently, on the analysis page, plots img width matches the width of the page. However, unless they are ina 16/9 ratio, they are cut and we can't see the whole height of the plots, even if we scroll. It's simply cut. 
To visualize some plots correctly, you are forced to download them.
This PR addresses that issue, by making sure that the plots img height matches the height of the page instead. That way, they might appear smaller, but the user can actually see the plots whole, and doesn't have to download them to see them properly.
That way, we also know that plots stay visible and are displayed properly even when we change the size of the browser's window.
Preview
=> SourceAnalysisPage: Better display of the plots

skyportal/handlers/api/observation.py
This PR returns success when querying for observations (otherwise throws JSON error now).
=> Return success when grabbing observations

services/gcn_service/gcn_service.py
This PR queries on allocation rather than proposal ID for default observation plans, relevant as not all allocations have proposal IDs specified.
=> Query on allocation rather than proposal ID

skyportal/handlers/api/observation.py
This PR simplifies the observation query by splitting it up.
=> Simplify observation overlap query

doc/setup.md
Update troubleshooting documentation to reflect a problem preventing access to localhost:5000 unless Airplay Receiver is disabled.
=> Add troubleshooting line about Macs and Airplay Receiver

skyportal/facility_apis/ztf.py
This PR logs when there are no ztf observations.
=> Log message if no ztf observations

skyportal/handlers/api/candidate.py
This PR tries to address session detached errors associated with object thumbnails.
=> Session detached for thumbnails

static/js/components/GroupSources.jsx
This PR uses a loading symbol if either saved or pending sources are still loading.
=> Loading symbol for group sources

skyportal/handlers/api/source.py
This PR makes it such that if any undesired classification is present in addition to other (potentially desired classifications), the object will be rejected.
=> make non-classifications inclusive

doc/usage.md
This PR adds a documentation section on classification management (via the frontend and API) to the Usage page (see #3431).
=> Add classification management to usage doc

tools/nginx_ip_and_requests.py
This PR adds the ability to read and plot request_length from the nginx log (paired with https://github.com/cesium-ml/baselayer/pull/341).
=> Add ability to read request_length

config.yaml.defaults, services/gcn_service/gcn_service.py
This PR allows one to set a group_id for GCN which will remember the last entry committed from the kafka stream.
=> set group_id for GCN

.dockerignore, Dockerfile, config.yaml.defaults, docker-compose.yaml
* Update `.dockerignore` so we do not send more data into a new docker image than is needed
* Update `Dockerfile` to point to the newly mounted `/skyportal/persistentdata` directory
* Update `config.yaml.defaults` for the analysis data to be written to  `/skyportal/persistentdata`
* Make sure that `docker-compose.yaml` is up to date.
To make SP docker images
```bash
make docker-local
```
(On ARM architectures on Mac you may need to run `export DOCKER_DEFAULT_PLATFORM=linux/amd64` first)
=> mount new persistent data directory for analysis results & fixup Docker builds

requirements.txt
This PR pins confluent-kafka to the latest version, suggested by Leo to understand gcn memory requirements.
=> Pin confluent-kafka

doc/followup.md, doc/index.rst, doc/mma.md
This PR moves follow-up requests to own documentation page (it is not MMA specific).
=> Move follow-up requests to own doc page

skyportal/handlers/api/source.py
This PR attempts to address #3516 by setting `use_cache=True` in the call to `grab_query_results` in source.py. While I have not been able to replicate the duplicate source download issue in my local instance of SkyPortal, I have tested this change locally and downloads continue to work as expected.
=> Use cache in source.py grab_query_results

static/js/components/UploadPhotometry.jsx
This PR clarifies the text upon photometry upload, where it was said instrument_id in the upload file is for multiple instruments, where its really possible for one or more instrument.
=> Clarify text upon photometry upload

skyportal/tests/utils/test_ztf_gaia_backup.py, skyportal/utils/offset.py
This PR catches errors when the Gaia and backup Gaia DBs are down. It also retries the query just in case it's a temporary issue.
=> Use public ZTFRef stars if Gaia servers are down (after retry)

skyportal/app_server.py
This PR limits token_ids to just letters and numbers.
=> Limit token_ids to just letters and numbers

skyportal/handlers/api/db_stats.py
The queries on candidates times are slow on a large DB, and do not really add anything. This PR removes them.
=> remove slow (and unhelpful) DB stats queries

static/js/components/SourceMobile.jsx
Change plot width to fixed size instead of using unreliable react-grid-layout width for the time being, to slighltly improve mobile experience while using plots. 
addresses part of #2966
=> improve mobile plot experience slightly

skyportal/handlers/api/thumbnail.py
The new thumbnail code requires alerts.py to post a new thumbnail. But that code imports thumbnails.py so there's a circular import (only on fritz).
=> fix circular import

skyportal/handlers/api/thumbnail.py
Turns out, doing `try, finally` is not the same as `try, except: pass, finally`.
=> patch try/except for missing thumbnails file

skyportal/handlers/api/thumbnail.py
I have not correctly copied the input names from `post_alerts` on fritz. 
It is very hard to develop across different repos. 
But I think we really got it this time!
=> fix interface between thumbnails and post_alert

static/js/components/ShowClassification.jsx
This PR modifies the frontend to display classifications with null probability on the group source list. In the attached screenshot, the YSO classification has null probability. It is displayed with a '?', and mousing over the classification shows `P=null`. Classifications with non-null probabilities continue to be displayed as before. Closes #3253
=> Display group source classifications with null probability

static/js/components/MultipleClassificationsForm.jsx, static/js/ducks/classifications.js
This PR simplifies the behavior of the classification slider scaling on group source pages and resolves #2366 with a slight variation on the requested behavior:
- Parent classifications are updated such that their probability is ≥ the maximum of their children's probabilities.
- Sibling classification probabilities are not updated.
- Child classifications are updated such that their probabilities are ≤ their parent's probability. This is slightly different from the issue's request not to update children at all. I think it is appropriate to avoid parent classifications having a probability that is less than their children's probabilities.
This new behavior no longer normalizes the probabilities, so the toggle is now named 'Scale parent/child probabilities'. The benefit of these changes is …
=> Update classification slider scaling

skyportal/utils/gcn.py
This PR checks for the GRB_identified flag in Swift notices when making tags.
=> Swift GRB tags

skyportal/plot.py
J-band points for PGIR are currently plotted in yellow, making them really difficult to read. This PR changes the color to black. 
It also specifies colors for the WINTER filters (Y, J and H) to avoid a similar issue in the future.
=> Specify colors for Y, J and H band photometry

static/js/components/SourceTable.jsx
This PR adds the galactic longitude and latitude to the list of displayable columns on the group sources page. The new columns are not shown by default. See below for an example of this change:
=> Add galactic longitude and latitude to group source column options

skyportal/handlers/api/followup_request.py
This PR explicitly sets exposure time in computed schedule (the block time includes overheads).
=> Exposure time in observation plans

requirements.txt, skyportal/facility_apis/_base.py
This PR removes jsonschema-to-openapi, which provides unused functionality (with an unmaintained package).
=> Remove jsonschema-to-openapi

skyportal/handlers/api/source.py, static/js/components/SourceTableFilterForm.jsx
This PR allows users to filter sources by whether the user has personally labelled or not labelled a source. This will allow users to easily pick up where they left off in the labelling process regardless of how their progress compares to other users.
A new 'by me' checkbox is added in the 'Which have been...' part of the filter table to facilitate this change (see below). Users will get an error if they select 'by me' without also selecting one of 'labelled' or 'not labelled'. If 'by me' is not checked, the filter will return the sources labelled or not labelled by any user, as it currently does.
=> Filter sources labelled by current user

doc/conf.py, doc/setup.md
Sync some of the system dependencies in the docs to those in baselayer (c.f. `baselayer/tools/check_app_environment.py). Bump copyright dates to 2023.
=> bump version numbers to sync with baselayer requirements

Dockerfile
As having SNID and STDPipe installed in SP does not cause any problem with existing features, and facilitates SP's deployment and testing (as well as its maintenance by avoiding a duplicate Dockerfile in the extension folder of Fritz), it seems like a good decision to uncomment the dependencies install lines from the Dockerfile.
=> Dockerfile - Uncommented SNID and STDPipe dependencies

.github/workflows/test_docker_build.yaml
#3862 introduced a bug by only triggering action on label, and not running it on push. This PR attempts to make both conditions work.
=> Fix issue with Docker workflow on push

config.yaml.defaults
This PR adds fail_timeout to the skyportal config.
=> fail_timeout

services/recurring_apis/recurring_apis.py, services/reminders/reminders.py
This PR removes the "get" call throwing sqlalchemy warnings in a few services.
=> remove user get

config.yaml.defaults
This PR adds MAXI_UNKNOWN to GCN ingestion list (low rate, but interesting objects).
=> MAXI events

requirements.txt, skyportal/models/schema.py
fix the `RemovedInMarshmallow4Warning: The 'default' argument to fields is deprecated. Use 'dump_default' instead.` warning
=> bump arviz version; fix some marshmallow warnings

config.yaml.defaults, doc/analysis.md, package.json, services/sn_analysis_service/app.py, skyportal/app_server.py, skyportal/handlers/api/__init__.py, skyportal/handlers/api/analysis.py, skyportal/handlers/api/webhook.py, skyportal/models/analysis.py, skyportal/tests/api/test_analysis.py
This PR enabled an upload-only endpoint for analysis services. 
After creation of an analysis service (with the parameter `upload_only`=True), this analysis service id can be used for authenticated uploads of analysis results from an external 3rd party. It is the responsibility of the 3rd party to maintain any provenance for the analysis (ie. what specific data was used to run the analysis), to delete outdated versions of the analysis on a given `obj`, and to avoid leaking sensitive data available to the 3rd party but not available to the groups that a specific analysis is attached to. By default we place a cap of 50 completed analyses per object per user/token.
As an example, a 3rd party analysis on the object named `MySourceName` using service number `service_id` can be uploaded as …
=> Upload-only Analysis

skyportal/handlers/api/classification.py
This PR allows the labelling checkbox to remain unchecked after deleting one or all of a source's classifications. This will make it easier to replace classifications in an active learning group without marking the sources as labelled.
=> Let labelling checkbox remain unchecked after classification deletion

static/js/components/SourceAnnotationButtonPlugins.jsx, static/js/components/SourceAnnotationButtons.jsx
This PR adds a placeholder component for plugins to `SourceAnnotationButtons.jsx` and imports these plugins to the same. The intent is to allow additional buttons to appear for specific instances of SkyPortal (e.g. a 'Kowalski' button for Fritz).
=> Add plugins to SourceAnnotationButtons.jsx

config.yaml.defaults
This PR adds the social auth timeout (see https://github.com/cesium-ml/baselayer/pull/353).
=> Social auth timeout

skyportal/plot.py
This PR sets js_on_change for RadioGroup to be active. See https://docs.bokeh.org/en/latest/docs/examples/models/buttons.html.
=> RadioGroup js_on_change to active

skyportal/facility_apis/observation_plan.py
This PR uses field_id rather than id to track fields.
=> Track Field IDs

skyportal/handlers/api/comment.py, skyportal/utils/fits_display.py, static/js/components/CommentAttachmentPreview.jsx
In this PR, we try to provide users with a better preview of fits file, as well as fits.fz files (currently missing)
Here is an example:
| Before | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/49785117/219990179-0ef872e3-6aed-4272-a61b-f8dd8e2671ca.png) | ![image](https://user-images.githubusercontent.com/49785117/219989890-2c0e6707-0fe3-40db-ab93-7106d283be4c.png) |
*Details: I used [ZScaleInterval](https://github.com/spacetelescope/stsci.numdisplay/blob/master/lib/stsci/numdisplay/zscale.py) followed by a [SinhStretch](https://docs.astropy.org/en/stable/visualization/normalization.html#combining-stretches-and-matplotlib-normalization) to achieve this result.*
=> Comments attachments: Better fits file preview

static/js/components/NewGcnEvent.jsx
This PR explicitly checks for undefined variables when performing GcnEvent form validation.
=> GcnEvent form validation

skyportal/handlers/api/gcn.py
This PR undefers the GcnNotice content column so it is downloadable on the GcnEvent page.
=> GcnNotice content

skyportal/model_util.py
This PR needs https://github.com/cesium-ml/baselayer/pull/357 to go in first.
=> Missing SQLAlchemy2 syntax

package.json
Updating Vega, Vega-embed and Vega-lite to the latest versions seem to fix the issue mentioned in https://github.com/skyportal/skyportal/issues/4036
=> Vega zoom bugfix

services/gcn_service/gcn_service.py, skyportal/handlers/api/gcn.py, skyportal/handlers/api/observation_plan.py, skyportal/models/user_notification.py
This PR is a 2nd attempt to reduce (or get rid of) the flakiness experienced in production, where some events have missing localizations.
In production, we notice a warning that says: 
"Attribute history events accumulated on `N` previously clean instances within inner-flush event handlers have been reset, and will not result in database updates."
This happens when we try committing the session right after adding the localization to it. Turns out, that adding notification preferences on events recreates this bug locally. And that both locally and in prod, `N` corresponds exactly to the number of UserNotifications being added to the session. 
Moreover, while testing skymap ingestion locally (with LVC stream catching up to a few days, which means a LOT of alerts at once), we notice that the …
=> Gcn event service: Non Async ingestion | Notifications: Async Ingestion

skyportal/facility_apis/sedmv2.py
Change the `frame_exposure_time` option to a drop-down menu. Drop-down options are the only valid options for the SEDMv2 EMCCD stellar observation mode.
=> add SEDMv2 frame exposure time menu

config.yaml.defaults, requirements.txt, services/openai_analysis_service/app.py, skyportal/handlers/api/analysis.py, skyportal/handlers/api/config_handler.py, skyportal/handlers/api/internal/profile.py, skyportal/tests/frontend/test_openai_prefs.py, static/js/components/AnalysisForm.jsx, static/js/components/CustomizeOpenAIParameters.jsx, static/js/components/FollowupRequestPreferences.jsx, static/js/components/NotificationSettingsSelect.jsx, static/js/components/OpenAIPreferences.jsx, static/js/components/StartBotSummary.jsx
This PR allows each user to customize which OpenAI chat model and parameters are used in source summaries. The default remains the site-wide parameters set in `config.yaml` but those will be overridden if set by the end user.
Small other fixes are in this PR, including removing a console message and cleaning up the view in the start AI summary dialog.
=> User-specific OpenAI preferences

skyportal/facility_apis/sedmv2.py
Remove the 60s single frame option from SEDMv2 follow-up requests. It is not a valid option within the software for the imaging mode.
=> remove 60s single frame exposure for SEDMv2

skyportal/facility_apis/_base.py, skyportal/facility_apis/interface.py, skyportal/facility_apis/sedm.py, skyportal/handlers/api/followup_request.py, static/js/components/EditFollowupRequestDialog.jsx, static/js/components/FollowupRequestLists.jsx
This PR addresses Don and Jesper's comments about the SEDM new fields that needs to be optional and always have default value. 
Moreover, this makes it possible to resubmit if the previous submission has a  "failed to submit" status. This is useful for example if you created a followup requests with an allocation that was missing credentials which you fixed right after, or if the instrument's API wasn't available for a sec... That way, you can retry submitting your request without having to delete it and input all the values again.
=> Follow-up requests: missing SEDM defaults + re-submit on failure

skyportal/app_server.py
It is already possible in baselayer to specify the engine args of the database (pool size, overflow, ...) in the config, but a piece of code in SP specified other values than the default ones in a way that creates issues when specifying them in the config. 
This PR addresses that issue by using the SP default values (that are a little higher than the baselayer ones) if not provided in the config, and otherwise uses the ones specified in the config.
=> Custom Engine args

requirements.txt
It seems that a recent release of simple-json breaks some of the json compliant verification we do in the data loader method. 
It's very probable that we could just change some code on our side rather than pin a version, but given that its still a little unclear what needs to chance, it is best to pin a version while we modify the code to allow unit tests and the app to still function.
=> Bugfix: make load_demo_data

skyportal/facility_apis/ztf.py, skyportal/handlers/api/observation_plan.py, skyportal/tests/flaky/test_frontend_flaky.py, static/js/components/AddGcnTag.jsx, static/js/components/GcnProperties.jsx, static/js/components/GcnSummary.jsx, static/js/components/GcnTags.jsx, static/js/components/NewDefaultObservationPlan.jsx
In the GCN Summary component, we fetch groups and users and until those are fetched, we can't open the component. 
This PR removes this component, as anyway groups are hydrated when loading SP, and we shouldn't fetched all users but only the group_users of the selected group.
=> GCN Bugfix: Summary won't open

config.yaml.defaults, skyportal/facility_apis/observation_plan.py, skyportal/handlers/api/gcn.py, skyportal/handlers/api/gcn_tach.py, skyportal/handlers/api/observation_plan.py, skyportal/model_util.py, skyportal/tests/api/test_gcn.py, skyportal/tests/frontend/test_gcn.py, skyportal/utils/gcn.py, static/js/components/GcnAliases.jsx, static/js/components/GcnEventAllocationTriggers.jsx, static/js/components/GcnEventPage.jsx, static/js/components/GcnLocalizationsTable.jsx, static/js/components/GcnProperties.jsx, static/js/components/GcnSelectionForm.jsx, static/js/components/GcnSummary.jsx, static/js/components/GcnTags.jsx, static/js/components/ObservationPlanRequestForm.jsx, static/js/components/ObservationPlanRequestLists.jsx, static/js/components/SourceTable.jsx, static/js/ducks/gcnEvent.js
This PR makes it possible to choose which method to use to get the fields to observe when creating an obs plan: Postgres query, or gwemopt code. This is because currently in production, the Postgres query does not return in time, as the queries involving instrument field tiles and localization tiles do not scale well as the localization tiles table grows larger.
Also, we add several minor changes that improve the user experience and make many GCN-related features more practical to use (this is based on multiple astronomers' feedback).
=> WIP: Find fields with gwemopt configurable + minor quality of life improvements

static/js/components/ShowClassification.jsx
It seems that if the classifications and source are fetched before the config, the page crashed. This minor change should fix that.
=> Source Page classification: Avoid errors when config colors aren't fetched yet.

skyportal/utils/gcn.py
This PR allows redirects when using a HEAD request to verify whether a skymap file is available or not.
=> Skymap availability: Allow redirects

.gitignore, services/notification_queue/notification_queue.py, services/observation_plan_queue/observation_plan_queue.py, skyportal/models/user_notification.py
In this PR, we make sure that the handler pushing to the queue, and the service processing it run on different threads. Using only asyncio means that right now both are running on the same thread, in the same event loop. Because of that, we may end up having timeouts when pushing a notification, which could impact every feature that needs might trigger notifications (many).
By reducing delays in general, this PR also should help with the flakiness of some tests.
---------------------------------------------------------
Here are 2 tests who's flakiness is more persistent, and should be addressed in later PRs:
- test_analysis_with_file_input -> unknown origin
- test_gcn_tach -> frontend issue, page crashes here but not locally
*Both are frontend tests*
=> Notification Queue: Multi-threading

static/js/components/GcnLocalizationsTable.jsx, static/js/components/GcnProperties.jsx, static/js/components/GcnPropertiesSelect.jsx, static/js/components/NotificationGcnEvent.jsx
In this PR, we display some values nicely in more readable units (like FAR), and allow users to also enter these values in these units. For the backend, however, everything stays the same.
----
This PR also contains a frontend bugfix to try to help with the flakiness of the gcn tach test
=> GCN Notifications frontend: Nicer display

package.json, static/js/components/GcnEventPage.jsx, static/js/components/GcnSelectionForm.jsx, static/js/components/LocalizationPlot.jsx, static/js/components/ObservationPlanRequestForm.jsx, static/js/components/ObservationPlanRequestLists.jsx, static/js/ducks/localization.js
This PR adds:
- a projection dropdown to switch between mollweide and orthographic, which can be easily extended to more projections.
- Default to mollweide in the obsplan list for better visibility.
- Fixed bug where changing localization wouldn't load the newly selected one.
=> Localization plot: Mollweide projection and bugfix

skyportal/handlers/api/gcn.py, static/js/components/FilterCandidateList.jsx, static/js/components/GcnEvents.jsx
Previously, it was impossible to search events by date in the gcn event list, and we could only filter candidates by the last 10 events. In this PR, we make it possible to search events by typing partial dateobs strings in both components.
This will be followed by a (less urgent) PR where the code added to the candidate list will be reused in all other components where we need a dropdown to select events.
=> GCN Table and GCN Candidate filtering: Search by dateobs

skyportal/tests/frontend/test_profile.py, static/js/components/OriginSelect.jsx
In this PR, we temporarely prevent the frontend from fetching ALL unique origins from the photometry table, which times out and puts too much load on the database.
This PR will be followed by a second PR, where we change the feature entirely to avoid running that query.
=> Plotting preferences: Temporarely deactivate all origins fetching

skyportal/handlers/api/tns.py
In an f-string, one needs to double the curly brackets if they are part of the string and not just to add variables in the string. This seems to be missing in the handler to submit sources to TNS.
=> TNS Submission bugfix

config.yaml.defaults, skyportal/handlers/api/internal/annotations_info.py, skyportal/tests/frontend/test_scanning_page.py, skyportal/utils/cache.py, static/js/components/CandidateList.jsx, static/js/components/CandidatesPreferences.jsx, static/js/components/FilterCandidateList.jsx, test_config.yaml
In this PR, we cache the result of the annotations info caching.
The annotation page is heavily used, and this query is expected to pretty much always return the same output. Especially now that it has a tendency to time out, it makes sense to cache it given that the results will almost always be the same. We cache it for 6 hours by default, as the only time the output might change is overnight when a new Kowalski filter has been added.
Also, we modify the frontend to remove repetitive calls to that endpoint.
In this PR, we also add a `dict_to_bytes` method to the cache utils, which might come in handy when one needs to cache something other than a list/array.
=> Annotations info caching

config.yaml.defaults, skyportal/handlers/api/config_handler.py, skyportal/handlers/api/summary_query.py, skyportal/tests/api/test_query.py, skyportal/tests/api/test_summary_query.py, static/js/components/ShowSummaries.jsx, static/js/components/SummarySearch.jsx, static/js/ducks/summary.js
This PR adds the ability to query the summary vector database with a natural language query, by adding a new frontend page `/summary_search`.
Changes the API from GET to POST and updates the tests.
TODO:
=> Frontend Search Summary Query

skyportal/handlers/api/galaxy.py, static/js/components/GcnSelectionForm.jsx
We've transitioned to a partitioned table for the LocalizationTiles. We added code to use the correct partition in other handlers, but not in this one yet.
Also, we add a few frontend lines to prevent resetting the GcnSelectionForm values upon submission and re-rendering.
=> Galaxy in Localization Query: Use specific partition

skyportal/handlers/api/sources_confirmed_in_gcn.py, static/js/components/ConfirmSourceInGCN.jsx, static/js/components/GcnSelectionForm.jsx, static/js/components/SourceTable.jsx
In this PR we:
- Fix the download of sources from the source table on the gcn page [issue #4231]
- Stop hiding the table when there are no sources, so that additional filters can be reset without having to requery sources [issue #4231]
- Increase the default nb of sources in the table to 100 [issue #4230]
- Rename "confirmed" to "highlight" in the component to confirm/reject sources in gcn [issue #4228]
=> Sources in GCN Table: Various user requests

static/js/components/LocalizationPlot.jsx, static/js/components/ObservationPlanRequestForm.jsx
It seems that the fields selection was using the ids in the DB and not the actual field ids. With these changes, I can successfully get gwemopt to target specific fields 👍 
TODO: In a following PR, fix the field selection from the map. Right now it works for the primary and not the secondary somehow. Probably that the fields plotted first (that end up underneath) can't be clicked. This is not very important and requires some D3 magic.
=> Field picking fix: use field_id instead of id

services/gcn_service/gcn_service.py
Skip retractions ingestion if the event doesn't exist in the DB
=> GCN Ingestion: Skip retractions if the event doesn't exist in the DB

skyportal/handlers/api/allocation.py
This PR checks if the follow-up requester is None.
=> Allow requester to be none when returning allocation

static/js/components/CatalogQueryForm.jsx
This PR uses the follow-up allocations for catalog queries (which makes more sense).
=> Use follow-up allocations for catalog queries

skyportal/utils/tns.py
This makes reading TNS spectra files more generic.
=> TNS spectra columns

skyportal/handlers/api/tns.py, skyportal/models/tns.py, static/js/components/Group.jsx, static/js/components/TNSRobots.jsx, static/js/ducks/tnsrobots.js
This PR adds the frontend necessary to create, edit and delete TNS robots from the frontend.
When creating/editing a robot, a user can activate the 'auto_report' feature (if so, it is also necessary to specify an `auto_reporters` string).
=> Group page: TNS Robots management

config.yaml.defaults, services/tns_queue/tns_queue.py, skyportal/handlers/api/tns.py, skyportal/utils/calculations.py, skyportal/utils/tns.py, static/js/units.js
In this PR, we add a TNS name retrieval queue that runs in the same place as the submission queue, only in a different thread.
This system will query for the TNS names from the last `X` days, and run 2 arcseconds cone searches to determine whether or not an object in the database might be associated with it. If that is the case, it will add a TNS name to it.
In a following PR, we want to extend that system to add as much `tns_info` as we can to the objects in the DB. Here we used bs4 to get the TNS data instead of the API, simply because the API does not return the coordinates of objects when fetching multiple objects at once, while the frontend does. Given that we get 50 objects per page, even with just 50 objects added in a day or 2, that brings us to 1 GET request instead of 1+50x1=51 …
=> TNS Monitoring

skyportal/handlers/api/photometry.py
Pandas converts obj_ids that are just made of numbers to int64, which breaks the query that checks if the object exists as the datatype doesn't match the one of the column. This is a quick bugfix.
=> Photometry upload bugfix: avoid issue with obj_ids converted to int64

skyportal/handlers/api/gcn.py, skyportal/handlers/api/observation.py, static/js/components/GcnSelectionForm.jsx, static/js/components/GcnSummary.jsx
This PR adds an (optional) parameter to specify a minimum of observations per field required when fetching observations overlapping with a localization at the Nth credible region. 
This is useful as some folks only care about reporting observations of fields that have been observed at least N times (especially when generating summaries, which has been added here too).
When None or set to 1, this will simply be ignored and the query will be unchanged.
=> Observations in GCN: Min obs per field

skyportal/handlers/api/gcn.py
This PR removes observation plans queried with GcnEvent, as they are not used.
=> No need for observation plans queried with GcnEvent

config.yaml.defaults
After deploying an app kept dying caus it used the port I specified (app 10), as the app ports are in that range.
I added a hotfix, but good to know.
=> TNS submission queue port: Change to something an api instance wouldn't use

static/js/components/AnnotationsTable.jsx
We already had the possibility to open a dialog with the annotation table (on the source page) so that it could be easier to read. However, this didn't work, as its height was still constrained and basically showed the same table. Also, the button to expand the table showed even in the table in the dialog, resulting in an annotations-ception if used incorrectly 🕳️ .
This PR solves both of these problems.
=> Expanded Annotation table: Fit screen

Dockerfile
This PR bumps Dockerfile to use node.js 18.
=> Bump to node.js 18

skyportal/utils/catalog.py
The table behind the conesearch had a change in its schema -- and `jdendhist` is now `jd`.
In addition, conesearch performances should be much better.
=> Use jd instead of jdendhist to account for schema change in Fink

requirements.txt, skyportal/handlers/api/catalog_services.py, skyportal/utils/catalog.py, static/js/components/AddCatalogQueryPage.jsx, static/js/components/CatalogQueryLists.jsx, static/js/ducks/gcnEvent.js
Best way to try this is to take the Kowalski config from prod, add a token to a P48 allocation of the demo data, and run it on some events. the GW event in the test demo data (from 2019) wont work because the fits file is too large for Kowalski currently. I suggest grabbing a voevent from prod and ingesting that to run it on a gw event from O4. Like:
[S230627c.txt](https://github.com/skyportal/skyportal/files/11962708/S230627c.txt)
or
[S230615az.txt](https://github.com/skyportal/skyportal/files/11962709/S230615az.txt)
=> Catalog queries: Use kowalski's new skymap endpoint + better frontend

.github/workflows/test_docker_build.yaml, Dockerfile
add screen to the docker image, which is very useful when we need to run long running scripts to update entries of the db in bulk for example, which has proven challenging and suboptimal which dedicated endpoints (both for development and when running the code).
With screen, we can create screens in which to run the scripts, detach (when leaving the container) and re-attach to verify the progress of a script.
=> Dockerfile: add screen

static/js/components/FilterCandidateList.jsx, static/js/components/GcnSelectionForm.jsx
This PR is the frontend counterpart of #4404, added separately to not expose the frontend in prod before all the photstats are updated.
=> Frontend - Candidate scanning and sources in GCN: exclude forced photometry

services/observation_plan_queue/observation_plan_queue.py
Limit how far back in time we look when fetching plans to process
=> Obsplan queue: time limit

skyportal/tests/frontend/test_user.py, static/js/components/CommentEntry.jsx, static/js/components/CommentListMobile.jsx, static/js/components/EarthquakePage.jsx, static/js/components/GcnEventPage.jsx, static/js/components/GcnSelectionForm.jsx, static/js/components/Main.jsx.template, static/js/components/OriginSelect.jsx, static/js/components/ShareDataForm.jsx, static/js/components/ShiftManagement.jsx, static/js/components/ShiftPage.jsx, static/js/components/SourceDesktop.jsx, webpack.config.js
This PR is an attempt to fix the issues with chrome and firefox not caching our monolithic webpack that's over 50MB, by splitting it in a smaller main bundle, along with individual assets for each route. 
This seems to fix all caching issues on chrome and firefox, and here's why:
Currently, our webpack is over 50MB. This seems to prevent browsers like chrome and firefox from caching it once it has been loaded. For firefox, this is imply because there is a hard limit to how big one file can be to be cached. For chrome it is still unclear, as they claim there is no limit, even though it behaves like there is one.
Most websites don't send the client all of the assets as soon as they access any page, but rather split their website in smaller chunks, that will be lazy loaded in the background, …
=> Frontend caching fix: routes lazy loading

static/js/components/UploadSpectrum.jsx
This PR allows us to pre-fill the upload spectrum page's form by passing arguments directly in the URL.
When it comes to uploading the file itself, the file can be passed as a URL from where it can be downloaded.
These are the arguments that can be passed:
-observed_by (list of ints of user ids)
- reduced_by (list of ints of user ids)
- spectrum_type (source, host, or host_center)
- instrument_id (int)
- mjd (float)
- group_ids (list of ints of group ids)
- has_fluxerr (Yes or No)
- fluxerr_column (int, nb of the column in the ascii file. To pass only if has_fluxerr is Yes)
- flux_column (int, nb of the column in the ascii file)
- wave_column (int, nb of the column in the ascii file)
- file_name (string)
- file_url (string)
String values should NOT be in quotes, though we do recommend it …
=> Spectrum upload: Pre-fill form using URL arguments

skyportal/plot.py
If there are too many items in the legend, those are cropped and it makes it impossible to hide/show items on the photometry plot. This is a quick fix as this is impacting user experience, but we might want to handle this better in the future.
Basically, here, we just add more height as needed, which already the case on other deviced, but didn't work on desktop as we forced the height to 500.
=> Phot plot height fix when legend is too long

config.yaml.defaults, skyportal/facility_apis/observation_plan.py, skyportal/facility_apis/ztf.py, skyportal/handlers/api/gcn.py, skyportal/handlers/api/observation_plan.py, skyportal/tests/api/candidates_sources_events/test_observation_plan.py, static/js/components/FollowupRequestLists.jsx, static/js/components/LocalizationPlot.jsx, static/js/components/NewShift.jsx, static/js/components/ObservationPlanRequestForm.jsx, static/js/components/RunSummary.jsx
This PR allows us to pass reference filters to gwemopt, but also improves on a few things:
- only show sub-parameters when the parameter they depend on it set on the right value, which helps make the frontend form WAY more usable.
- allows to change the airmass threshold used when plotting fields, from the frontend directly.
- fixes a bug where downloading an airmass chart on browsers other than firefox wouldn't save it as PDF.
=> Observation planning - Use references, better frontend.

skyportal/handlers/api/instrument.py, skyportal/handlers/api/observation_plan.py, skyportal/utils/calculations.py
This PR duplicates some of the methods found in telescopes, instruments, and observation_plans models, and refactors them to process multiple fields add once. That way, fetching the instrument fields that overlap with a skymap (where we calculate airmass), and fetching a single observation plan (where we calculate rise and set times) is **much** faster.
The speed up is more than x100 times, and even better than that for large maps and for plans with a lot of observations. It takes us from a few seconds to virtually nothing, removing some of the delay experienced when going to an event's page.
Latency aside, the goal here is to reduce the load put on the machine running the app.
=> Faster airmass, rise and set time calculations

skyportal/handlers/api/source.py, static/js/ducks/sources.js
Adding back the flags. This ensures that scripts that might use them don't break, while still attempting not to use them on the frontend (for performances, testing).
=> Bring back the ...exists flag in the backend (not used in webapp)

skyportal/handlers/api/source.py
Right now, the `use_cache` flag is forced to true, no query_id can actually be provided. This results in a broken cache feature, running a longer query for every single query and affecting performance.
In a following PR, we will make sure to use the cache from the frontend.
=> Fix source query cache

static/js/components/CentroidPlot.jsx
One problem with the centroid plot is the current color scheme, which makes it hard to figure out which points are in which filter and instrument. Fixing the color scheme is a problem of it's own (to fix here, and in Fritz with the addition of the Kowalski crossmatches), but I found that at least adding the filter in the tooltip allows one to know what they're looking at.
=> Centroid plot: add filter in tooltip

services/tns_retrieval_queue/tns_retrieval_queue.py, skyportal/utils/tns.py, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx
I was wondering why we had the TNS prefix on the TNS objects we create but not the existing objects. This is because the watcher service that takes care of that didn't get updated like the other service.
=> TNS Watcher service: keep TNS prefix

skyportal/handlers/api/tns.py
Set the required permission to `Manage groups`, given that robots are attached to groups it should be the same permission.
=> TNSRobotHandler: change permission

services/facility_queue/facility_queue.py
RIght now, we update a Followup request's status every time we query the external service for the results. This causes us to spam some users.
This PR makes sure that we don't update the status if it hasn't changed. But we still update the associated facility transaction request as needed by the service.
=> Facility service: avoid duplicate notifications

static/js/components/AddCatalogQueryPage.jsx, static/js/components/AddSurveyEfficiencyObservationsPage.jsx, static/js/components/NewDefaultObservationPlan.jsx, static/js/components/ObservationPlanRequestForm.jsx
Avoid repeating some API calls. The tricky thing is that the useEffect is triggered on changes on the event (for good reason), but the fetch methods called in the useEffect modify the event, retriggering it.
To prevent that, we just add some `fetching...` state variables, to prevent starting an API call while one is already running.
=> GCN Event page: avoid some repetitive API calls

.github/workflows/build-and-deploy-docs.yaml, .github/workflows/test_api_and_frontend.yaml, .github/workflows/test_migrations.yaml, .github/workflows/test_models.yaml
We haven't pinned a specific dockerhub image for postgres. It looks like the latest one (version 16.0) creates some issues.
This is an attempt to pin the latest available image for version 14 (the one we support), to see if that helps.
Of course we can consider fixing it for version 16, but we need to get the Github actions to work again first.
=> Github actions: pin postgres version

skyportal/handlers/api/gcn.py
Some summaries fail in prod, and I believe it might be because of that line. The error has to do with 'SSL connection closed', so maybe using the session we just created rather than the old sqlalchemy syntax might fix it.
=> Gcn summary: bugfix attempt

skyportal/handlers/api/source.py
fix the default sort order when no sort by is specified.
=> Legacy get_sources method: fix default sort order

skyportal/handlers/api/catalog_services.py, skyportal/handlers/api/comment.py, skyportal/handlers/api/followup_request.py, skyportal/handlers/api/observation_plan.py, skyportal/handlers/api/source.py, skyportal/models/followup_request.py, skyportal/models/schema.py
This PR adds 3 features:
- (1) When using the POST endpoint to save a source to group(s), cancel saving to some group(s) if they've already been saved as sources to some defined groups. Here's an example: you want to save an obj as a source to group A, but only if it's not already saved to group B. So you pass an extra argument called `ignore_if_in_group_ids` equal to `{group_A_id: [group_B_id]}`.
- (2) When triggering a follow-up request on an object, pass a list of group IDs to which the object needs to be saved as a source already. Example: you want to trigger a follow-up with allocation A, but only if the obj is saved as a source to group A, so you pass `source-group_ids` as an argument, which value will be `[group_A_id]`.
- (3) When posting a comment with the same author, text, …
=> Sources: don't save if already saved to group_ids, avoid duplicate comments

skyportal/handlers/api/followup_request.py, skyportal/models/schema.py
add more followup constraints (which if met, cancel triggering):
- not_if_classified
- not_if_spectra_exists
This will be used by the auto-followup feature of Kowalski, to avoid triggering if a source is already classified or already has spectra data.
Also, if constraints are met and we don't trigger, still send a 200 instead of an error (as this cancelation has been requested by the user), along with an ignored flag set to true, and a message containing the reason why it wasn't triggered (which constraint was met).
=> More follow-up constraints 

skyportal/handlers/api/group.py
Igor wasn't able to add another user to his group, because the user did not have access to one of your group's stream(s).
Stream access control is limited to super admin (for a good reason), so this is something that a user needs to contact a super admin to take care of it. 
The current error message isn't that clear and isn't very helpful in understanding what to do.
This should help.
=> GroupUser without stream access: better error message

skyportal/handlers/api/followup_request.py
add missing target group ids in the response when fetching follow-up request(s), which is useful information in general, but especially when you want to update the request, so you have the list and you do not risk to change it without knowing when using the PUT handler.
=> FollowupRequestHandler: return target groups

skyportal/handlers/api/followup_request.py, static/js/components/FollowupRequestLists.jsx, static/js/components/FollowupRequestPage.jsx, static/js/components/FollowupRequestSelectionForm.jsx
This PR:
- fixes the filtering by start_date and end_date of the requests, and makes it optional by default
- adds filtering by allocation
- adds filtering by requester
- display the created_at date of each request on the followup requests page
- adds sorting on created_at, modified, and obj_id
- sort by created_at desc (newer first) by default on the followup requests page
=> Follow-up requests GET: more filtering options

static/js/actions.js, static/js/components/Main.jsx.template, static/js/ducks/hydration.js
If users open multiple tabs one after the other, with the current code, new tabs might think they are fully hydrated when really the previous tab was only partially hydrated.
This should help with that, by better tracking how complete hydration is, and partially hydrating if needed.
=> Hydration from existing tabs - allow partial hydration

skyportal/handlers/api/source.py, static/js/components/QuickSaveSource.jsx, static/js/components/QuickSaveSourcePreferences.jsx, static/js/components/SourceDesktop.jsx, static/js/components/SourceMobile.jsx, static/js/components/UpdateProfileForm.jsx, static/js/store.js
This PR adds a quick save button on the source page. Most scanners save sources to the same groups, and complain that saving a source to the same groups every time is not practical, as they need to go click save -> which opens a dialog window -> they need to go through their list of groups and select them -> confirm. When really, they could just set which groups they want to always save to, and click a "quick save" button instead.
This PR adds that, by adding a section in the user preferences to select the groups to "quick save" to, and the button to do so on the source page.
=> Source: Quick save

skyportal/handlers/api/sources.py
Make sure that the pageNumber and NbPerPage, once returned in the query response, are integers and not strings.
=> Experimental source queries: fixed pagination datatypes

services/health_monitor/health_monitor.py
I noticed in prod that the health monitor wasn't running as expected. Before it starts monitoring the apps, it wants to check if the DB is migrated. For that, it queries the DB migration server, which runs some alembic code. Aside from using quite a bit of CPU resources when running this alembic code, the timeout set in the health monitor is too short (10sec) so this query timeouts, and runs again 30 seconds after, also timing out.
Changing that 10-second timeout to 30 seems to be enough to not timeout anymore.
=> Health monitor: DB migration check patience

skyportal/tests/frontend/sources_and_followup_etc/test_sources.py, static/js/components/ClassificationForm.jsx
Instead of having to go through long lists of classifications within a taxonomy (which is highly impractical), this allows users to type the classification they are looking for, see a list of N suggestions that match that string, and pick which one to submit.
This is based on feedback from the ZTF team meeting Oct 23
=> Classification: search with autoselect

skyportal/handlers/api/telescope.py, skyportal/models/telescope.py
Cache telescope current time info (next day time, next night time, is it day or night right now), and only refresh the cache when any of these dates are past the current UTC date. This ensures that we don't trigger astroplan's slow calculations every time we hit the telescopes endpoint from the frontend, which currently takes ~7 seconds to return in production. This should get that back to ~100 ms, except of course when one or more telescopes' current time info needs to be updated.
=> Telescopes: next day/night time caching

skyportal/handlers/api/followup_request.py
It looks like the handler currently implements pagination, but does not return pagination info.
It does not "break" anything, but makes it confusing if you are using it without knowing about the pagination.
=> Follow-up requests GET: pagination info

skyportal/handlers/api/analysis.py, skyportal/handlers/api/webhook.py, static/js/components/AnalysisList.jsx, static/js/ducks/source.js
Currently, the list of analyses isn't responsive at all to any changes. This PR ensures that:
- we refresh the list to show a new analysis when a user submits one
- we refresh the list correctly after deleting an analysis
- we refresh the list when an analysis gets updated (as completed or failed) through the associated webhook
This should help prevent users from refreshing the whole page every time they perform any actions there, or when the results are uploaded back to SkyPortal.
=> Analysis Frontend: update list after adding,deleting, and updating

skyportal/handlers/api/comment.py
Recently folks have been uploading attachments that are png screenshots. However, looks like their system includes some non standard space chars, which can't be encoded with the default latin-1 that tornado uses.
To get around that, and prevent any other weird names from breaking the download process, we make sure that non-ascii characters are all replaced by simple spaces. We can imagine something a little smarter, but having a first bugfix is important.
Right now that failure leads to the "system provisioning" error for the client for some reason, preventing any other API call from running for a few seconds.
=> Download/Preview attachments: bugfix

static/js/components/FollowupRequestLists.jsx
It looks like the count parameter passed to the mui datatable options used the totalMatches value. However, since the requests are split in lists by instruments, we want the count to be the one for that instrument.
For that, and since the pagination here isn't server-side, we can simply not pass that count parameter and only pass it when navigating the follow-up requests page (where we only query one instrument at a time/allocation at the time anyway, so that number is always accurate).
=> Follow-up requests lists on source page: fix table count

services/facility_queue/facility_queue.py, skyportal/facility_apis/atlas.py, skyportal/facility_apis/ps1.py, skyportal/facility_apis/tess.py, skyportal/facility_apis/ztf.py, skyportal/handlers/api/photometry.py, static/js/components/AirmassPlot.jsx, static/js/components/PhotometryTable.jsx, static/js/components/UpdatePhotometry.jsx, static/js/ducks/photometry.js
This PR extends on the current add_external_photomety method to make sure that we can either:
- as we do currently, error when any new rows already exist, and not even add the non-duplicates
- ignore duplicates, and only add new ones
- update duplicates if needed, and then add new ones
I made it so that the update is the default behavior, as I believe most places in the code that do call that method want to be doing that, but we could keep it to "error" by default, and specify that we allow an "update" where needed.
=> external_photometry method - different behaviors regarding duplicates

static/js/components/NewGroupForm.jsx
The form elements were not sized correctly. The text boxes were small and the Group admin placeholder overlapped with the dropdown icon. Though this did not affect functionality, it made the UI look incomplete.
I changed the css in NewGroupForm.jsx to fix this.
Add screenshots and/or movies showing the changes, if relevant
changed to:
=> 'Create New Group' form css changed

.github/workflows/build-and-deploy-docs.yaml, .github/workflows/test_api_and_frontend.yaml, .github/workflows/test_migrations.yaml, .github/workflows/test_models.yaml
Looks like the GAs are not running because we're not managing to install a few system dependencies we need for pycurl.
Opening a PR just so I can run said actions and try a few potential bugfixes.
=> GA bugfix: pycurl system dependencies

requirements.txt
An attempt to fix a failed dependabot PR
=> Pin gcn-kafka to 0.3.3 and confluent-kafka to 2.2.0

.github/labeler.yml, .github/workflows/add_labels.yaml
In our GitHub actions, we're not specifying a version of the labeler to use. They recently released a new version which seems to break ours.
This is an attempt to update to that newer syntax, which honestly isn't as clear as the previous version in my opinion.
=> GA: labeler v5 update

.github/workflows/add_labels.yaml
Numerous issues with the version of the action that's on its main branch. Following the new documentation to fix breaking changes still leaves us with an issue that prevents anything from running. This is an attempt to just pin the previous (working) version while we figure out the v5 or while it gets fixed.
EDIT: The version number I pinned is incorrect. Let's try to fix that first to see if the v5 actually works now
=> Labeler action: fix version number

services/facility_queue/facility_queue.py, services/notification_queue/notification_queue.py, services/thumbnail_queue/thumbnail_queue.py
We had an issue in production where the thumbnails queue kept filling up and didn't seem to get processed at all, as if the API running on one thread was doing just fine, but the queue processing running on the other wasn't there anymore. Nothing in said queue processing service seems to be able to just get stuck like that, so it's likely that the thread was just not alive anymore for some reason. The app had been up for more than a week which rarely happens, so that might be the reason.
This should check if the threads are still up and restart them if necessary.
=> Multi-threaded microservices: thread health check

static/js/components/FollowupRequestForm.jsx
Right now, the start and end date values of our instrument forms are calculated in the backend when they are fetched. However, this means that the values aren't updated in real time. So for example, if you have a Fritz tab left open, the date will never update.
This PR addresses that problem for both forced photometry and follow-up requests:
- for the forced photometry, we simply use 30 days with now as the end date.
- for follow-up requests, we calculate the time range used from the default values, and recalculate new values using now as the start date and now + calculated range as the end date.
=> Forced Photometry Form - dynamic date range

skyportal/handlers/api/photometry.py
A variable (upload_id) ended up being undefined if there is no new photometry to upload. This should fix it.
=> Insert photometry bugfix - no error when no rows are uploaded

.github/workflows/build-and-deploy-docs.yaml, .github/workflows/test_api_and_frontend.yaml, .github/workflows/test_migrations.yaml, .github/workflows/test_models.yaml
Migrate to PostgreSQL 15 for the GitHub actions.
If possible, we'll also want to open a PR where we document how to upgrade the DB in our docs.
=> GitHub actions: PostgreSQL 15

skyportal/models/schema.py
This causes BTSBot requests to fail recently, so adding it quickly to prevent future failures.
=> Follow-up request schema: add missing optional constraint field

config.yaml.defaults, services/gcn_service/gcn_service.py, services/observation_plan_queue/observation_plan_queue.py, services/recurring_apis/recurring_apis.py, services/reminders/reminders.py, services/thumbnail_queue/thumbnail_queue.py, services/watch_list/watch_list.py, skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py, skyportal/models/obj.py, skyportal/utils/offset.py, skyportal/utils/services.py, skyportal/utils/thumbnail.py
Truth is we do not need a queue for all thumbnails types. Only PS1 is challenging, because we can't simply format a string and BOOM we've got the URL to add in the DB. Instead, we have to run an API call which proved to be more and more unstable.
So here, we do a few things:
- Synchronously post thumbnails for sdss and ls as this doesn't require any external requests, wherever we need. This effectively replaces all the bits of code where we pushed the obj_id to the thumbnails queue's internal API endpoint.
- Remove the internal API endpoint from the queue, making it much simpler to maintain.
- Instead of getting the list of objects to process from an internal API queue, the service now runs a simple DB query which does: "give me the most recent object for which we don't have all three …
=> Thumbnails ingestion - Simpler & (hopefully) better

skyportal/utils/offset.py
This PR logs exception rather than raises when no PS1 url.
=> Log rather than raise exception when PS1 does not work

skyportal/models/obj.py, skyportal/utils/offset.py
Recent commits on main handled the SSL error we get when querying PS1 with Python `requests`, but the problem is this keeps adding unavailable PS1 thumbnails in production while slowing down the thumbnails queue as we are waiting for the error to occur every time, meaning we take 10 seconds to add thumbnails to any object.
This prevents this error from occurring, even if moving to http isn't ideal. However, let's remember that this first URL is used to get the final image URL, which does have https in it, so it's not a problem for the end user. The URL saved in the DB for the thumbnails does have https in it.
=> PS1 Thumbnails: https -> http

skyportal/models/phot_stat.py
We aren't ingesting ZTF alert-based forced photometry in SkyPortal yet, but before we do we want to make sure that we take that forced photometry into account when calculating photstats, to reject them from the stats that exclude forced photometry.
=> Alert-based forced photometry - photstats

skyportal/handlers/api/photometry.py
Right now, if a source has no photometry the handler throws a pandas-related error as it tries to access a column that doesn't exist.
=> Photometry handler bugfix: avoid deduplication error if there is no photometry

.github/dependabot.yml
Looks like dependabot's time formatting is more strict than it used to be :)
=> fix dependabot config (schedule.time format)

static/js/components/HeaderContent.jsx.template, static/js/components/PhotometryPlot.jsx, static/js/components/ShowSummaries.jsx, static/js/components/ShowSummaryHistory.jsx, static/js/components/SidebarAndHeader.jsx.template, static/js/components/Source.jsx, static/js/components/SpectraPlot.jsx, static/js/components/SpectroscopyButtonsForm.jsx, static/js/components/ThumbnailList.jsx, static/js/components/UIPreferences.jsx, static/js/components/UpdateSourceSummary.jsx
We got a batch of users to try the new source page before deployment to production. Overall they are happy with it, but they do have some suggestions. This PR implements those + some of the suggestions from @profjsb brought up during the weekly SkyPortal meeting.
Now, if there's enough space, we get the thumbnails in a 6x1 layout, and 3x2 thereafter. Users can decide to hide summaries from the source page's header by default, or only hide the AI-generated ones. Also, they can hide the "similar sources" feature (which is based on said AI summaries embeddings) which is now hidden by default as it created some amount of confusion. The edit/pen icons for most editable fields are now hidden except on hover.
Other items addressed here:
- brought back the background greyed-out spectra when …
=> New source page: thumbnails and user preferences feedback

skyportal/handlers/api/followup_request.py, skyportal/models/schema.py
This PR adds an optional argument when posting follow-up requests, that allows the system to cancel triggering if there are any sources within 0.5 arcsec that have a TNS SN designation already.
=> Follow-up requests constraints: cancel if already classified in TNS

skyportal/handlers/api/observation.py, skyportal/handlers/api/observation_plan.py, static/js/components/AddSurveyEfficiencyObservationsPage.jsx, static/js/components/CatalogQueryLists.jsx, static/js/components/ProgressIndicators.jsx, static/js/components/SurveyEfficiencyForm.jsx, static/js/components/SurveyEfficiencyObservationPlanLists.jsx, static/js/components/SurveyEfficiencyObservationsLists.jsx, static/js/ducks/gcnEvent.js
- have the table on the left and form on the right, using the whole width of the page (unless the screen is too small, in which case they are on top of each other).
- use websockets to get the frontend to fetch the updated list of survey analysis when adding and deleting, and when a survey that's running finishes.
- custom search and download logics.
- fix the path to the dustmaps
=> GCN Observations Survey - Bugfixes and frontend improvements

skyportal/facility_apis/winter.py
- add a delete method to the WINTERAPI, that grabs the schedule name from the POST response (from facility transactions) and calls the `/too/delete` endpoint.
- add a method to grab said schedule name from the POST response
- send the target_name (obj_id) to WINTER when submitting a request (max 30 chars).
=> Followup - WINTERAPI: implement DELETE + add target name in POST payload

.github/workflows/test_api_and_frontend.yaml, Dockerfile, doc/setup.md, nginx.service, skyportal/tests/frontend/test_brotli.py
See https://github.com/cesium-ml/baselayer/pull/379
This PR adds the necessary lines in the dockerfile to install nginx with brotli support, and the documentation needed.
This is a draft, and thinks need to change before reviewing and/or merging. For example, I would like to move the `nginx.service` file to baselayer's nginx service.
=> Brotli support in nginx

skyportal/handlers/api/followup_request.py, skyportal/models/schema.py, static/js/components/Source.jsx, static/js/components/SourceGCNCrossmatchList.jsx
In practice, we noticed how many duplicates of a source you might get with a survey like ZTF.
So it makes more sense to apply these constraints to nearby sources and not by exact name.
Also, we add a "no_duplicates" constraints to cancel triggering if there's already a follow-up request with the same allocation that is submitted or completed. We already have that logic in Kowalski but this will add redundancy and help with concurrency issues.
=> Follow-up requests constraints: conesearches

skyportal/handlers/api/followup_request.py
Just like for the other conditions, use a cone search instead of an exact match.
Also, change the queries from scalars().all() to scalars().first() to only get one match, as anyway our conditions are of the form "if any", meaning we don't need more than one.
=> Follow-up requests constraints: not_if_duplicates as cone search

.github/workflows/test_api_and_frontend.yaml, Dockerfile
Looks like installing the module with `libnginx-mod-brotli` creates some issues after an nginx update. We can simply install the 2 underlying modules separately, which works without creating any versions mismatch conflict.
=> Brotli install fix

static/js/components/FilterCandidateList.jsx
I spotted an issue on preview, where searching for groups with the search bar would cause incorrect groups to be selected. 
This PR stops using the form to handle that selected group state so we don't need to hack our way around using indexes to map to group ids which is a mess.
=> Candidates Filter Form V2 Bugfix: program selection

package.json, skyportal/tests/frontend/test_scanning_page.py, static/js/components/CandidateList.jsx, static/js/components/FilterCandidateList.jsx
I saw the impact of the "infinity scrolling" in production as soon as you start loading 50+ candidates that have a lot of data. This is an attempt at fixing that by only rendering what's in the view using [react-viewport-list](https://www.npmjs.com/package/react-viewport-list)
=> Candidates List V2: use react-viewport-list to only render candidates that are in view

skyportal/facility_apis/generic.py
This PR checks for empty altdata in the generic API allocations.
=> Empty altdata in follow-up triggering

skyportal/facility_apis/ztf.py
Adds a dropdown to pick what position to use: the object's, flux weighted alerts only (ignoring FP), and flux weighted ZTF alerts only (ignoring FP).
=> ZTF Forced Photometry: Flux weighted position

requirements.txt
With the 1.0.12 version errors when i try to lauch skyportal -> typo errors (md5sum -> md5) (md5extisting -> md5existing)
=> fix dustmaps version 1.0.12 -> 1.0.13

skyportal/utils/offset.py
Looks like maybe one of the API services we grab data from when generating starlists has changed the 'source_id' column to 'SOURCE_ID'. 
This just makes sure that we are not dependant on capitalization anymore, to fix the current problem and maybe avoid another one.
it was hot-patched in production.
=> Starlist bugfix: source_id col

services/tns_retrieval_queue/tns_retrieval_queue.py
* if the TNS obj exists in the DB but isn't saved as a source to the public group, save it
* fix issue created by one of the last commit in the TNS V2 PR, where I exchange the name of 2 variables for clarity but forgot to do so for 2 lines.
* use websockets to update the frontend when adding a TNS name to an existing source or it's TNS source counterpart.
* keep the start_date of the TNS query for new objects identical until we do get new objects.
=> TNS Retrieval: bugfixes

services/tns_retrieval_queue/tns_retrieval_queue.py, services/tns_submission_queue/tns_submission_queue.py, skyportal/models/tns.py
That way we can have a copy of a TNS robot as long as that copy is in testing mode and not the existing bot (or vice versa).
Useful to have a copy of a bot in testing mode to test the auto-reporting while the real bot can still be used for manual reporting only.
TODO: try to improve the TNS to existing source matching, because the conesearch results from TNS contain no distance information or position, and we've matched some older TNS sources with newer ones. Without running a billion extra API calls, this could be as simple as just using a smaller conesearch radius, from 2 to 1 arcsec or less.
=> TNS Robots: Including testing in unique constraint

services/tns_retrieval_queue/tns_retrieval_queue.py, services/tns_submission_queue/tns_submission_queue.py, skyportal/handlers/api/source.py, skyportal/handlers/api/source_groups.py, skyportal/handlers/api/sources_confirmed_in_gcn.py, skyportal/handlers/api/tns.py, static/js/components/PhotometryTable.jsx
When sending a report, TNS gives us a report_id. Reports are processed in their server async (meaning after we sent them), so we can use that report_id (here in our data model called `submission_id`) to query TNS and validate that the report resulted in the creation of a new object, or was posted on an existing one.
This PR adds a little service that loops over submitted reports and tries to query TNS for the report's status. The API docs is not clear enough for me to catch failures to send reports, so for now this only figures out if it was successful. I'm hoping that some reports fail at some point so I can query their system and figure out what a failed response looks like...
When a report is "validated" we make the tns_retrieval_queue fetch the information of the newly added TNS …
=> TNS submission: confirm report processing on TNS

skyportal/handlers/api/internal/source_views.py, skyportal/handlers/api/tns.py, static/js/components/TNSATForm.jsx, static/js/components/TNSRobotsPage.jsx
Some folks keep querying sources for months using scripts (at like a 1-hour cadence).
Though maybe I should just BAN ALL OF THEM USERS, given that we know how much frontend is king for SP, it makes total sense to only show frontend source views in the frontend, and not those registers by API calls.
This PR doesn't just that by ignoring token source views when querying for views in the internal API used by the dashboard widget.
=> Source Views Dashboard Widget: don't count token source views

requirements.txt, skyportal/handlers/api/gcn.py, skyportal/handlers/api/photometric_series.py, skyportal/tests/api/candidates_sources_events/test_photometric_series.py, skyportal/tests/api/test_comments_on_gcn.py, skyportal/tests/api/test_comments_on_spectrum.py, skyportal/tests/api/test_thumbnail.py, skyportal/tests/frontend/sources_and_observingruns_etc/test_scanning_page.py, skyportal/tests/frontend/sources_and_observingruns_etc/test_top_sources.py, skyportal/tests/frontend/test_reminders.py, skyportal/tests/frontend/test_shifts.py
Not sure how many PRs I'll need to get this back on track (some of the flaky tests give me no information whatsoever as to why they are really failing, which makes it hard to fix them), but this is a first set of fixes for a few tests.
The tests on comments are the most annoying, looks like the comments on GCN fail (again, don't know why really) and that cascades into the app not being able to run a single test. Finishing the ThreadSession PR on baselayer to run these GCN-related processes in a separate session to avoid potentially killing the same session as the one used by the API could help for sure, but not guaranteed either.
=> GitHub actions: back on track (part 1)

requirements.txt, services/tns_submission_queue/tns_submission_queue.py, skyportal/models/instrument.py, skyportal/models/stream.py, static/js/components/SpectraPlot.jsx
On the spectra plot, we want the top X axis (rest wavelength) stay in sync with the spectral lines we plot as the redshift and velocity inputs change. 
The only way to have a "dynamic layout" is to simply recreate the layout when needed. Ideally I wanted to only recreate the layout when it needs to be, without having to recreate it when we change the data that's being plotted (with smoothing for example). So, I had it stored in a state variable that the plot would take as an input. 
The problem there is that when the layout gets updated the plot is rendered and the user's current zoom is lost (goes back to the default, as per the new layout axes ranges). I tried to use the `uirevision` argument of the layout (https://plotly.com/javascript/uirevision/) to prevent reset of the zoom on …
=> Spectra plot: keep zoom level after layout updated

requirements.txt
ligo.skymap 0.6.0 is incompatible with latest astropy. We should be using latest version.
=> use latest ligo.skymap

skyportal/facility_apis/trt.py
This PR sets TRT ids to an array when cancelling.
=> TRT ids for cancelling need to be an array

static/js/components/NewPhotometry.jsx
Looks like on some browsers it was using the locale and not the UTC, by assuming the date string was in local time.
=> NewPhotometry ISOT date input - bugfix

skyportal/handlers/api/gcn.py, static/js/components/GcnEvents.jsx
- Updated and improved the display of Localizations and GCN Notices columns
- Removed the repetition of the ‘dateobs’
- Changed ‘overrides’ to ‘components’ for the getMuiTheme function due to its deprecation
- Added styles, removed margins, and added a tooltip to store the URL of the GCN notice
- Moved repeated code to new style functions
- Displayed the types of GCN notices
- Display only 3 localizations and 2 GCN Notices by default, with an option to expand them
- Removed the sort option for all columns except the ‘Date Observed’ column.
=> Issue 4819 gcn events too much white space

skyportal/handlers/api/allocation.py, skyportal/handlers/api/telescope.py, skyportal/models/telescope.py
Looks like astropy is using it's own datatypes for some of the masked arrays now, so we need to look for those too when we want to convert missing values to None, otherwise the response can't serialize that astropy masked dtype.
=> Astropy 6.0 breaking changes: MaskedArray -> MaskedNDArray

skyportal/handlers/api/observingrun.py
Just like for the instruments and telescopes, we check that the results from ephemeris calculations are not MaskedArray OR MaskedNDArray.
=> Astropy 6.0 - Observing run ephemeris bugfix

services/tns_submission_queue/tns_submission_queue.py, skyportal/utils/tns.py
Looks like in production, we sent a report to TNS which gave us a submission ID back, but using it to look for the submission status we get a "404" error, as if they acknowledged receiving it and then... lost it?
Whatever the reason for that, these changes set such a failed submission back to pending after a minute, so we can retry submitting to TNS.
=> TNS Submission: "report not found"

skyportal/handlers/api/source.py, skyportal/handlers/api/sources.py, skyportal/utils/asynchronous.py, static/js/ducks/source.js
Addresses #4884, where a user without delete permissions for thumbnails couldn't remove let the handler remove the public_url ones (sdss, ls, ps1) when updating the coordinates of a source.
This PR fixes that by adding a new decorator named `run_async`. This decorator can take any method and its argument, and will run them in an async process where it will set a unique context for the DBSession created in the method passed to the decorator. This ensures that we can run async processes which DBSessions aren't shared with the main thread or other threads, and therefore don't get killed in the middle of an async operation when the main thread or other threads use the same session. Here, each thread has it's own scope for its session, avoiding this problem entirely.
If this new decorator …
=> Obj Coordinates update: thumbnails delete permission fix

skyportal/handlers/api/observingrun.py
https://github.com/skyportal/skyportal/pull/4875 stopped the handler from crashing, but looks like as soon as one target is not visible, since we reshape the masked array we end up with all the value being 0-dimensional masked arrays, even those that might have a value that's usable.
This PR deals with those appropriately, checking if the 0-dimensional array (which is just a scalar) doesn't have its only value masked.
=> ObservingRunHandler GET: handle rise/set vectorized masked array

skyportal/handlers/api/sources_confirmed_in_gcn.py
The current handler verifies if a source being confirmed as inside of a GCN handler is spatially coincident with the localization. Aside from being unnecessary for all use cases we had so far, this extra validation step comes with some assumptions as to what the first and last detection to use (and min nb detections) when querying the sources in the localization are, which can come with some issues.
In this PR we simply remove this extra check.
=> SourcesConfirmedInGCN: don't validate sources spatially

services/tns_submission_queue/tns_submission_queue.py, skyportal/facility_apis/swift.py
Looks like every now and then TNS gives us a 504 error, where their server is inaccessible. Weirdly enough that seems to happen even when a report gets received by their system.
Here we re-use the "report confirmation" queue to look for reports with a gateway timeout error and figure out if they were submitted or need to be reprocessed again.
=> TNS submission - 504 (gateway timeout)

skyportal/facility_apis/winter.py, skyportal/facility_apis/ztf.py
* ZTF: for FP lightcurves with an overall non-zero procstatus, make sure to filter out individual datapoints that don't have a procstatus=0, to avoid bad substractions and things of that nature.
* WNTR: fix the class method call to retrieve the schedule_name from the response from the POST method that runs when sending a target to WNTR.
=> Facility requests: various bugfixes

skyportal/handlers/api/observingrun.py
Earlier this week we had issues where runs where a target would never rise/set would not return rise/set for any of the targets, because all of the individual rise/set would be masked arrays. When fixing it, it ended up causing troubles for runs where the targets are ALL visible, and none of the items end up having masked arrays to look at.
This PR fixes that
=> Observing run API GET: dtype bugfix

services/tns_submission_queue/tns_submission_queue.py, skyportal/facility_apis/swift.py
Removes unnecessary continue statement that would prevent a following block of code from running, and only commit the session if we had any changes to make.
=> TNS submission job validation: remove continue statement

skyportal/facility_apis/ztf.py, skyportal/handlers/api/observation.py, skyportal/handlers/api/observation_plan.py
- When sending a plan to the scheduler, don't show an error due to a unique index on the GCNTrigger table
- When deleting queued observations from ZTF, based on the queue name, mark any associated observation plans as "deleted from telescope queue" to avoid having plans on a GCN page look like they are still in the queue when they aren't anymore.
=> Observation plan request send/delete: various bugfixes

static/js/components/PhotometryPlot.jsx
Pick units from: minutes, hours, days when plotting a period-folded photometry plot. Defaults to the current option with it per day.
=> Period plot: units

skyportal/facility_apis/swift.py, skyportal/handlers/api/source.py, skyportal/tests/api/candidates_sources_events/test_sources.py
In the context of BTSbot, we need to have Kowalski (ZTF's alert broker) to save candidates as sources but not using the dedicated Kowalski account. However, for obvious security reasons, we don't want to start sending user tokens to Kowalski, and for technical reasons, we don't want to split the unique API call to save sources in multiple API calls per user we want to save the objects as.
Instead, we just add an admin-only API query argument that allows super admins to save objects to groups as sources just like we usually would, but specifying users to use as the `saved_by` for each sources.
If a non-admin user tries to use that argument it will raise an error. If one of the user to use as the `saved_by` does not exist or does not have access to the group to which we are saving, do not …
=> WIP - SourceHandler POST: save sources as another user (admin-only)

skyportal/facility_apis/_base.py, skyportal/facility_apis/interface.py, skyportal/facility_apis/swift.py
add a priorityOrder field to all followup requests API, to (internall…y) keep track of the priority/urgency order. Used by Fritz to tell Kowalski what priority order to use when updating automated triggers
=> Followup APIs: priorityOrder

skyportal/handlers/api/user.py, skyportal/models/annotation.py, skyportal/models/comment.py, skyportal/models/user_token.py, static/js/components/CommentListMobile.jsx, static/js/components/CompactCommentList.jsx, static/js/components/NewsFeed.jsx, static/js/components/RegularCommentList.jsx, static/js/components/TNSRobotSubmissionsPage.jsx, static/js/components/TNSRobotsPage.jsx, static/js/components/TopSavers.jsx, static/js/components/UserAvatar.jsx, static/js/components/UserProfileInfo.jsx
Add a bunch of visual cues to make the difference between bot and non-bot users on:
- UserAvatar
- list of users across different TNS related components
This PR also adds a color coding to the statuses shown on the TNSRobotSubmissions page
Here are some screenshots:
=> Bot users: visibility across the frontend

Dockerfile
Add cargo and rust install to the Dockerfile, necessary for python dependencies that have a rust-based core
=> Add rust & cargo to Dockerfile for mocpy

skyportal/tests/frontend/sources_and_observingruns_etc/test_sources.py, static/js/components/CentroidPlot.jsx, static/js/components/CentroidPlotPlugins.jsx, static/js/components/PhotometryPlot.jsx, static/js/components/Source.jsx, static/js/components/TNSRobotSubmissionsPage.jsx, static/js/components/TopSavers.jsx, static/js/components/UserAvatar.jsx
Migrating the vega centroid plot to a much more customizable one with plotly, implementing some of the feed back from the October 2023 ZTF team meeting.
I still don't really know for sure:
- how I should compute the centroid: I implemented the hopefully smarter method we've been using the starlists, finding charts, ... in the frontend too which in theory is better than using a simple median/avg
- what the current red and blue circle represent. I think that the blue one is a 1-sigma circle (so basically a circle around the photometry. Only modification I made here is to only include the photometry that's not further than the 0.5" max offset (same as enforced while calculated the centroid), effectively applying a 0.5" upper bound on that circle. For the red circle, I honestly don't know …
=> Centroid Plot V2 (with plotly)

requirements.txt
1.4.1 pins an older sqlalchemy.
=> obspy 1.4.0

skyportal/handlers/api/observation.py, static/js/components/ExecutedObservationsTable.jsx, static/js/components/QueuedObservationsTable.jsx
I noticed in prod really heavy queries hammering the DB on a daily basis around the same time that we ingest observations. I thought that was the issue but looking at the exact query logged by the gcloud console it looks more like something is fetching observations with a lot of nested joinedloads which are unnecessary during the query itself most of the time and where the relationships could just be lazy loaded when accessed later on (which is the default behavior).
All the joinedloads on the ExecutedObservations or QueuedObservations from the `get_observations` method are removed, and now only the fields are accessed after the query. Adding the instruments and their telescope to every single observations seems super overkill, especially given how easy it is to fetch those separately and …
=> get_observations method: remove heavy joinedload statements

skyportal/app_server.py, skyportal/handlers/api/comment.py, static/js/components/QuickSearchBar.jsx
Part 2 of #5031, allows to query comments without specifying a resourceID (we make it optional now) but by specifying a text. Both options can be combined, but one cannot leave both unspecified.
We then make it possible to search for said objects using the quick search bar.
=> Search by comment: Part 2 (Sources & GCN, via QuickSearchBar)

skyportal/facility_apis/_base.py, skyportal/facility_apis/generic.py, skyportal/facility_apis/observation_plan.py, skyportal/facility_apis/slack.py, skyportal/facility_apis/ztf.py, skyportal/handlers/api/internal/plot.py, skyportal/handlers/api/internal/robotic_instruments.py, skyportal/handlers/api/internal/source_savers.py
adds kwargs to the render_frontend_info method of all instrument API classes. That way, reusable quantities (like unique galaxy catalog names that some instruments take as a parameter) can be computed once before we loop on each instrument and build the rjsf form for each.
=> Instrument API classes: render_frontend_info kwargs

requirements.txt
Python Requirements: add brotli==1.1.0 so requests can use `br` encoding
=> Python Requirements: add brotli==1.1.0 (so requests can use `br` encoding)

skyportal/handlers/api/observation.py
This PR catches arrow parser errors in the observation endpoint.
=> catch arrow parser errors in the observation endpoint

skyportal/handlers/api/photometric_series.py, skyportal/handlers/api/photometry.py, skyportal/handlers/api/photometry_validation.py, skyportal/handlers/api/sharing.py, static/js/ducks/photometry.js
We had this weird situation where the `FETCH_SOURCE_PHOTOMETRY` emitted by the function to well fetch photometry, was also used as the action name for the websocket. It's confusing to read it (as it differs from everywhere else in the app) and it (though fortunately it looks like it doesn't) trigger some funky never ending refresh loop.
This PR updates `FETCH_SOURCE_PHOTOMETRY` to `REFRESH_SOURCE_PHOTOMETRY` for all the backend -> frontend updating logic with websockets.
=> Websocket action: photometry refresh action name

skyportal/handlers/api/observation_plan.py
This PR ensures that we do not require specific permission to make an observation plan.
=> Do not require specific permission to make an observation plan

services/gcn_service/gcn_service.py
This PR strips out the "gcn.notices." part of the topic name.
=> strip out start of notice_type

skyportal/handlers/api/candidate.py, skyportal/handlers/api/source.py
Same treatment as for the `get_sources` method, applied here to the HEAD endpoints for candidates and sources, hoping to speed-up these API queries that are run in large quantities when Kowalski is trying to send data to Fritz during the night.
=> Candidate & Source HEAD: raw sql for speed

static/js/components/user/UserProfileInfo.jsx
An attempt to help people understand that there is a fixed email used for login, so that they do not think the `email` in the "contact" section is the same thing.
=> User Profile: show oauth email

static/js/components/photometry/NewPhotometry.jsx
Don't show the full list of filters of an instrument in the dropdown menu, which breaks the display when the instrument has more than a few filters, and isn't that useful given that the filters are selectable in a dropdown in the form anyway.
=> Upload Single Photometry: simpler instrument select

skyportal/facility_apis/ztf.py, skyportal/handlers/api/candidate.py, skyportal/tests/frontend/sources_and_observingruns_etc/test_scanning_page.py, static/js/components/allocation/AllocationTable.jsx, static/js/components/candidate/CandidatesPreferences.jsx, static/js/components/candidate/CandidatesPreferencesForm.jsx, static/js/components/candidate/FilterCandidateList.jsx, static/js/components/candidate/ScanningProfilesList.jsx
This PR adds the frontend and backend necessary to let users pick if they want to scan for candidates not just WITH but also WITHOUT the classifications of their choice. Previously we could only scan for candidates with the selected classifications, which turned out to not be that useful, as most users want to filter out already classified objects when scanning.
This is a suggestion from Lynne Hillenbrand btw, who scans for large batches of objects every few weeks and wanted to stop seeing the ones she already classified.
Also, we migrate the scanning profiles page to the "new" tables layout, where we use the full width for the table and have the forms to add/edit in a pop up. Creating profiles new profiles also supports that new include vs exclude feature. In the future maybe we want to …
=> Candidate scanning - classification filtering: with OR without

skyportal/facility_apis/lco.py, skyportal/facility_apis/soar.py
This PR fixes a bug where you could only delete observations with LCO / SOAR when there was an observation ID.
=> soar / lco delete when no obs id

.github/workflows/test_docker_build.yaml, skyportal/handlers/api/source_groups.py
Migrate to docker compose v2, where docker-compose is now docker comp…ose (no dash).
Tests are currently failing and that's likely why, as per: https://github.com/orgs/community/discussions/116610
=> GitHub Action -  Docker build: migrate to docker compose v2

.github/workflows/test_docker_build.yaml, doc/deploy.md
Looks like with recent versions of docker-compose (including the one used by GitHub action runners), container names use dashes instead of underscores.
So this is what engineering actually is???
=> Docker-compose update: new container naming schema

skyportal/facility_apis/swift.py, static/js/components/followup_request/FollowupRequestLists.jsx
* the notification we show when clicking "retrieve" on a follow-up request had its type set to "success" when it should have been set to "info" to appear green.
* adds the SWIFT ToO mode
=> Follow-up request: SWIFT ToO mode

skyportal/handlers/api/observation_plan.py
* force the ztf filters to r,g,i when sending to treasuremap, as otherwise treasuremap matches the central wavelength + bandpass of ztf i-band to TESS.
=> ZTF Treasuremap filters

skyportal/handlers/api/candidate.py, static/js/components/source/SourceRedshiftHistory.jsx, static/js/components/source/UpdateSourceRedshift.jsx
We already have a concept of redshift origin but we've been ignoring it from the frontend. This PR let's user set it from the frontend if desired, and then shows it on the redshift history table.
=> Obj Redshift - use existing z origin

static/js/components/source/source_publish/SourcePublish.jsx
Improve the user experience of the publish pop-up by adding:
- tool-tips
- (optional) info when its needed
Pop-up to update:
=> Public page: Add optional title to release panel and tootips

skyportal/handlers/api/followup_request.py, skyportal/models/schema.py
add a followup constraint named ignore_allocation_ids, to cancel posting follow-up requests if there are existing submitted/completed requests with any of the allocations specified in that list.
This is to help bots that run on one allocation that want to avoid triggering if there is a request for another allocation already.
There is a PR on Kowalski here: https://github.com/skyportal/kowalski/pull/412
=> Followup constraint: ignore_allocation_ids

skyportal/utils/offset.py
This PR adds a ReadTimeout exception as an option when querying PS1 thumbnails.
=> PS1 thumbnails ReadTimeout

static/js/components/comment/CommentAttachmentPreview.jsx
This PR makes a few minor changes to help use more of the screen to display attachments, with:
- smaller DialogTitle bar at the top of the dialog
- replace the "Comment attachment" by the filename (user knows they already are looking at the attachment they just clicked on), so we can remove the filename from where it was previously and regain some height.
- make the dialog a little higher and wider
- replace the "DOWNLOAD" text-based button by a download MUI icon, which we use everywhere else already anyway.
=> Comment Attachment Preview: simpler UI

skyportal/handlers/api/sources.py
Fixes a call to session.execute() when fetching photometric series, which we never noticed because it is only called when there is no photometry.
=> get_sources: phot series session.execute fix

skyportal/handlers/api/gcn.py
Differentiate between XRT and BAT, so we can select what to auto trigger on with the default follow-up requests.
=> Autogenerated GCN sources: GRB SWIFT type

.github/workflows/build-and-deploy-docs.yaml, .github/workflows/test_api_and_frontend.yaml, .github/workflows/test_docker_build.yaml, .github/workflows/test_migrations.yaml, .github/workflows/test_models.yaml
Propagate that extra caching to other GitHub action workflows, and updates the version we are using for a bunch of actions (cache, checkout, setup-python, setup-node, ...)
=> GitHub actions: dustmap+sncosmo caching + action versions updates

.github/labeler.yml, .github/workflows/build-and-deploy-docs.yaml
Based on a suggestion from @stefanv, this PR is an attempt at using the github action from https://github.com/MercuryTechnologies/delete-cancelled-runs.
The problem we are facing is that the github action we rely on to build&deploy the docs already cancels previous workflows that are still running, except that when workflow are just cancelled they make the overall test suite appear as failed. Deleting cancelled workflows makes a lot of sense here, and prevents the tests from appearing as failed.
Also, I made small changes to the `labeler.yaml` config, because pretty much all of our PRs ended up with this `needs-migrations?` label. I think that it needs merging for that behavior to stop.
=> Build & Deploy docs GitHub action: auto delete cancelled

.github/workflows/test_migrations.yaml, requirements.txt
the fiona package (that geopandas uses) released a new version that broke geopandas. Until geopandas makes a new release, we can simply pin fiona its previous version.
This impacts features like the earthquake stuff, which breaks make load_demo_data and the migration CI
=> pin fiona to 1.9.6 to fix geopandas

requirements.txt, skyportal/utils/gcn.py
`ligo.skymap.postprocess` provides a `crossmatch` method that you can use for various things, but we use it to simply compute some statistics that we can use to generate properties like of the probability is in 500 sq. deg, what's that contains 90% of the probability, and a couple of tags that derive from that.
However we don't just send the 2d data (uniq and probdensity) that `ligo.skymap` needs to compute the numbers needed for these stats, but we also send the 3d data (distmu, distsigma, distnorm) that `ligo.skymap` can optionally use to give us some volume-related results.
When the volume is added into the mix, much more memory is required which causes some systems to send a sigkill and stop the program. But, we do not even read these 3d results in the first place, so we can avoid …
=> Localization properties computation: memory usage fix

skyportal/handlers/api/gcn.py
Turns out we didn't really need that, so let's keep it simple :)
=> Swift sources origin - no BAT/XRT

services/reminders/reminders.py, skyportal/tests/api/test_reminders.py, skyportal/tests/frontend/test_profile.py, skyportal/tests/frontend/test_reminders.py
This is an attempt at making some tests a little less flaky (if not, not flaky at all) by specifying timezones, and being a little more smart about the checks that we run to not be too sensible to the timing of things.
=> Reminders: API & Frontend tests: less flaky

skyportal/facility_apis/trt.py
TRT joins the club of APIs that give us a 200 when it actually fails, so this PR accounts for some of those failures, updates to SQL alchemy 2.0 syntax, adds more error handling + frontend notifications, and moves to the `run_async` decorator to call the `download_observations` method.
The reviewer should keep in mind that I do not have access to the machine where this is running, so hard to test until deployed. However, the current API class if faulty anyway, so it doesn't hurt to test that in prod (on ICARE).
=> TRT Facility API: various improvements

services/observation_plan_queue/observation_plan_queue.py, skyportal/handlers/api/gcn.py, skyportal/handlers/api/observation_plan.py, skyportal/models/schema.py, static/js/components/observation_plan/NewDefaultObservationPlan.jsx, static/js/components/observation_plan/PlanPropertiesSelect.jsx
This PR addresses a couple of issues such as:
- associating that localization of the plan to the correct GCN notice
- looking at an incorrect key when filtering on gcn notices
Also, it let's the user - optionally - set a list of plan_properties, that the plan generated by gwemopt needs to meet before we can send a plan to the scheduler (when auto send is turned on).
=> Default Observation Plans: auto send - plan properties filter

.github/workflows/build-and-deploy-docs.yaml
https://github.com/skyportal/skyportal/pull/4516 upgrades the version of the action responsible of building the docs, but was merged before validating that it still worked. It shows as green anyways, so none of us noticed.
=> Docs deploy - Fix incorrect GA arguments

.github/workflows/build-and-deploy-docs.yaml, .github/workflows/test_api_and_frontend.yaml, .github/workflows/test_docker_build.yaml, .github/workflows/test_migrations.yaml, .github/workflows/test_models.yaml
This should save our CI cycles for when it's necessary. Could also consider adding a label to control `no-ci`.
=> Only run CI on non-draft PRs

requirements.txt
@stefanv mentioned that it wasn't possible to run SkyPortal on Python 3.12 because of the strict requirement we had on a numpy version.
In general, pinning exact versions has proved to make deployment and the CI much nicer and more reliable for us, but it is true that it makes it a little restrictive when trying to just run SkyPortal on whatever environment one has already.
In this PR, I tried to be a bit more flexible version-wise, for a couple of very packages python packages that I expect people to already have installed, or that might have some Python-version requirement.
If the reviewer has python 3.12 on their system, it could be a good idea to give that a go and see if they can run SkyPortal without downgrading to 3.11
PS: I still specific some maximum major version for these …
=> Python dependencies: loose version requirement for common packages

doc/conf.py, doc/openapi.html.template, requirements.docs.txt, skyportal/handlers/api/analysis.py, skyportal/handlers/api/gcn.py, skyportal/handlers/api/internal/log.py, skyportal/handlers/api/invalid.py, skyportal/handlers/api/reminder.py, skyportal/handlers/api/source.py, skyportal/openapi.py
This PR requires https://github.com/cesium-ml/baselayer/pull/387 to be merged first, and once that done the new version of baselayer should be pinned on this PR before merging
Essentially it:
- adds the authentication/security (that we already specified in the `components` of the openapi spec) to ALL endpoints by default
- based on what is added in that baselayer PR, is able to figure which endpoints do not use authentication, and makes an exception for those. That way the autogenerated API docs show headers with a token when needed, otherwise do not.
- fixes the endpoint displayed for a few handlers' methods that had unused arguments (often happened on post methods that had the resource_id just to comply with the endpoint's regex, but didn't need them) to avoid confusion for the end …
=> OpenAPI spec - security/auth + ACLs

config.yaml.defaults, skyportal/api_description.md, skyportal/handlers/api/sources.py
Users have been complaining about the consistency of sources (notice the S, it's not an issue when querying just one) queries with the API. This happens because these lists are dynamic, and can see items being added and/deleted while the user paginates through the results.
This becomes an issue because even if we implement pagination for this endpoint, we had no functional caching so far meaning that the query would rerun everytime you request a new page, meaning that if things are added/deleted at some random spot in the list, the results would be shifted as you paginate. That means potential duplication, missing some objects, etc.
This PR implements caching for that endpoint. That way, the database query runs ONLY ONCE when requesting the first page, and then the user can paginate with …
=> get_sources caching

skyportal/handlers/api/followup_request.py
This PR does not enforce isot format, as some of our observatories do iso format.
=> followup_request time could be iso or isot

skyportal/handlers/api/weather.py, static/js/components/widget/WeatherWidget.jsx
In this PR:
- invalidate the weather data that's in redux if it's older than 1 hour, which is also the default caching time we use in the config (we don't query openweathermap's API more than once every hour).
- migrate openweathermap's `onecall` API from 2.5 (discontinued) to 3.0
Note: Instances that use that feature might want to go to their openweathermap account, and subscribe to the onecall API service. It will ask for credit card info but we get 1000 free API calls a day, and a limit can be added on top of that to make sure the free tier becomes not so free anymore. Also since SkyPortal caches every hour (and per telescope), you would need people to query weather info for >41 distinct facilities (lon/lat coordinates) to get to the paid tier, which is VERY unlikely.
=> Weather: API migration and frontend cache invalidation

services/observation_plan_queue/observation_plan_queue.py, skyportal/handlers/api/observation_plan.py
In this PR we:
- change the obsplan generation retry window from plans that are older than 24 hours but younger than 72 hours, to plans that are older than 5 minutes but younger than 1 hour. This is in an effort to only bother regenerating plans that failed soon after they were created when we care about getting the results and potentially sending them to an instrument.
- when it comes to auto-sending, don't auto-send anything if the plan request is older than an hour (i.e. we took too long to generate that plan).
I'm opening this PR because what happened in prod is that gwemopt kept dying (which is a problem that still needs fixing!) and a plan got generated 3 days after the trigger time, and was sent to the ZTF scheduler. Meaning it appeared as sent though it was sent too late, and …
=> Observation Plan Queue & Autosend: safety against old requests

skyportal/utils/observation_plan.py
Some keys from the `map_struct` we build with gwemopt's `read_skymap()` method are only necessary for plotting or running some efficiency calculations which we do not use. These use quite a bit of memory and can cause OOM issues. 
In this PR, we simply remove these unused variables to avoid OOM issues that are currently killing the observation plan python process.
=> Gwemopt - del unused skymap data

skyportal/handlers/api/gcn.py
This PR logs the full traceback when posting autogenerated GCN sources fails
@mcoughlin that's for Icare. The current log message doesn't show us where the error happens, so it's not sufficient for debugging.
=> log full traceback when posting autogenerated GCN sources fails

skyportal/handlers/api/followup_request.py, skyportal/models/schema.py
Add an optional `not_if_tns_reported` constraints that can be passed to the API when posting follow-up requests. This parameter is a float/int (in hours). If a source within the specified `radius` parameter (which defaults to 0.5 arcsec) has been reported on TNS more than `not_if_tns_reported` hours before the current time, we can avoid triggering.
Depends on: https://github.com/skyportal/kowalski/pull/444
=> Follow-up requests constraints: not_if_tns_reported

config.yaml.defaults, skyportal/handlers/api/gcn.py, skyportal/handlers/api/photometric_series.py, skyportal/handlers/api/shift.py, skyportal/handlers/api/user.py, static/js/components/analysis/AnalysisServicePage.jsx, static/js/components/gcn/GcnSelectionForm.jsx, static/js/components/shift/ShiftManagement.jsx, static/js/components/user/UserManagement.jsx
This PR:
- fixes an issue on the analysis services page where the popup dialog that shows the details of a service aren't showing the right ones
- fixes the indent of the docstring of a few endpoints (POST & PATCH of the photometric series, GET of the GCN events), which prevented from them appearing on the documentation.
- Hides group users that can be added to a shift, if they are expired
- Show expired users again in the user management page, because otherwise it is impossible to extend their account's expiration date from the frontend.
- document the includeExpired flag of the users endpoint
- fixes the download of executed observations on the GCN page
- adds the `ports` section in the default config, present in baselayer but missing here in Fritz. Both need to be edited to change the …
=> Analysis Services Page - details mixup bugfix

.github/workflows/test_docker_build.yaml
An attempt at fixing the docker build action which is often not running when it should on PRs.
=> Docker build action rules - fix

skyportal/facility_apis/soar.py
This PR updates the SOAR configuration to be arcs only (this is in practice the desire).
=> arcs only for soar calibration

skyportal/handlers/api/observation_plan.py
Looks like `arrow` creates a timezone aware date in new versions, which break this feature when comparing it to the vanilla `utcnow()` generated `datetime`. This PR is a quick fix, but overall we should migrate to the non `datetime.utcnow()` syntax that newer versions of python are deprecating.
Honestly it's such a stupid choice, everyone uses it and this syntax was perfectly intuitive...
=> Observation plan auto trigger - end date check bugfix

skyportal/facility_apis/swift.py
It's not super clear from the follow-up request form on the frontend if the exposure time is a total, or per visit. the "number of visits" field is called "exposure counts" so that does help but it's still not intuitive.
This PR renames these fields to "Exposure time per visit" and "Number of visits" to make it as transparent as possible.
=> Swift triggering - exposure time clarification

skyportal/utils/observation_plan.py
In the `skyportal.utils.observation_plan.py`'s `generate_observation_plan_statistics()` method, we do not make use of the python-based selection of the database partition everywhere
The LocalizationTile table is partitioned, and we can either just query the table and let the DB select the partition, or bypass that and query the partition directly which we do pretty much everywhere already.
In this PR, we make sure that the pre-selected partition is used for all the queries in that method, for consistency but also as it seems to prevent index-selection issues on a production system (Icare) where the postgres migration created issues.
=> Obsplan statistics - localization tiles partition selection

services/slack/slack.py, skyportal/facility_apis/gemini.py, skyportal/facility_apis/generic.py, skyportal/facility_apis/sedm.py, skyportal/facility_apis/swift.py, skyportal/facility_apis/winter.py, skyportal/handlers/api/followup_request.py, skyportal/handlers/api/sources.py, skyportal/utils/calculations.py, skyportal/utils/notifications.py
This PR:
- refactor Generic API to move the slack & email notification logic into the notification utils, to be important by other facility APIs
- adds optional slack OR email notifications when submitting/updating follow-up requests (for winter, sedm, swift).
- Upgrade the format of Slack and email notifications, to look nicer and be more functional
- change Gemini auth parameter names
- move radec2lb from sources to utils
The idea here is that having every single user that has an allocation set up notifications for it is cumbersome, and often its the same group of user that has access to an allocation that could just easily get notifications sent to a slack channel for everyone to see, or to an email list. This PR enables that.
TODOs (in future PRs):
- when I'll redesign the …
=> Follow-up requests: allocation-wide notifications (by slack & email)

.github/workflows/build-and-deploy-docs.yaml, .github/workflows/test_api_and_frontend.yaml, .github/workflows/test_migrations.yaml, .github/workflows/test_models.yaml, services/tns_retrieval_queue/tns_retrieval_queue.py, services/tns_submission_queue/tns_submission_queue.py, skyportal/handlers/api/tns.py, skyportal/utils/tns.py
In this PR we adopt some of the changes recently added to the TNS API, that broke most (if not all!) the scripts that interact with it.
We had to fix a few endpoints, and directly look for the responses' data in `data`, and not `data.reply`.
PS: I already made these changes in production, on Fritz. I already reprocessed all of the failed submissions so we're ok.
=> TNS API changes

Dockerfile
I've been asked to make a clone of Fritz on another machine, as a point in time backup for ZTF partners that should not access the live instance anymore, as they should not see any of the new data.
One problem I have is that copying the persistent data & thumbnails to another machine isn't very easy to do on gcp, and having access to `rsync` would make that much easier.
So, this PR adds it to the Docker image
=> Dockerfile - install rsync

.github/workflows/test_migrations.yaml
In the migration test, we use the new caching composite action. Issue is we try to cache dependencies after checking out to the reference commit (down migration version of SkyPortal, from which we then try to migrate the db to the latest). However the composite caching does not exist in that down migration, creating a failure.
This PR removes the caching of the dependencies from the reference commit, which while it can help, creates an issue and prevents us from running the GA. We can think about how to reintroduce caching at that step at a later date.
=> Test Migration - caching issue

skyportal/handlers/api/gcn.py, skyportal/handlers/api/group_admission_request.py, skyportal/tests/frontend/test_group_admission_requests.py
Currently, to create the obj_id of GCN autogenerated sources (when an event's localization is a small enough cone, we create a source associated with it) we first try to see if the GCN notice came with a pre-defined name for the event, and if not generate a name based on the dateobs of the event.
The issue is for the same event, some notices can have that name and some won't (e.g. SWIFT notices show this irregularity), this means we might end up with 2 sources for the same event: one named based on the notice content, one based on the dateobs. This creates confusion for the users.
This PR simplifies the source creation code and makes sure that we only use the dateobs to generate a source's name/id.
=> GCN autogenerated sources: only use dateobs for obj_id

static/js/components/photometry/NewPhotometry.jsx
mag and magerr are technically of type string, but their default value was null. This makes rjsf panic and throw and error saying that it isn't a string, since null isn't a valid string value.
This PR fixes that and adds a few extra checks here and there for empty strings.
=> UploadPhotometry (single point) form - mag & magerr default value fix

skyportal/handlers/api/group_admission_request.py, skyportal/tests/frontend/test_group_admission_requests.py
the stream access error triggered when adding a user with insufficient stream access to a group was not clear as we reported IDs rather than actual stream names. This PR hopefully makes that message clearer
=> Group admission - stream access error message clarification

skyportal/handlers/api/sharing.py, static/js/ducks/spectra.js
The Sharing handler was sending the obj_id and not the obj_internal_key to the frontend (via websockets) to refresh the data displayed when updating the data access of spectra, which prevented it from being refreshed as expected.
This PR fixes this.
=> Data Sharing - frontend refresh fix

skyportal/handlers/api/gcn.py, skyportal/utils/gcn.py
I noticed that some - not all - EP events wouldn't get an associated source, and I tracked it as a bug coming from a PR of mine https://github.com/skyportal/skyportal/commit/a2a929b2daccc33db5d8d80650db76a64c4a6270
This PR fixes that
=> GCN JSON events - missing tags

Dockerfile
This PR adds `top` to the Dockerfile, so we can easily monitor CPU and RAM usage in production
=> Dockerfile: add top command

skyportal/utils/offset.py
the NGPS starlist is a CSV, and the presence of control characters (newlines, tabs, ...) in comments breaks the formatting. This PR makes sure that all of these are discarded from the comment before inserting it in the starlist
=> Starlist assignment comment - no control characters

config.yaml.defaults, services/notification_queue/notification_queue.py, skyportal/facility_apis/tarot.py, static/js/components/allocation/AllocationSummary.jsx, static/js/components/followup_request/FollowupRequestLists.jsx
=> Improve follow up information tarot API

skyportal/handlers/api/followup_request.py, skyportal/models/schema.py
This PR fixed the not_if_tns_reported constraint which was ignored, and adds a new "don't report if assigned to an observing run" constraint: not_if_assignment_exists".
This is required for btsbot
=> Triggering constrain: bugfix + not trigger if assigned

skyportal/handlers/api/gcn.py, static/js/components/FindingChart.jsx
In this PR we:
- fix the finding chart print button, broken after the update of a dependency. We also refactor some of the code to use the already downloaded & rendered image rather than retrigger a download when hitting "Print"
- fix the GCN sources autogeneration, which was broken - yet again - by a previous PR of mind, where the "id" field was renamed to "name" by error.
=> Bugfixes: Finding chart print & GCN automated source generation

skyportal/models/localization.py, skyportal/utils/gcn.py
Some notices come with a radius = 0, which of course makes no sense, and would lead to incorrect sky localizations and unpredictable errors (e.g. incorrect localization center, area calculation, ...).
If the radius is 0, in this PR we set it to a very small value instead (4 arcsec) to avoid said errors. We might have to increase that value if still causes issues.
EDIT:
We also now use the localization name as the center we report for a localization, rather than the ligo.skymap calculated ones which gives us weird results for those small maps
=> GCN cone-based localization: avoid zero radius

config.yaml.defaults
Adds the missing `gcn.notices.` prefix to the JSON notices we currently support.
=> Default config: GCN JSON notices fix

skyportal/tests/frontend/test_upload_spectroscopy.py
For some reason this has been flaky for a while, but worked locally just fine.
Turns out, looking at the screenshots from the tests run here on git, we can see that the filename of the selected file is rendered as markdown. By that I mean that the 2 `_` that surround a part of the filename make it render as _italicized_ text!
It doesn't look like that behavior happens locally for me, so it could be due to a new version of firefox, used by the GitHub actions?
Anyways, instead of doing an exact filename match this PR simply splits the filename in it's different alphanumeric parts, and checks for those in the DOM. This allows the test to pass.
=> Upload spectra frontend test: fix

config.yaml.defaults, skyportal/handlers/api/moving_object.py, skyportal/utils/moving_objects.py, static/js/components/gcn/GcnSelectionForm.jsx, static/js/components/moving_object/MovingObjectObsPlanPage.jsx, static/js/ducks/moving_object.js
This PR: 
* adds a minimal frontend to generate observation plans for moving objects
* adds a route and menu icon to that new page in the config
* handles some connection errors that can occur when querying the JPL horizon API
=> Moving Object Observation planning - minimal frontend

static/js/components/allocation/AllocationTable.jsx, static/js/components/allocation/ModifyAllocation.jsx, static/js/components/allocation/NewAllocation.jsx, static/js/components/followup_request/FollowupRequestForm.jsx, static/js/components/instrument/InstrumentForm.jsx, static/js/components/instrument/InstrumentPage.jsx, static/js/components/instrument/InstrumentTable.jsx, static/js/components/telescope/TelescopePageDesktop.jsx, static/js/components/telescope/TelescopeSummary.jsx, static/js/ducks/allocations.js, static/js/ducks/instruments.js
The main cause of this PR was related to the hydration behavior of different API forms. When an instrument or an allocation was updated or created in a way that should have made it appear or change in the list of possible follow-up request allocations, the update did not take effect. This happened because modifying or adding an instrument or allocation only refreshed the list of instruments or allocations but did not update the list of forms or the allocationListApiClassname, which is used for the follow-up request selection.
With Sarah, we had filtered the allocations and created one for TAROT, but the change did not appear and could not be selected. So I had already noticed this behavior but didn’t know its cause. While working on the TAROT API, I finally understood where the issue was …
=> Improve instruments management and hydrate

services/facility_queue/facility_queue.py, skyportal/facility_apis/atlas.py, skyportal/facility_apis/ztf.py, skyportal/handlers/api/photometry.py
At the moment the Facility Transaction micro service fetched existing and un-processed requests from the DB only once when starting up, but then is fed new requests by an API endpoint that the different APIs can communicate with. This isn't ideal, and can cause issues.
In this PR we simplify that service's logic by simply letting it query requests to process (either new requests, or uncompleted requests which has been last processed more than N minutes ago) from the DB in it's main loop, and remove the API component entirely.
The ATLAS and ZTF forced photometry services (which are the only 2 using that microservice) are also edited to avoid trying to push data to that API.
One more thing that needs to be considered is how we keep triggering way too many notifications for the requests. I'm …
=> Facility Transaction Service: DB rather than API-driven

.github/workflows/test_migrations.yaml, Dockerfile, config.yaml.defaults, skyportal/models/gcn.py
No one wants to use the same value for their skyportal and really isn't practical to have to open a PR every time this quantity should change, so instead this PR makes it configurable so it can be customized on a per-instance basis.
=> GCN auto-generated sources - configurable SOURCE_RADIUS_THRESHOLD

skyportal/facility_apis/mmt/binospec.py, skyportal/facility_apis/mmt/mmirs.py, skyportal/facility_apis/mmt/mmt_utils.py, static/js/components/candidate/scan_reports/EditReportItemForm.jsx, static/js/components/candidate/scan_reports/ReportItems.jsx
- Rename 'filter' to 'filters' in MMT API payload to fit others APIs payloads.
- Add gap between "edit report item" and source name and rename a title to improve clarity.
=> Small improve on scanning report and MMT api

doc/deploy.md
Issue #5529
I also made some suggested changes earlier in the file -- you don't need to figure out the actual name that docker sees for the running container, as you can just run `docker compose exec`.
=> Add troubleshooting docs to deployment

Dockerfile, Makefile, doc/deploy.md
The uid/gid change is one I had to make to install on my kubernetes cluster to allow me to use bind-mounted directories.  The image name change was just for convenience (allows me to skip a `docker tag` step).
I broke the `useradd` out from the long `RUN` that included `apt-get` because making it a separate line doesn't appreciably affect size, but does allow skipping all the `apt-get` when rebuilding the dockerfile after changing those arguments.
=> Parameterize Dockerfile to allow specification of image name, uid, gid

static/js/API.js, static/js/components/followup_request/FollowupRequestSelectionForm.jsx, static/js/ducks/followup_requests.js
In this PR we:
- add a API.DOWNLOAD method for the frontend, that downloads files if successful, and shows error message from structured response if status isn't 200
- add methods in the ducks for follow-up requests, to download schedule and allocation analysis report
- make use of these methods in the frontend component for the follow-up request page
=> Follow-up requests Frontend - fixes to API calls that return files

static/js/components/followup_request/FollowupRequestForm.jsx
If an allocation's API does not implement a delete method, this PR adds a confirmation dialog that shows up after clicking `submit` on the form, where the user has to click `confirm` to go ahead and submit, or `cancel` to, well, cancel.
Addresses #5571
=> Follow-up request frontend: confirmation dialog if delete isn't implemented

skyportal/handlers/api/tns/tns_robot.py
For some reason I am getting an error with the preview version of Fritz when adding a tns robot, where it says that a non-nullable field of the `TNSRobotGroup` (an entry is created for the owner group of the bot being created) is null. That field is the `auto_report_allow_bots` which was added to that table after the initial migration, and to make sure existing records got a value for it when running the migration script it has a `server_default="false"` rather than a `default=False`. However it looks like the server for the preview instance isn't picking up on that default, a behavior I can't reproduce locally or in the production instance of Fritz (at least with the current version, as preview is running on a more recent commit).
Whatever the reason may be, a simple fix is to explicitly …
=> TNS Bot creation: owner group default values bugfix

skyportal/handlers/api/followup_request.py, skyportal/handlers/api/moving_object.py, skyportal/handlers/api/unsourced_finder.py, skyportal/utils/parse.py
This PR adds a function to parse a string (or anything that can be converted to string) to a bool. If accepts a variety of string-like representations for True or False, and can be given a `default` (which is set to None if not specified in which case it yields an error if the input does not match a valid True/False value) to return if there is no match to True or False.
=> Parsing utils: str to bool

skyportal/handlers/api/photometry.py
Right now in the `add_external_photometry` method which takes a dataframe of photometry rows as input, we run 2 queries:
- the first looks for which rows are new
- the second looks for which rows are duplicates (already exist)
when instead we could just look for which are duplicates, and get the new ones in python just by doing a simple diff between the idx of the duplicates and the new ones in the dataframe, indexes which we get back when we run the query.
I suspect that this can be applied in other places. It does speed things up quite a bit (between 25% and 50%) when it comes to adding the new rows in the DB. This is a simple but really appreciated speed boost when uploading data in bulk
=> Photometry upload/update: less queries

skyportal/handlers/api/instrument.py
when looping over delimiters, don't try loading df with pandas if the delimiter does not even appear in the string. This is required because we try a comma and then a space, but even if there is no comma pandas will successfully read the df and the whole row (regardless of the number of columns) will just be assumed to be one col. 
This PR simply makes sure that we don't even attempt to read it with a certain delimiter if it's char isn't even found in the data string.
=> Instrument field data post/put: delimiter check

skyportal/utils/offset.py
* specifies the bytes limit of the cache size after initiating the Memory() object, since that is now deprecated in joblib v1.5.0 (released on May 3rd 2025)
=> Joblib update bugfix

.github/workflows/test_migrations.yaml, requirements.txt, skyportal/utils/offset.py
* make sure joblib version is less than 1.5.0 in the migration test, as the migration reference commit would otherwise run on joblib latest which yields an error (see #5607)
=> Test Migration bugfix: joblib version

static/js/components/photometry/PhotometryTable.jsx
Resolves issue #5622 
Removes the following default columns :
* Ra
* Dec
* Ra_unc
* Dec_unc
Add these columns by default:
* SNR
* Magnitude System (e.g., AB/Vega)
Move UTC column next to MJD column
=> enh: change default columns in the photometric table

skyportal/handlers/api/candidate/scan_report_item.py
Sometimes, follow-up requests may not include a priority value which create an error when creating scanning report. This case should be handled properly when sorting and selecting the follow-up request to display.
=> Fix priority handling in scanning report to handle None values

skyportal/facility_apis/tarot.py, static/js/ducks/favorites.js
Add a 10-minute delay to TAROT's observing time when observing now to ensure the observation.
=> Add delay on tarot request

skyportal/facility_apis/tarot.py
fix tarot: defer config access to prevent early KeyError
- Move configuration access inside the error-handled function to avoid KeyError during initialization.
Link to this comment:
https://github.com/fritz-marshal/fritz/issues/562#issuecomment-2905559788
=> Fix tarot config key error

skyportal/facility_apis/tarot.py, skyportal/utils/calculations.py
- Set the 10 minutes delay before observation time calculation and improve error message.
- Use a 12-hour increment instead of 1 day when the target is not visible, to better avoid wasting all 7 loop attempts, since if T₀ is not visible, T₀ + 1 day likely won't be either.
=> Fix tarot time calculation

skyportal/facility_apis/ztf.py
Looks like the current version of the code isn't happy when we get an empty/incorrect table from IPAC's depot. This PR should fix that and log what empty/incorrect tables look like, so we can implement a better fix at a latter date if needed.
=> ZTF Executed observations download fix

skyportal/handlers/api/taxonomy.py
The "delete mode" when querying a taxonomy makes sure that:
- (1) the user does not get the taxonomy to delete if he's not an admin or does not have the delete taxonomy permission.
- (2) the user does not get the taxonomy to delete if there are classifications associated with it.
The problem is that in the handler after running the query and not getting the taxonomy back, we send an error message for (1) but do not mention (2) at all.
This PR makes sure that we check if there are associated classifications first, and return a comprehensive error message if there are any, so the user knows that they can't drop the taxonomy because of that and not because there is some permission issue.
This is based on a comment from @howardisaacson (to clarify if you see this howard, for data integrity …
=> Taxonomy delete: comprehensive error messages

skyportal/handlers/api/annotation_services.py, skyportal/utils/offset.py, skyportal/utils/tap_services/__init__.py, skyportal/utils/tap_services/gaia.py
Currently, in `skyportal/utils/offset.py` and `skyportal/handlers/api/annotation_services.py` we query the Gaia DR3 `gaia_source` catalog. We first try to use `astroquery`'s implement (class called `Gaia`), then if that fails to connect we then use `pyvo`'s `TapService` to connect to a backup service. However:
- the `astroquery.gaia` import causes a lot of issues, because in their code they instantiate their class which triggers a query. So the imports are slowed down and when servers are unstable/down like they are now, it just **prevents the app from even starting**.
- the `astroquery.gaia` implementation does not let us specify timeouts, so queries that take longer than expected just paralyze us and we can't do anything about it.
- out of these 2 options to query gaia, the query …
=> TAP Services: Gaia implementation

skyportal/tests/api/candidates_sources_events/test_followup_requests_api.py, skyportal/tests/api/candidates_sources_events/test_followup_requests_reprioritize.py, skyportal/tests/conftest.py
Most follow-up request test rely on the `sedm_allocation` test fixtures, which itself depends on the `sedm` fixture. Naturally, the `sedm` fixture uses the associated SEDMAPI. However for a lot of tests we just want to test more generic follow-up request features and absolutely do not need to do that w/ SEDM's API which points to telescope's server.
In this PR we introduce a `generic_instrument` and `generic_instrument_allocation` test fixtures that we can use in place of the `sedm` one in most tests that aren't SEDM-specific. Then we use said fixture in a handful of tests which have been failing today as the SEDM server seems to be down.
PS: In the future we may consider making that move to an SEDM-less allocation (one that in general does not ping a distant server) for most follow-up …
=> SEDM Allocation based unit tests failures: fix

services/facility_queue/facility_queue.py, services/tns_submission_queue/tns_submission_queue.py, skyportal/handlers/api/candidate/candidate.py, skyportal/handlers/api/candidate/candidate_filter.py
Originally, we made the decision to exclude forced photometry when selecting photometry that can be reported to TNS. But we've seen by now that very often said forced photometry recovers data we do not get from alert streams, and it would be good to report earlier detections to TNS. On the other hand since we lower the SNR cut from 5 to 3 in the FP context, we want to be a bit more conservative when selecting that data (and we might benefit from an SNR cut in general here).
So in this PR, we remove the cut that excludes forced photometry from reports, and replace it by an SNR cut so the newly added FP doesn't yield potentially spurious detections.
PS: This is done based on some issues w/ the alert pipeline of ZTF that resulted in incorrect non detections (from the alert pipeline) to be …
=> TNS Submissions: include forced photometry + SNR cut

skyportal/handlers/api/photometry.py
add some error handling when calling sncosmo's `normalized` method, which can yield an error if the provided magsys is incorrect. But sncomo returns an `Exception` while we have a try/except on `ValidationError`, so this PR makes sure that the sncosmo error is caught and propagated as a formatted `ValidationError`.
PS: This is to solve an issue that was caught by sentry.
=> Photometry validation: handle incorrect magsys

static/js/components/shift/ShiftCalendar.jsx, static/js/components/source/Source.jsx, static/js/components/templates/HeaderContent.jsx.template
- Fixes an issue preventing PDF downloads (observability and finder chart) from working reliably on the source page.
The error occurred most of the time due to the MenuItem's onClick event interfering with the anchor tag's default behavior, preventing the download from triggering properly.
- Add UTC time in the header and refresh time display every minute (My idea on this one, this is something I often need when requesting follow-ups, and I imagine other users might benefit from having both timezones visible as well.
- Add UTC time to shift calendar display. Not the prettiest solution visually, but it's the best I can do with the calendar component. This was requested by Christina and apparently several other users as well.
=> Add utc time header and shift calendar and fix PDF error

skyportal/handlers/api/source.py
Right now the SourceFinderHandler calls a method that handles errors and returns `ValueError`s, but we do not try/except those and therefore yield the python error instead of gracefully returning it to the user. Also, this means that a missing (or unaccessible source) yields a 400 and not a 404. This PR fixes both of these issues.
PS: Also added some extra full traceback + logging to the SourceOffsetsHandler to make things easier to debug when a starlist fails to generate
=> SourceFinderHandler: handle errors gracefully

.github/workflows/test_migrations.yaml, requirements.txt
=> Pin python-ligo-lw to 1.8.4, as ligo.skymap does not pin a version

skyportal/models/tag.py
This PR improved user right management for deletion and update of a tag association to a source.  
Before: use default strategy for the delete mode eg. only admin can delete data.  
Now: Admin, user with "Manage sources" rights and author of the association can remove and update a tag on a source.
fix: https://university-of-minnesota-gz.sentry.io/issues/6714911642/?referrer=slack&notification_uuid=a8953fb5-4830-4e5e-a98b-6ad41dcc3e6c&alert_rule_id=15261568&alert_type=issue
=> enh: improved user right management for deletion and update of a tag association to a source

.github/workflows/build-and-deploy-docs.yaml, .github/workflows/test_api_and_frontend.yaml, .github/workflows/test_migrations.yaml, .github/workflows/test_models.yaml
This is an attempt at using postgresql version 17 instead of 15 for the CI, so we know if that version is suitable for SkyPortal
=> CI: Use PostgreSQL v17

static/js/components/photometry/UpdatePhotometry.jsx
The goal of this PR is to allow user to edit the instrument name in the Photometry table.
Before:  
After:
=> enh: enable instrument edit in the photometry table

static/js/components/plot/PhotometryPlot.jsx
This PR sorts the photometry plot legend to improve readability for users.
Before:  
After:
=> enh: sort photometry legend alphabetically (filter and instrument)

skyportal/handlers/api/photometry.py, static/js/components/plot/PhotometryPlot.jsx, static/js/components/plot/VegaPhotometry.jsx
The goal of this PR is to fix the conversion problem when a user is trying to convert to vega system some photometry points that are in the x-ray domain and cannot be converted. Photometry points are also hidden in the plot using vega system to be coherent.
The solution is to ignore photometry points with the filter swiftxrt during the conversion :
Note: x-ray data while valid in AB mag system, is not defined / can't be converted in Vega. So this isn't an issue with SkyPortal failing to convert from one system to another, it's just that x-ray data does not exist in Vega to begin with.
=> fix: Fix mag system conversion with data with the swiftxrt filter

skyportal/tests/frontend/test_allocation.py
The test_allocation_comment_display Selenium test was failing intermittently with an ElementClickInterceptedException:
```
Element <span class=""> is not clickable at point (1898,489) because another element <div class="MuiDialog-container MuiDialog-scrollPaper css-hz1bth-MuiDialog-container"> obscures it
```
Added an explicit wait condition in the one_request_comment_process helper function to ensure the comment edit dialog fully closes to continue
=> fix: fix allocation unit test

rspack.config.js
Fixes issue introduces by latest @mui/x-data-grid, that added some *.css file that rspack tried to load as a javascript one.
=> Docker build: rspack fix

skyportal/handlers/api/instrument.py
Fixing  the following sentry error : https://university-of-minnesota-gz.sentry.io/issues/6808630071/?alert_rule_id=15261570&alert_type=issue&notification_uuid=151021c4-8127-4a0f-9472-12eabea507ff&project=4507403282546688&referrer=slack
=> fix: add a try catch to avoid error on the airmass_time calculation

static/js/components/gcn/NewGcnEvent.jsx
- Refactor error handling in NewGcnEvent form validation to avoid error: `TypeError: can't access property "addError", errors.dateobs is undefined`.
- Push the error `Either (i) ra, dec, and error or (ii) polygon or (iii) skymap must be defined if not uploading VOEvent / JSON` to the base form instead of the skymaps field for consistency.
- Refactor NewGcnEvent component to simplify form data handling, improve readability and delete duplicate info.
=> Fix "new gcn event" form issue

package.json, skyportal/models/schema.py
- Fix "KeyError" in PhotometryHandler in sentry-backend.
- Fix `cannot find module 'versor/src/index'` error by downgrading `d3-geo-zoom` to "1.4.4"
=> Fix mjd key error
