skyportal/skyportal

- static/js/components/Source.css
- static/js/components/Source.jsx
This has to be improved, but it at least moves the comments to the side
> Add some styling to Source rendering

- static/js/API.js
- static/js/actions.js
- showNotifications wasn't imported
- HTTP GETs cannot have a body
> Fix API calls

- static/js/actions.js
- static/js/components/Main.css
- static/js/components/Main.jsx
- static/js/containers/Logo.css
- static/js/containers/Logo.jsx
- static/js/reducers.js
> Add rotating logo.

- Dockerfile
- Makefile
- docker-compose/docker-compose.yml
- docker/skyportal.yaml
- requirements.txt
- skyportal/models.py
- skyportal/tests/conftest.py
- skyportal/tests/fixtures.py
- skyportal/tests/frontend/test_frontpage.py
Also copied over the default Docker configuration from `cesium_web`; don't think anything about that needs to change for now.
> Create fixture data for tests

- skyportal/app_server.py
- skyportal/handlers/__init__.py
- skyportal/handlers/become_user.py
Navigate to `/become_user/<user_id>` to see it in action.
Obviously a massive security hole right now, so needs the correct ACL :)
> Add ability to become another user

- skyportal/handlers/become_user.py
- skyportal/model_util.py
- skyportal/tests/conftest.py
- skyportal/tests/fixtures.py
- skyportal/tests/frontend/test_frontpage.py
- skyportal/tests/frontend/test_sources.py
Right now only tests basic functionality:
- Front page renders
- Source page renders
- Plots are present
- Can post a comment
Worth looking closely at the way fixtures are setup before merging, but once we're happy we should merge and add additional tests as we go along.
> Initial fixture data and tests

- skyportal/model_util.py
- skyportal/models.py
- skyportal/plot.py
- tools/download_ptf.py
- tools/import_ptf.py
Not meant for production use of any kind, just a convenient way to bootstrap a test environment.
> Tools for scraping/uploading PTF data

- .gitignore
- config.yaml
This also ensures that `make production` runs out of the box.`
> Add example customized configuration file.

- package.json
A security vulnerability in momentjs was identified using nsp
> Upgrade moment.js

- .travis/travis_script.sh
- static/js/components/Group.jsx
- static/js/components/Main.jsx
- static/js/components/NewGroupUserForm.jsx
- static/js/containers/CachedSource.jsx
> Delint the JavaScript sources

- static/js/components/CommentList.jsx
- static/js/components/FoldBox.jsx
- static/js/components/Group.jsx
- static/js/components/GroupList.jsx
- static/js/components/Main.jsx
- static/js/components/NewGroupForm.jsx
- static/js/components/NewGroupUserForm.jsx
- static/js/components/Plot.jsx
- static/js/components/Profile.jsx
- static/js/components/ProfileDropdown.jsx
- static/js/components/Source.jsx
- static/js/components/SourceList.jsx
- static/js/components/SurveyLinkList.jsx
- static/js/components/ThumbnailList.jsx
- static/js/containers/CachedSource.jsx
- static/js/containers/PlotContainer.jsx
stop linter from complaining about the need to --fix
> Lint fixes

- .eslintrc.yaml
- Dockerfile
- Makefile
- README.md
- static/js/components/CommentList.jsx
- static/js/components/FoldBox.jsx
- static/js/components/Group.jsx
- static/js/components/GroupList.jsx
- static/js/components/Main.jsx
- static/js/components/NewGroupForm.jsx
- static/js/components/NewGroupUserForm.jsx
- static/js/components/Plot.jsx
- static/js/components/Profile.jsx
- static/js/components/ProfileDropdown.jsx
- static/js/components/Source.jsx
- static/js/components/SourceList.jsx
- static/js/components/SurveyLinkList.jsx
- static/js/components/ThumbnailList.jsx
- static/js/containers/CachedSource.jsx
- static/js/containers/PlotContainer.jsx
Updated the README to show docker-compose usage. Python3.6 is the default python in ubuntu:17.10 so no need to use 3rd party ppa repos here.
> push ubuntu/node versions; fix Dockerfile

- README.md
Step by step for getting going on Mac.
> updated README for Mac OSX usage

- requirements.txt
- skyportal/app_server.py
- skyportal/handlers/__init__.py
- skyportal/handlers/userinfo.py
- skyportal/tests/frontend/test_user.py
- static/js/actions.js
- static/js/components/Group.jsx
- static/js/components/UserInfo.jsx
- static/js/containers/Main.jsx
- static/js/containers/UserInfo.jsx
- static/js/reducers.js
Takes over https://github.com/skyportal/skyportal/pull/126
> Add user info endpoint

- requirements.txt
- skyportal/handlers/comment.py
- skyportal/handlers/group.py
- skyportal/handlers/source.py
- skyportal/tests/frontend/test_groups.py
- skyportal/tests/frontend/test_photometry.py
- skyportal/tests/frontend/test_sources.py
- static/js/components/NewGroupForm.jsx
> Allow all fields to be updated in PUT requests by using Marshmallow schemas for validation

- Makefile
Also fix version display on MacOS
> Show SkyPortal-specific Makefile targets in make help

- skyportal/models.py
- static/js/components/ThumbnailList.css
- static/js/components/ThumbnailList.jsx
> Replace PS1 cutout image with DESI DR8

- static/js/components/SurveyLinkList.jsx
Removed '{ }s' formatting from survey urls, addressing https://github.com/skyportal/skyportal/issues/121
> Fix survey link URL formatting issue

- requirements.txt
update requirement.txt to fix the version number of marshmallow-sqlalchemy, marshmallow-enum, apispe.
> pin requirement

- skyportal/app_server.py
- skyportal/handlers/__init__.py
- skyportal/handlers/comment.py
- skyportal/handlers/photometry.py
- skyportal/handlers/spectrum.py
- skyportal/handlers/userinfo.py
- skyportal/model_util.py
- skyportal/models.py
- skyportal/tests/api/test_comments.py
- skyportal/tests/api/test_groups.py
- skyportal/tests/api/test_photometry.py
- skyportal/tests/api/test_sources.py
- skyportal/tests/api/test_spectrum.py
- skyportal/tests/api/test_user.py
- skyportal/tests/frontend/test_profile.py
> Implement GET/PUT/DELETE methods for Photometry and Spectrum endpoints; fix broken cascade delete relationship configuration; add tests

- skyportal/handlers/group.py
- skyportal/tests/frontend/test_groups.py
> Fix duplicate group admins error when user lists self explicitly

- skyportal/app_server.py
- skyportal/handlers/__init__.py
- skyportal/handlers/group.py
- skyportal/handlers/photometry.py
- skyportal/handlers/source.py
- skyportal/handlers/user.py
- skyportal/tests/api/test_groups.py
- skyportal/tests/api/test_photometry.py
- skyportal/tests/api/test_sources.py
- skyportal/tests/api/test_user.py
- skyportal/tests/conftest.py
- skyportal/tests/fixtures.py
- skyportal/tests/frontend/test_groups.py
- skyportal/tests/frontend/test_tokens.py
- static/js/components/Group.jsx
- static/js/components/NewGroupForm.jsx
- static/js/components/TokenList.jsx
- static/js/ducks/groups.js
> Add delete group functionality to front-end; add delete user endpoint handler; expand test coverage

- skyportal/handlers/become_user.py
- skyportal/handlers/logout.py
- skyportal/handlers/token.py
- skyportal/tests/frontend/test_tokens.py
> Clear auth token cookie on become_user and logout; update frontend tests

- skyportal/model_util.py
- skyportal/tests/conftest.py
- skyportal/tests/frontend/test_sources.py
- static/js/components/CommentList.jsx
- static/js/components/Footer.jsx
- tools/load_demo_data.py
Closes https://github.com/skyportal/skyportal/issues/207
> Only render add comment component for users who have comment permissions; add view-only user role; add test

- skyportal/models.py
- skyportal/tests/api/test_sources.py
Closes https://github.com/skyportal/skyportal/issues/185
> Remove redundant created field

- .travis.yml
- requirements.txt
- skyportal/handlers/photometry.py
- skyportal/tests/api/test_photometry.py
- skyportal/tests/frontend/test_sources.py
> Allow POSTing thumbnails along with photometry data in /api/photometry handler

- skyportal/handlers/group.py
- skyportal/tests/api/test_groups.py
Closes https://github.com/skyportal/skyportal/issues/249
> Fix token requesting all groups bug; add test

- skyportal/app_server.py
- skyportal/handlers/__init__.py
- skyportal/handlers/instrument.py
- skyportal/handlers/telescope.py
- skyportal/tests/api/test_instrument.py
- skyportal/tests/api/test_telescope.py
Closes https://github.com/skyportal/skyportal/issues/243
> Implement Telescope and Instrument API

- Makefile
- doc/setup.md
See also https://github.com/cesium-ml/baselayer/pull/66
> Set FLAGS to point to config.yaml

- requirements.txt
- skyportal/app_server.py
- skyportal/handlers/__init__.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/group.py
- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/internal/__init__.py
- skyportal/handlers/api/internal/dbinfo.py
- skyportal/handlers/api/internal/plot.py
- skyportal/handlers/api/internal/profile.py
- skyportal/handlers/api/internal/token.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/spectrum.py
- skyportal/handlers/api/sysinfo.py
- skyportal/handlers/api/telescope.py
- skyportal/handlers/api/thumbnail.py
- skyportal/handlers/api/user.py
Organize API handlers according to URLs
> Move API handlers to match URL hierarchy

- .dependabot/config.yaml
Lower frequency of non-security updates
> Add dependabot configuration

- skyportal/handlers/api/internal/token.py
- skyportal/tests/frontend/test_tokens.py
> Handle duplicate token name and return informative error message

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- doc/about.md
- doc/deploy.md
- doc/index.rst
- docker-compose.yaml
- docker.yaml
- Update docker-compose file to v3
- Upgrade postgres, and add now-required password
- Store database data in a volume that lives outside of web container
- Add deployment docs
- Update node to 12 in Docker images
- Add config.yaml to .dockerignore so it doesn't get added to images,
accidentally exposing tokens
Closes #377
> Fix and improve docker-compose deployment

- static/js/components/NewTokenForm.jsx
See also https://github.com/react-hook-form/react-hook-form/issues/1558
> Correctly reset new token form

- static/js/components/SearchBox.jsx
Closes https://github.com/skyportal/skyportal/issues/445
> Use react-hook-form in filter sources component

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/filter.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/spectrum.py
- skyportal/handlers/api/thumbnail.py
- skyportal/models.py
- skyportal/tests/api/test_candidates.py
- skyportal/tests/api/test_filters.py
- skyportal/tests/conftest.py
- skyportal/tests/fixtures.py
- static/js/components/SearchBox.jsx
- static/js/ducks/sources.js
- tools/load_demo_data.py
Closes https://github.com/skyportal/skyportal/issues/408
> Add CandidateHandler and FilterHandler & tests; minor data model updates; update load_demo_data

- skyportal/tests/tools/test_offset_util.py
This PR implements the skipping of DESI finding chart test if
the DESI DR8 legacy server is down. It first tests for the server 
being up then uses `@pytest.mark.skipif` capability.
Closes issue #456.
> skip DESI test if legacy server is down

- skyportal/handlers/api/photometry.py
- skyportal/tests/api/test_photometry.py
- Handle null mags / magerrs in api/sources/photometry
- Output correct mag systems in `serialize` 
- Handle invalid source id in SourcePhotometryHandler
- Add tests for these cases
> fix a few bugs in the photometry handler

- skyportal/handlers/api/photometry.py
- skyportal/schema.py
> replace __repr__ of the packet with index in PhotHandler validation errors

- skyportal/utils/offset.py
- static/js/components/Source.jsx
> add finding chart link to source page

- skyportal/tests/frontend/test_sources.py
- static/js/components/Source.jsx
- static/js/components/StarList.css
- static/js/components/StarList.jsx
> Add inline starlist display

- static/js/ducks/candidates.js
> Retain current page number when FETCH_CANDIDATES WS message is received by front-end

- skyportal/handlers/api/thumbnail.py
Closes https://github.com/skyportal/skyportal/issues/511
> Catch invalid ttype exception in ThumbnailHandler.post

- static/js/components/VegaPlot.jsx
- Selection of filter by legend
- Zooming via wheel and panning via drag
- Draw mag limit and error bars
- Add hover tooltip with mag ± magerr and magsys
> Add features to Vega plot

- static/js/components/VegaPlot.jsx
Sorry @stefanv, noticed these only after having merged #507 .
> Limiting mags for non-detections and error bars in VegaPlot.jsx

- skyportal/tests/frontend/test_upload_photometry.py
- static/js/components/UploadPhotometry.jsx
> Display list of possible filters for each instrument as tooltip over select menu items

- config.yaml.defaults
- skyportal/handlers/api/candidate.py
- skyportal/tests/frontend/test_candidate_page.py
- static/js/components/Candidate.jsx
- static/js/components/CommentList.jsx
- static/js/ducks/candidate.js
> Add candidate page to front-end

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/followup_request.py
- skyportal/handlers/api/internal/source_views.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/spectrum.py
- skyportal/handlers/api/thumbnail.py
- skyportal/models.py
Closes https://github.com/skyportal/skyportal/issues/455 
This makes the return type more obvious from the function name
> Rename {Source,Candidate}.get_if_owned_by -> {Source,Candidate}.get_obj_if_owned_by

- static/js/components/CommentEntry.css
- static/js/components/NewGroupForm.css
- static/js/components/ProfileDropdown.css
- static/js/components/SidebarAndHeader.jsx
Comments and Bokeh tools were scrolling over the top bar.
Closes #530
> Set z-index for comments, top bar, and profile dropdown.

- skyportal/tests/frontend/test_sources.py
Closes https://github.com/skyportal/skyportal/issues/551
> Patch up delete comment test

- skyportal/handlers/api/telescope.py
Closes https://github.com/skyportal/skyportal/issues/571
> Document group_ids parameter in telescope API docs

- skyportal/handlers/api/internal/profile.py
- skyportal/handlers/api/user.py
> sort ACLs to fix #589

- skyportal/tests/api/test_sources.py
> mark test_finder xfail as it relies on a flaky web resource (NERSC DR8)

- skyportal/model_util.py
- skyportal/tests/frontend/test_profile.py
Adds "Classify" ACLs to more roles. Closes issue #580. 
This PR replaces the (unrebased) #583, #584 (already reviewed by Ari)
> add Classify to more roles

- package.json
> Bump material-ui/core to 4.11.0

- static/js/components/SidebarAndHeader.jsx.template
> Fix shadow over sidebar button hamburger icon

- skyportal/models.py
- skyportal/schema.py
Source/Candidate API docs: 
Photometry API docs:
Closes #612
> Better document {Photometry,Obj}.altdata

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
- skyportal/models.py
> Fix bugs in Obj.last_detected, Photometry.snr and return last_detected in Source and Candidate handlers

- skyportal/tests/frontend/test_profile.py
- skyportal/tests/frontend/test_sources.py
Closes https://github.com/skyportal/skyportal/issues/607
> Mark profile and classification front-end tests as flaky

- .gitignore
> add .idea/ to gitignore for PyCharm users

- skyportal/handlers/api/source.py
- skyportal/tests/fixtures.py
- skyportal/tests/frontend/test_sources.py
- static/js/components/Source.jsx
> Render groups badges at top of source page

- skyportal/tests/frontend/test_sources.py
Closes https://github.com/skyportal/skyportal/issues/665
> Mark test_sources::test_comment_groups_validation as flaky

- doc/contributing.md
Specifically address review concerns, and what should happen with larger
PRs.
> Update contribution guide

- skyportal/tests/api/test_groups.py
Closes https://github.com/skyportal/skyportal/issues/678
> Robustify groups api test

- skyportal/handlers/api/internal/source_views.py
Closes https://github.com/skyportal/skyportal/issues/658
> Push skyportal/FETCH_TOP_SOURCES WS message to all users after each source view

- skyportal/handlers/become_user.py
This accelerates the test suite
> Return JSON from become_user instead of redirecting to a page

- skyportal/tests/frontend/test_sources.py
- static/js/components/ClassificationList.jsx
- static/js/components/ShowClassification.jsx
> Classification frontend tests

- static/js/components/UploadPhotometry.jsx
Closes https://github.com/skyportal/skyportal/issues/593
> Fix upload photometry page initial render bug

- skyportal/handlers/api/source.py
Closes https://github.com/skyportal/skyportal/issues/609
> Order comments on source page newest to oldest

- static/js/components/UploadPhotometry.jsx
> Add buttons to load sample flux, mag data on upload photometry page

- skyportal/handlers/api/group.py
- static/js/components/ShareDataForm.jsx
- static/js/ducks/groups.js
> Fetch and display single user groups in data sharing component; update handler & action creator

- static/js/components/AssignmentList.jsx
> fetch users using UseEffect in AssignmentList

- .github/workflows/test.yml
Earlier, I believed that GA did not do a merge before testing, but this was incorrect.  This PR therefore removes the manual steps put in place to fix it.
FWIW, the manual step was subtly incorrect, and merged against the *user's* master branch instead of against *upstream/master* (I think).
> GA: merge with correct upstream branch

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
- skyportal/models.py
- static/js/components/Candidate.jsx
- static/js/components/CandidateList.jsx
- static/js/components/Source.jsx
Added galactic coordinates to the sources/candidates. 
This shows up in the scanning page as well as in the individual pages for candidates or sources.
> added galactic coordinates

- .github/workflows/build-and-deploy-docs.yaml
- test.yaml
@dmitryduev This should resolve the building on your own repo that you've been seeing.
> Only run GA on pull requests or on pushes to master

- doc/setup.md
…t about load_demo_data a little more clear.
> updated setup page 

- static/js/components/HeaderContent.jsx.template
- static/js/components/QuickSearchBar.jsx
- static/js/components/SidebarAndHeader.jsx.template
Fixes a typo in `HeaderContent.jsx.template` which caused the strange formatting and adds @stefanv's style changes from #732.
> location fix + Stefan's style changes

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
Closes https://github.com/skyportal/skyportal/issues/747
> Filter sources/candidates on user's accessible groups list

- package.json
Try downgrading redoc to fix `npm` issue on master.
> Downgrade redoc hotfix

- static/js/components/AssignmentList.jsx
> fix overfetching Users

- static/js/components/CandidateCommentList.jsx
- static/js/components/CommentList.css
- static/js/components/CommentList.jsx
- Include annotations in comment bubbles
- Reskin candidate list autoannotations to match new source comments look
> Fix comments attachments and candidates autoannotations

- static/js/ducks/sidebar.js
> Close sidebar by default on mobile

- static/js/components/Theme.jsx
Issue #765 
Issue was setting background to dark color for null user preferences
> Fix default theme to be light background

- skyportal/tests/frontend/test_groups.py
- static/js/components/Group.jsx
- static/js/components/GroupList.jsx
> User react-router-dom Link for in-site navigation

- static/js/components/CentroidPlot.jsx
> Add wheel zooming to centroid plot

- skyportal/tests/frontend/test_scanning_page.py
- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
- static/js/components/ThumbnailList.jsx
> Reskin Candidates page to use MUI

- static/js/components/CandidateCommentList.jsx
- static/js/components/CommentList.css
> Put candidate annotations within scrollbars

- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
Closes https://github.com/skyportal/skyportal/issues/784
Closes https://github.com/skyportal/skyportal/issues/785
> Add previous/next page buttons below candidate list & show spinner when query is in progress

- static/js/components/CommentEntry.css
- static/js/components/CommentEntry.jsx
> Make comment form groups wrap

- static/js/components/GroupManagement.jsx
- static/js/components/Groups.jsx
Sorry, forgot to add this after the last bit of changes to my PR that just got merged
> Fix warning on groups page from recent sources merge

- skyportal/handlers/api/group.py
- skyportal/tests/api/test_groups.py
- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
- static/js/ducks/groups.js
> Return user_accessible_groups in GroupHandler.get multiple requests; allow candidate filtering on accessible_groups; update API tests

- doc/adding_features.md
- skyportal/handlers/api/classification.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/followup_request.py
- skyportal/handlers/api/source.py
- skyportal/models.py
- static/js/ducks/source.js
Closes https://github.com/skyportal/skyportal/issues/780
> Use Obj.internal_key for all REFRESH_SOURCE WS messages

- static/js/components/CandidateList.jsx
Closes https://github.com/skyportal/skyportal/issues/825
> Add padding to spinner on scanning page

- skyportal/tests/frontend/test_about_page.py
- static/js/components/About.jsx
> Add citation text to about page with foldable BiBTeX

- skyportal/tests/frontend/test_frontpage.py
- static/js/components/SidebarAndHeader.jsx.template
> Highlight selected sidebar menu item.

- skyportal/models.py
- skyportal/tests/tools/test_date.py
fixes an issue on the candidates page spotted by @dmitryduev
> fix timezone issueon candidates page

- skyportal/tests/frontend/test_groups.py
- static/js/components/Group.jsx
- static/js/components/NewGroupForm.jsx
- static/js/components/NewGroupUserForm.jsx
- static/js/ducks/group.js
> Addresses various errors (components becoming controlled, etc.)

- skyportal/tests/frontend/test_upload_photometry.py
Fixes test failures introduced in https://github.com/skyportal/skyportal/commit/ee2d8894b262cd4b61bcf0e9a63ca3730c931e3f
> Fix upload photometry front-end tests: use Instrument filter list specified in test fixtures

- skyportal/handlers/api/taxonomy.py
Closes https://github.com/skyportal/skyportal/issues/824
> Return taxonomies associated with user's accessible groups

- skyportal/handlers/api/source.py
- Execute the PDF generation in a thread
- Download the file in chunks
> Make PDF generation async

- config.yaml.defaults
- skyportal/tests/frontend/test_observing_planner.py
- static/js/components/ObservingRunList.jsx
This PR adds a page that shows all of the observing runs in the skyportal DB and links to them from the side bar. It also tests this functionality.
> Observing Run Page

- doc/database.rst
> fix erd link

- skyportal/handlers/api/comment.py
- skyportal/handlers/api/news_feed.py
- skyportal/models.py
- skyportal/tests/fixtures.py
- static/js/components/CandidateCommentList.jsx
- static/js/components/CommentList.jsx
> Refactor comment author to be User instead of User.username

- static/js/components/SaveCandidateButton.jsx
Closes https://github.com/skyportal/skyportal/issues/859
> Limit group name in save candidate button to 15 chars

- static/js/components/TopSources.css
> replace topsources iamge scaling on hover with warm glow

- static/js/components/Candidate.jsx
- static/js/components/Source.jsx
increased display precision of galactic coordinates in sources/candidates pages. Fixes issue #809
> display precision of galactic coordinates

- skyportal/handlers/api/group.py
- static/js/components/Group.jsx
Closes https://github.com/skyportal/skyportal/issues/874
> Only allow users with 'Manage users' ACL to add/rm users from groups

- static/js/components/FollowupRequestForm.jsx
This simplifies the followup request frontend to only have one select for instrument/allocation instead of 2 which were degenerate with each other (only an allocation_id is needed to fully specify everything). 
This also fixes a bug that @mcoughlin found where the form was not working for more than 1 instrument.
> Simplify robotic followup-request menu

- skyportal/app_server.py
- skyportal/handlers/become_user.py
- skyportal/onboarding.py
This depends on https://github.com/cesium-ml/baselayer/pull/142
> Use same auth pipeline for fake/non-fake auth

- skyportal/tests/frontend/test_recent_sources.py
- static/js/components/RecentSources.jsx
- static/js/components/SourceQuickView.jsx
Switch to using `@data-testid` instead of MUI class names to fix broken recent sources test
> Fix recent sources test

- static/js/components/FollowupRequestLists.jsx
> More informative loading message for followup requests

- skyportal/handlers/api/candidate.py
Closes https://github.com/skyportal/skyportal/issues/903
> Only show candidate as previously saved if saved to one of user's groups

- skyportal/handlers/api/candidate.py
Closes https://github.com/skyportal/skyportal/issues/918
> Do not push FETCH_CANDIDATES WS message on post

- skyportal/handlers/api/comment.py
- skyportal/tests/api/test_comments.py
> Update source redshift if comment text starts with 'z='; add API test

- static/js/components/SurveyLinkList.jsx
> add sdss to survey list

- skyportal/facility_apis/sedm.py
@rswalters This adds RA and Dec to the SEDM payload. Let's iterate here if any more modifications to the SEDM API are needed
> bring SEDM payload format in line with spec

- skyportal/handlers/api/classification.py
- skyportal/models.py
Now catching this error properly so we get the proper message:
> Properly detect inaccessible taxonomies for classifications

- static/js/components/GroupSources.jsx
> added maximum height to comment box on group sources page

- skyportal/handlers/api/internal/recent_sources.py
- skyportal/tests/frontend/test_recent_sources.py
- static/js/components/SaveCandidateButton.jsx
> Query for recent sources based on time saved

- static/js/components/Main.jsx.template
- static/js/components/Theme.jsx
- test_config.yaml
> Disable transitions to help with testing

- static/js/components/GroupSources.jsx
Like in the candidates page. Fixes issue #959
> group sources page comments more condensed

- skyportal/plot.py
Addresses #975 . 
Adds "days ago" to the X axis of the photometry plots.
> add days ago time axis to light curve plot

- static/js/components/UploadPhotometry.jsx
[ch1289].
This PR sorts the instrument list on the upload photometry page (request from @steveschulze).
> sort instrument list on  upload photometry page

- static/js/components/CandidateList.jsx
Fix warning from recent scanning page candidates-per-page fix
> Fix scanning page warning

- skyportal/handlers/api/group.py
- skyportal/models.py
- static/js/components/Group.jsx
- static/js/components/NewGroupForm.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
Closes https://github.com/skyportal/skyportal/issues/995
> Add group nicknames; show nickname if not None instead of full name on Source page

- skyportal/plot.py
> Properly use mag detections for mag photometry boundary lines

- static/js/components/FilterCandidateList.jsx
> Add minimum page number to scanning page

- skyportal/onboarding.py
Closes https://github.com/skyportal/skyportal/issues/1018
> Grant user access to streams specified in invitation; check group streams against this list

- data/db_demo.yaml
- skyportal/handlers/api/internal/profile.py
- skyportal/handlers/api/user.py
- skyportal/onboarding.py
- skyportal/tests/fixtures.py
- static/js/components/UpdateProfileForm.jsx
Closes  https://github.com/skyportal/skyportal/issues/883 
Depends on https://github.com/cesium-ml/baselayer/pull/145
> Slugify usernames

- skyportal/models.py
@dmitryduev Can you deploy this on private once green? 
Fixes the upload problem encountered by @scizen9 and related to 
https://github.com/skyportal/skyportal/pull/977#discussion_r496302244
> Fix serialization of JSON types to postgresql in spectrum upload

- static/js/components/CommentList.jsx
- static/js/components/CommentListMobile.jsx
> Truncate long file attachment names for comments

- skyportal/models.py
- skyportal/tests/api/test_sources.py
- static/js/components/NotificationPreferences.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- test_config.yaml
Missed a couple of places where alerts should be renamed to notifications - none of which were breaking
> Finish renaming source alerts to source notifications

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/source.py
- skyportal/models.py
- skyportal/tests/api/test_sources.py
- skyportal/tests/frontend/test_sources.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/SourceRedshiftHistory.jsx
- static/js/components/UpdateSourceRedshift.jsx
- static/js/ducks/source.js
Closes https://github.com/skyportal/skyportal/issues/1012
> Add components for setting redshift & viewing redshift history on source page

- skyportal/handlers/api/spectrum.py
- skyportal/schema.py
- skyportal/tests/api/test_spectrum.py
> use Marshmallow to validate user-posted spectra

- config.yaml.defaults
- static/js/components/Candidate.jsx
- static/js/components/ShowClassification.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- Shows the classification capitalization as it is in the taxonomy (before it was all caps)
- puts the RA/DEC sexigesimal position out in front, in big bold font.
Closes #1052
> Improved Source/Candidate classification and position view

- skyportal/plot.py
Fix photometry plots if there are either no detections or no non-detections
> Fix photometry plots

- static/js/components/ShareDataForm.jsx
[ch1273] @scizen9
This PR adds an explanatory blurb to the share data page to explain what the page is and how it works.
> add an explanatory blurb on the share data page

- config.yaml.defaults
- skyportal/handlers/api/observingrun.py
- skyportal/tests/conftest.py
- skyportal/tests/frontend/test_observing_planner.py
- static/js/components/AssignmentForm.jsx
- static/js/components/AssignmentList.jsx
- static/js/components/NewObservingRun.jsx
- static/js/components/ObservingRunPage.jsx
- static/js/ducks/observingRun.js
- static/js/ducks/observingRuns.js
[ch1240]
This PR adds a form that allows users to add a new observing run on the observing run page.
> Add form to add observing run on observing run page

- skyportal/enum_types.py
- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/observingrun.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/thumbnail.py
- skyportal/models.py
- skyportal/tests/api/test_thumbnail.py
- skyportal/tests/fixtures.py
- static/js/components/CandidateList.jsx
- static/js/components/ThumbnailList.jsx
> Decouple thumbnails from photometry; add PS1 thumbnails; show more thumbnails on source/scanning pages

- skyportal/app_server.py
See also https://github.com/cesium-ml/baselayer/pull/153
> Ask migration manager for permission to launch app

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
Closes https://github.com/skyportal/skyportal/issues/1076
> Clean up source/candidate API response data

- skyportal/app_server.py
See also https://github.com/cesium-ml/baselayer/pull/158
> We now rely on baselayer to handle all migration logic

- skyportal/tests/tools/test_offset_util.py
- skyportal/utils/offset.py
When the positional uncertainty is nongiven or zero, make sure that the centroid positioning for the starlist/finder returns a sensible position.
> Make position determination more robust in the starlist

- skyportal/handlers/api/internal/recent_sources.py
- skyportal/handlers/api/internal/source_views.py
> Fix showing "new" thumbnail by default on homepage widgets

- static/js/components/SurveyLinkList.jsx
Found the reason why the car was driving off the cliff on the Source/Candidate page.
> Add optional chaining when fetching photometry in SurveyLinkList

- static/js/components/SourceRedshiftHistory.jsx
Closes https://github.com/skyportal/skyportal/issues/1114
> Add defaultProps for SourceRedshiftHistory component

- Dockerfile
Testing locally, since this isn't exercised on the CI.
Will report when done.
> System setup docker build

- static/js/components/GroupSources.jsx
> Group sources hotfix

- static/js/components/StarList.css
> add overflow scroll to starlist code div

- skyportal/tests/frontend/test_sources.py
Fix test that's been failing on GA since my #1109 PR went in (sorry, that was my bad! Didn't check the test properly since it was XFAILed on Travis already).
> Fix comment attachments test

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
- skyportal/handlers/base.py
Also require a message to be passed when calling a handler's
`error` method.
> Return 404 on HEAD request if source not found

- static/js/components/ProfileDropdown.jsx
> Disable scroll lock in ProfileDropdown.jsx

- skyportal/tests/frontend/test_user_management.py
- static/js/components/UserManagement.jsx
Partially addresses https://github.com/skyportal/skyportal/issues/914
> Allow adding users to new groups from user management page

- static/js/units.js
> format dec d,m as 02d

- static/js/components/NewGroupForm.jsx
Closes https://github.com/fritz-marshal/fritz-beta-feedback/issues/3
> Reset new group nickname form field value upon submission

- requirements.txt
Uses the new taxonomy with FBOT as a subclass of SNe
> push tdtax to 0.1.2 with FBOT

- static/js/components/WeatherWidget.jsx
Addresses https://github.com/fritz-marshal/fritz-beta-feedback/issues/14
> Alphabetize telescope list in weather widget

- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
- static/js/components/SaveCandidateButton.jsx
Addresses https://github.com/fritz-marshal/fritz-beta-feedback/issues/6
> Make default candidate save to groups those selected in filtering form

- skyportal/models.py
Closes https://github.com/skyportal/skyportal/issues/1098
> Update Obj.get_if_owned_by to account for Obj w/out photometry

- skyportal/facility_apis/sedm.py
> Ensure latest photometry is sent to SEDM in SEDM handler

- skyportal/tests/conftest.py
- skyportal/tests/frontend/test_user_management.py
- static/js/components/UserManagement.jsx
Partially addresses https://github.com/skyportal/skyportal/issues/914
> Allow adding user to streams from user management page

- skyportal/tests/frontend/test_upload_spectroscopy.py
- static/js/components/FollowupRequestForm.jsx
@kmshin1397 Is there another branch I should merge this into?
> wait for spectrum plot to load on test_upload_spectroscopy

- skyportal/handlers/api/spectrum.py
- static/js/components/GroupSources.jsx
- static/js/components/VegaSpectrum.jsx
added VegaSpectrum for viewing source spectra on groups sources and source list pages. 
I added this to the group sources page, and will also add it to the source list when it is done.
> Vega Spectra

- skyportal/models.py
- skyportal/tests/api/test_spectrum.py
> coerce spectrum flux,fluxerr,wave to floats

- skyportal/plot.py
> fix spectral line overlotting

- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
Closes #1233 
- MUI table is now properly aware of external filter form state, including group Ids and unsavedOnly checkbox
- The filter form's search button is aware of the MUI table's pagination state
> Scanning page filtering fixes

- static/js/components/ObjPageAnnotations.jsx
> Fix annotations table width on source/candidate page

- skyportal/handlers/api/taxonomy.py
> fix taxonomy API docs

- static/js/components/SaveCandidateButton.jsx
Closes https://github.com/skyportal/skyportal/issues/1218
> Display max of 3 group names in save candidate button

- skyportal/handlers/api/candidate.py
> Fix missing candidates' saved groups info

- skyportal/handlers/api/observingrun.py
Fixes this error on the observingrun page
> Remove autoflush statement in observingrun handler

- skyportal/tests/frontend/test_upload_spectroscopy.py
Use new baselayer driver function options with test_upload_spectroscopy.
Noticed this was failing on recent CI runs - looks like I forgot to update this test yesterday
> Robustify test_upload_spectroscopy

- skyportal/handlers/api/group.py
- skyportal/handlers/api/user.py
- skyportal/tests/frontend/test_sources.py
- static/js/components/CommentEntry.jsx
Addresses https://github.com/fritz-marshal/fritz-beta-feedback/issues/15
> Sort users and groups alphabetically in GET handlers

- skyportal/handlers/api/internal/token.py
> Return with informative error message if request received to create token with ACLs user doesn't have access to

- skyportal/handlers/api/candidate.py
- skyportal/models.py
Close #1317 
Also fix typo in classifications docstring
> Fix autoflush error on scanning page

- static/js/components/UserProfileInfo.jsx
Closes https://github.com/skyportal/skyportal/issues/1304
Before:
After:
> Fix user acls length check bug

- skyportal/tests/frontend/test_followup_requests.py
> fix sedm timeout

- skyportal/utils/offset.py
Addresses #1345 by increasing cache size dramatically
> push number of cached files to 1000

- static/js/components/SaveCandidateButton.jsx
Closes https://github.com/skyportal/skyportal/issues/1351
> Fix candidate quick save groups bug

- static/js/components/SourceMobile.jsx
> show upload spectroscopy button on mobile

- config.yaml.defaults
- skyportal/email_utils.py
- skyportal/models.py
Tested locally with my own gmail account
> Add capability for sending emails via SMTP

- alembic/versions/fbf89710dead_refactor_candidates_table.py
- skyportal/handlers/api/candidate.py
- skyportal/models.py
- skyportal/tests/api/test_candidates.py
- skyportal/tests/conftest.py
- skyportal/tests/frontend/test_recent_sources.py
- skyportal/tests/frontend/test_scanning_page.py
Closes https://github.com/skyportal/skyportal/issues/1267
> Refactor candidates table to use 3-col index (obj_id, filter_id, passed_at)

- skyportal/tests/conftest.py
Closes https://github.com/skyportal/skyportal/issues/1375
> Add random timedelta to Candidate.passed at and other test fixture updates

- skyportal/handlers/api/source.py
Fixes source API test failures
Unsure why these would suddenly be failing, as the relevant code hasn't changed recently (related package version upgrades, perhaps)
> Fix relationship loading in source handler

- requirements.txt
Add new SN subclasses (v0.1.3 of tdtax)
> bump tdtax version

- skyportal/handlers/api/followup_request.py
- skyportal/tests/api/test_assignments.py
Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/51
> let other users modify observing run assignments

- skyportal/handlers/api/group.py
- skyportal/models.py
Closes https://github.com/skyportal/skyportal/issues/1158
> Add {User,Token}.accessible_streams and use where applicable in handlers

- skyportal/handlers/api/observingrun.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/49
> Use colon instead of hms, dms as hexadecimal coordinate separators on source page

- static/js/components/SourceNotification.jsx
> Use stacking chips for group selection in source notifications

- skyportal/tests/frontend/test_scanning_page.py
- static/js/components/CandidateList.jsx
> Fix scanning filter form issue with common key names

- skyportal/handlers/api/observingrun.py
- skyportal/models.py
- skyportal/tests/conftest.py
- skyportal/tests/fixtures.py
- skyportal/tests/frontend/test_observing_planner.py
- static/js/components/RunSummary.jsx
Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/44
> dont crash observing run page for targets that dont rise

- skyportal/handlers/api/news_feed.py
- skyportal/models.py
- static/js/components/NewsFeed.jsx
Closes https://github.com/skyportal/skyportal/issues/1353
> Expand newsfeed to include spectra, classifications and followup photometry

- skyportal/handlers/api/source_groups.py
- static/js/components/CandidateList.jsx
In this PR:
- Move classification chip to new line
- Refresh candidate upon group changes
> Minor scanning page updates

- static/js/components/ThumbnailList.jsx
Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/60
> shore up links to survey viewers on source page

- skyportal/tests/frontend/test_upload_spectroscopy.py
- static/js/components/UploadSpectrum.jsx
Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/68
> fix share with... bug in upload spectrum

- skyportal/tests/frontend/test_sources.py
- static/js/components/PhotometryTable.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
Mostly addresses https://github.com/fritz-marshal/fritz-beta-feedback/issues/66.
> add photometry table

- skyportal/handlers/api/comment.py
Fixes `make load_demo_data` on the CI
> add commit back to comment post handler

- skyportal/tests/frontend/test_scanning_page.py
- static/js/components/FilterCandidateList.jsx
Closes https://github.com/fritz-marshal/fritz-beta-feedback/issues/58
> Make default date range on scanning page past 24 hours

- package.json
- requirements.txt
- skyportal/handlers/api/internal/plot.py
- skyportal/plot.py
- skyportal/tests/frontend/test_followup_requests.py
- skyportal/tests/frontend/test_observing_planner.py
- skyportal/tests/frontend/test_quick_search.py
- skyportal/tests/frontend/test_sources.py
- skyportal/tests/frontend/test_upload_spectroscopy.py
- static/js/components/AssignmentForm.jsx
- static/js/components/BokehModels.js
- static/js/components/Plot.jsx
- static/js/components/ShareDataForm.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/plotjs/download.js
- webpack.config.js
Closes https://github.com/skyportal/skyportal/issues/1250
> Upgrade to bokeh 2 & robustify front-end tests

- skyportal/tests/frontend/test_sources.py
- static/js/components/ClassificationForm.css
- static/js/components/ClassificationForm.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
> Refactor classifications form to use react-jsonschema-form and add group IDs 

- skyportal/plot.py
- skyportal/tests/frontend/test_followup_requests.py
- skyportal/tests/frontend/test_sources.py
Fixes https://github.com/fritz-marshal/fritz/issues/123
Fixes https://github.com/fritz-marshal/fritz/issues/124
> Increase effective wavelength range of photometry colormap 

- skyportal/handlers/api/candidate.py
- skyportal/tests/api/test_candidates.py
- skyportal/tests/frontend/test_scanning_page.py
- static/js/components/ClassificationForm.jsx
- static/js/components/FilterCandidateList.jsx
Addresses [beta-feedback issue #72](https://github.com/fritz-marshal/fritz-beta-feedback/issues/72)
> Add classifications and redshift filtering to scanning page

- static/js/API.js
- static/js/ducks/annotations.js
- static/js/ducks/candidates.js
- static/js/ducks/invitations.js
- static/js/ducks/sources.js
- static/js/ducks/users.js
Closes https://github.com/skyportal/skyportal/issues/358
> Add queryParams parameter to API.GET

- skyportal/app_server.py
Closes https://github.com/skyportal/skyportal/issues/1414
> Only add tables in debug mode

- static/js/components/Group.jsx
- static/js/components/GroupFiltersStreams.jsx
- static/js/components/GroupPageManageUserButtons.jsx
- static/js/components/GroupUsers.jsx
This PR attempts to tame the beast that Group.jsx has become.  
Closes https://github.com/skyportal/skyportal/issues/768
> Split up Group component into several smaller, more manageable components

- skyportal/handlers/api/group.py
- skyportal/tests/frontend/test_group_admission_requests.py
Closes https://github.com/skyportal/skyportal/issues/1482
> Fix GroupHandler.get bug where group w/ no members could not be fetched via API

- skyportal/plot.py
Closes https://github.com/fritz-marshal/fritz-beta-feedback/issues/76
Credit to @dannygoldstein for intuiting the source of the error
> Use np.nanmedian in spectrum plot normalization to account for NaN flux values

- skyportal/handlers/api/acls.py
- skyportal/handlers/api/allocation.py
- skyportal/handlers/api/annotation.py
- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/classification.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/facility_listener.py
- skyportal/handlers/api/filter.py
- skyportal/handlers/api/followup_request.py
- skyportal/handlers/api/group.py
- skyportal/handlers/api/group_admission_request.py
- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/invitations.py
- skyportal/handlers/api/news_feed.py
- skyportal/handlers/api/observingrun.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/public_group.py
- skyportal/handlers/api/roles.py
- skyportal/handlers/api/sharing.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/source_groups.py
- skyportal/handlers/api/spectrum.py
- skyportal/handlers/api/stream.py
- skyportal/handlers/api/sysinfo.py
- skyportal/handlers/api/taxonomy.py
- skyportal/handlers/api/telescope.py
- skyportal/handlers/api/thumbnail.py
- skyportal/handlers/api/user.py
- skyportal/handlers/api/weather.py
Closes https://github.com/skyportal/skyportal/issues/1438
Closes https://github.com/skyportal/skyportal/issues/1509
> Add tags to API docs

- skyportal/tests/frontend/test_group_sources.py
- static/js/components/CandidateList.jsx
- static/js/components/GroupSources.jsx
- static/js/components/SourceList.jsx
- static/js/components/SourceTable.jsx
> Refactor source table to use sorting via clicking on column header

- doc/dev.md
Closes https://github.com/skyportal/skyportal/issues/1514
> Add example of running single test to developer docs

- static/js/components/ThumbnailList.jsx
Fixes https://github.com/fritz-marshal/fritz/issues/121
> update legacysurvey link

- skyportal/plot.py
Fix the normalization in the spectrum plot for the individual spectrum plotting tool.
> Spectrum plot median(abs(flux))

- config.yaml.defaults
- data/db_demo.yaml
- data/instruments.yaml
- requirements.txt
- skyportal/facility_apis/__init__.py
- skyportal/facility_apis/lt.py
- skyportal/models.py
- skyportal/tests/frontend/test_followup_requests.py
- skyportal/utils/http.py
- static/js/components/EditFollowupRequestDialog.jsx
- static/js/components/FollowupRequestForm.jsx
- static/js/components/FollowupRequestLists.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
This PR provides a submission interface for the LT interface along with associated test suite. It enables submission to IOO, IOI and SPRAT, closely tracking the example Danny provided with SEDM. Please consider submitting and deleting a test request, on review (the test account used does not have any actual submission power, but does interact with their interface).
> Liverpool Telescope - IOO, IOI, SPRAT APIs

- alembic/versions/b74a9ff3b29d_add_missing_revisions.py
Forgot to check for database migrations on #1432 and #1261. This PR adds them in.
> add migrations missing from #1432 and #1261

- skyportal/handlers/api/group.py
- skyportal/tests/api/test_groups.py
Closes https://github.com/skyportal/skyportal/issues/1536
> Do not allow empty string (or all whitespace) group names

- skyportal/tests/frontend/test_group_sources.py
- static/js/components/GroupSources.jsx
Closes https://github.com/skyportal/skyportal/issues/1524
> Re-skin group sources header

- skyportal/plot.py
Changed line plot style for spectra from step to line to enable hover tool.  Modified tooltips struct to access wavelength and flux and formatted same.
> Fixed spectrum hover in skyportal/plot.py

- skyportal/plot.py
Implemented initial version of rest wavelength axis on spectrum plots.  Remaining question: should it react to the redshift slider, or is that just for the atomic lines?
Also found that the hover on the spectrum plot does not work, so I commented it out.
> Implemented rest wavelength axis on spectrum plots

- skyportal/tests/frontend/test_assignments.py
Should hopefully get master back to green
> Robustify test broken by #1595

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/source.py
- static/js/components/CandidateList.jsx
- static/js/ducks/candidates.js
Closes https://github.com/fritz-marshal/fritz/issues/105
> Add button to scanning page allowing generation of PS1 cutout

- static/js/components/FilterCandidateList.jsx
Before:
After:
Closes https://github.com/skyportal/skyportal/issues/1615
> Allow blank start date on scanning page

- requirements.txt
- skyportal/models.py
Closes https://github.com/skyportal/skyportal/issues/1608
> Upgrade astropy to v4.2

- skyportal/handlers/api/allocation.py
Updates the allocations handler to use the permissions checking infrastructure introduced in #1542
> Use New Permissions Framework on Allocations Handler

- skyportal/handlers/api/annotation.py
- skyportal/tests/api/test_annotations.py
Updates the annotations handler to use the permissions checking infrastructure introduced in #1542
> Use New Permissions Framework on Annotations Handler 

- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_models.yaml
- .pre-commit-config.yaml
- doc/setup.md
Closes https://github.com/skyportal/skyportal/issues/1628
> Require Python >=3.8

- static/index.html.template
This needs https://github.com/cesium-ml/baselayer/pull/183
Closes https://github.com/skyportal/skyportal/pull/1492
> Add md5hash query to bundle to ensure reload when necessary

- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_models.yaml
The `npm@next` tag was recently updated so that it would install npm 7.5.2 instead of that latest npm 6 version we were on (6.14.11). The major version bump in NPM would then lead to React 17 being installed instead of React 16, and that led to compatibility issues with Material UI when installing SkyPortal dependencies. For now, I think we should pin the last working NPM version until this is resolved on MUI's side.
> Fix CI dependency issue

- alembic/versions/99958ac9a5b1_rename_usernotificaiton_column_to_avoid_.py
- alembic/versions/fbf89710dead_refactor_candidates_table.py
This PR adds migration steps for schema changes that were introduced in previous PRs, but did not have migrations explicitly written.
> Add some missing lines to previous database migrations

- static/js/components/Notifications.jsx
> Add disableScrollLock to Notifications' Popover

- skyportal/handlers/api/group_admission_request.py
- skyportal/tests/conftest.py
- skyportal/tests/frontend/test_group_admission_requests.py
Closes https://github.com/skyportal/skyportal/issues/1652
> Ensure user has sufficient stream access before creating group admission request

- doc/usage.md
Closes https://github.com/skyportal/skyportal/issues/1660
> Update pre-commit linter setup docs

- skyportal/plot.py
Very simple change to address issue [#81](https://github.com/fritz-marshal/fritz-beta-feedback/issues/81) requesting that spectra be sorted on date
> Sort spectra on date

- skyportal/plot.py
This was a one-line fix: just added hover source to toggle callback by adding one line to callback code.
> Set visibility of hover source in toggle callback (one line change)

- static/js/components/SidebarAndHeader.jsx.template
Simplifies & improves sidebar link highlighting logic.
Closes #1683
> Improve sidebar menu item highlighting logic

- static/js/components/DBStats.jsx
Closes https://github.com/skyportal/skyportal/issues/1736
> Show cron job output in Dialog on click rather than Popover on hover on DB Stats page

- skyportal/utils/offset.py
See also https://github.com/joblib/joblib/issues/574
> Limit size of Joblib memory cache

- skyportal/api_description.md
> Add sample query parameter request to API docs header

- .github/labeler.yml
- .github/workflows/add_labels.yaml
Check modified files in PRs and automatically add the following labels where relevant (some labels were already in the repository, some I just created):
- config-change
- demo-data
- dependencies
- docker
- documentation
- formatting-and-linting
- javascript
- migration
- needs-migration?
- python
- workflows
See inline comments for detailed specification of what triggers each label. Feel free to suggest more labels if you see come up with any.
Addresses #1707
> Add a GA workflow to automatically add labels to PRs

- skyportal/plot.py
- static/js/plotjs/download.js
- static/js/plotjs/foldphase.js
- static/js/plotjs/stackf.js
- static/js/plotjs/stackm.js
- static/js/plotjs/togglef.js
- static/js/plotjs/togglem.js
- static/js/plotjs/togglep.js
Use the bokeh.transform factor_mark to map markers onto data['instrument'] in photometry plot.
However, I cannot find an easy way to perform the same mapping for the CheckboxWithLegendGroup(CheckboxGroup) object.  I tried using the same methodology as the colors property in that object, but then the photometry plot does not appear even though the code throws no errors.
I suggest we try using interactive legends and the factor_mark and the factor_cmap bokeh transform functions without splitting the data on the label.  Here is an example from the bokeh docs:
[Mapping marker types](https://docs.bokeh.org/en/latest/docs/user_guide/data.html#mapping-marker-types)
It would change the character of the labels, but would simplify this function greatly.  I'm open to suggestions.
> Better phot plot

- skyportal/plot.py
- static/js/plotjs/download.js
- static/js/plotjs/foldphase.js
- static/js/plotjs/stackf.js
- static/js/plotjs/stackm.js
- static/js/plotjs/togglef.js
- static/js/plotjs/togglem.js
- static/js/plotjs/togglep.js
This reverts commit 42b8342e6610106904b1ae4330706556fe897a4b.
> Revert "Better phot plot (#1758)"

- static/js/components/RecentSources.jsx
- static/js/components/ThumbnailList.jsx
- static/js/components/TopSources.jsx
- static/js/components/UIPreferences.jsx
> Add a profile preference for inverting thumbnails app-wide

- requirements.txt
Fixes this error that seems to be derailing GA builds. 
```
==================================================
Server at: http://localhost:5000
Database at: localhost:5432 (skyportal)
Fake OAuth: enabled
Debug mode: enabled
==================================================
Press Ctrl-C to abort the server
[✗] Verifying Python package dependencies
dask 2021.2.0 is installed but dask>=2021.03.0 is required by {'distributed'}
Collecting dask>=2021.03.0
Using cached dask-2021.3.0-py3-none-any.whl (925 kB)
Installing collected packages: dask
Attempting uninstall: dask
Found existing installation: dask 2021.2.0
Uninstalling dask-2021.2.0:
Successfully uninstalled dask-2021.2.0
Successfully installed dask-2021.3.0
Collecting dask<2021.3,>=2020.12
Using cached dask-2021.2.0-py3-none-any.whl (900 …
```
> relax dask requirements to allow GA builds to succeed

- skyportal/tests/frontend/test_followup_requests.py
LT folks complained about our tests hitting their servers too much - this PR temporarily disables the LT tests. This is probably a good time to revisit trying to do some sort of mocking with these. I'll work on it.
> Disable LT tests

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
- static/js/components/UpdateSourceRedshift.jsx
Closes https://github.com/fritz-marshal/fritz-beta-feedback/issues/89
> Allow redshift to be nullified in source page component

- skyportal/plot.py
Useed @kmshin1397 's add_plot_legend to add interactive plot to spec plot.  Now phot and spec plots are consistent, thus satisfying the hobgoblin of my little mind and addressing [Issue 1786](https://github.com/skyportal/skyportal/issues/1786).
> use interactive legend for spec plots

- skyportal/handlers/api/photometry.py
Closes https://github.com/skyportal/skyportal/issues/1815
See also https://github.com/skyportal/skyportal/issues/1812
> Include altdata in photometry API GET request response data

- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
Closes https://github.com/skyportal/skyportal/issues/1767
> Reset annotations sorting parameters upon new candidates search submission

- doc/index.rst
- doc/permissions.md
This PR documents the row level security framework introduced in https://github.com/cesium-ml/baselayer/pull/184 and https://github.com/skyportal/skyportal/pull/1542 and iterated on in a series of subsequent PRs.
> Document row level security framework within SkyPortal

- skyportal/handlers/api/source.py
Closes https://github.com/skyportal/skyportal/issues/1828
> Include units for ra, dec, radius in SourceHandler.get docs

- skyportal/handlers/api/source.py
> temporarily disable security checks on source handler

- skyportal/handlers/api/followup_request.py
- skyportal/handlers/api/photometry.py
This PR bumps baselayer a second time to use the new anti-join on SQL
> bump baselayer a second time

- skyportal/tests/frontend/test_profile.py
- skyportal/tests/frontend/test_user_management.py
This was caused by the addition of the "Annotate" ACL to some user roles.
> Fix frontend tests broken in #1858

- skyportal/handlers/api/candidate.py
Closes https://github.com/skyportal/skyportal/issues/1863
> Add optional includeComments query param to candidates GET API which defaults to False

- alembic/versions/19b72aac66cd_add_thumbnail_is_grayscale.py
The current migration attempts to pull every existing thumbnail and determine if they are colored or grayscale. On production-scale databases, this would take way too long to do the migration leading to too much downtime. This PR updates the migration script to set all existing thumbnails to just be marked as colored by default. 
I will do a follow-up PR to add a separate utility script to use the API to do this thumbnail processing in a more efficient/parallelized external process without spending all that time in the migration. Until then, the color inversion preference will just have to only work on thumbnails posted after the migration.
> Fix way too slow thumbnail color migration

- skyportal/handlers/api/source.py
Closes https://github.com/fritz-marshal/fritz/issues/231
> Fix join b/w Group and Source in SourceHandler

- skyportal/handlers/api/candidate.py
- skyportal/tests/api/test_photometry.py
Same thing with subqueries as in the source handler.
> Fix saved groups for fetched candidate

- skyportal/handlers/api/source.py
This addresses a database session leak.
Each handler (request) gets its own session. The handler is responsible
for closing the session (and, by implication, associated database connection)
when it is done.  This happens in `on_finish`.
When a handler launches a task using `add_callback`, that task could
a) access the database and b) continue operating after the handler's
`on_finish` method had been called.  This would result in the session's
database connection remaining active, and not being returned to the
SQLAlchemy thread pool.
Such connection leaks result in the following error:
```
QueuePool limit of size 5 overflow 10 reached, connection timed out,
timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
```
> Remove session before returning in PS1 callback

- skyportal/handlers/api/source.py
Closes https://github.com/fritz-marshal/fritz/issues/233
> Update queries in SourceHandler.get

- doc/migrations.md
Closes https://github.com/skyportal/skyportal/issues/1222
> Update docs outlining basic alembic usage

- skyportal/handlers/api/source.py
There was a bad join when filtering the sources page by classification (a cross-join between all taxonomy and all objs). The current version actually joins in a whole new taxonomy subquery and pairs them with the classifications subquery to look for the filtered on value.
This fixes the subqueries involved in that to get rid of the cross join and actually filter on proper `(taxonomy.name, classification.classification)` pairs from the same subquery.
> Fix join in sources filtering by classification

- doc/index.rst
Is there anything else we need to add except this line? @dmitryduev
> added advanced_usage to TOC

- static/js/components/GroupList.jsx
- static/js/components/Groups.jsx
Closes https://github.com/skyportal/skyportal/issues/1747
> Fix nested Paper components on Groups page

- static/js/components/HeaderContent.jsx.template
- static/js/components/SidebarAndHeader.jsx.template
Closes https://github.com/skyportal/skyportal/issues/1891
> Re-hydrate when clicking any link to Homepage/Dashboard

- skyportal/tests/frontend/test_source_list.py
- static/js/components/SourceTable.jsx
We want to have a spinner running when there is a filtering/sorting request, so it doesn't look like nothing changes when those changes are applied. 
Closes #1911
> Source page spinner

- alembic/versions/c0e0173c90b0_add_lco_apis.py
Migration for updating the followup requests API ENUM values for the recently merged LCO requests (#1883)
> Add LCO APIs migration

- alembic/versions/c0e0173c90b0_add_lco_apis.py
Fix branching in Alembic history caused by #1974
> Fix migration history

- requirements.txt
Attempt to fix dependencies collision
> Resolve dask dependency conflicts

- .flake8
- skyportal/tests/utils/test_cache.py
- skyportal/utils/cache.py
This is a POC to illustrate cache invalidation by age.
Note that, currently, cache invalidation happens only on insert.  We can modify this if it seems more prudent to do it on get, or even in both places.
> Add cache invalidation by age

- skyportal/handlers/api/invitations.py
- skyportal/tests/api/test_invitations.py
- skyportal/tests/frontend/test_invitations.py
- static/js/components/UserInvitations.jsx
Closes https://github.com/skyportal/skyportal/issues/1998
> Allow invitation role to be updated via User Management page

- skyportal/handlers/api/source.py
Not sure if there's another reason for the slowness in the query but this seems to at least resolve the duplicates issue. Will look into it further tomorrow.
> Remove duplicates in sources query

- skyportal/app_server.py
We now allow names like `ZTFJ170249.34-350323.3`, but not `ZTFJ170249.34+350323.3` - this PR fixes it.
> Allow plus sign in source names

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/facility_listener.py
- skyportal/handlers/api/filter.py
- skyportal/handlers/api/followup_request.py
- skyportal/handlers/api/group.py
- skyportal/handlers/api/group_admission_request.py
- skyportal/handlers/api/internal/notifications.py
- skyportal/handlers/api/internal/token.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/sharing.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/stream.py
- skyportal/handlers/api/taxonomy.py
- skyportal/tests/api/test_group_admission_requests.py
- skyportal/tests/api/test_groups.py
- skyportal/tests/api/test_sources.py
- skyportal/tests/api/test_streams.py
- skyportal/tests/conftest.py
Closes https://github.com/skyportal/skyportal/issues/2006
> Patch potential security vulnerabilities in Tornado handler methods

- skyportal/app_server.py
- skyportal/onboarding.py
Depends on https://github.com/cesium-ml/baselayer/pull/202 
Closes https://github.com/skyportal/skyportal/pull/1744
> Suppress logging of expected authentication pipeline-related exceptions

- skyportal/handlers/api/candidate.py
Closes https://github.com/skyportal/skyportal/issues/1768
> Prioritize autoannotations from groups being scanned in candidates results

- doc/adding_features.md
Closes https://github.com/skyportal/skyportal/issues/2070
> Add note about RHF and RJSF in dev intro docs

- data/instruments.yaml
Hi,
I added the SDSS filters to the NOT/ALFOSC instrument.
Cheers,
Steve
> Added SDSS filters to NOT/ALFOSC

- static/js/components/CommentList.jsx
Closes https://github.com/skyportal/skyportal/issues/2087
> Fix bug in delete spectrum comments on source page

- skyportal/plot.py
Closes #1889
The error seen in the issue seems to be with `sncosmo` and not our code, perhaps related to this https://github.com/sncosmo/sncosmo/issues/210, or something similar. This PR just catches the errors in case it pops up again to provide a more informative error message.
> Catch sncosmo errors when plotting

- doc/setup.md
I added a couple of notes about using Windows Subsystem for Linux to the setup doc to avoid some hard-to-diagnose errors.
> Adding notes on WSL to setup doc

- static/index.html.template
- static/login.html.template
See Google's instructions at:
https://developers.google.com/search/docs/advanced/crawling/block-indexing
> Request that robots do not index our website

- skyportal/tests/api/test_photometry.py
This has still been failing much of the time on CI.
> Further reduce data size in test_big_phot_post API test

- skyportal/handlers/api/internal/token.py
- skyportal/tests/frontend/test_tokens.py
Closes https://github.com/skyportal/skyportal/issues/2010
> Limit regular users to one token

- tools/data_loader.py
Also update data loader timeouts to be a bit more robust
> Pin latest baselayer

- skyportal/handlers/api/internal/plot.py
Addresses https://github.com/fritz-marshal/fritz/issues/333
The code was missing a check in case sunrise was after sunset to ensure you have positive delta t. Also increased sampling slightly to smooth out behavior.
> Fix airmass plot

- skyportal/handlers/api/source.py
Addresses https://github.com/skyportal/skyportal/issues/2254.
> Grab SDSS and DR8 thumbnails if they don't exists for some reason

- static/js/components/AssignmentList.jsx
- static/js/components/CandidateList.jsx
- static/js/components/CandidatesPreferences.jsx
- static/js/components/CandidatesPreferencesForm.jsx
- static/js/components/CentroidPlot.jsx
- static/js/components/ClassificationForm.jsx
- static/js/components/CommentEntry.jsx
- static/js/components/EditSourceGroups.jsx
- static/js/components/FilterCandidateList.jsx
- static/js/components/GroupManagement.jsx
- static/js/components/GroupSources.jsx
- static/js/components/Groups.jsx
- static/js/components/MultipleClassificationsForm.jsx
- static/js/components/NewGroupUserForm.jsx
- static/js/components/NewTokenForm.jsx
- static/js/components/NonMemberGroupList.jsx
- static/js/components/Observability.jsx
- static/js/components/ObservabilityPreferences.jsx
- static/js/components/Periodogram.jsx
- static/js/components/RecentSources.jsx
- static/js/components/SaveCandidateButton.jsx
- static/js/components/ShowClassification.jsx
- static/js/components/SourceTable.jsx
- static/js/components/SourceTableFilterForm.jsx
- static/js/components/ThumbnailList.jsx
- static/js/components/TopSources.jsx
- static/js/components/UserInvitations.jsx
- static/js/components/UserManagement.jsx
This patch adds `?` optional chaining when filtering JS arrays to
ensure that non-existent methods of null objects are not called.
Closes https://github.com/skyportal/skyportal/issues/2259
> Use optional chaining when filtering JS arrays

- static/js/components/ClassificationForm.jsx
- static/js/components/FilterCandidateList.jsx
- static/js/components/FollowupRequestForm.jsx
- static/js/components/FollowupRequestLists.jsx
- static/js/components/GroupShareSelect.jsx
- static/js/components/ManageDataForm.jsx
- static/js/components/MultipleClassificationsForm.jsx
- static/js/components/NewGroupForm.jsx
- static/js/components/ObjPageAnnotations.jsx
- static/js/components/ObservabilityPreferences.jsx
- static/js/components/ScanningPageCandidateAnnotations.jsx
- static/js/components/ShowClassification.jsx
- static/js/components/SourceNotification.jsx
- static/js/components/SourceRedshiftHistory.jsx
- static/js/components/SourceTable.jsx
- static/js/components/SourceTableFilterForm.jsx
Closes https://github.com/fritz-marshal/fritz/issues/347
> Add optional chaining ? for arrayVar.forEach usage

- static/js/components/CommentListMobile.jsx
This patch fixes a bug where comment attachment previews were
unable to be viewed in mobile view.
> Fix broken comment attachment preview in mobile view

- doc/index.rst
> Add DB initialization to quickstart docs

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
- skyportal/models.py
This explicitly creates a new SQLAlchemy scoped session
in thumbnail generation subroutine, removing it when done.
> Create new session for each async thumbnail gen task

- static/js/components/CommentAttachmentPreview.jsx
- static/js/components/CommentList.jsx
- static/js/components/CommentListMobile.jsx
- static/js/components/ManageDataForm.jsx
- static/js/components/Notifications.jsx
...to comply with the changes introduced in https://github.com/skyportal/skyportal/pull/2301.
> Replace spectrum->spectra in associatedResourceType throughout the codebase

- doc/advanced_usage.md
I found yet another problem with the documentation of the Gaia / HR diagram docs. This fixes that problem.
> Fix data heirarchy in advanced_usage.md docs

- requirements.txt
- skyportal/handlers/api/source.py
- skyportal/models/obj.py
- skyportal/models/photometry.py
- skyportal/tests/tools/test_radial_query.py
Tries to address the refactoring of healpix-alchemy
> Change healpix-alchemy -> conesearch-alchemy

- skyportal/tests/frontend/sources_and_followup_etc/test_followup_requests.py
- static/js/components/AirmassPlot.jsx
- static/js/components/AssignmentForm.jsx
- static/js/components/AssignmentList.jsx
- static/js/components/FollowupRequestForm.jsx
- static/js/components/Groups.jsx
- static/js/components/ManageDataForm.jsx
- static/js/components/NonMemberGroupList.jsx
- static/js/components/Observability.jsx
- static/js/components/PhotometryTable.jsx
- static/js/components/Plot.jsx
- static/js/components/RecentSources.jsx
- static/js/components/RunSummary.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/SourceQuickView.jsx
- static/js/components/SourceTable.jsx
- static/js/components/UploadPhotometry.jsx
- static/js/components/UploadSpectrum.jsx
- static/js/components/UserInfo.jsx
Taking screenshots is a little tricky since they load really pretty fast
Addresses #2343
> Replaced loading messages with material ui circularProgress spinners

- doc/slack.md
> Slack integration: Add blurb in docs to point directly to existing app

- skyportal/handlers/api/source.py
- skyportal/tests/api/test_sources.py
- skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py
- static/js/components/SourceTableFilterForm.jsx
Closes https://github.com/skyportal/skyportal/issues/2337
I added 2 inputs to filter source list so you can filter to all with a spectra taken before or after a certain date
> Filter by Spectra date

- skyportal/handlers/api/instrument.py
Closes https://github.com/skyportal/skyportal/issues/2454
> Decrease verbosity of instrument field loading

- doc/advanced_usage.md
- requirements.txt
Provide info for how an admin updates a taxonomy in a live version.
> bump default taxonomy version and add info for updating taxonomy in SP

- skyportal/handlers/api/source.py
- skyportal/tests/api/test_sources.py
This PR implements (and enforces) pagination in GET
/api/sources requests where `saveSummary=true` so as
to limit the size of queries users can execute against
the DB via this endpoint.
API tests are added.
Closes #2428
> Paginate saveSummary=true source API requests

- skyportal/api_description.md
Add sample script showing how to use pagination parameters 
in sources/candidates API.
> Add sample pagination script to API docs

- skyportal/handlers/api/spectrum.py
This patch attempts to speed up the source spectra fetching query
in the source spectra handler.
> Attempt to speed up source spectra query

- config.yaml.defaults
- data/db_demo.yaml
- data/instruments.yaml
- data/telescopes.yaml
- data/tests/test_server_recordings_static.yaml
- skyportal/facility_apis/__init__.py
- skyportal/facility_apis/kait.py
- skyportal/services/test_server/test_api_server.py
- skyportal/tests/flaky/test_followup_requests.py
- test_config.yaml
> Add KAIT as instrument

- skyportal/models/user_notification.py
- static/js/components/SlackPreferences.jsx
This PR adds GCN notice notifications for slack.
> Add GCN notice notifications for slack

- requirements.txt
- skyportal/handlers/api/photometry.py
Allows us to bump to latest pandas following the NaN changes in 1.3.X.
> fix NaN handling for new pandas conventions

- .github/workflows/test_migrations.yaml
- alembic/env.py
Depends on https://github.com/cesium-ml/baselayer/pull/277
> Allow alembic to handle multiple configuration files

- config.yaml.defaults
- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/telescope.py
- skyportal/tests/frontend/test_instruments_page.py
- static/js/components/InstrumentPage.jsx
- static/js/components/NewInstrument.jsx
- static/js/ducks/instrument.js
- static/js/ducks/instruments.js
- static/js/ducks/telescopes.js
Similar to the last PR, this page adds the ability to add an instrument.
> Add instrument page

- .github/workflows/test_migrations.yaml
Checks for changes in enum_types and facilities_api in case we need a migration.
> watch enum_types and facilities_apis for potential database changes

- skyportal/handlers/api/gcn.py
This PR fixes the cases when GCNs do not have skymaps.
> Hotfix for GCNs without skymaps

- .github/workflows/build-and-deploy-docs.yaml
- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_migrations.yaml
- .github/workflows/test_models.yaml
- requirements.txt
I think the release of pip 22 broke our dependency installation...
> pip 22 breaks our dependencies

- .github/workflows/test_api_and_frontend.yaml
- skyportal/tests/api/test_sources.py
Using this PR for testing test_sources.py::test_sources_include_detection_stats.
> Testing source detection_stats on Github's CI

- skyportal/handlers/api/candidate.py
- skyportal/tests/api/test_candidates.py
This PR handles the posting of identical candidates more gracefully.
Closes #2666.
> Add handling of identical candidates

- doc/advanced_usage.md
- package.json
Added and modified the documentation for the spectroscopic lines according to https://github.com/skyportal/skyportal/issues/1914 .
> Documentation for spectroscopic lines

- data/db_demo.yaml
- skyportal/handlers/api/allocation.py
- skyportal/handlers/api/internal/robotic_instruments.py
- skyportal/handlers/api/observation_plan.py
- skyportal/tests/frontend/test_gcnevents.py
- static/js/components/FollowupRequestForm.jsx
- static/js/components/GcnEventPage.jsx
- static/js/components/GcnSelectionForm.jsx
- static/js/components/ObservationPlanRequestForm.jsx
- static/js/components/ObservationPlanRequestLists.jsx
- static/js/ducks/allocations.js
- static/js/ducks/gcnEvent.js
- static/js/ducks/instruments.js
This API adds a front end to interact with the ObservationPlanRequest API.
> Frontend modifications for observation plans

- .github/labeler.yml
- .github/workflows/test_migrations.yaml
Forces migration check on requirements.txt change in PRs. Adds needs-migration? label too.
> Migration labeler reqs

- skyportal/tests/api/test_thumbnail.py
- skyportal/tests/flaky/test_thumbnail_flaky.py
This PR moves the thumbnail cascade test to flaky.
> thumbnail cascade is flaky

- skyportal/tests/frontend/test_gcnevents.py
- static/js/components/ObservationPlanRequestLists.jsx
This PR adds a download button for the observation plans. 
Supercedes #2682.
> Download button for observation plans

- skyportal/handlers/api/instrument.py
- static/js/components/NewInstrument.jsx
- static/js/components/NewObservation.jsx
This PR adds the ability to upload instrument files from the webpage.
> Enable instrument file uploads

- skyportal/plot.py
This PR uses a with DBSession() as session to automatically close sessions.
> call session using with

- skyportal/handlers/api/annotation.py
- skyportal/plot.py
This PR tries to add some extra catches for the production SkyPortal instance.
> try to catch some errors

- config.yaml.defaults
- doc/mma.md
- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/ztf.py
This PR adds an example of extracting ZTF forced photometry from the ZTF forced photometry service.
> Ztf forced photometry

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/observation_plan.py
- static/js/components/GcnEventPage.jsx
- static/js/components/LocalizationPlot.jsx
- static/js/components/ObservationPlanRequestLists.jsx
This PR adds observation plan plotting capabilities.
> add geojson endpoint for observation plan

- static/js/components/ObservationPage.jsx
This PR better handles no observation data.
> Better handle missing data

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/observation_plan.py
- static/js/components/ObservationPlanRequestForm.jsx
This PR adds a button to download an airmass chart for a given telescope/localization.
> Download airmass chart

- static/js/components/CandidateList.jsx
- static/js/components/GcnEventPage.jsx
- static/js/components/GcnEvents.jsx
- static/js/components/Source.jsx
- static/js/components/SourceList.jsx
- static/js/components/SourceTableFilterForm.jsx
- static/js/components/Spinner.jsx
- static/js/components/UserInvitations.jsx
- static/js/components/UserManagement.jsx
Adds a new centered spinner component to be used in several locations throughout the app
Closes #2290
> Center spinner

- skyportal/handlers/api/source.py
- skyportal/tests/api/test_sources.py
- skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py
- static/js/components/SourceTableFilterForm.jsx
This PR introduces the ability to filter negatively based on classifications.
> Add ability to reject based on classifications

- static/js/components/GcnEventPage.jsx
This PR adds Grid to GcnEventPage.
> Use Grid to improve GcnEventPage layout

- skyportal/app_server.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/gcn.py
- skyportal/models/comment.py
- skyportal/tests/api/test_comments_on_gcn.py
- static/js/components/CommentAttachmentPreview.jsx
- static/js/components/CommentList.jsx
- static/js/components/CommentListMobile.jsx
- static/js/components/GcnEventPage.jsx
- static/js/components/LocalizationPlot.jsx
- static/js/ducks/gcnEvent.js
This PR adds a comment block to the GcnEvent page.
> add gcnevent comments

- requirements.txt
Make sure black uses latest release, which gets around the click issue.
> upgrade black

- requirements.txt
This PR pins click to try to deal with the black issue.
> try pinning click too

- skyportal/plot.py
- static/js/components/SourceDesktop.jsx
https://user-images.githubusercontent.com/82007190/160194147-ea89c997-ff26-41a2-ae8f-5f89e4d3f454.mp4
@mcoughlin Is this what's desired? Adds a button for clearing photometry, add all, and add ZTF only.
> Add buttons for clearing/adding photometry

- static/js/components/ObservationPlanRequestLists.jsx
This PR fixes the multi-telescope plans failure.
Closes #2794
> Multi-telescope plans failure

- skyportal/facility_apis/sedm.py
- skyportal/facility_apis/sedmv2.py
This PR adds a REFRESH to SEDM/SEDMv2 requests so updates appear on front-end.
> Add a REFRESH to SEDM/SEDMv2 requests

- requirements.txt
- skyportal/tests/api/test_instrument.py
This PR upgrades to regions 0.6
> Upgrade to regions 0.6

- Dockerfile
- webpack.config.js
This PR sets webpack url to resolve docker issue.
> Try setting url explicitly

- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/observation_plan.py
- static/js/components/ObservationPlanRequestForm.jsx
- static/js/components/ObservationPlanRequestLists.jsx
This PR opens the possibility to submit multiple plans at once.
> Try out submitting multiple plans at once

- static/js/components/VegaFoldedPlot.jsx
- static/js/components/VegaPlot.jsx
> Increase axis label font size for vega plots

- static/js/components/NewSource.jsx
This PR sets the groups from the front end that are accessible for new source posting.
Closes #2833
> New source should be posted to one of the accessible groups

- skyportal/tests/frontend/sources_and_followup_etc/test_observing_planner.py
- static/js/components/InstrumentPage.jsx
- static/js/components/NewObservingRun.jsx
- static/js/components/ObservingRunPage.jsx
This PR makes small quality of life improvements to the instrument and observing run page. Instrument page adds a space between the filter strings so the string wraps. Observing run page adds checkbox to display near-term runs by default.
> Small instrument page / observing run page improvements

- static/js/components/AirmassPlot.jsx
- static/js/components/CentroidPlot.jsx
- static/js/components/HoursBelowAirmassPlot.jsx.template
- static/js/components/Theme.jsx
- static/js/components/UploadSpectrum.jsx
- static/js/components/VegaFoldedPlot.jsx
- static/js/components/VegaHR.jsx
- static/js/components/VegaPlot.jsx
- static/js/components/VegaSpectrum.jsx
Closes #2490 
As for the `Conflicting scale property "domain"` warning, I think it should be fine [according to this](https://github.com/vega/vega-lite/issues/5733#issuecomment-575743421)?
There's also an `Infinite extent for field` warning but I can't figure out how to make it go away.
> Update vega version

- skyportal/handlers/api/annotation.py
- skyportal/tests/api/test_annotations.py
- skyportal/tests/api/test_annotations_on_spectrum.py
> Catch IntegrityError

- skyportal/handlers/api/followup_request.py
Attempt to fix the many queries to followup requests.
> short circuit the FollowupRequestSchedulerHandler

- skyportal/handlers/api/followup_request.py
- skyportal/tests/api/test_followup_requests_api.py
- static/js/components/FollowupRequestForm.jsx
- static/js/components/FollowupRequestLists.jsx
- static/js/components/FollowupRequestPage.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/ducks/followup_requests.js
This PR attempts to add pagination of follow-up requests (inspired by the style in the Users table).
> Pagination of followup requests

- skyportal/handlers/api/observingrun.py
- skyportal/model_util.py
- skyportal/tests/api/test_observing_runs.py
- skyportal/tests/conftest.py
- skyportal/tests/frontend/test_profile.py
- skyportal/utils/offset.py
- static/js/components/ObservingRunPage.jsx
- static/js/ducks/observingRun.js
This PR adds ability to delete observing runs.
> Add ability to delete observing runs

- skyportal/facility_apis/sedm.py
- skyportal/facility_apis/sedmv2.py
- skyportal/handlers/api/followup_request.py
- static/js/actions.js
- static/js/components/FollowupRequestPage.jsx
- static/js/ducks/followup_requests.js
- static/js/ducks/source.js
This PR makes some of the followup request handler improvements discussed on the call today.
> Some followup request handler improvements

- skyportal/plot.py
To aid the spring cleaning effort I've refactored `skyportal/plot.py`. Previously there was some duplicated code with creating the photometry panels, I've extracted a lot of that out to some helper functions. Also closes #2867
> Refactor plot.py

- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/ztf.py
- skyportal/handlers/api/photometry.py
This PR adds more logs for photometry.
> Add more photometry logging

- skyportal/handlers/api/news_feed.py
- skyportal/tests/api/test_newsfeed.py
This PR makes it possible to query the news feed from the API.
> Fix newsfeed API

- skyportal/handlers/api/classification.py
- skyportal/tests/api/test_classifications.py
This PR adds the ability to query multiple classifications.
> Query multiple classifications

- skyportal/handlers/api/news_feed.py
- skyportal/tests/api/test_newsfeed.py
This PR adds improvements to the newsfeed checking based on Stefan's ideas on the first PR.
> Stefan's newsfeed ideas

- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/ztf.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/photometry_request.py
This PR uses a single session to make external requests.
> Single session for external photometry request

- skyportal/plot.py
I think this will fix the issue with the abs mag scale being upside down on the photometry plot.
fixes fritz-marshal/fritz#412
> Fix abs mag scale on phot plot

- skyportal/tests/frontend/test_profile.py
- static/js/components/UpdateProfileForm.jsx
disable classification shortcuts added in #2972 until the other buttons on the scanning page are added
> Disable classification shortcuts

- skyportal/handlers/api/photometry.py
- skyportal/tests/api/test_obj_photometry.py
This PR catches an access error for the ObjPhotometryHandler.
> ObjPhotometryHandler access error

- skyportal/tests/frontend/test_profile.py
- skyportal/tests/frontend/test_scanning_page.py
- static/js/components/AddClassificationsScanningPage.jsx
- static/js/components/CandidateList.jsx
- static/js/components/ClassificationSelect.jsx
- static/js/components/ClassificationShortcutButtons.jsx
- static/js/components/ClassificationsShortcutForm.jsx
- static/js/components/FilterCandidateList.jsx
- static/js/components/UpdateProfileForm.jsx
Add classifications on scanning page
full interaction:
> Add classifications on scanning page

- static/js/components/FilterCandidateList.jsx
This PR fixes the annotation sorting variable names. Closes https://github.com/fritz-marshal/fritz/issues/416.
> Fix candidate annotation sorting variable names

- skyportal/tests/api/test_photometry.py
- skyportal/tests/flaky/test_photometry_api_flaky.py
This PR moves external photometry test to flaky.
> Move external photometry test to flaky

- alembic/versions/8acd303bd097_shift_replacement.py
This PR tries to fix the default shift column.
> Drop the needs_replacement column default

- services/gcn_service/gcn_service.py
- skyportal/handlers/api/gcn.py
This PR refactors the GcnEvent handler so we can use it in the gcn_service.
> Refactor GcnEvent Handler

- skyportal/tests/frontend/sources_and_followup_etc/test_observing_planner.py
- static/js/components/ObservingRunPage.jsx
Add a little popup to confirm deletion
also makes the titles clickable.
fixes fritz-marshal/fritz-beta-feedback#117
> Improve observing run page ui

- static/js/components/FollowupRequestForm.jsx
In case of list default, do not need a list of a list.
> FollowupRequestForm Default is already a list

- static/js/components/SurveyLinkList.jsx
- static/js/units.js
Copied Jan's code (https://github.com/skyportal/skyportal/pull/2862) and did some linting.
> Add Aladin and Galax Links

- requirements.txt
- skyportal/models/telescope.py
This PR bumps timezonefinder to 6.0.1.
> timezonefinder 6.0

- skyportal/plot.py
hotfix for plot legends, revert back to old code [https://github.com/skyportal/skyportal/blob/b7ba75f355cbc12ebb110ea3c5c320ecc9e01cc4/skyportal/plot.py#L434](https://github.com/skyportal/skyportal/blob/b7ba75f355cbc12ebb110ea3c5c320ecc9e01cc4/skyportal/plot.py#L434)
legend back on the right for browser
> Hotfix plot legends

- static/js/components/GcnEventPage.jsx
This PR comments out GCN sources, which awaits the last_detected optimization in https://github.com/skyportal/skyportal/pull/3057.
> Comment out GCN sources for now

- static/js/components/ObservingRunPage.jsx
> Show imminent/ongoing runs on the Observing Runs page

- skyportal/handlers/api/observation_plan.py
This PR better handles the potential deletion of default plans.
> better handle the delete of default plans

- skyportal/handlers/api/gcn.py
- static/js/components/GcnEvents.jsx
- static/js/ducks/gcnEvents.js
This PR adds pagination to the GCN events.
> Paginate GCN events

- skyportal/handlers/api/source.py
This PR makes the sourceID search case agnostic.
Closes #2974.
> Case agnostic sourceID search

- skyportal/app_server.py
- skyportal/handlers/api/galaxy.py
- skyportal/tests/flaky/test_galaxy_flaky.py
- static/js/components/GalaxyPage.jsx
- static/js/components/NewGalaxy.jsx
- static/js/ducks/galaxies.js
This PR adds ability to delete galaxy catalogs.
> Add galaxy catalog deletion

- static/js/components/FollowupRequestForm.jsx
- static/js/components/FollowupRequestPreferences.jsx
- static/js/components/UpdateProfileForm.jsx
This PR allows the user to set a default follow up request.
Closes fritz issue: https://github.com/fritz-marshal/fritz/issues/415
> Allow for followup request default

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/allocation.py
- static/js/components/FollowupRequestSelectionForm.jsx
This PR makes an endpoint to make some basic plots to track allocation usage.
> Basic plots to track allocation usage

- data/GW190814.xml
- data/db_demo.yaml
This PR uses GW190814 in the demo data in an attempt to keep the memory foot print down.
> Use GW190814 in demo data

- skyportal/handlers/api/observation.py
This PR improves query efficiency on the observation table by calling distinct() as appropriate.
> Observation table query efficiency

- config.yaml.defaults
- skyportal/enum_types.py
- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/observation_plan.py
- skyportal/facility_apis/slack.py
- skyportal/handlers/api/annotation_services.py
- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/config_handler.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/spectrum.py
- skyportal/handlers/api/user.py
- skyportal/handlers/api/weather.py
- skyportal/handlers/base.py
- skyportal/initial_setup.py
- skyportal/model_util.py
- skyportal/models/obj.py
- skyportal/models/user_notification.py
- skyportal/tests/utils/test_cosmology.py
- skyportal/utils/cosmology.py
- skyportal/utils/offset.py
- skyportal/utils/thumbnail.py
This requires eyes from @mcoughlin, @guynir42, @profjsb, and @Theodlz, since it touches pieces of code you wrote.
> Update config to provide defaults where possible, otherwise use `cfg.get`

- skyportal/models/observation_plan.py
This PR improves the area and probability calculation for observation plans with a subquery.
> Improve area and probability calculation with subquery

- skyportal/facility_apis/observation_plan.py
This PR restricts the galaxies that go to gwemopt to only those within the localization region.
> Restrict galaxies going into schedule to those within localization

- static/js/components/FilterCandidateList.jsx
- static/js/components/ObservationPlanRequestForm.jsx
- static/js/components/UIPreferences.jsx
This PR makes a 24 hour or AM/PM type clock optional
> Make 24 hour or AM/PM optional

- skyportal/tests/frontend/test_user_management.py
This PR adds a timeout to make test_user_management test more robust.
> Add timeout to test_user_management test

- skyportal/handlers/api/allocation.py
- static/js/components/FollowupRequestForm.jsx
This PR sets the group defaults for the default allocation.
> Set the group defaults for the allocation

- skyportal/tests/frontend/test_favorites_page.py
This PR adds a timeout and scroll_parent to try to improve reliability of a currently flaky test.
> Favorites page timeout and scroll_parent

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/observation.py
- skyportal/handlers/api/observation_plan.py
- skyportal/models/observation_plan.py
- static/js/components/ObservationPlanRequestLists.jsx
This PR passes the width and height of fields to simsurvey. It also uses the with DBSession() as session syntax.
> Pass width and height of fields to simsurvey

- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/kait.py
- skyportal/facility_apis/lco.py
- skyportal/facility_apis/lt.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/sedm.py
- skyportal/facility_apis/sedmv2.py
- skyportal/facility_apis/slack.py
- skyportal/facility_apis/swift.py
- skyportal/facility_apis/ztf.py
- skyportal/handlers/api/followup_request.py
- skyportal/tests/api/test_followup_requests_reprioritize.py
- static/js/components/FollowupRequestPage.jsx
- static/js/components/FollowupRequestPrioritizationForm.jsx
- static/js/components/FollowupRequestSelectionForm.jsx
This PR enables to order follow-up priority by magnitude.
> Order follow-up priority by magnitude

- requirements.txt
- skyportal/handlers/api/observation.py
- skyportal/handlers/api/observation_plan.py
- skyportal/utils/simsurvey.py
- static/js/components/ObservationPlanRequestLists.jsx
- static/js/components/SurveyEfficiencyForm.jsx
- static/js/components/SurveyEfficiencyObservationPlanLists.jsx
This PR adds more models for survey efficiency assessment.
> Add more models for survey efficiency assessment

- skyportal/handlers/api/photometry.py
This PR fixes a raise AccessError to instead return self.error.
> return self.error for AccessError

- skyportal/handlers/api/source.py
This PR removes includePhotometry for multiple sources.
> Remove includePhotometry for multiple sources

- tools/nginx_parse.py
This PR adds a small tool to plot IP's for diagnostic purposes.
> Tool to plot access usage by IP address (using nginx logs)

- skyportal/handlers/api/candidate.py
This PR checks if last detected is None.
> Check for no detections in photstats

- skyportal/handlers/api/instrument.py
- static/js/components/GcnSelectionForm.jsx
- static/js/components/ObservationPlanRequestLists.jsx
This PR simplifies the  instrument fields queries to make them async.
> Simplify instrument fields queries

- skyportal/handlers/api/instrument.py
This PR sets sensitivity data in the instrument handler.
> Set sensitivity data in instrument handler

- tools/nginx_ip_and_requests.py
- tools/nginx_parse.py
This PR adds a piechart for the endpoints too.
> Add an endpoint piechart

- skyportal/handlers/api/candidate.py
This PR checks for last_detected_at to be None in the candidate handler.
> Check for last_detected_at to be None

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
- skyportal/tests/api/test_sources.py
This PR moves the SourceHandler to the new select syntax.
> Move SourceHandler to the new select syntax

- static/js/components/ObservationPage.jsx
- static/js/components/SurveyEfficiencyForm.jsx
This PR sets limits on number of injections and makes observations upload enabled for non-admins.
> Set limits on number of injections

- skyportal/handlers/api/galaxy.py
- skyportal/handlers/api/source.py
This PR breaks down the Localization query by querying for those tiles first.
> Try querying for tiles first

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/source.py
- skyportal/utils/sizeof.py
This PR adds a log to source and candidate handlers for large queries.
> Log queries returning a lot of data

- skyportal/handlers/api/phot_stat.py
I accidentally used `last_full_update` instead of `last_update` in one of the filters.
> fix minor bug in phot stat handler

- static/js/components/AssignmentForm.jsx
Closes https://github.com/skyportal/skyportal/issues/3249
> Make it possible to submit day-of runs as "upcoming"

- skyportal/handlers/api/internal/plot.py
- skyportal/plot.py
This PR fixes an issue seem on fritz where the plot height was not reported properly.
> Fix issue with plotting widths

- requirements.txt
- skyportal/handlers/api/observation_plan.py
This PR enables one to simulate efficiencies for skymaps without distance information.
> Simulate efficiencies for skymaps without distance information

- skyportal/utils/sizeof.py
This PR reduces the warning size threshold for big queries.
> Reduce warning size threshold

- data/instruments.yaml
This PR changes the name of GMOS between Gemini North / South.
> GMOS repeated in instruments file

- skyportal/handlers/api/annotation.py
- skyportal/handlers/api/comment.py
This PR adds query size logs to the annotation and comment handlers.
> Add query size logs to annotation and comment handlers

- skyportal/handlers/api/db_stats.py
This PR updates db_stats to use new syntax.
> Update db_stats to use new syntax

- skyportal/handlers/api/tns.py
This PR updates the TNS handler to use new query style.
> Update TNS handler to use new query style

- skyportal/handlers/api/taxonomy.py
- skyportal/models/taxonomy.py
This PR updates the taxonomy handler to the new query style
> Taxonomy handler to new query style

- skyportal/handlers/api/spectrum.py
This PR updates the spectrum handler to the new syntax.
> Update spectrum handler to use new syntax

- skyportal/handlers/api/telescope.py
This PR updates the telescope handler to the new syntax.
> Update telescope handler to new syntax

- skyportal/handlers/api/followup_request.py
- skyportal/handlers/api/observation_plan.py
This PR updates the follow-up request handler to use the new syntax.
> Update follow-up request handler to use new syntax

- data/instruments.yaml
This PR fixes a misspelled filter name in instruments.yaml.
> Misspelled filter in instruments.yaml

- skyportal/handlers/api/comment.py
- skyportal/models/comment.py
- skyportal/tests/api/test_comments.py
- skyportal/tests/api/test_comments_on_spectrum.py
This PR removes attachments from the generic comment query.
> Remove attachment from comment query

- config.yaml.defaults
- skyportal/handlers/api/analysis.py
- skyportal/tests/frontend/sources_and_followup_etc/test_sources.py
- static/js/components/AnalysisForm.jsx
- static/js/components/SourceAnalysisPage.jsx
- static/js/ducks/source.js
Add a linkable page for individual analyses on a given object. Accessed via `/source/source_name/analysis/analysis_id`.
> [Analysis Epic] Individual analysis page

- skyportal/handlers/api/source.py
- skyportal/tests/frontend/test_gcn.py
- static/js/components/GcnSelectionForm.jsx
This PR adds the number of detections as an option for the queries.
> Add number of detections as an option for the queries

- services/sn_analysis_service/supervisor.conf
Allow supervisord to control the sn fitter service.
> add SN fitter supervisor.conf

- static/js/components/GcnSelectionForm.jsx
This PR sets localizationName explicitly in GcnSelectionForm.
> Set localizationName explicitly in GcnSelectionForm

- doc/setup.md
add info for those with Mac M1/M2 AMD machines
> Update docs for Mac AMD (M1/M2) setup

- requirements.txt
- skyportal/handlers/api/webhook.py
- skyportal/tests/api/test_analysis.py
The webhook handler does not use a user or authenticated token. Revert this back, since the scoped session infrastructure throws errors.
> Revert webhook session

- skyportal/handlers/api/classification.py
- skyportal/handlers/api/taxonomy.py
This PR removes repeated taxonomies / classifications.
> Remove repeated taxonomies

- skyportal/handlers/api/allocation.py
This PR updates the allocation handler to the new syntax.
> Update allocation handler to new syntax

- skyportal/handlers/api/source.py
- skyportal/handlers/api/source_exists.py
This PR updates the source handler to the new syntax.
> Update source handler to new syntax

- skyportal/facility_apis/lco.py
This PR enables different observation modes for LCO requests.
> Enable different observation modes for LCO requests

- skyportal/handlers/api/group.py
- skyportal/tests/api/test_groups.py
- skyportal/tests/frontend/test_groups.py
This PR updates the group handler to new syntax.
> Update group handler to new syntax

- skyportal/handlers/api/group_admission_request.py
- skyportal/tests/api/test_group_admission_requests.py
This PR updates the group admission request handler to the new syntax.
> Move group_admission_request handler to new syntax

- skyportal/handlers/api/gcn.py
- skyportal/tests/api/test_gcn.py
- static/js/components/GcnEvents.jsx
- static/js/components/GcnEventsFilterForm.jsx
This PR enables filtering out GcnEvents with a specific tag.
> Filter out GcnEvents with a specific tag

- skyportal/handlers/api/spectrum.py
This PR adds unique() calls within spectrum to try to combat the repeated front-end instances.
> Add unique() everywhere in spectrum

- skyportal/handlers/api/photometry.py
This PR adds extra logging to photometry POST/PUSH.
> Add logging to photometry POST/PUSH

- static/js/components/GcnSelectionForm.jsx
- static/js/components/ObservationPlanRequestForm.jsx
This PR notes the skymap created time in the skymap display.
> Add note about the versions in the skymap display

- skyportal/handlers/api/photometry.py
This PR fixes the photometry tests broken by logging.
> Fix photometry tests broken by logging

- skyportal/tests/api/test_gcn.py
This PR adds retries to the gcn summary test.
> Retries for the gcn summary test

- skyportal/tests/flaky/test_analysis_flaky.py
- skyportal/tests/frontend/sources_and_followup_etc/test_sources.py
This PR adds retries for the analysis test, which is flaky.
> mark analysis test as flaky

- skyportal/tests/frontend/test_gcn.py
- skyportal/tests/frontend/test_reminders.py
- static/js/components/GcnEventPage.jsx
This PR removes the GcnEventPage sidebar if on mobile.
> Remove GcnEventPage sidebar if on mobile

- static/js/components/GroupSources.jsx
This PR adds the ability to download group sources.
> Add downloading for group sources

- static/js/components/GroupSources.jsx
This PR restricts the group sources on download.
> Restrict group sources on download

- skyportal/models/user_notification.py
- static/js/components/GcnTagsSelect.jsx
- static/js/components/NotificationPreferences.jsx
This PR adds the ability to filter notifications by GcnTags.
> Add GcnTags as an optional notification filtering option

- skyportal/handlers/api/source.py
- skyportal/tests/api/test_sources.py
This PR fixes the comment query to be done in the DB.
> Fix comments query

- skyportal/app_server.py
- skyportal/tests/api/test_gcn.py
- static/js/components/GcnEvents.jsx
- static/js/components/NewGcnEvent.jsx
- static/js/ducks/gcnEvent.js
This PR adds a GcnEvent upload page.
> GcnEvent upload page

- skyportal/handlers/api/source_groups.py
This PR uses the new syntax with source_groups.
> Use new syntax with source_groups

- services/gcn_service/gcn_service.py
- skyportal/handlers/api/gcn.py
This PR orders localizations by ingestion time.
> Order localizations by ingestion time

- static/js/components/ObservingRunPage.jsx
This PR adds observers to observing run page.
> Add observers to observing run page

- tools/data_loader.py
This PR allows retries on endpoints from data loader (to try to make the app loading more robust).
> Allow retries on endpoints from data loader

- skyportal/handlers/api/db_stats.py
This PR adds more db_stats for ease of reporting.
> Add more db_stats for ease of reporting

- skyportal/handlers/api/comment.py
This PR removes an error where the app falls over if an attachment with accents is uploaded in the name.
> Remove accents from character names in attachment strings

- data/db_demo.yaml
- data/instruments.yaml
This PR adds the Swift filters to demo data.
> Add Swift filters to demo data

- data/AMON.xml
- data/db_demo.yaml
- skyportal/utils/gcn.py
This PR adds neutrino tags to the ingester.
> Add neutrino tags

- skyportal/handlers/api/source.py
This PR adds a missing unique to the classifications query.
> Unique in classifications query

- skyportal/facility_apis/lco.py
This PR corrects the description of lunar distance in dropdown for LCO.
> Correct description of lunar distance in dropdown for LCO

- config.yaml.defaults
- doc/mma.md
- skyportal/facility_apis/lco.py
This PR adds the ability to get LCO images from archive.
> Add ability to get LCO images from archive

- static/js/components/Theme.jsx
This PR fixes the broken background color in dark mode.
> Fix broken dark mode

- skyportal/handlers/api/gcn.py
- skyportal/tests/api/test_gcn.py
- skyportal/utils/gcn.py
- static/js/components/NewGcnEvent.jsx
- static/js/ducks/gcnEvents.js
This PR allows for the creation of localizations with polygons.
> Create localizations with polygons

- skyportal/models/user_notification.py
- static/js/components/NotificationPreferences.jsx
- static/js/components/NotificationSettingsSelect.jsx
This PR enables notifications from completed analysis services.
> Add analysis services to notification list

- static/js/components/ThumbnailList.jsx
This PR adds thumbnail headers (to the images) to more accurately specify their origin.
> Add thumbnail headers

- skyportal/handlers/api/classification.py
- skyportal/tests/api/test_classifications.py
This PR enables the upload of multiple classifications.
> Upload multiple classifications at once

- doc/mma.md
- requirements.txt
- services/pdl_service/config.ini
- services/pdl_service/init.sh
- services/pdl_service/pdl_service.py
- services/pdl_service/supervisor.conf
This PR adds a service that enables query of the USGS PDL client for posting live earthquakes.
> PDL service

- config.yaml.defaults
- skyportal/app_server.py
- skyportal/handlers/api/earthquake.py
- skyportal/tests/api/test_earthquake.py
- static/js/actions.js
- static/js/components/CommentAttachmentPreview.jsx
- static/js/components/CommentList.jsx
- static/js/components/CompactCommentList.jsx
- static/js/components/EarthquakeInfo.jsx
- static/js/components/EarthquakeMap.jsx
- static/js/components/EarthquakePage.jsx
- static/js/components/EarthquakePredictionForm.jsx
- static/js/components/EarthquakePredictionLists.jsx
- static/js/components/EarthquakesFilterForm.jsx
- static/js/components/EarthquakesPage.jsx
- static/js/components/EarthquakesPageDesktop.jsx
- static/js/components/EarthquakesPageMobile.jsx
- static/js/components/NewEarthquake.jsx
- static/js/components/RegularCommentList.jsx
- static/js/ducks/earthquake.js
- static/js/ducks/earthquakeStatuses.js
This PR adds a map of earthquakes and a simple Earthquake page.
> Earthquake map

- skyportal/handlers/api/thumbnail.py
This PR refactor the thumbnail handler for simplifying posting external thumbnails.
> Refactor thumbnail handler

- static/js/components/CandidateList.jsx
- static/js/components/CandidatePlugins.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/SourcePlugins.jsx
This PR adds "plugins" for the source and candidate page to simplify extras for those pages (like in extensions).
> Add optional plugins for the source and candidate page

- static/js/components/ExecutedObservationsTable.jsx
This PR changes the observation page to remove button for saving a source if there is not an associated target name.
> Observation source button

- skyportal/utils/gcn.py
This PR adds GRB properties to the list.
> Add GRB property list

- services/pdl_service/pdl_service.py
This PR creates a directory for the pdl client if none exists.
> Create directory if missing

- skyportal/facility_apis/ztf.py
This PR keeps non-engineering time observations for ZTF.
> Non-engineering time observations for ZTF
