- doc/mma.md
- static/js/components/CandidateList.jsx
- static/js/components/ThumbnailList.jsx
This PR adds some documentation for GCN event ingestion.
> Add GCN event ingestion to docs

- skyportal/handlers/api/gcn.py
- skyportal/tests/api/test_gcn.py
- skyportal/tests/frontend/test_gcn.py
- static/js/components/GcnSummary.jsx
This PR makes some small changes to the number of sigfigs in the GCN summary.
> GCN Summary sigfigs

- skyportal/facility_apis/ztf.py
- skyportal/handlers/api/gcn.py
- skyportal/utils/gcn.py
- static/js/components/NewGcnEvent.jsx
This PR enables ingestion of skymaps from the front-end.
> Ingest skymap from the frontend

- skyportal/facility_apis/atlas.py
This PR adds more info returned for atlas queries.
> Add more logging for atlas

- skyportal/handlers/api/telescope.py
- skyportal/tests/api/test_telescope.py
This PR makes it possible to query telescopes based on latitude and longitude.
> Query telescopes based on latitude and longitude

- doc/advanced_usage.md
This PR adds further detail about posting taxonomies, addressing #3466.
> Update taxonomy documentation

- data/badsource.csv
- data/db_demo.yaml
- skyportal/plot.py
- static/js/components/Plot.jsx
Catch errors fetching plot data and display an error message to the user.
Partially addresses #3163
@mcoughlin @guynir42 please advise if there should be any changes to the photometry plot code so that the badsource data does not cause an exception to be thrown
> Catch photometry plot errors

- tools/skyportal_query_examples.ipynb
This PR adds a Jupyter notebook showing how to make API requests.
> Jupyter notebook showing API request

- tools/nginx_ip_and_requests.py
This PR adds a plot for the bytes sent.
> Include both request length and bytes sent plots

- services/pdl_service/pdl_service.py
This PR fixes the PDL service path in the script.
> PDL service path

- skyportal/plot.py
- static/js/plotjs/foldphase.js
- static/js/plotjs/post_annotation.js
This PR adds light curve smoothing (analogous to what is available for spectroscopy) and annotation posting from periods.
> Smoothing and annotations from periods

- static/js/components/NewShift.jsx
This PR makes it possible to add shifts in either local or UTC time.
> Add shifts in either local or UTC time

- skyportal/handlers/api/catalog_services.py
This PR adds more logging for catalog queries.
> Add more logging for catalog queries

- static/js/components/SurveyLinkList.jsx
This PR fixes the broken PTF link.
> Fix broken PTF link

- skyportal/handlers/api/annotation_services.py
- static/js/components/SourceAnnotationButtons.jsx
- static/js/ducks/source.js
This PR adds Galex as an annotation option.
> Add Galex as annotation option

- skyportal/tests/frontend/test_reminders.py
This PR clears the reminder form time.
> Try first clearing the reminder form time

- skyportal/handlers/api/db_stats.py
This PR adds more DB statistics (comments, annotations, etc.).
> Add more DB statistics

- skyportal/plot.py
- static/js/plotjs/foldphase.js
This PR enables one to turn smoothing on and off on light curves.
> Turn on and off smoothing

- requirements.txt
- skyportal/handlers/api/comment.py
- skyportal/utils/fits_display.py
- static/js/components/CommentAttachmentPreview.jsx
This PR enables fits file display in comment preview.
> Display fits file in comment preview

- doc/extensions.md
- doc/index.rst
This PR adds examples for introducing extensions.
> Add examples for introducing extensions

- skyportal/app_server.py
- skyportal/handlers/api/internal/token.py
- skyportal/tests/api/test_token.py
This PR adds ability to have multiple tokens posted if admin does the posting.
> Add more token power

- data/instruments.yaml
- data/telescopes.yaml
Add WINTER telescope and WNTR and SUMMER cameras to skyportal
> Winter telescope and instruments

- skyportal/handlers/api/analysis.py
- skyportal/tests/api/test_db_stats.py
- skyportal/tests/frontend/test_db_stats.py
This PR fixes a bug in the generic analysis serialization for numpy arrays, serializing them as lists.
> Serialize numpy array as list

- skyportal/facility_apis/sedm.py
- skyportal/handlers/api/annotation.py
- skyportal/handlers/api/annotation_services.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/facility_listener.py
- skyportal/handlers/api/internal/annotations_info.py
- skyportal/handlers/api/internal/ephemeris.py
- skyportal/handlers/api/internal/notifications.py
- skyportal/handlers/api/internal/profile.py
- skyportal/handlers/api/internal/recent_gcn_events.py
- skyportal/handlers/api/internal/recent_sources.py
- skyportal/handlers/api/internal/robotic_instruments.py
- skyportal/handlers/api/internal/source_counts.py
- skyportal/handlers/api/internal/source_views.py
- skyportal/handlers/api/internal/standards.py
- skyportal/handlers/api/observation.py
- skyportal/handlers/api/observation_plan.py
- skyportal/handlers/api/phot_stat.py
- skyportal/handlers/api/source_groups.py
- skyportal/handlers/api/spectrum.py
- skyportal/models/user_token.py
- skyportal/tests/utils/test_ztf_gaia_backup.py
- skyportal/utils/offset.py
This PR moves more (mostly internal) handlers to the Sqlalchemy 2.0 syntax.
> Sqlalchemy 2.0 syntax

- static/js/components/AnnotationsTable.jsx
- static/js/ducks/source.js
- static/js/plotjs/foldphase.js
This PR adds delete button for annotations and fixes errorbars in periodic plot.
> Annotation delete button

- skyportal/handlers/api/source.py
- skyportal/tests/api/test_sources.py
This PR reject sources in query based on object ID.
> Reject sources in query based on object ID

- skyportal/handlers/api/observation.py
- static/js/components/ExecutedObservationsTable.jsx
- static/js/components/ObservationFilterForm.jsx
- static/js/components/ObservationPage.jsx
- static/js/components/QueuedObservationsTable.jsx
This table adds basic observation table sorting / filtering.
> Observation table sorting/filtering

- skyportal/models/user_notification.py
- static/js/components/GcnPropertiesSelect.jsx
- static/js/components/NotificationPreferences.jsx
This PR adds GCN Properties to notifiication options.
> Gcn properties in notification options

- skyportal/handlers/api/catalog_services.py
- skyportal/handlers/api/thumbnail.py
This PR updates the  post_alert usage
> Update post_alert usage

- config.yaml.defaults
- data/db_demo.yaml
- requirements.txt
- services/ngsf_analysis_service/app.py
- services/ngsf_analysis_service/parameters.json
- services/ngsf_analysis_service/supervisor.conf
This PR adds a basic spectra analysis relying on chi^2 minimization (similar to sncosmo for light curves).
> basic spectra analysis

- static/js/components/Filter.jsx
This PR passes groups to FilterPlugins.
> Pass group to FilterPlugins

- skyportal/app_server.py
This PR updates the source route to fix incorrect comment route returned.
> Update source route

- skyportal/plot.py
This PR fixes the plotting in case of multiple instruments.
> Fix plotting in case of multiple instruments

- static/js/components/FollowupRequestPage.jsx
- static/js/components/FollowupRequestSelectionForm.jsx
This PR simplifies the selection form process by passing form parameters from the original page.
> Simplify selection form

- services/ngsf_analysis_service/app.py
- skyportal/handlers/api/analysis.py
- static/js/components/AnalysisList.jsx
This PR adds an option to download analysis results file (and exposes that from the NGSF download).
> Add option to download analysis results file

- data/db_demo.yaml
- skyportal/handlers/api/allocation.py
This PR adds a plot of moon phase to allocation summary.
> Add plot of moon phase to allocation summary

- skyportal/models/obj.py
This PR fixes the LS9 cutout link.
> fix LS9 cutout link

- skyportal/handlers/api/gcn.py
- skyportal/tests/api/test_gcn.py
- skyportal/tests/frontend/test_gcn.py
- static/js/components/ShiftCalendar.jsx
- static/js/components/ShiftManagement.jsx
This PR adds affiliations to GCN and shifts.
> Add affiliations to GCN and shifts

- skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py
This PR makes a front-end test more robust with scrolling.
> Try to make test more robust

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/observation_plan.py
- static/js/components/ObservationPlanRequestForm.jsx
This PR adds a basic observability plot for the GCN events.
> Add observability plot

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/source.py
- skyportal/tests/frontend/test_scanning_page.py
- static/js/components/CandidateList.jsx
- static/js/components/SaveCandidateButton.jsx
- static/js/components/ShiftPage.jsx
- static/js/ducks/candidates.js
This PR fixes the check for whether something is already saved or not, and adds some quality of life improvements to the scanning page: a dedicated button to retrieve PS1 thumbnails and a notification upon source saving.
> object is_source 

- skyportal/utils/notifications.py
If a source has no photstats (no photometry at all), the method that creates the content of the email and slack notifications encounters an error. Therefore, no notification can be sent.
This PR addresses that issue.
> Source notifications (email/slack): Issue when photstats are missing

- requirements.txt
This PR pins dask / distributed to 2022.10.2.
> dask / distributed 2022.10.2

- static/js/components/SaveCandidateButton.jsx
This PR reports the groups saved to on the classification page.
> Saved groups

- config.yaml.defaults
- requirements.txt
- skyportal/handlers/api/source.py
- skyportal/models/obj.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
This PR adds E(B-V) to source page.
> E(B-V) on source page

- static/js/components/NewDefaultObservationPlan.jsx
This PR changes the web form plan_name to default_plan_name.
> web form default_plan_name

- requirements.txt
- skyportal/models/obj.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
This PR adds a try except for dustmap download.
> Dustmap download try-except

- data/ZTF_Square_Region.reg
- data/db_demo.yaml
- skyportal/app_server.py
- skyportal/facility_apis/observation_plan.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/observation_plan.py
- static/js/actions.js
- static/js/components/ObservationPlanRequestForm.jsx
- static/js/components/ObservationPlanRequestLists.jsx
- static/js/ducks/observationPlanNames.js
- static/js/ducks/observationPlans.js
This PR adds checks and error handling for observation plans and names.
> Observation plan error handling

- skyportal/handlers/api/photometry.py
- static/js/components/PhotometryTable.jsx
- static/js/ducks/photometry.js
This PR adds simple delete button for photometry.
> Photometry delete button

- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/UpdateSourceCoordinates.jsx
This PR adds a form to update source coordinates.
> Source coordinates form

- skyportal/handlers/api/observation_plan.py
- skyportal/handlers/api/source.py
- static/js/components/AddRunFromObservationPlanPage.jsx
- static/js/components/ObservationPlanRequestLists.jsx
- static/js/ducks/gcnEvent.js
This PR creates a dedicated dialog box for observing run creation.
> Observing run dialog box

- skyportal/handlers/api/source.py
This PR adds check for power to save source to group.
> Group save power

- .pre-commit-config.yaml
- skyportal/handlers/api/source.py
This PR checks for  is_admin in user when posting source.
> check for is_admin in user

- static/js/components/CandidateList.jsx
This PR adds more options for number of candidates to display.
> Number of candidates to display

- skyportal/handlers/api/instrument.py
This PR makes field tiles replaceable.
> Replace field tiles

- skyportal/plot.py
> [3669] add padding to bottom of plot height

- skyportal/utils/offset.py
This PR adds more error handling on finding charts.
> Finding chart error handling

- skyportal/handlers/api/allocation.py
This PR sets to none any non-rising / non-setting sources.
> Non-rising / non-setting sources

- skyportal/handlers/api/classification.py
- skyportal/handlers/api/source_groups.py
- skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py
- static/js/components/CandidateList.jsx
- static/js/components/CustomDataTable.jsx
This PR tries to use React.memo to specify re-render criteria.
> Limiting candidate re-render with memo

- skyportal/handlers/api/source.py
We modify source.py and replace order_by = none by saved_at desc.
> Task 1 Sort by default date saved most recent

- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
This PR fixes the auto-input of the scanning profile ordering.
> Scanning profiles ordering

- skyportal/tests/frontend/sources_and_followup_etc/test_sources.py
- skyportal/tests/frontend/test_scanning_page.py
- static/js/components/CandidateList.jsx
- static/js/components/FilterCandidateList.jsx
This PR adds a spinner for the candidate table when rendering.
> Candidate table render

- Dockerfile
This PR adds the dustmap folder explicitly to docker file.
> Dustmap Docker

- requirements.txt
- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/observation_plan.py
- static/js/components/ObservationPlanRequestForm.jsx
This PR creates a downloadable telescope observability map.
> Telescope observability map

- static/js/components/NewSource.jsx
This PR checks for groups when specifying new source.
> Groups for new source

- skyportal/plot.py
- static/js/components/AssignmentForm.jsx
- static/js/components/NewSource.jsx
This PR tries to fix the assignment form.
> Assignment form

- static/js/components/SourceTableFilterForm.jsx
This PR fixes the source name check in source table filtering.
> Source name filtering

- static/js/components/CandidateList.jsx
- static/js/components/CustomDataTable.jsx
- static/js/components/ScanningPageCandidateAnnotations.jsx
This PR fixes the annotation table size so it doesn't dominate scanning page if long annotations.
> Annotation table size

- skyportal/utils/gcn.py
This PR adds sun occultation for Fermi sources.
> Sun occultation

- static/js/components/ShowClassification.jsx
This PR adds a basic trash icon for classifications.
> Delete classification icons

- doc/adding_features.md
I'm supervising a team of 10 students that started working for GRANDMA a few weeks ago. For now, they are getting started with Linux, installing SkyPortal, and more recently following the Adding New Features tutorial from the docs.
However, it came to my attention that:
- Some instructions are less detailed than others (it is only specified what to do, without giving the lines of code as clearly as in other sections). This imbalance leads to simply missing some instructions, or ending up stuck right before the last step.
-  Some code snippets are incomplete or incorrect (the file to edit does not exist, or imports are missing, or older syntaxes that new features **should not use** are given).
- The order in which some concepts are presented feels unnatural (this one is my personal …
> Updating and correcting the Adding New Features Tutorial (Docs)

- skyportal/handlers/api/gcn.py
- skyportal/models/localization.py
- static/js/components/GcnEventPage.jsx
- static/js/components/GcnLocalizationsTable.jsx
This PR adds localization properties to the GcnEventPage.
> Render localization properties

- skyportal/handlers/api/gcn.py
This PR removes calculation for center in case of multiple events.
> No center for multiple events

- doc/dev.md
- doc/query_analysis.md
- skyportal/onboarding.py
I am looking for the last places where we still use the old sqlalchemy methods for interacting with the session. 
There are still a lot of this code in the testing infrastructure but that would be very big refactor. 
For now this just wraps up loose ends.
> Fix a couple more DBSession instances

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/source.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
This PR adds an observability plot for an individual source.
> Source observability plot

- skyportal/handlers/api/user.py
- static/js/components/UpdateUsername.jsx
- static/js/components/UserManagement.jsx
This PR allows for admins to update usernames.
> Update username form

- skyportal/models/user_notification.py
- static/js/components/NotificationPreferences.jsx
- static/js/components/NotificationSettingsSelect.jsx
This PR adds notifications for allocation admins.
> Notify allocation admins

- .github/workflows/test_api_and_frontend.yaml
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/instrument.py
- static/js/components/CommentEntry.jsx
- static/js/instrumentTrie.js
This PR makes comments based on instruments possible.
> Instrument comments

- skyportal/handlers/api/allocation.py
- static/js/components/AllocationPage.jsx
- static/js/components/ModifyAllocation.jsx
- static/js/ducks/allocation.js
This PR enables allocation modification from the front-end
> Modify allocation

- skyportal/onboarding.py
The use of context managers in the onboarding process seems to fail because of user being created and then closing the session.
> Fix onboarding sessions

- skyportal/handlers/api/followup_request.py
A bug prevents other features (such as the triggering of a default obs plan based on a new classification) from being triggered correctly because the `source_filter` column receives a string instead of a dict when the DefaultFollowupRequest is created. 
These few lines ensure that it works as intended by converting the string input to dict if necessary. Of course, if the string is not in the correct format in the first place we use self.error to notify whoever submitted the DefaultFollowupRequest that it needs to be changed.
> DefaultFollowupRequestHandler Issue: Str instead of Dict (JSONB)

- services/ngsf_analysis_service/app.py
This PR fixes upload issue if requesting fixed redshift.
> NGSF redshift request

- skyportal/handlers/api/taxonomy.py
- skyportal/models/taxonomy.py
- skyportal/tests/api/test_taxonomy.py
- static/js/components/ModifyTaxonomy.jsx
- static/js/components/TaxonomyPage.jsx
- static/js/ducks/taxonomies.js
This PR enables modifications to taxonomies.
> Taxonomy modifications

- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/telescope.py
- skyportal/model_util.py
- static/js/components/InstrumentPage.jsx
- static/js/components/TelescopeInfo.jsx
- static/js/components/TelescopePageDesktop.jsx
- static/js/components/TelescopePageMobile.jsx
This PR adds specific telescope / instrument interaction permissions.
> Telescope / instrument permissions

- skyportal/handlers/api/telescope.py
This PR allows partial puts for telescopes.
> Telescope puts

- services/gcn_service/gcn_service.py
- skyportal/facility_apis/observation_plan.py
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/observation_plan.py
This PR moves observation plans inside gcn event ingestion.
> default observation plans 

- data/db_demo.yaml
- skyportal/facility_apis/sedmv2.py
- skyportal/handlers/api/followup_request.py
This PR adds ToO's to observation plan.
> Observation plan ToO

- static/js/components/ExecutedObservationsTable.jsx
- static/js/components/ObservationFilterForm.jsx
- static/js/components/ObservationPage.jsx
- static/js/components/QueuedObservationsTable.jsx
This PR enables downloading the full observation table.
> download full observation table

- skyportal/handlers/api/user.py
- static/js/components/UpdateUserParameter.jsx
- static/js/components/UserManagement.jsx
This PR enables name / email update from front-end.
> Name / email update

- skyportal/tests/flaky/test_gcnevents_flaky.py
- skyportal/tests/frontend/test_reminders.py
- static/js/components/ExecutedObservationsTable.jsx
- static/js/components/QueuedObservationsTable.jsx
- static/js/components/Reminders.jsx
This PR adds download of RA and dec for observations.
> Observation RA and dec

- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/internal/plot.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/sources_confirmed_in_gcn.py
- skyportal/plot.py
- static/js/components/GroupSources.jsx
This PR makes certain functions in source.py and plot.py asynchronous to address timeout issues. The modified code currently raises the following errors locally:
I welcome comments on which additional functions to make asynchronous and how to avoid the above errors.
> Make source and plot handlers async

- skyportal/models/user_notification.py
This PR adds notifications for requests to active shifters.
> Notifications to active shifters

- skyportal/facility_apis/ztf.py
This PR fixes the ZTF filter mapping.
> ZTF filter mapping

- skyportal/handlers/api/photometry.py
- static/js/components/NewPhotometry.jsx
This PR allows the photometry form to post upperlimits.
> Photometry form upperlimits

- static/js/components/InstrumentPage.jsx
- static/js/components/InstrumentTable.jsx
- static/js/ducks/instruments.js
Hi,
This PR improves the Instruments page by adding a MUI Datatable with some additional columns (instruments type, band, telescopes latitude and longitude).
For now there is no filter functionality but there is a search bar searching by instrument name. However, it only finds exact matching results (we have to include uppercase characters in the search text and write the entire name).
Also, it displays all the rows in one page even though the rowsPerPage is set on 10.
We are currently trying to fix these small issues, but the main part is working.
Thanks for your feedback ! 🚀
> Instruments page improvement

- skyportal/models/user_notification.py
- static/js/components/NotificationSettingsSelect.jsx
Allows contact through WhatsApp.
We used Twilio to send the alerts.
The possibility to toggle said notifications in the user parameters was also added.
> WhatsApp alerts

- skyportal/handlers/api/catalog_services.py
This PR adds more logging for the catalog query.
> Catalog query logging

- requirements.txt
- skyportal/facility_apis/observation_plan.py
- skyportal/tests/api/test_observation_plan.py
This PR updates gwemopt to 0.0.77.
> gwemopt 0.0.77

- static/js/components/SourceTable.jsx
This PR adds ability to up or downvote all classifications.
> Vote all classifications

- static/js/components/SourceTable.jsx
@Theodlz @mcoughlin 
link to issue : https://github.com/skyportal/skyportal/issues/3653 
Signed-off-by: Adiman007 <adiman.bonnefoy@gmail.com>
> fix the sorting reset bug Issue#3653

- skyportal/handlers/api/catalog_services.py
- skyportal/handlers/api/gcn.py
- skyportal/tests/api/test_gcn.py
- skyportal/tests/flaky/test_download_flaky.py
- static/js/components/GcnSummary.jsx
- static/js/components/LocalizationPlot.jsx
This PR adds localization name and number of detections to GCN summary front-end.
> GCN summary improvements

- skyportal/facility_apis/observation_plan.py
This PR adds logging for observation plan creation.
> Observation plan creation logging

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/observation_plan.py
- skyportal/models/schema.py
This PR enables upload of manual observation plans.
> Manual observation plan

- static/js/components/UploadSpectrum.jsx
This PR adds validation that you have uploaded a spectrum file.
> Spectrum file is required for upload

- skyportal/facility_apis/observation_plan.py
- skyportal/tests/api/test_observation_plan.py
- skyportal/tests/flaky/test_download_flaky.py
This PR adds a checkbox for galactic plane exclusion.
> Galactic plane exclusion

- data/db_demo.yaml
- static/js/components/TaxonomyPage.jsx
- static/js/components/TaxonomyTable.jsx
Hi,
This PR modifies the taxonomies page by adding a MUI Datatable to display the data (including the taxonomy ID)
Thanks for your feedback ! 🚀
@mcoughlin
> taxonomies page improvement

- skyportal/handlers/api/classification.py
This PR adds an option to turn off label when adding classification.
> Label when adding classification

- skyportal/facility_apis/observation_plan.py
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/observation_plan.py
- static/js/ducks/recentGcnEvents.js
This PR adds a retry for observation plan creation.
> Observation plan retries

- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/observation_plan.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/swift.py
- skyportal/facility_apis/ztf.py
This PR explicitly closes postgresql sessions.
> explicitly close postgresql sessions

- requirements.txt
This PR pins the astroscrappy requirement.
> astroscrappy

- skyportal/facility_apis/observation_plan.py
This PR includes a rollback if the plan fails.
> rollback if plan fails

- skyportal/plot.py
This PR fixes bug as groups are already dictionaries.
> Plotting groups

- skyportal/tests/api/test_annotation_services.py
- skyportal/tests/api/test_spatial_catalog.py
- skyportal/tests/frontend/sources_and_followup_etc/test_observing_planner.py
- skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py
- skyportal/tests/frontend/sources_and_followup_etc/test_sources.py
- skyportal/tests/frontend/test_bokeh_plots_frontend.py
- skyportal/tests/frontend/test_notifications.py
- skyportal/tests/frontend/test_quick_search.py
- skyportal/tests/tools/test_radial_query.py
Some of our tests are flaky on GA, even though they pass locally. 
This PR is an exploration of this conundrum.
> Add flaky rerun decorators

- static/js/components/EarthquakePage.jsx
This PR adds an extra check on ID to avoid load issues.
> eq page question mark

- skyportal/models/user_notification.py
This PR fixes GCN notifications such that they do not require notices.
> GCN notifications should not require notices

- requirements.txt
- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/lco.py
- skyportal/facility_apis/observation_plan.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/swift.py
- skyportal/facility_apis/ztf.py
- skyportal/handlers/api/analysis.py
- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/catalog_services.py
- skyportal/handlers/api/db_stats.py
- skyportal/handlers/api/earthquake.py
- skyportal/handlers/api/galaxy.py
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/gcn_tach.py
- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/observation.py
- skyportal/handlers/api/observation_plan.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/recurring_api.py
- skyportal/handlers/api/spatial_catalog.py
- skyportal/handlers/api/webhook.py
- skyportal/model_util.py
- skyportal/models/photometry.py
This PR pairs with https://github.com/cesium-ml/baselayer/pull/349 to upgrade to SQLAlchemy 2.0
> Upgrade to SQLAlchemy 2.0

- skyportal/handlers/api/instrument.py
This PR fixes the instrument field column  deferral.
> Instrument column deferral

- data/db_demo.yaml
This PR adds DECam instrumental sensitivity.
> DECam instrumental sensitivity

- skyportal/facility_apis/observation_plan.py
- skyportal/handlers/api/gcn.py
This PR makes automated plan finish at end of next night.
> End of automated plan end of night

- requirements.txt
This PR updates to dask 2023.1.1.
> Update to dask 2023.1.1

- skyportal/handlers/api/source.py
- skyportal/handlers/api/spectrum.py
- static/js/components/AnnotationsTable.jsx
- static/js/ducks/spectra.js
This PR fixes delete button for spectrum annotations.
> Delete spectrum annotations

- skyportal/handlers/api/source.py
- static/js/components/NewSource.jsx
This PR prevents spaces in source names, which break SP.
> No spaces in names

- config.yaml.defaults
- skyportal/handlers/api/comment.py
This PR sets the comments to be in persistent folder.
> persist comments

- skyportal/handlers/api/source.py
This PR tries to speed-up classifications query be querying separately.
> query classifications separately

- services/recurring_apis/recurring_apis.py
- services/reminders/reminders.py
This PR specified host explicitly in recurring API and reminder.
> Set host for recurring API and reminder

- skyportal/handlers/api/comment.py
- static/js/components/CommentList.jsx
This PR specifies associated resource in comment list, such that the correct function can be called for delete.
> Associated resource in comment list

- static/js/components/ModifyInstrument.jsx
- static/js/components/NewGcnEvent.jsx
This PR checks that the GCN Event creation variables are defined in front-end.
> GCN Event upload

- skyportal/handlers/api/gcn.py
- static/js/components/NewGcnEvent.jsx
- static/js/components/SurveyEfficiencyForm.jsx
This PR checks for survey efficiency variables.
> Survey efficiency form

- services/recurring_apis/recurring_apis.py
- skyportal/handlers/api/spectrum.py
- static/js/components/FindingChart.jsx
This PR fixes the finding chart page form.
> Finding chart page form

- skyportal/handlers/api/photometry.py
- skyportal/plot.py
This PR serializes photometry to return groups and annotations only if you need them.
> Serialize photometry with groups and annotations optional

- skyportal/models/user_notification.py
This PR checks for notice tied to GCN event when doing notifications.
> GCN notice notification

- services/reminders/reminders.py
- skyportal/handlers/api/instrument.py
- skyportal/tests/api/test_recurring_api.py
- skyportal/tests/api/test_reminders.py
- static/js/components/GcnEvents.jsx
This PR updates field tile delete to 2.0 style.
> InstrumentFieldTile delete

- skyportal/tests/frontend/test_reminders.py
This PR extends delay on reminders test.
> reminders test delay

- skyportal/facility_apis/observation_plan.py
This PR closes the observation plan session outside while loop.
> observation plan session

- skyportal/tests/frontend/sources_and_followup_etc/test_source_list.py
- static/js/components/NewInstrument.jsx
This PR checks for all variables being defined in instrument file uploads.
> Defined variables in instrument upload

- static/js/components/NewSource.jsx
This PR requires a user to choose a group when make a new source.
> When making a new source, choose a group

- skyportal/facility_apis/observation_plan.py
- skyportal/handlers/api/instrument.py
- skyportal/tests/api/test_observation_plan.py
- skyportal/tests/api/test_spatial_catalog.py
This PR updates how galaxy fields are created.
> Galaxy field creation

- static/js/components/SourceTableFilterForm.jsx
- static/js/components/SpatialCatalogPage.jsx
- static/js/components/SpatialCatalogTable.jsx
This PR enables spatial catalog source filtering from the front-end.
> Spatial catalog source filtering

- skyportal/handlers/api/photometry.py
This PR adds option to return photometry created_at to help study double photometry.
> Photometry created_at

- skyportal/handlers/api/candidate.py
- skyportal/tests/api/test_candidates.py
This PR adds a filter on photometric annotations for candidates.
> Candidates photometric annotations filter

- skyportal/handlers/api/gcn.py
- static/js/components/GcnSummary.jsx
- static/js/ducks/gcnEvent.js
This code has been made by @jolyanem with the help of @celiune (and me). 
Now we are able to save new modification of a summary text.
> Keep History of Gcn Summaries

- static/js/components/FindingChart.jsx
This PR fixes the finder chart form numerical inputs.
> Finder chart form

- static/js/components/RecentSources.jsx
This PR adds a fix for missing sources in search bar.
> Source search bar

- static/js/components/RecentSources.jsx
This PR checks if the source list is not null.
> recent sources not null

- skyportal/handlers/api/internal/token.py
- static/js/components/TokenList.jsx
- static/js/components/UpdateTokenACLs.jsx
- static/js/ducks/profile.js
> Edit token acls

- requirements.txt
- skyportal/handlers/api/analysis.py
This PR uses json.dumps to be sure result is in sensible download format.
> json dumps the analysis results

- requirements.txt
- skyportal/handlers/api/gcn.py
- skyportal/utils/gcn.py
This PR pins healpix-alchemy to 1.0.2
> healpix-alchemy 1.0.2

- requirements.txt
This PR updates gwemopt to 0.0.80.
> gwemopt 0.0.80

- skyportal/plot.py
- static/js/components/AnalysisList.jsx
This PR adds a time column to the analysis list.
> Analysis list time

- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
This PR fixes link to duplicate source page.
> Duplicate source page link

- requirements.txt
- skyportal/utils/gcn.py
This PR updates mocpy to 0.12.3.
> mocpy 0.12.3

- skyportal/handlers/api/source.py
- skyportal/tests/api/test_analysis.py
This PR returns analyses upon request to a source.
> Source analyses

- requirements.txt
This PR pins a new version of pysedm, which allows us to pin newer versions of iminuit and shapely
> pysedm update

- doc/analysis.md
> Update documentation for creating and using summaries & AI Summarization

- services/openai_analysis_service/app.py
- services/openai_analysis_service/supervisor.conf
Add the services needed to wrap ChatGPT for summarization and embeddings. See #4014
> Add openai analysis service

- Dockerfile
This PR sets the sncosmo cache to be in persistentdata.
> sncosmo cache

- static/js/components/NewSource.jsx
- static/js/units.js
This PR allows for a new source with HH:MM:SS and DD:MM:SS.
> New source with HH:MM:SS and DD:MM:SS

- skyportal/handlers/api/followup_request.py
This PR vectorizes the custom constraint functions we wrote for astroplan (ToOs, Hour Angle).
> Vectorize astroplan constraint functions

- package.json
This PR updates webpack to 5.76.0. See https://github.com/skyportal/skyportal/security/dependabot/8.
> Webpack 5.76.0

- services/gcn_service/gcn_service.py
- skyportal/facility_apis/observation_plan.py
- skyportal/handlers/api/gcn.py
- skyportal/model_util.py
- skyportal/tests/api/test_gcn.py
This PR tries to divide each step of a gcnevent ingestion (from XML), and performs the Localization creation a little earlier hoping to avoid an error noticed in prod.
> Gcn Events: Attempt to reduce skymap ingestion flakiness

- data/db_demo.yaml
- static/js/components/FollowupRequestPage.jsx
- static/js/components/FollowupRequestSelectionForm.jsx
This PR moves the instrument selection into follow-up request page form.
> Follow-up request form

- config.yaml.defaults
- skyportal/app_server.py
- skyportal/handlers/api/config_handler.py
- skyportal/handlers/api/gcn.py
- skyportal/models/schema.py
- static/js/components/AddGcnTag.jsx
- static/js/components/GcnTags.jsx
- static/js/components/RecentGcnEvents.jsx
- static/js/ducks/gcnTags.js
This PR makes it possible to add GCN tags.
> Add GCN Tags

- static/js/ducks/source.js
This PR adds option to only check source name when making a new source.
> Check source name only

- static/js/components/FollowupRequestForm.jsx
- static/js/components/NewAPIObservation.jsx
- static/js/components/NewAPIQueuedObservation.jsx
- static/js/components/NewDefaultFollowupRequest.jsx
- static/js/components/NewDefaultObservationPlan.jsx
- static/js/components/ObservationPlanRequestForm.jsx
- static/js/components/ObservationPlanRequestLists.jsx
- static/js/components/QueueAPIDisplay.jsx
- static/js/ducks/instruments.js
Right now, the normal instrument forms are showing in the obsplan form, not the instrument obsplan forms.
> Bugfix: Incorrect instrument form type showing on GCN Page

- services/gcn_service/gcn_service.py
- services/recurring_apis/recurring_apis.py
- services/reminders/reminders.py
Due to how the difference in url to access the app between dev and prod (not ports to specify in prod), we didn't catch an error that caused some microservices to never run in prod 😓. This PR hopefully fixes that.
> Bugfix: Microservices not loaded in production

- skyportal/handlers/api/followup_request.py
This PR fixes a bug where status updates on followup_requests did not return success.
> Status updates should also return success

- data/db_demo.yaml
- skyportal/facility_apis/sedmv2.py
This PR sets SEDMv2 to only allow for one request at a time.
> SEDMv2: one request at a time

- skyportal/tests/frontend/test_gcn.py
- static/js/components/CommentList.jsx
- static/js/components/FollowupRequestLists.jsx
- static/js/components/GcnEventPage.jsx
- static/js/components/GcnSelectionForm.jsx
- static/js/components/GcnTags.jsx
- static/js/components/LocalizationPlot.jsx
- static/js/components/ObservationPlanRequestForm.jsx
This PR lays the foundations of what the GCN Event page should look like to make it more user friendly. Other PR's will follow:
- Desktop adaptative (easy, using MUI grid breakpoints)
- Mobile version (harder)
> Better GCN Page (Desktop fullscreen only)

- static/js/components/GcnEventPage.jsx
- static/js/components/GcnSelectionForm.jsx
- static/js/components/ObservationPlanRequestForm.jsx
This PR makes most of the GCN event page responsive, except the list of observation plans which needs a rework even in its non responsive version.
> GCN Event page: Responsive

- skyportal/app_server.py
- skyportal/handlers/api/gcn.py
- static/js/ducks/gcnTags.js
This PR simplifies api paths for GCN tags.
> GCN tag api 

- skyportal/facility_apis/ztf.py
This PR fixes a repeated call to observation ingestion, it should only be async.
> Observation ingestion async

- requirements.txt
- skyportal/handlers/api/analysis.py
- skyportal/handlers/api/group.py
- skyportal/handlers/api/user_obj_list.py
This PR upgrades apispec to 4.7.1.
> apispec 4.7.1

- Makefile
- requirements.txt
- skyportal/handlers/api/classification.py
- tools/openapi/requirements.txt
This PR fixes a missing type in the docstring.
> Missing type in classification docstring

- skyportal/handlers/api/shift.py
This PR lowers the permissions threshold for signing up for shifts.
> Shift user permissions

- skyportal/handlers/api/analysis.py
This PR checks if an analysis service is found before retrieving info about it.
> Check if analysis service exists

- skyportal/handlers/api/candidate.py
- static/js/components/FilterCandidateList.jsx
This PR adds the same kind of filtering found on the sources list to filter candidate by: event, localization, cumulative probability. But also filtering them by: first detection date after, last detection date before, and min number of detections.
> Candidate Scanning: GCN-based filtering

- services/facility_queue/facility_queue.py
This PR adds further logging in the facility queue. If you have any way to improve this queue based on the others, please do so @Theodlz.
> Facility queue logging

- services/openai_analysis_service/app.py
- skyportal/handlers/api/analysis.py
- skyportal/handlers/api/source.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/SourceTable.jsx
- static/js/ducks/sources.js
This PR fixes api_key being popped out never to return.
> deepcopy config

- skyportal/handlers/api/source.py
- skyportal/handlers/api/source_exists.py
This PR clarifies duplication for objects and sources.
> Object / source duplication

- static/js/components/CandidateList.jsx
- static/js/components/DisplayPhotStats.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/SourceTable.jsx
- static/js/ducks/source.js
This PR makes (optional) display of photometry statistics.
> Display photometry stats optionally

- skyportal/handlers/api/source_exists.py
This PR returns object IDs in source_exists API.
> source_exists object IDs

- skyportal/handlers/api/allocation.py
- skyportal/utils/gcn.py
- static/js/components/AllocationPage.jsx
- static/js/components/ConfirmSourceInGCN.jsx
- static/js/components/ModifyAllocation.jsx
- static/js/components/NewShift.jsx
- static/js/components/ShiftManagement.jsx
This PR addresses 3 issues:
- When uploading a fits file with special characters in its name (like the comma in LVC skymaps), you would end up generating and storing the localization with an odd name that would break the handler to get a localization).
- When creating weekly shifts, if running skyportal locally all is fine but it seems that in production timezones issues arise. This PR should address that.
- When modifying allocations, the current values wouldn't be loaded in the form. Therefore the user had to re-add everything by hand and would risk modifying some values unintentionally.
> Several frontend improvements and bugfixes

- static/js/components/GcnEventsFilterForm.jsx
This PR solves a bug introduces in another PR concerning the GCN properties filtering.
> Gcn filtering bugfix

- skyportal/handlers/api/gcn.py
This PR tries to improve tag query performance by following classification style.
> Rejection tag query performance

- skyportal/facility_apis/observation_plan.py
- skyportal/handlers/api/instrument.py
This PR adds in some missing optional gwemopt options, including RA slicing.
> Optional gwemopt options

- services/notification_queue/notification_queue.py
- skyportal/email_utils.py
- skyportal/facility_apis/observation_plan.py
This PR enables sending observation plans by slack and email.
> Send observation plan by slack and email

- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/observation_plan.py
- skyportal/tests/api/test_gcn.py
- skyportal/tests/api/test_observation_plan.py
This PR adds query parameters for ObservationPlanRequests.
> ObservationPlanRequest query parameters

- skyportal/facility_apis/generic.py
- static/js/components/EditFollowupRequestDialog.jsx
This PR adds email/slack request when making follow-up requests.
> Follow-up requests to email/slack

- skyportal/handlers/api/instrument.py
This PR allows for instrument column uploads.
> Instrument column uploads

- skyportal/handlers/api/mmadetector.py
- skyportal/handlers/api/shift.py
- skyportal/tests/api/test_shifts.py
- static/js/components/ShiftManagement.jsx
- static/js/components/UpdateShift.jsx
- static/js/ducks/shift.js
This PR makes it possible to edit shifts.
> Edit shifts

- skyportal/app_server.py
- skyportal/handlers/api/internal/__init__.py
- skyportal/handlers/api/internal/notifications_test.py
- static/js/components/UpdateProfileForm.jsx
- static/js/ducks/userNotifications.js
This PR adds a button to the User profile page to test email / SMS receiving.
> Test email / SMS notification

- data/db_demo.yaml
- skyportal/facility_apis/generic.py
- skyportal/facility_apis/sedmv2.py
The exposure counts is not part of the pipeline anymore.
> SEDM-v2 - Remove exposure counts

- services/notification_queue/notification_queue.py
This PR checks for variable before looping over it in notifications.
> Notifications watchers variable

- skyportal/handlers/api/instrument.py
- skyportal/models/instrument.py
- static/js/components/InstrumentTable.jsx
This PR adds quick summary of region shapes.
> Region summaries

- static/js/components/Periodogram.jsx
This PR adds a few extra periodogram parameters (minimum and maximum frequency, etc.).
> Periodogram parameters

- skyportal/handlers/api/photometry.py
- skyportal/model_util.py
- skyportal/tests/api/test_photometry.py
This PR makes it simpler to delete an object's photometry.
> Delete object photometry

- data/db_demo.yaml
- skyportal/handlers/api/instrument.py
This PR adds basic AuxTel info to demo data.
> AuxTel info

- services/notification_queue/notification_queue.py
- skyportal/facility_apis/lco.py
- skyportal/facility_apis/swift.py
This PR fixes the analysis notification queue (and sets Comments from Swift and LCO queue to be bot=True).
> Analysis notification queue

- skyportal/tests/api/test_bulk_delete_photometry.py
Closes https://github.com/skyportal/skyportal/issues/4192.
> Bulk photometry test

- Dockerfile
This PR adds the photseries folder to Docker.
> Phot series folder: Docker

- skyportal/handlers/api/followup_request.py
- skyportal/utils/offset.py
- static/js/components/FollowupRequestSelectionForm.jsx
This PR adds ability to retrieve standards in observation plan.
> Standards in observation plan

- config.yaml.defaults
- static/js/components/ShareDataForm.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
This PR changes the name of "ManageData" to "ShareData" since Manage implies more than what it really is.
> Manage data is really share data

- skyportal/tests/api/test_summary_query.py
This PR fixes the summary query test.
> Fix summary query test

- skyportal/handlers/api/classification.py
- skyportal/plot.py
- static/js/components/AnnotationsTable.jsx
- static/js/components/CommentList.jsx
This PR makes a few cosmetic improvements.
> cosmetic improvements

- config.yaml.defaults
- skyportal/handlers/api/config_handler.py
- skyportal/handlers/api/internal/plot.py
- skyportal/handlers/api/internal/profile.py
- skyportal/plot.py
- skyportal/tests/api/test_spectrum.py
- skyportal/tests/frontend/test_upload_spectroscopy.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/SpectroscopyButtonsForm.jsx
- static/js/components/SpectroscopyColorSelect.jsx
- static/js/components/SpectroscopyPlottingPreferences.jsx
- static/js/components/UpdateProfileForm.jsx
This PR adds user-defined wavelengths as options for spectroscopy plot.
> User-defined wavelengths

- skyportal/utils/gcn.py
This PR adds distance_error upon skymap ingestion.
> Skymap distance_error

- skyportal/facility_apis/sedmv2.py
This PR makes priority of 0 possible (which will indicate fillers for SEDMv2).
> SEDMv2 0 priority option

- skyportal/facility_apis/ztf.py
- skyportal/plot.py
This PR reduces alpha for vertical plot lines. Closes https://github.com/skyportal/skyportal/issues/4219.
> Reduce opacity in vertical plot lines

- skyportal/facility_apis/ztf.py
This PR moves ZTF forced photometry threshold from 5 to 3.
> ZTF forced photometry threshold

- package.json
This PR pins kapsule (whose unpinned upgrade broke things today).
> Pin kapsule

- skyportal/handlers/api/sources_confirmed_in_gcn.py
- skyportal/plot.py
This PR notes GCN Event in confirmed sources plot. (closes https://github.com/skyportal/skyportal/issues/4226)
> GCN Event in confirmed sources plot

- skyportal/handlers/api/observation_plan.py
- skyportal/models/observation_plan.py
This PR includes rise and set time for planned fields.
> Rise and set time for planned fields

- skyportal/handlers/api/tns.py
Make sure last non-detection is before first detection
> TNS submission: Make sure last non-detection is before first detection

- skyportal/handlers/api/galaxy.py
- skyportal/handlers/api/source.py
- static/js/components/GalaxyPage.jsx
- static/js/components/UpdateSourceMPC.jsx
This PR sets better MPC defaults. Closes https://github.com/skyportal/skyportal/issues/4247.
> MPC defaults

- skyportal/models/observing_run.py
- static/js/components/RunSummary.jsx
- static/js/ducks/source.js
This PR fixes the observing run always up / down behavior.
> Observing run always up / down

- services/notification_queue/notification_queue.py
- skyportal/handlers/api/gcn.py
- skyportal/models/user_notification.py
- skyportal/utils/notifications.py
This PR triggers notification check when GcnTag is added.
> GcnTag notification

- config.yaml.defaults
- skyportal/utils/gcn.py
- static/js/components/GcnEvents.jsx
- static/js/components/GcnTags.jsx
This PR gets "Significant" tag from the events.
> Significant tag

- skyportal/handlers/api/followup_request.py
This PR adds the STD- prefix for standards, as expected for CALSPEC.
> Standard names in observation requests

- requirements.txt
This PR upgrades OpenAI to 0.27.7 to try to fix GA.
> OpenAI 0.27.7

- skyportal/utils/gcn.py
This PR saves the number of instruments on event ingestion.
> Number of instruments

- static/js/components/GcnEventAllocationTriggers.jsx
This PR fixes the trigger for mixed.
> For mixed, make sure trigger is false

- skyportal/handlers/api/followup_request.py
This PR uses nautical (rather than civil) twilight for observing cutoff.
> Nautical twilight

- static/js/components/CrossmatchGcnEvents.jsx
- static/js/components/FindGcnEvents.jsx
This PR tries to refactor the GCN event getter to make it useful for the crossmatch page. Something about the state is funny.. I wonder if you can take a quick look @Theodlz?
> GCN event getter

- alembic/versions/6f23bbeb119d_gcn_crossmatch.py
This PR fixes the recently merged GCN in-out down revision.
> GCN down revision

- skyportal/facility_apis/swift.py
This PR adds the Swift urgency meaning to form.
> Swift urgency

- skyportal/initial_setup.py
- skyportal/model_util.py
An attempt to avoid auth errors, and more generally make them easier to debug, while not relying on a package that isn't maintained anymore.
> Update baselayer (No social auth alchemy dependency)

- skyportal/handlers/api/tns.py
This PR adds zeropadding and sign for TNS query.
> TNS zeropadding and sign

- config.yaml.defaults
This PR updates treasuremap link to https. Closes #4281.
> treasuremap link

- skyportal/models/gcn.py
This PR fixes the GCN tag delete permissions in the database model.
> GCN tag delete permissions

- skyportal/handlers/api/skymap_trigger.py
This PR fixes the skymap trigger API to use partitions.
> Partitions for skymap trigger

- skyportal/handlers/api/source.py
- skyportal/plot.py
This PR does more careful source photometry handling.
> Source photometry handling

- skyportal/models/gcn.py
This PR makes it such that all GCN tables are updateable
> Make all GCN tables updateable

- skyportal/utils/gcn.py
This PR prevents underflow from small skymap values.
> Underflow from small skymap values

- services/tns_queue/tns_queue.py
- skyportal/handlers/api/sources_confirmed_in_gcn.py
- skyportal/handlers/api/tns.py
- skyportal/utils/tns.py
- static/js/components/TNSATForm.jsx
This PR enables TNS "archival" submission (those without upperlimits).
> TNS archival submission

- package.json
- requirements.txt
This PR pins latest langchain.
> langchain 0.0.187

- .github/dependabot.yml
- .github/workflows/build-and-deploy-docs.yaml
- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_migrations.yaml
- .github/workflows/test_models.yaml
This PR updates GA workflows to pip 23.1.2
> GA workflows pip

- services/notification_queue/notification_queue.py
- skyportal/utils/notifications.py
- static/js/components/NotificationPreferences.jsx
This PR fixes GCN email notiifcations.
> GCN email notifications

- static/js/components/FollowupRequestPreferences.jsx
This PR adds a little more type safety to the profile page's followup requests preferences components.
> Profile page safety: Followup requests preference

- services/tns_queue/tns_queue.py
- skyportal/handlers/api/tns.py
- skyportal/utils/tns.py
- static/js/components/UpdateSourceTNS.jsx
This PR enables retrieval of TNS photometry.
> TNS photometry

- skyportal/handlers/api/followup_request.py
This PR fixes divide by 0 issues when requesting observation plans.
> Follow-up request priorities

- skyportal/handlers/api/gcn.py
- static/js/components/FilterCandidateList.jsx
- static/js/components/FindGcnEvents.jsx
- static/js/components/UpdateSourceGCNCrossmatch.jsx
This PR addresses #4300 for:
- candidate scanning
- gcnevents list page
- gcnevents crossmatch dialog
Also addresses #4336
> GCN event search: by partial dateobs and aliases

- skyportal/handlers/api/followup_request.py
This PR adds individual object constraints in observing planner.
> Individual object constraints

- services/watch_list/watch_list.py
- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/lco.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/swift.py
- skyportal/facility_apis/tess.py
- skyportal/facility_apis/ztf.py
- static/js/components/DisplayPhotStats.jsx
- static/js/components/FollowupRequestLists.jsx
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceGCNCrossmatchList.jsx
- static/js/components/SourceMobile.jsx
- static/js/components/UpdateSourceTNS.jsx
Compared to "triggered" followup, there is no queue_name for forced phot, or anything to delete from the server in general it seems.
This PR skips deleting from server for FP.
> Forced photometry Delete Bugfix

- static/js/components/SourceGCNCrossmatchList.jsx
That's what  you get when you merge too quick :)
> Frontend Bugfix: SourceGCNCrossmatchList.jsx

- skyportal/handlers/api/photometry.py
This PR fixes broken altdata tests.
> altdata tests

- services/recurring_apis/recurring_apis.py
- skyportal/handlers/api/recurring_api.py
- static/js/components/AllocationTable.jsx
This PR allows recurring API calls to use get.
> get with recurring API

- static/js/components/ConfirmSourceInGCN.jsx
This PR addresses issue #4354 4280
> Gcn Status Explanations: More options

- static/js/components/SourceAnnotationButtons.jsx
Very small change to support another change in Fritz (annotation buttons plugins)
> Annotation buttons: Styling

- skyportal/handlers/api/observation.py
- static/js/components/GcnSelectionForm.jsx
It seems that the subquery created when using the cache slows the query by at least a factor of 2 (but sometimes more than that as the time that a query takes in postgres varies).
That happens only when specifying an instrument to query for. Without it's somehow quicker. 
I also noticed that the frontend to fetch observations wasn't passing the selected instrument as query param, which is the behavior that is expected from the form.
So this PR might slow down fetching observations from the frontend, while accelerating/fixing the treasuremap submission. If it turns out that after these changes even if the query (with specified instrument id) is faster, fetching observations is now too slow and the treasuremap still takea too long, we can easily reverse the frontend change and make the …
> Fetch Executed Observations in Localization: Better performance

- skyportal/handlers/api/news_feed.py
This PR uses sqlalchemy 2.0 syntax in news feed.
> sqlalchemy 2.0 syntax in news feed

- doc/image_analysis.md
- skyportal/handlers/api/internal/image_analysis.py
- static/js/components/ImageAnalysisForm.jsx
This PR adds some Mac specific instructions for image analysis dependencies.
> Mac image analysis instructions

- skyportal/handlers/api/gcn.py
- skyportal/tests/api/candidates_sources_events/test_gcn.py
- skyportal/utils/gcn.py
This PR modifies the map tags to read distmean / standard deviation from map header.
> mean / error from map header

- skyportal/handlers/api/tns.py
- skyportal/utils/tns.py
- static/js/components/CandidateList.jsx
- static/js/ducks/candidates.js
This PR fixes the PS1 thumbnails button.
> PS1 thumbnails

- skyportal/models/telescope.py
This PR updates check for telescope observability.
> Telescope observability

- static/js/components/FilterCandidateList.jsx
> Candidate scanning: GCN filtering bugfix

- services/facility_queue/facility_queue.py
- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/ztf.py
This PR modifies forced photometry such that the retrieval is automated.
> Forced photometry queue

- skyportal/handlers/api/gcn.py
This PR fixes the obj_id in photometry table.
> photometry obj_id

- data/db_demo.yaml
- doc/image_analysis.md
- skyportal/handlers/api/internal/image_analysis.py
- static/js/components/ImageAnalysisForm.jsx
This PR adds saturation as front-end variable.
> Saturation to image form

- services/facility_queue/facility_queue.py
- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/ztf.py
- static/js/components/FollowupRequestForm.jsx
- static/js/components/FollowupRequestLists.jsx
@mcoughlin feel free to add to this based on what we discussed on slack.
> FacilityTransaction queue: bugfixes

- skyportal/handlers/api/followup_request.py
This PR ensures HA is between 0-24 before converting to negative HAs.
> More mods for HA

- skyportal/handlers/api/tns.py
This PR ensures groupIds are specified for bulk TNS reporting.
> Require groupIds for bulk TNS reporting

- skyportal/handlers/api/followup_request.py
- skyportal/tests/api/candidates_sources_events/test_gcn.py
This PR catches corner cases in the HourAngleConstraint.
> HourAngleConstraint transposes

- skyportal/utils/tns.py
This PR adds more TNS mappings.
> More TNS mappings

- skyportal/handlers/api/followup_request.py
This PR reduces dimensions if necessary in HA constraint.
> Reduce dimensions in HA constraint

- skyportal/utils/fits_display.py
This PR fixes the pysedm preview in comments.
> pysedm preview

- services/sn_analysis_service/app.py
This PR removes the limits between first and last detection when doing sncosmo fit.
> sncosmo fit limits

- services/tns_queue/tns_queue.py
- static/js/components/UpdateSourceTNS.jsx
Add TNS to all sources within 2 arcsec, and not just the closest one.
> TNS 2 arcsec crossmatch: update all sources

- skyportal/handlers/api/observation.py
- static/js/components/GcnSelectionForm.jsx
This PR adds the number of observations to the treasuremap submission query.
> numberObservations to TreasureMap submission query

- config.yaml.defaults
- services/tns_queue/supervisor.conf
- services/tns_retrieval_queue/supervisor.conf
- services/tns_retrieval_queue/tns_retrieval_queue.py
- services/tns_submission_queue/supervisor.conf
- services/tns_submission_queue/tns_submission_queue.py
- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/tns.py
- skyportal/tests/api/candidates_sources_events/test_sources.py
- skyportal/utils/tns.py
This PR creates separate TNS submission and retrieval queues.
> separate tns retrieval and submission queues

- skyportal/utils/tns.py
This PR fixes the TNS instrument nickname error.
> TNS instrument nickname error

- static/js/components/UserManagement.jsx
This PR fixes the user expiration date picker.
> user expiration date picker

- skyportal/facility_apis/atlas.py
- skyportal/handlers/api/comment.py
- skyportal/handlers/api/comment_attachment.py
- skyportal/handlers/api/source.py
- static/js/ducks/source.js
- static/js/ducks/sources.js
This PR adds source query option to always return sources in True or ambiguous.
> GcnEvent: Always return True or ambiguous in list

- static/js/components/SourceTable.jsx
This PR adds a link to NewSource from the SourceTable toolbar.
> NewSource from the SourceTable toolbar

- requirements.txt
This PR updates distributed / dask to 2023.6.1.
> distributed / dask 2023.6.1

- .github/workflows/build-and-deploy-docs.yaml
- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_docker_build.yaml
- .github/workflows/test_migrations.yaml
- .github/workflows/test_models.yaml
- Dockerfile
This PR updates workflows from python 3.8 to 3.9.
> Update workflows from python 3.8 to 3.9

- static/js/components/FollowupRequestLists.jsx
This PR adds more more info for follow-up request allocations.
> Follow-up request allocation info

- config.yaml.defaults
- skyportal/handlers/api/telescope.py
- static/js/components/AllocationTable.jsx
- static/js/components/InstrumentTable.jsx
- static/js/components/TelescopeInfo.jsx
- static/js/components/TelescopeSummary.jsx
- static/js/components/WeatherWidget.jsx
- static/js/ducks/weather.js
This PR adds a telescope summary page with associated instruments and allocations tables.
> Add telescope summary page

- skyportal/handlers/api/galaxy.py
- static/js/API.js
- static/js/components/GalaxyTable.jsx
- static/js/components/GalaxyTableFilterForm.jsx
- static/js/components/GcnEvents.jsx
- static/js/components/GcnEventsFilterForm.jsx
This PR adds a filter on galaxy table.
> galaxy table filter

- static/js/components/CandidateList.jsx
- static/js/components/ScanningPageCandidateAnnotations.jsx
This PR addresses issues:
- https://github.com/fritz-marshal/fritz/issues/531
- https://github.com/fritz-marshal/fritz/issues/532
> Candidates list: Sorting bugfix + order annotations alphabetically

- config.yaml.defaults
This PR highlights retraction tag in white.
> Highlight retraction

- skyportal/handlers/api/observation.py
- skyportal/handlers/api/observation_plan.py
- skyportal/models/gcn.py
- static/js/components/SurveyEfficiencyObservationPlanLists.jsx
- static/js/components/SurveyEfficiencyObservationsLists.jsx
- static/js/ducks/survey_efficiency_observation_plans.js
- static/js/ducks/survey_efficiency_observations.js
This PR fixes the report skymap to center on peak probability.
> Center skymap on peak probability

- skyportal/handlers/api/gcn.py
- skyportal/models/gcn.py
- static/js/components/GcnReport.jsx
- static/js/components/SurveyEfficiencyObservationPlanLists.jsx
- static/js/components/SurveyEfficiencyObservationsLists.jsx
- static/reports/gcn_report.html
This PR adds button to also save survey efficiency analyses.
> GCN Report --- survey efficiency analyses

- skyportal/handlers/api/spectrum.py
It looks like the method to update a spectrum isn't doing what the documentation is claiming it does.
This gets us closer to that by allowing one to update the list of reducers and observers of a spectrum.
> Spectrum: Fix patching reducers and observers

- requirements.txt
This PR updates langchain to the latest on pypi.
> langchain 0.0.229

- static/js/components/ObservationPlanRequestLists.jsx
This PR fixes a display issue where fields are not displayed when submitted to telescope queue.
> Still display fields when submitted to telescope queue

- skyportal/handlers/api/photometry.py
This PR adds a str typecast to origin duplicate photometry check.
> str typecast for origin

- skyportal/handlers/api/source.py
- skyportal/models/obj.py
- static/js/components/SourceDesktop.jsx
- static/js/components/SourceMobile.jsx
This PR adds host separation calculation to the source page.
> Host separation

- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/source.py
- skyportal/models/instrument.py
- static/js/components/ModifyInstrument.jsx
- static/js/components/ShowClassification.jsx
Make it possible to add references from the frontend, and also fixes the has_fields flag which had a tendency to stay false.
> Modify Instruments; add/update references

- skyportal/handlers/api/instrument.py
This makes it possible to update the contour and contour summary of fields of an instrument.
> Modify instruments: update regions

- static/js/components/LocalizationPlot.jsx
- static/js/components/TNSATForm.jsx
- static/js/components/TNSRobots.jsx
Missing frontend changes, to make sure we still show the tns instruments correctly
> Frontend: tns instruments lowercase

- services/tns_retrieval_queue/tns_retrieval_queue.py
- skyportal/handlers/api/news_feed.py
- skyportal/tests/frontend/sources_and_followup_etc/test_top_sources.py
- static/js/components/NewsFeed.jsx
This PR adds a TNS prefix to the query. It also adds the classification to the news feed.
> TNS prefix

- .github/workflows/build-and-deploy-docs.yaml
This PR updates the docs action to v4
> Deploy docs v4

- requirements.txt
This PR updates pydantic / langchain.
> pydantic / langchain

- skyportal/utils/offset.py
Fixes formatting issue with the P200 starlist, which prevents observers from using it as is.
> P200 Starlist formatting

- data/db_demo.yaml
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/tns.py
- skyportal/tests/api/candidates_sources_events/test_gcn.py
- skyportal/tests/frontend/sources_and_followup_etc/test_group_sources.py
- static/js/components/DisplayPhotStats.jsx
- static/js/components/Filter.jsx
- static/js/components/ShowClassification.jsx
- static/js/components/SourceTable.jsx
- static/js/components/TNSATForm.jsx
- static/js/components/TNSRobots.jsx
- add the missing API Key fields when adding/editing a bot
- always display the TNS name on the sources list
- better sources list display
- display sources TNS names on the gcn summary, instead of the alias field which is always empty anyway.
- if the robot has autoreporters, it will use that as the default in the submission form instead of the user's name
> TNS - various improvements

- skyportal/handlers/api/annotation_services.py
This PR updates default to Legacy Survey dr10.
> Legacy Survey dr10

- requirements.txt
This PR downgrades Selenium to 4.8.3.
> Selenium 4.8.3

- skyportal/facility_apis/sedm.py
- skyportal/handlers/api/followup_request.py
Handle the cases where a user tries to edit or delete a request that the instrument is already processing.
> SEDM interactions: handle new status message

- Dockerfile
Remove sudo's from the Dockerfile (added with the new nodejs installation instructions, my fault!)
> Dockerfile: system dependencies install fix

- static/js/components/FollowupRequestLists.jsx
> Follow-up list download fix

- .github/workflows/build-and-deploy-docs.yaml
This PR extends the timeout for the docs action and uses the new way of installed nodejs as in the other action.
> docs action

- skyportal/handlers/api/followup_request.py
In the context of BTSBot (but it could very well bu useful for other applications), we want Kowalski to be able to send a request without having access to more info about the source. However, we want to cancel triggering if the source is saved to the junk groups. This offloads the check to Fritz, like we already do with other constraints.
> Follow-up request constraints: don't trigger if saved to group(s)

- config.yaml.defaults
- skyportal/enum_types.py
- skyportal/handlers/api/config_handler.py
- skyportal/handlers/api/gcn.py
- static/js/components/GcnSummary.jsx
Takes care of https://github.com/skyportal/skyportal/issues/4633
> GCN summary - acknowledgments in config

- data/db_demo.yaml
This PR adds the NMMA analysis service to `db_demo.yaml` to facilitate easier local testing.
> Add commented NMMA analysis to db_demo.yaml

- skyportal/facility_apis/atlas.py
- skyportal/facility_apis/ps1.py
- skyportal/facility_apis/tess.py
- skyportal/facility_apis/ztf.py
> Forced Photometry - Data sharing bugfix

- skyportal/utils/offset.py
This PR fixes a PS1 url SSL error.
> PS1 url SSL error

- static/js/plotjs/download.js
This PR adds magnitude and error columns to downloaded light curves.
> Magnitude and error columns in downloaded light curve

- static/js/components/QuickSaveSource.jsx
This PR fixes the quick save source to only save updated groups.
> Quick save source to only save updated groups

- skyportal/handlers/api/photometry.py
- skyportal/handlers/api/source.py
- skyportal/tests/api/candidates_sources_events/test_sources.py
- static/js/ducks/photometry.js
This PR enables photometry deduplication.
> Photometry deduplication

- package.json
- static/js/components/SharePage.jsx
- static/js/components/TokenList.jsx
This PR adds a QR code embedding the token.
> QR token embedding

- skyportal/handlers/api/internal/source_savers.py
- skyportal/tests/api/candidates_sources_events/test_candidates.py
This PR fixes the savers query to enable different lookback times and number of savers.
> Query options for savers and times

- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_migrations.yaml
- .github/workflows/test_models.yaml
- .pre-commit-config.yaml
Upgrade baselayer to its latest version, and applies the necessary changes to the github actions regarding firefox.
> pin baselayer to d3c9506f3196de3fc67f854b6c204c5eef696306

- .github/dependabot.yml
Fixed another formatting issue missed in the first PR
> fix dependabot config - part 2 (schedule.time format)

- skyportal/handlers/api/internal/source_savers.py
- skyportal/handlers/api/internal/source_views.py
- static/js/components/TopSavers.jsx
This PR makes fractional days for sinceDaysAgo possible.
> sinceDaysAgo float

- skyportal/handlers/api/followup_request.py
> Followup constraints: TNS name, non-case sensitive but position sensitive

- static/js/components/PhotometryTable.jsx
This PR fixes the photometry table download csv.
> photometry table download

- alembic/versions/1d0d58fe42fe_spectrum_pi.py
- skyportal/handlers/api/spectrum.py
- skyportal/models/schema.py
- skyportal/models/spectrum.py
- skyportal/tests/api/test_spectrum.py
- skyportal/tests/frontend/test_individual_spectra.py
- static/js/components/ShareDataForm.jsx
- static/js/components/UploadSpectrum.jsx
This PR adds concept of spectrum PI(s).
> Spectrum PI(s)

- skyportal/handlers/api/followup_request.py
How to open an embarrassing one line PR 👍
> Follow-up requests constraints bugfix

- skyportal/handlers/api/followup_request.py
> Follow-up constraints: if statement bug fix

- skyportal/utils/gcn.py
This PR adds the lost lock tag for Swift notices.
> Swift Lost lock

- ARCHITECTURE.md
This PR adds an ARCHITECTURE.md file. See https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html for concept.
> architecture file

- skyportal/handlers/api/gcn.py
- skyportal/utils/gcn.py
This PR makes voevent xml file more flexible.
> More flexibility in xml file ingestion

- CODE-OF-CONDUCT.md
This PR adds a standard code of conduct: https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md
> Code of Conduct

- skyportal/models/telescope.py
This PR checks for masked arrays in ephemeris.
> Ephemeris for objects that never set

- skyportal/handlers/api/allocation.py
- skyportal/tests/api/test_allocations.py
- static/js/components/AllocationSummary.jsx
- static/js/components/FollowupRequestLists.jsx
- static/js/ducks/allocation.js
This PR paginates allocation requests.
> Paginate allocation requests

- static/js/ducks/photometry.js
This PR fixes the patch photometry call.
> Patch photometry ID

- static/js/components/CandidateList.jsx
- static/js/components/DisplayPhotStats.jsx
- static/js/components/PhotometryMagsys.jsx
- static/js/components/PhotometryPlot.jsx
- static/js/components/PhotometryTable.jsx
- static/js/components/Source.jsx
- static/js/components/VegaPhotometry.jsx
This PR adds a switch between AB and Vega.
> Front-end AB and Vega

- services/tns_submission_queue/tns_submission_queue.py
- skyportal/handlers/api/tns.py
- skyportal/tests/api/candidates_sources_events/test_tnsrobots.py
- skyportal/utils/tns.py
- static/js/components/TNSATForm.jsx
- static/js/components/TNSRobotsPage.jsx
* make it mandatory to specify instruments when adding a robot, and must be specified too before being able to submit to TNS
* validate the source obj_id before submitting using the source_group_id on TNS (basically, what survey the source comes from) and the survey's naming convention.
> TNS Submission: bugfixes and stricter submission rules

- services/tns_retrieval_queue/tns_retrieval_queue.py
- skyportal/utils/tns.py
Looks like some TNS responses (from both success and failures) came back as non-JSON compliant..., which would kill our TNS watcher service and stop us from ingesting TNS sources in the app after any error is encountered. 
This PR wraps all `respoonse.json()` statements in a try except to use the `response.text` if we can't read the JSON, and also wraps the entire TNS watcher service's white loop content in a try except to avoid killing the service if we get any error.
> TNS Retrieval: Watcher lifetime

- static/js/components/PhotometryPlot.jsx
- static/js/components/Source.jsx
> plotting label

- static/js/components/TNSRobotsPage.jsx
- static/js/components/TransferList.jsx
as the title suggests we make sure that items in lists of things to add/delete/edit are all ordered alphabetically to make it easier to find what you are looking for in prod.
> TNS Robots management: sort group users, groups, and coauthors alphabetically

- services/tns_submission_queue/tns_submission_queue.py
This is an attempt at scoping the DBSession appropriately to avoid issues with shared sessions between 2 threads. As DBSession is scoped with a contextvar that is None, it looks like it ends up having one session shared between threads. So here, we defined the relevant contextvar with a random UUID (just like we do for an individual API request) to try to see if sessions are different for each thread which is what we want
Before I tried to import DBSession in each thread which didn't help, but I kept that here which means that the contextvar is defined before the DBSession import, which I'm not sure works. 
If this does not work, I might want to switch to one import of DBSession on top of the file as usual, and simply set the context in the main method/logic of each thread before opening …
> TNS submissions DBSession bugfix

- skyportal/handlers/api/classification.py
This PR fixes the page_num cast for classifications endpoint.
> page_num cast for classifications

- static/js/ducks/tnsrobots.js
This PR fixes the TNS submissions pagination.
Resolves https://github.com/skyportal/skyportal/issues/4878
> TNS submissions pagination

- skyportal/facility_apis/swift.py
This PR adds 0 as swift trigger option.
> Swift triggers: priority 0

- skyportal/handlers/api/observation_plan.py
This PR fixes the manual plan upload loop.
> manual plan upload

- skyportal/handlers/api/observation_plan.py
This PR queries DB for field ID in case using different skyportal for plan.
> field ID in manual plan

- skyportal/handlers/api/annotation_services.py
- static/js/components/CommentEntry.jsx
- static/js/components/EditComment.jsx
This PR adds a few Gaia columns to the query (and fixes the comment edit dismissal -- trivial fix).
> Gaia columns

- skyportal/handlers/api/followup_request.py
- static/js/components/FollowupRequestSelectionForm.jsx
This PR adds a priority threshold option to followup request queries.
> priority threshold

- skyportal/handlers/api/candidate.py
- skyportal/handlers/api/observation_plan.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/sources.py
- static/js/API.js
- static/js/components/FilterCandidateList.jsx
- static/js/components/GcnSelectionForm.jsx
- static/js/components/SourceTable.jsx
- static/js/ducks/sources.js
This PR allows for no detections in the source queries.
> No detections in the source queries

- skyportal/app_server.py
- skyportal/handlers/api/__init__.py
- skyportal/handlers/api/allocation.py
- static/js/components/AllocationSummary.jsx
- static/js/components/ObservationPlanGlobe.jsx
- static/js/components/ObservationPlanRequestForm.jsx
- static/js/components/ObservationPlanRequestLists.jsx
- static/js/components/ObservationPlanSummaryStatistics.jsx
- static/js/ducks/observationPlans.js
This PR adds a table for plan status for individual allocations.
> Allocation observation plan table

- skyportal/handlers/api/source.py
> Source name validation: accept periods

- data/db_demo.yaml
- requirements.txt
- skyportal/facility_apis/observation_plan.py
This PR updates gwemopt to 0.2.1.
> gwemopt 0.2.1

- skyportal/facility_apis/trt.py
TRT SBO accepts Ic and Rc, not I and R.
> SBO -- Ic/Rc

- services/observation_plan_queue/observation_plan_queue.py
When marking an observation plan as complete, make sure to refresh the list of plans in the frontend for the users that are looking at that GCN event's page.
> Observation plans status=complete frontend refresh

- skyportal/app_server.py
- skyportal/facility_apis/winter.py
- skyportal/handlers/api/internal/log.py
- skyportal/utils/files.py
Adds a GET method to the existing LogHandler, with:
- if no file_name is specified, returns the full list of files from the log directory.
- otherwise, download the specified `.log` file.
This is reserved to `System Admin` only for obvious reasons.
> LogHandler: GET

- requirements.txt
- services/reminders/reminders.py
- skyportal/handlers/api/galaxy.py
- skyportal/handlers/api/observation_plan.py
- skyportal/handlers/api/reminder.py
- skyportal/tests/flaky/test_analysis_flaky.py
- skyportal/tests/flaky/test_download_flaky.py
- skyportal/tests/flaky/test_frontend_flaky.py
- skyportal/tests/flaky/test_gcn_flaky.py
- skyportal/tests/flaky/test_gcnevents_flaky.py
- skyportal/tests/flaky/test_observation_plan.py
- skyportal/tests/flaky/test_upload_galaxies_flaky.py
This PR updates gwemopt to 0.2.2.
> gwemopt 0.2.2

- requirements.txt
> Python requirements: penquins==2.4.1

- skyportal/facility_apis/winter.py
Update the WINTERAPI dither_distance default from 30 to 90, as suggested by @robertdstein.
Also update the end_date to be +7 days from the start_date, not just +1
> WINTERAPI: dither_distance default 30 -> 90

- static/js/components/ObservationPlanRequestLists.jsx
- static/js/components/ObservationPlanSummaryStatistics.jsx
Show the localization plot and statistics which are not visible right now once sent to queue
> Obsplan list: display fix

- services/tns_submission_queue/tns_submission_queue.py
> TNS report remarks: fix key name in payload

- skyportal/handlers/api/classification.py
This PR fixes the classification test.
> classification test

- requirements.txt
> gwemopt 0.3.1

- .github/workflows/build-and-deploy-docs.yaml
- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_migrations.yaml
- .github/workflows/test_models.yaml
- webpack.config.js
This PR updates the webpack to handle a UnhandledSchemeError.
> UnhandledSchemeError

- skyportal/facility_apis/swift.py
mean floats ruining my day (and night)
> SWIFT ToO: urgency dtype

- config.yaml.defaults
- services/gcn_service/gcn_service.py
- skyportal/handlers/api/gcn.py
- skyportal/models/gcn.py
- skyportal/models/schema.py
- skyportal/tests/api/candidates_sources_events/test_gcn.py
- skyportal/tests/data/EP240508.json
- static/js/components/SpectraPlot.jsx
This PR adds support for JSON GCN notices, including Einstein Probe and GUANO alerts.
PS: Due to a limitation of pygcn we are not saving the notices yet, but this is enough to create event pages with localizations to trigger observations of.
> einstein probe

- Makefile
- package.json
This PR fixes the docs command depracation.
> Docs upgrade

- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_models.yaml
This PR uses a GA for geckodriver to see if cacheing is better.
> geckodriver

- skyportal/enum_types.py
This PR adds the JSON notice types in dropdown.
> JSON notice types in dropdown

- skyportal/handlers/api/gcn.py
This PR handles json alerts for source creation.
> JSON alerts for source creation

- skyportal/handlers/api/internal/plot.py
This PR checks the sunrise and sunset is None.
> sunrise and setset

- skyportal/models/phot_stat.py
This PR makes a minor optimization to only query necessary columns for phot stats.
> only query necessary columns for phot stats

- skyportal/handlers/api/annotation_services.py
This PR specifies radius as argument to GaiaClass.cone_search().
> radius in GaiaClass.cone_search()

- skyportal/handlers/api/gcn.py
This PR fixes geojson summary.
> geojson name in summary

- .pre-commit-config.yaml
- skyportal/handlers/api/gcn.py
- skyportal/utils/gcn.py
- static/js/components/SkymapTriggerAPIDisplay.jsx
- static/js/components/gcn/CrossmatchGcnEvents.jsx
- static/js/components/gcn/DefaultGcnTagPage.jsx
- static/js/components/gcn/DefaultGcnTagTable.jsx
- static/js/components/gcn/FindGcnEvents.jsx
- static/js/components/gcn/GcnEvents.jsx
- static/js/components/gcn/NewDefaultGcnTag.jsx
- static/js/components/gcn/NewGcnEvent.jsx
This PR (i) puts gcn components in that folder and (ii) enables reading icecube+lvk notices.
> icecube+lvk notices

- skyportal/handlers/api/gcn.py
This PR only looks for data if report is not None.
> report data

- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/observation.py
- skyportal/models/gcn.py
- static/js/components/ModifyInstrument.jsx
This PR uses MOC for generating the report plot.
> MOCify report

- skyportal/handlers/api/gcn.py
This PR catches issues with non-integer summary_id.
> non-integer summary_id

- skyportal/handlers/api/gcn.py
This PR sorts GCN summary and report by observation time.
> GCN sort by observation time

- config.yaml.defaults
- services/gcn_service/gcn_service.py
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/photometry.py
- skyportal/utils/gcn.py
- static/js/components/gcn/GcnLocalizationsTable.jsx
- static/js/ducks/localization.js
This PR prevents skymap underflow.
> prevent skymap underflow

- skyportal/handlers/api/galaxy.py
- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/photometry.py
- static/js/components/source/CopyPhotometryDialog.jsx
- static/js/components/source/Source.jsx
This PR addresses 2 more sentry errors: a copy photometry error and missing gcn_report.
> copy error and missing gcn_report

- skyportal/handlers/api/allocation.py
- static/js/components/NewAPIObservation.jsx
- static/js/components/NewAPIQueuedObservation.jsx
- static/js/components/QueueAPIDisplay.jsx
- static/js/components/SkymapTriggerAPIDisplay.jsx
This PR only return allocations which implement relevant APIs for the observations page.
> Allocations which implement relevant APIs

- skyportal/facility_apis/trt.py
This PR adds SBO filter options.
> SBO filter options

- requirements.txt
- skyportal/utils/observation_plan.py
This PR updates gwemopt to 0.3.4.
> gwemopt 0.3.4

- skyportal/facility_apis/trt.py
This PR enables TRT image retrieval.
> retrieve TRT images

- skyportal/onboarding.py
This PR exists for invite username.
> check for existing invite username

- static/js/components/plot/PhotometryPlot.jsx
This PR adds error bar to photometry period plot.
> error bar to photometry period plot

- skyportal/handlers/api/gcn.py
- static/js/components/gcn/GcnSummaryTable.jsx
* make sure that the tns_name and redshift columns are empty and not showing `None/nan` if there is no value to display.
* add some padding to the tables when rendering the markdown
> GCN Summary bugfix: NaN/None -> empty str 

- services/facility_queue/facility_queue.py
This PR checks for None url in atlas.
> None url in atlas

- skyportal/handlers/api/observation_plan.py
This PR checks for observation_plans when making GCN.
> check for observation_plans when making GCN

- static/js/components/followup_request/FollowupRequestLists.jsx
This PR also checks for pending observations when showing get button.
> pending observations also show get button

- skyportal/handlers/api/user.py
- static/js/components/user/UserManagement.jsx
This PR filters expired accounts in user table.
> filter expired accounts

- static/js/components/localization/LocalizationPlot.jsx
- static/js/components/observation_plan/ObservationPlanRequestForm.jsx
fixes https://github.com/skyportal/skyportal/issues/5103, and reverses the primary and secondary field selector for ZTF (that were reversed).
> Obsplan List: tiles transparency

- skyportal/handlers/api/source.py
- static/js/components/followup_request/FollowupRequestLists.jsx
This PR shows transactions for follow-up requests.
> transactions for follow-up requests

- static/js/components/photometry/PhotometryTable.jsx
Fixed a bug introduces by the addition of the UTC columns earlier this year, and the lack of type checking of the streams
> Photometry table download fix

- skyportal/tests/frontend/sources_and_observingruns_etc/test_assignments.py
- static/js/components/observing_run/AssignmentForm.jsx
- static/js/components/observing_run/AssignmentList.jsx
- static/js/components/observing_run/ModifyAssignment.jsx
let users edit the priority and comment for an assigned target, which I noticed was quite annoying as one had to delete and re-assign the target.
> AssignmentList (on SourcePage): edit

- skyportal/handlers/api/gcn.py
- skyportal/handlers/api/observation_plan.py
- static/js/components/localization/LocalizationPlot.jsx
- static/js/components/observation_plan/DefaultObservationPlanTable.jsx
- static/js/components/observation_plan/NewDefaultObservationPlan.jsx
Adds filtering on gcn and localization properties, not just the tags and notice types.
> Default observation plan filters: gcn & localization properties

- static/js/components/plot/PhotometryPlot.jsx
This PR adds a missing parseFloat in period annotation.
Closes #5139.
> add parseFloat to period annotation

- static/js/components/allocation/NewAllocation.jsx
- static/js/components/instrument/NewInstrument.jsx
This PR fixes 2 small front-end bugs (i) allocation admins are not required and (ii) validation for field_region upload was not correct.
> front-end fixes

- skyportal/handlers/api/instrument.py
This PR checks for observer being None for calculating airmass.
> observer is None when calculating airmass

- config.yaml.defaults
This PR turns down the sentry sample rate to 0.25.
> Set sentry sample rate to 0.25

- skyportal/facility_apis/tarot.py
This PR adds default options for TAROT.
> tarot defaults option

- skyportal/facility_apis/swift.py
This PR enumerates possible UVOT modes.
> enumerate UVOT modes

- skyportal/facility_apis/ztf.py
Fallback to an alternative file on the IPAC depot when the usual one is missing.
TODO: figure out which column to use for the seeing. In the current file we use a `fwhm` column, but here we have `diffhwm` and `sciseeing`.
> ZTF Executed Observations: fallback

- skyportal/facility_apis/lt.py
This PR makes some front-end fixes for LT.
> LT front-end fixes

- requirements.txt
- skyportal/handlers/api/observation_plan.py
- skyportal/utils/earthquake.py
This PR updates to geopandas 1.0.1
> geopandas 1.0.1

- skyportal/handlers/api/observation_plan.py
- skyportal/utils/earthquake.py
This PR fixes the filepath to natural earth.
> naturalearth path

- skyportal/facility_apis/soar.py
- skyportal/facility_apis/tarot.py
- skyportal/utils/offset.py
This PR updates the star list to use the first letter of the telescope name.
> offset stars with the first letter of the telescope

- skyportal/tests/frontend/sources_and_observingruns_etc/test_sources.py
- Correct the test_show_starlist which searching for _o1 instead of _k1.
> Correct test_show_starlist

- skyportal/handlers/api/gcn.py
- skyportal/models/gcn.py
* increases the radius threshold from 5 arcmin to 8 arcmin
* fixes a bug introduced end of last week, that prevented EP sources from being created
> GCN - Point source auto-generation: larger radius threshold

- README.md
This PR adds the bibtex entries to the README.
> Add bibtex entries

- skyportal/facility_apis/lt.py
- skyportal/facility_apis/soar.py
- skyportal/handlers/api/group.py
- static/js/components/followup_request/FollowupRequestForm.jsx
This PR checks first for a group with an existing name.
> check for group with existing name

- skyportal/handlers/api/source.py
This PR checks that group_ids are accessible when making a source.
> check group_ids when making a source

- skyportal/facility_apis/lt.py
- skyportal/facility_apis/soar.py
- static/js/components/followup_request/FollowupRequestForm.jsx
This PR use strings rather than form (which has funky local time behavior)
> date-time in form

- static/js/components/followup_request/FollowupRequestForm.jsx
This PR only uses the split on the date if specifying date format (need full isot in some cases).
You might have a better way of doing this @Theodlz
> do not split date if want full date

- skyportal/models/schema.py
In a previous PR, and incorrect schema was added, missing some changes.
This PR fixes it. Hotfix in production already
> Followup constraint schema: fix

- skyportal/models/obj.py
- static/js/components/source/SurveyLinkList.jsx
- static/js/components/thumbnail/Thumbnail.jsx
Move to DR18 since some of DR12s services seem to be down when DR18's aren't.
> SDSS thumbnails: dr12 -> dr18

- skyportal/handlers/api/followup_request.py
- static/js/components/followup_request/FollowupRequestLists.jsx
This PR adds more logs in failures of  follow-up submissions.
> log failures in follow-up submission

- .github/workflows/test_api_and_frontend.yaml
This is an attempt at caching some of the stuff that we keep downloading when we start github actions.
Might have to commit a few times to see this in action.
> GitHub actions: dustmap & sncosmo filters caching

- skyportal/facility_apis/swift.py
- skyportal/tests/api/candidates_sources_events/test_gcn.py
- skyportal/tests/frontend/test_gcn.py
- static/js/components/Notes.jsx
This PR adds a UVOT justification entry to the form.
> UVOT justification

- skyportal/handlers/api/source.py
- static/js/components/source/UpdateSourceCoordinates.jsx
This PR fixes issue if only patching RA or Dec.
> more careful source patching

- .github/workflows/test_api_and_frontend.yaml
- .github/workflows/test_migrations.yaml
- .github/workflows/test_models.yaml
- skyportal/handlers/api/instrument.py
This PR tries to fix a sentry error: Scalar 'Time' object has no len().
> np.array() the time array

- skyportal/models/telescope.py
This PR checks for sunrise is None in ephemeris.
> sunrise is none in ephemeris

- skyportal/facility_apis/ztf.py
This PR checks for empty depot file.
> check for empty depot file

- skyportal/handlers/api/comment.py
This PR checks for a non-empty body.
> comment body

- skyportal/handlers/api/gcn.py
This PR adds more logging for source creation from GCN sources.
> logging for source creation

- .pre-commit-config.yaml
- eslint.config.js
- package.json
- static/js/components/observing_run/ObservingRunPage.jsx
- static/js/components/plot/PhotometryPlot.jsx
- static/js/components/templates/Main.jsx.template
- static/js/components/templates/SidebarAndHeader.jsx.template
- static/js/components/user/UserManagement.jsx
It's very poorly documented but when specifying a path to eslint (say, what's in static/js, as added recently on main's recommit config) in the pre-commit config, it stops running it **only** on newly committed files, and instead keeps running it on everything in that folder, instead of the behavior I hoped it would have (which is running with just the same logic, but limited to the specified directory).
This PR fixes that, in an attempt to fix the CI. Also fixed a few jsx files.
> ESLint fix

- requirements.txt
pin the latest version of gwemopt
> pin gwemopt to 0.3.5

- skyportal/handlers/api/photometry.py
- static/js/components/photometry/NewPhotometry.jsx
- static/js/components/source/Source.jsx
This PR:
- fixes the date to mjd conversion
- is more strict on the date format
- doesn't get rid of all the forms data when changing the instrument that is selected.
> Frontend Photometry Single upload - date fix

- skyportal/tests/frontend/test_upload_photometry.py
Fixes a test broken in a previous PR that edited the form's layout and parameter names.
> Photometry form frontend test: fix

- skyportal/facility_apis/winter.py
- skyportal/handlers/api/followup_request.py
This PR:
- catches errors appropriately rather than returning the request's URL which contains credentials of the allocation.
- fixes the re-submission of failed requests
> WINTER API: various improvements

- skyportal/facility_apis/observation_plan.py
This PR changes the default end of an observation plan from sunrise to 12 degree twilight. 
Closes #5348.
> next sunrise to next twilight

- skyportal/handlers/api/spectrum.py
This PR adds check for spectrum units for synthetic photometry.
> check for spectrum units for synthetic photometry

- skyportal/handlers/api/source.py
This PR fixes the source deletion endpoint.
> source deletion endpoint

- skyportal/handlers/api/classification.py
This PR adds a check for an object before adding classification.
> check for object before creating classification

- skyportal/utils/offset.py
In this PR we:
- change the ra, dec to hms, dms format
- if the associated assignment comment contains the column separator in it (a comma), we replace it with a space to avoid breaking the CSV
> P200 NGPS Starlist: formatting changes

- skyportal/utils/observation_plan.py
gwemopt's read_skymap function is giving us issues, and as I looked at what it did, it's pretty obvious that most of it doesn't run for us as we already have the skymap read, and only constraints such as confidence level and galactic latitude need to be enforced on the map we got out of the DB. Also, I noticed that the confidence level constraint could be ignored given that we enforce it when we query the instrument tiles, meaning that anyway we don't give gwemopt the tiles that overlap with parts of the map outside of the requested confidence level. That said it does set a bunch of skymap tiles to zero, so we might as well still do that in an abundance of caution when it comes to gwemopt's potential memory usage.
> Observation plan queue - replace heavy dependency methods by lightweight code

- skyportal/utils/offset.py
- static/js/components/StarList.jsx
Adds a download button on the starlist
> Starlist - download button

- services/tns_submission_queue/tns_submission_queue.py
handle 400 errors which can occur when the reports sent are not valid, or just rejected by TNS. This happens after the report is sent, when we check if it has been posted on TNS using the provided submission ID.
> TNS submission validation - handle 400 errors

- skyportal/handlers/api/gcn.py
it looks like the API had it's own source creation code that was very outdated and caused issues in production, especially as it saved the autogenerated source to all the groups of a user and not just the sitewide group.
This PR creates one method that can be reimported by both functions that need to create a source.
> GCN source creation - deduplication between API handler & GCN service

- skyportal/handlers/api/spectrum.py
- skyportal/tests/api/test_spectrum.py
allow users to filter on when a spec was modified (before/after) when retrieving data from the SpectrumHandler
> SpectrumHandler - filter on modified date

- skyportal/facility_apis/tarot.py
- skyportal/utils/calculations.py
- static/js/components/allocation/ModifyAllocation.jsx
- static/js/components/allocation/NewAllocation.jsx
- Fix observing time logic to handle when the target set before the observation time but not the night. The observing time is then recalculate.
- Add altdata key verification on tarot
- Rename altdata stuff
- Fix status url
> Fix tarot small issues

- skyportal/facility_apis/tarot.py
- skyportal/tests/frontend/sources_and_observingruns_etc/test_observing_planner.py
- skyportal/tests/utils/test_calculations.py
- skyportal/utils/calculations.py
Fix input handling in observing planner test for calendar keys.
[Fix sun time calculation errors, improve tarot API handler and fix calculations error and tests.
> Fix frontend test error

- .gitmodules
> Update .gitmodules to point to baselayer main

- static/js/components/followup_request/FollowupRequestForm.jsx
- static/js/components/thumbnail/Thumbnail.jsx
Fix link placement in Thumbnail component to still work even when there is the crosshairs in front.
> Fix ps1 legacy link

- doc/dev.md
- skyportal/facility_apis/gemini.py
- skyportal/handlers/api/candidate/candidate.py
- skyportal/handlers/api/candidate/candidate_filter.py
- skyportal/handlers/api/followup_request.py
- skyportal/handlers/api/internal/ephemeris.py
- skyportal/handlers/api/source.py
- skyportal/handlers/api/tns/tns_robot.py
- skyportal/handlers/api/tns/tns_robot_group_autoreporter.py
- skyportal/tests/utils/test_parse.py
- skyportal/utils/parse.py
- Add utility functions for parsing integers and pagination handling
- Refactor integer parsing across multiple files to use parsing integers and pagination handling utility function
- Refactor candidate and candidate_filter modules to utilize utility functions for integer parsing and pagination handling and move duplicate code to a new function.
> Create utils parse function

- skyportal/handlers/api/internal/recent_sources.py
- static/js/components/widget/RecentSources.jsx
- static/js/components/widget/WidgetPrefsDialog.jsx
Addresses issues https://github.com/skyportal/skyportal/issues/5536 by adding an optional groups autoselect in the widget preferences dialog, and using selected groups (if any) in the backend when querying sources.
> RecentSources widget: optional group select

- skyportal/handlers/api/instrument.py
Fixes an error encountered while running `VACUUM ANALYZE instrumentfieldtiles` after inserting new instrument field tiles, since `VACUUM` can't run in a pending transaction so now we run it in a separate session, async and with auto-commit which is required.
> InstrumentFieldTiles: VACUUM query fix

- skyportal/handlers/api/weather.py
- static/js/components/telescope/TelescopeSummary.jsx
- static/js/components/widget/WeatherWidget.jsx
- static/js/ducks/weather.js
Fix the Infinit loop fetching weather when no token to access it.
> Fix Infinite loop fetching weather

- skyportal/facility_apis/trt.py
The goal of this PR is to add `CTO` to the station name options.
> feat: adding CTO option to station name in the followup request

- config.yaml.defaults
- skyportal/facility_apis/colibri.py
- skyportal/facility_apis/sedmv2.py
- skyportal/handlers/api/followup_request.py
This PR updates the Colibri submission form to be in line with SEDM-KP style (with the correct filter set).
> Colibri submission form

- .github/workflows/test_migrations.yaml
- requirements.txt
- skyportal/facility_apis/tarot.py
- skyportal/handlers/api/annotation_services.py
- skyportal/tests/frontend/sources_and_observingruns_etc/test_scanning_page.py
- skyportal/tests/frontend/test_allocation.py
- skyportal/tests/frontend/test_profile.py
- skyportal/utils/cosmology.py
- static/js/components/SharePage.jsx
Trying to revive some of the CI, pinecone update caused some weird issues on main (runs locally for me but fails here...).
I took advantage of this PR to update some dependencies, and address a couple of deprecation warnings. I also opened a PR on baselayer to address more warnings there.
> Migration CI bugfix + python dependencies updates

- skyportal/models/photometric_series.py
- tools/photseries_update/update_stats.py
Looks like the stats were hardcoded to mjd and not the field they should be looking at in a loop. This PR fixes that.
Unfortunately this is in the DB itself so we should add some endpoint to force recompute all photstats series or something like that, to make it easier for users that already rely on those to update them.
> PhotSeries: stats bugfix

- static/js/components/Notes.jsx
Follow the baselayer style and improve style.
> Improve notification styles and layout in Notes component.

- skyportal/handlers/api/public_pages/public_source_page.py
Fix wrong public source page filtering logic for groups and streams.
> Fix public page groups filtering

- config.yaml.defaults
- skyportal/facility_apis/tarot.py
- static/js/components/allocation/ModifyAllocation.jsx
Update TAROT API integration to use Icare tarot proxy endpoints and improve error handling.
> Update tarot API to call Icare

- skyportal/handlers/api/instrument.py
- skyportal/handlers/api/source_exists.py
- static/js/components/instrument/InstrumentForm.jsx
- static/js/components/observation/ExecutedObservationsTable.jsx
- static/js/components/source/NewSource.jsx
- static/js/ducks/source.js
Fix:
- Improve error handling for field_fov_attributes input and improve description in InstrumentForm.
- When checking the existence of a source by position (api/source_exists), and if there is no source at the given ra/dec/radius, the returned information says “a source of that name does not exist.”
- Improve handling of source_exists on the frontend.
- Correct improper use of form_data during source creation which prevents using the form twice by updating the actual form data.
> Fix small skyportal issues

- skyportal/facility_apis/tarot.py
- skyportal/handlers/api/photometry_request.py
- Improve status handling for tarot requests based on observing time
- Improve error message for request retrieval
> Improve tarot

- package.json
- skyportal/handlers/api/annotation_services.py
- static/js/components/plot/AirmassPlot.jsx
- static/js/components/plot/VegaFoldedPlot.jsx
- static/js/components/plot/VegaHR.jsx
- static/js/components/plot/VegaPlot.jsx
- static/js/components/plot/VegaSpectrum.jsx
- static/js/components/spectrum/UploadSpectrum.jsx
- static/js/components/templates/HoursBelowAirmassPlot.jsx.template
This PR updates all Vega-related dependencies (and schema urls in all vega components, to match the version in package.json).
PS: It also fixes an issue querying for gaia annotations
> Update Vega dependencies

- skyportal/facility_apis/gemini.py
This PR updates Gemini to take multiple template_ids.
> Gemini takes multiple template_ids

- static/js/components/photometry/PhotometryDownload.jsx
The goal of this PR is to fix the order of the Photometry table when it's downloaded.
> enh: refactoring column order

- skyportal/handlers/api/internal/plot.py
- skyportal/handlers/api/photometry.py
- skyportal/models/schema.py
- static/js/components/user/preferences/OriginSelect.jsx
- static/js/ducks/photometry.js
- Improved error handling and input validation in the photometry API.
- Deprecated and removed unused features, including the PhotometryOriginHandler.get endpoint and related frontend code.
- Cleaned up unused code.
> Fix some issues

- skyportal/facility_apis/ttt.py
This PR allows users to set the expected sensitivity in the TTT API.
> enh: update TTT API to allow users to choose the expected sensitivity

- skyportal/facility_apis/ttt.py
This PR is adding camera choice for TTT-200 between iKon936 and QHY600M Pro.
> enh: improve TTT API for TTT-200

- skyportal/handlers/api/observation.py
- skyportal/handlers/api/observation_plan.py
- static/js/ducks/sharingServices.js
- Resolve key error in post_survey_efficiency_analysis when loading demo data
- Delete forgotten console.log.
> Fix planned observations key error on load demo data

- package.json
- static/js/components/Paper.jsx
- static/js/components/spectrum/UploadSpectrum.jsx
- static/js/ducks/spectra.js
- Enhance Upload Spectrum page style and code to try to avoid lagging.
- Create a custom Paper component with default 1rem padding.
This custom component seems useless for now but there is many places where we duplicate that style just for this padding so this component can be use to replace this code everywhere.
> Enhance Upload Spectrum page

- skyportal/facility_apis/blanco.py
This PR adds sequence repeats and dithering for NEWFIRM triggering.
> NEWFIRM: add sequence repeats and dithering

- skyportal/tests/frontend/test_favorites_page.py
- static/js/components/gcn/GcnSelectionForm.jsx
- static/js/components/listing/FavoritesButton.jsx
- static/js/components/listing/FavoritesPage.jsx
- static/js/components/shift/ShiftSummary.jsx
- static/js/components/source/SourceTable.jsx
- static/js/components/spatial_catalog/SpatialCatalogPage.jsx
_Part of the major front-end improvements I made last month._
- Improvement of the source favorite
- Refactor FavoritesButton component to simplify logic, remove useless code, add yellow to the favorite button and fix button not display sometime on the source list page.
> Improve source favorite
